#!/usr/bin/env python3
"""Gera perguntas-v2/ester.json (5 missões × 18)."""
import json
from pathlib import Path

OUT = Path(__file__).with_name("ester.json")


def q(
    trail,
    section,
    diff,
    skill,
    typ,
    nn,
    verse_ref,
    lo,
    evidence,
    question,
    feedback_correct,
    feedback_wrong,
    options,
    correct,
    passage,
    **extra,
):
    short = {"semente": "sem", "caminhada": "cam", "profundezas": "pro"}[diff]
    item = {
        "difficulty": diff,
        "skill": skill,
        "verseRef": verse_ref,
        "learningObjective": lo,
        "evidence": evidence,
        "type": typ,
        "question": question,
        "prompt": question,
        "cue": question,
        "feedbackCorrect": feedback_correct,
        "feedbackWrong": feedback_wrong,
        "options": options,
        "correctOptionId": correct,
        "correctAnswer": correct,
        "passageText": passage,
        "trail": trail,
        "section": section,
        "id": f"{trail}-{short}-{section}-{nn}",
    }
    item.update(extra)
    assert len(feedback_correct) <= 100, (len(feedback_correct), feedback_correct)
    return item


def tf_opts():
    return [{"id": "true", "text": "Verdadeiro"}, {"id": "false", "text": "Falso"}]


def opts(*pairs):
    return [{"id": i, "text": t} for i, t in pairs]


def mission(section, verse, passage, lo, evidence, items):
    out = []
    for spec in items:
        extra = {}
        for k in ("template", "correctOrder", "passageA", "passageB"):
            if k in spec:
                extra[k] = spec[k]
        out.append(
            q(
                "ester",
                section,
                spec["diff"],
                spec["skill"],
                spec["type"],
                spec["nn"],
                verse,
                lo,
                evidence,
                spec["question"],
                spec["ok"],
                spec["wrong"],
                spec["options"],
                spec["correct"],
                passage,
                **extra,
            )
        )
    return out


bank = []

# ---------------------------------------------------------------------------
# M1 Ester 2:17
# ---------------------------------------------------------------------------
P1 = (
    "O rei amou a Ester mais do que a todas as mulheres, e ela alcançou graça e "
    "favor diante dele mais do que todas as virgens; de sorte que lhe pôs sobre "
    "a cabeça a coroa real e a fez rainha em lugar de Vasti."
)
LO1 = (
    "Perceber que Ester se torna rainha por graça e favor, coroada no lugar de Vasti."
)
bank += mission(
    "ester-corte-01-ester-rainha",
    "Ester 2:17",
    P1,
    LO1,
    ["Ester 2:17"],
    [
        dict(
            diff="semente",
            skill="observe",
            type="true_false",
            nn="01",
            question="O rei amou a Ester mais do que a todas as mulheres.",
            ok="Certo: o versículo abre exatamente com esse amor do rei.",
            wrong={"false": "Releia Ester 2:17: o rei amou Ester mais do que a todas."},
            options=tf_opts(),
            correct="true",
        ),
        dict(
            diff="semente",
            skill="observe",
            type="tap",
            nn="02",
            question='Em Ester 2:17, toque a palavra que falta em "e ela alcançou ___ e favor diante dele mais do que todas as virgens"?',
            ok='Exato: ela alcançou "graça" e favor diante do rei.',
            wrong={
                "b": "Virgens compara o alcance do favor, não preenche esta lacuna.",
                "c": "Vasti é quem Ester substitui, não o que ela alcançou.",
            },
            options=opts(("a", "graça"), ("b", "virgens"), ("c", "Vasti")),
            correct="a",
            template="e ela alcançou ___ e favor diante dele mais do que todas as virgens",
        ),
        dict(
            diff="semente",
            skill="observe",
            type="choice",
            nn="03",
            question="Qual fato Ester 2:17 afirma diretamente sobre Ester?",
            ok="Certo: o rei pôs-lhe a coroa e a fez rainha no lugar de Vasti.",
            wrong={
                "a": "O texto afirma amor, não desprezo do rei.",
                "b": "O texto diz que o rei a fez rainha, não que ela recusou a coroa.",
                "d": "Vasti é substituída; o texto não diz que ela voltou ao trono.",
            },
            options=opts(
                ("a", "O rei a desprezou depois de vê-la no palácio."),
                ("b", "Ela recusou a coroa real oferecida pelo rei."),
                ("c", "O rei pôs-lhe a coroa e a fez rainha no lugar de Vasti."),
                ("d", "Vasti voltou ao trono depois da festa real."),
            ),
            correct="c",
        ),
        dict(
            diff="semente",
            skill="observe",
            type="order",
            nn="04",
            question="Qual sequência mostra a ordem dos fatos em Ester 2:17?",
            ok="Certo: amor, graça e favor, depois a coroa e o lugar de Vasti.",
            wrong={
                "b": "Essa peça não vem primeiro no versículo.",
                "c": "Releia a ordem: a coroa vem depois do favor alcançado.",
            },
            options=opts(
                ("a", "O rei amou a Ester mais do que a todas as mulheres"),
                ("b", "ela alcançou graça e favor diante dele mais do que todas as virgens"),
                ("c", "lhe pôs sobre a cabeça a coroa real e a fez rainha em lugar de Vasti"),
            ),
            correct="a",
            correctOrder=["a", "b", "c"],
        ),
        dict(
            diff="semente",
            skill="observe",
            type="complete",
            nn="05",
            question='Complete a frase: "de sorte que lhe pôs sobre a cabeça a ___ real e a fez rainha em lugar de Vasti."',
            ok='Certo: o rei lhe pôs a "coroa" real sobre a cabeça.',
            wrong={
                "a": "Graça é o que ela alcançou, não o objeto posto na cabeça.",
                "c": "Mulheres compara o amor do rei, não o que ele pôs nela.",
            },
            options=opts(("a", "graça"), ("b", "coroa"), ("c", "mulheres")),
            correct="b",
            template="de sorte que lhe pôs sobre a cabeça a ___ real e a fez rainha em lugar de Vasti.",
        ),
        dict(
            diff="semente",
            skill="observe",
            type="connect",
            nn="06",
            question="O que Ester 2:17 comunica que se liga a este contexto?",
            ok="Certo: a elevação de Ester vem de graça e favor, não de mérito ostensivo.",
            wrong={
                "a": "O texto não atribui a coroa a feito militar de Ester.",
                "c": "Vasti é substituída; o texto não narra o seu retorno.",
            },
            options=opts(
                ("a", "Mérito militar de Ester"),
                ("b", "Graça que a eleva rainha"),
                ("c", "Retorno de Vasti ao trono"),
            ),
            correct="b",
            passageA={"ref": "Ester 2:17", "text": "ela alcançou graça e favor diante dele mais do que todas as virgens"},
            passageB={
                "ref": "Contexto",
                "text": "Ester é rainha por graça e favor — a coroa não apaga o povo escondido.",
            },
        ),
        dict(
            diff="caminhada",
            skill="understand",
            type="true_false",
            nn="01",
            question="O texto diz que Ester foi feita rainha só por beleza, sem mencionar graça e favor.",
            ok="Certo: o versículo destaca graça e favor, não só aparência.",
            wrong={"true": "Ester 2:17 afirma graça e favor diante do rei, não só beleza."},
            options=tf_opts(),
            correct="false",
        ),
        dict(
            diff="caminhada",
            skill="understand",
            type="tap",
            nn="02",
            question='Em Ester 2:17, toque a palavra que falta em "e a fez ___ em lugar de Vasti"?',
            ok='Exato: o rei a fez "rainha" em lugar de Vasti.',
            wrong={
                "a": "Graça é o que ela alcançou, não o título que o rei lhe deu.",
                "c": "Mulheres compara o amor do rei, não o ofício de Ester.",
            },
            options=opts(("a", "graça"), ("b", "rainha"), ("c", "mulheres")),
            correct="b",
            template="e a fez ___ em lugar de Vasti",
        ),
        dict(
            diff="caminhada",
            skill="understand",
            type="choice",
            nn="03",
            question="O que o encadeamento de Ester 2:17 mostra sobre a subida de Ester?",
            ok="Certo: o trono segue o favor alcançado, não uma troca de impérios.",
            wrong={
                "a": "O texto não diz que ela comprou o trono com ouro.",
                "c": "Não há aqui uma aliança militar com Pérsia contra Judá.",
                "d": "O versículo não apresenta Vasti restaurando Ester.",
            },
            options=opts(
                ("a", "Ela comprou o trono com ouro das províncias."),
                ("b", "O favor alcançado antecede a coroa e o lugar de Vasti."),
                ("c", "Ela firmou aliança militar contra o próprio povo."),
                ("d", "Vasti a restaurou como conselheira do palácio."),
            ),
            correct="b",
        ),
        dict(
            diff="caminhada",
            skill="understand",
            type="order",
            nn="04",
            question="Como se encadeiam os eventos de Ester 2:17?",
            ok="Certo: o amor do rei, o favor alcançado e então a coroa.",
            wrong={
                "a": "A coroa não vem antes do favor no texto.",
                "c": "Essa peça não fecha o encadeamento do versículo.",
            },
            options=opts(
                ("a", "lhe pôs sobre a cabeça a coroa real e a fez rainha em lugar de Vasti"),
                ("b", "O rei amou a Ester mais do que a todas as mulheres"),
                ("c", "ela alcançou graça e favor diante dele mais do que todas as virgens"),
            ),
            correct="b",
            correctOrder=["b", "c", "a"],
        ),
        dict(
            diff="caminhada",
            skill="understand",
            type="complete",
            nn="05",
            question='Complete a frase: "ela alcançou graça e favor diante dele mais do que todas as ___."',
            ok='Certo: o favor é maior do que o de todas as "virgens".',
            wrong={
                "a": "Coroa é o que o rei põe nela depois, não o termo desta comparação.",
                "b": "Rainha é o título dado no fim, não o grupo comparado aqui.",
            },
            options=opts(("a", "coroa"), ("b", "rainha"), ("c", "virgens")),
            correct="c",
            template="ela alcançou graça e favor diante dele mais do que todas as ___.",
        ),
        dict(
            diff="caminhada",
            skill="understand",
            type="connect",
            nn="06",
            question="O que Ester 2:17 comunica que se liga a este contexto?",
            ok="Certo: a coroa eleva Ester sem apagar a origem do seu povo.",
            wrong={
                "a": "O texto não declara vitória política de Vasti.",
                "b": "Nada aqui afirma o fim da identidade judaica.",
            },
            options=opts(
                ("a", "Vitória política de Vasti"),
                ("b", "Fim da identidade judaica"),
                ("c", "Coroa sem apagar a origem"),
            ),
            correct="c",
            passageA={"ref": "Ester 2:17", "text": "lhe pôs sobre a cabeça a coroa real e a fez rainha em lugar de Vasti"},
            passageB={
                "ref": "Contexto",
                "text": "A coroa chega por graça e favor; o povo de Ester permanece escondido no palácio.",
            },
        ),
        dict(
            diff="profundezas",
            skill="interpret",
            type="true_false",
            nn="01",
            question="A coroa de Ester, recebida por graça e favor, não apaga o povo ao qual ela pertence.",
            ok="Certo: o favor a eleva, mas a identidade do povo continua em jogo.",
            wrong={"false": "A missão lê a coroa como graça, não como apagamento do povo."},
            options=tf_opts(),
            correct="true",
        ),
        dict(
            diff="profundezas",
            skill="interpret",
            type="tap",
            nn="02",
            question='Em Ester 2:17, toque a palavra que falta em "a fez rainha em lugar de ___"?',
            ok='Exato: Ester ocupa o lugar de "Vasti".',
            wrong={
                "a": "Rei é quem coroa, não quem é substituído no trono.",
                "b": "Graça descreve o favor alcançado, não a antecessora.",
            },
            options=opts(("a", "rei"), ("b", "graça"), ("c", "Vasti")),
            correct="c",
            template="a fez rainha em lugar de ___",
        ),
        dict(
            diff="profundezas",
            skill="interpret",
            type="choice",
            nn="03",
            question="Qual leitura teológica Ester 2:17 sustenta sem forçar o texto?",
            ok="Certo: o trono é graça, e o povo de Ester não desaparece com a coroa.",
            wrong={
                "a": "O texto não apresenta a coroa como mérito puro de Ester.",
                "b": "Nada aqui ensina que o palácio apaga a vocação do povo.",
                "c": "O versículo não trata a rainha como ídolo do império.",
            },
            options=opts(
                ("a", "A coroa prova mérito absoluto de Ester perante Deus."),
                ("b", "O palácio apaga qualquer vínculo de Ester com seu povo."),
                ("c", "Ser rainha a torna objeto de culto no império."),
                ("d", "Favor a eleva, mas a coroa não dissolve o povo escondido."),
            ),
            correct="d",
        ),
        dict(
            diff="profundezas",
            skill="interpret",
            type="order",
            nn="04",
            question="Qual sequência revela o sentido de Ester 2:17?",
            ok="Certo: o sentido vai do amor do rei ao favor e, então, à coroa.",
            wrong={
                "a": "Começar pela coroa inverte o sentido do versículo.",
                "b": "Essa ordem não revela o movimento de graça do texto.",
            },
            options=opts(
                ("a", "lhe pôs sobre a cabeça a coroa real e a fez rainha em lugar de Vasti"),
                ("b", "ela alcançou graça e favor diante dele mais do que todas as virgens"),
                ("c", "O rei amou a Ester mais do que a todas as mulheres"),
            ),
            correct="c",
            correctOrder=["c", "b", "a"],
        ),
        dict(
            diff="profundezas",
            skill="interpret",
            type="complete",
            nn="05",
            question='Complete a frase: "e ela alcançou graça e ___ diante dele mais do que todas as virgens."',
            ok='Certo: além da graça, o texto fala de "favor" diante do rei.',
            wrong={
                "a": "Vasti é a antecessora, não o que Ester alcançou.",
                "b": "Cabeça é onde a coroa é posta, não o que ela alcançou.",
            },
            options=opts(("a", "Vasti"), ("b", "cabeça"), ("c", "favor")),
            correct="c",
            template="e ela alcançou graça e ___ diante dele mais do que todas as virgens.",
        ),
        dict(
            diff="profundezas",
            skill="interpret",
            type="connect",
            nn="06",
            question="O que Ester 2:17 comunica que se liga a este contexto?",
            ok="Certo: o favor real não cancela o povo escondido de Ester.",
            wrong={
                "b": "O texto não apresenta a coroa como fim da aliança.",
                "c": "Nada aqui reduz Ester a um enfeite sem povo.",
            },
            options=opts(
                ("a", "Favor que não apaga o povo"),
                ("b", "Coroa como fim da aliança"),
                ("c", "Rainha sem vínculo algum"),
            ),
            correct="a",
            passageA={"ref": "Ester 2:17", "text": "o rei amou a Ester mais do que a todas as mulheres"},
            passageB={
                "ref": "Contexto",
                "text": "Ester é rainha por graça e favor — a coroa não apaga o povo escondido.",
            },
        ),
    ],
)

# ---------------------------------------------------------------------------
# M2 Ester 3:8
# ---------------------------------------------------------------------------
P2 = (
    "Hamã disse ao rei Assuero: Há um povo espalhado e disperso por entre os povos, "
    "em todas as províncias do teu reino, e as suas leis divergem das de todos os povos. "
    "Não observa as leis do rei; portanto, não convém ao rei tolerá-lo."
)
LO2 = (
    "Identificar que Hamã denuncia um povo disperso, de leis distintas, e pede que o rei não o tolere."
)
bank += mission(
    "ester-corte-02-o-plano-de-hama",
    "Ester 3:8",
    P2,
    LO2,
    ["Ester 3:8"],
    [
        dict(
            diff="semente",
            skill="observe",
            type="true_false",
            nn="01",
            question="Hamã afirmou ao rei que havia um povo espalhado e disperso por entre os povos.",
            ok="Certo: essa é a abertura da denúncia de Hamã em Ester 3:8.",
            wrong={"false": "Releia Ester 3:8: Hamã fala de um povo espalhado e disperso."},
            options=tf_opts(),
            correct="true",
        ),
        dict(
            diff="semente",
            skill="observe",
            type="tap",
            nn="02",
            question='Em Ester 3:8, toque a palavra que falta em "as suas leis ___ das de todos os povos"?',
            ok='Exato: as leis do povo "divergem" das dos demais.',
            wrong={
                "a": "Espalhado descreve o povo, não o verbo desta frase.",
                "c": "Assuero é o rei ouvido, não o que as leis fazem.",
            },
            options=opts(("a", "espalhado"), ("b", "divergem"), ("c", "Assuero")),
            correct="b",
            template="as suas leis ___ das de todos os povos",
        ),
        dict(
            diff="semente",
            skill="observe",
            type="choice",
            nn="03",
            question="O que Hamã afirma literalmente sobre esse povo?",
            ok="Certo: Hamã diz que o povo não observa as leis do rei.",
            wrong={
                "a": "O texto o chama de espalhado, não de concentrado em Susã só.",
                "c": "Hamã pede que não o tolerem, não que o honrem.",
                "d": "Ele fala de leis que divergem, não de tributo dobrado.",
            },
            options=opts(
                ("a", "O povo vive reunido só na capital do reino."),
                ("b", "O povo não observa as leis do rei, segundo Hamã."),
                ("c", "O povo merece honra especial nas províncias."),
                ("d", "O povo pagava tributo dobrado a Assuero."),
            ),
            correct="b",
        ),
        dict(
            diff="semente",
            skill="observe",
            type="order",
            nn="04",
            question="Qual sequência mostra a ordem dos fatos em Ester 3:8?",
            ok="Certo: povo disperso, leis que divergem, pedido para não tolerá-lo.",
            wrong={
                "b": "Essa peça não ocupa este lugar no discurso de Hamã.",
                "c": "O pedido de não tolerar fecha o argumento, não o abre.",
            },
            options=opts(
                ("a", "Há um povo espalhado e disperso por entre os povos"),
                ("b", "as suas leis divergem das de todos os povos"),
                ("c", "não convém ao rei tolerá-lo"),
            ),
            correct="a",
            correctOrder=["a", "b", "c"],
        ),
        dict(
            diff="semente",
            skill="observe",
            type="complete",
            nn="05",
            question='Complete a frase: "portanto, não convém ao rei ___."',
            ok='Certo: Hamã conclui que não convém "tolerá-lo".',
            wrong={
                "a": "Disperso descreve o povo, não o verbo do pedido final.",
                "c": "Leis é o tema da denúncia, não o que o rei não deve fazer.",
            },
            options=opts(("a", "disperso"), ("b", "tolerá-lo"), ("c", "leis")),
            correct="b",
            template="portanto, não convém ao rei ___.",
        ),
        dict(
            diff="semente",
            skill="observe",
            type="connect",
            nn="06",
            question="O que Ester 3:8 comunica que se liga a este contexto?",
            ok="Certo: Hamã veste o ódio de zelo pelas leis do rei.",
            wrong={
                "b": "O texto não apresenta o povo como sem lei alguma.",
                "c": "Hamã não pede honra pessoal neste versículo.",
            },
            options=opts(
                ("a", "Ódio vestido de lealdade"),
                ("b", "Povo sem lei alguma"),
                ("c", "Pedido de honra pessoal"),
            ),
            correct="a",
            passageA={"ref": "Ester 3:8", "text": "Não observa as leis do rei; portanto, não convém ao rei tolerá-lo."},
            passageB={
                "ref": "Contexto",
                "text": "O plano de Hamã é apagar um povo cuja lei diverge — ódio vestido de lealdade ao rei.",
            },
        ),
        dict(
            diff="caminhada",
            skill="understand",
            type="true_false",
            nn="01",
            question="Hamã descreve o povo como unido numa só cidade e fiel às leis do rei.",
            ok="Certo: ele o chama de espalhado e diz que não observa as leis do rei.",
            wrong={"true": "Ester 3:8 diz o contrário: povo disperso e leis que divergem."},
            options=tf_opts(),
            correct="false",
        ),
        dict(
            diff="caminhada",
            skill="understand",
            type="tap",
            nn="02",
            question='Em Ester 3:8, toque a palavra que falta em "Há um povo ___ e disperso por entre os povos"?',
            ok='Exato: o povo é chamado de "espalhado" e disperso.',
            wrong={
                "b": "Tolerá-lo é o pedido final, não o adjetivo do povo.",
                "c": "Assuero é o rei, não a condição do povo.",
            },
            options=opts(("a", "espalhado"), ("b", "tolerá-lo"), ("c", "Assuero")),
            correct="a",
            template="Há um povo ___ e disperso por entre os povos",
        ),
        dict(
            diff="caminhada",
            skill="understand",
            type="choice",
            nn="03",
            question="Como Hamã constrói o argumento para o rei em Ester 3:8?",
            ok="Certo: a diferença de leis vira pretexto para não tolerar o povo.",
            wrong={
                "a": "Hamã não pede censo fiscal neste versículo.",
                "b": "Ele não recomenda diálogo com os sábios de Susã.",
                "d": "Não há aqui um elogio à lealdade do povo.",
            },
            options=opts(
                ("a", "Pede um censo para aumentar o tributo real."),
                ("b", "Sugere diálogo com os sábios de todas as cidades."),
                ("c", "Usa a diferença de leis como razão para não tolerar."),
                ("d", "Elogia a lealdade do povo às leis de Assuero."),
            ),
            correct="c",
        ),
        dict(
            diff="caminhada",
            skill="understand",
            type="order",
            nn="04",
            question="Como se encadeiam os eventos de Ester 3:8?",
            ok="Certo: a denúncia vai da dispersão à divergência e ao pedido de exclusão.",
            wrong={
                "a": "Essa ordem embaralha o encadeamento do discurso.",
                "b": "O pedido de não tolerar não abre o argumento.",
            },
            options=opts(
                ("a", "não convém ao rei tolerá-lo"),
                ("b", "Há um povo espalhado e disperso por entre os povos"),
                ("c", "as suas leis divergem das de todos os povos"),
            ),
            correct="b",
            correctOrder=["b", "c", "a"],
        ),
        dict(
            diff="caminhada",
            skill="understand",
            type="complete",
            nn="05",
            question='Complete a frase: "Há um povo espalhado e ___ por entre os povos."',
            ok='Certo: além de espalhado, o povo é chamado de "disperso".',
            wrong={
                "a": "Divergem refere-se às leis, não a este adjetivo do povo.",
                "c": "Províncias indica o alcance geográfico, não este par com espalhado.",
            },
            options=opts(("a", "divergem"), ("b", "disperso"), ("c", "províncias")),
            correct="b",
            template="Há um povo espalhado e ___ por entre os povos.",
        ),
        dict(
            diff="caminhada",
            skill="understand",
            type="connect",
            nn="06",
            question="O que Ester 3:8 comunica que se liga a este contexto?",
            ok="Certo: a denúncia visa apagar um povo cuja lei diverge.",
            wrong={
                "a": "Hamã não propõe reforma das leis do império.",
                "b": "O texto não é um elogio à diversidade do povo.",
            },
            options=opts(
                ("a", "Reforma das leis do império"),
                ("b", "Elogio à diversidade do povo"),
                ("c", "Denúncia para apagar um povo"),
            ),
            correct="c",
            passageA={"ref": "Ester 3:8", "text": "Há um povo espalhado e disperso por entre os povos"},
            passageB={
                "ref": "Contexto",
                "text": "O plano de Hamã é apagar um povo cuja lei diverge — ódio vestido de lealdade ao rei.",
            },
        ),
        dict(
            diff="profundezas",
            skill="interpret",
            type="true_false",
            nn="01",
            question="Hamã veste o ódio ao povo de lealdade ao rei, pedindo que não o tolerem.",
            ok="Certo: a lealdade ao rei é a roupagem do pedido de exclusão.",
            wrong={"false": "Ester 3:8 mostra ódio apresentado como zelo pelas leis reais."},
            options=tf_opts(),
            correct="true",
        ),
        dict(
            diff="profundezas",
            skill="interpret",
            type="tap",
            nn="02",
            question='Em Ester 3:8, toque a palavra que falta em "em todas as ___ do teu reino"?',
            ok='Exato: o povo está em todas as "províncias" do reino.',
            wrong={
                "b": "Leis é o tema da divergência, não o lugar da dispersão.",
                "c": "Povos é o conjunto entre o qual estão, não esta palavra.",
            },
            options=opts(("a", "províncias"), ("b", "leis"), ("c", "povos")),
            correct="a",
            template="em todas as ___ do teu reino",
        ),
        dict(
            diff="profundezas",
            skill="interpret",
            type="choice",
            nn="03",
            question="Qual erro de leitura Ester 3:8 ajuda a desmascarar?",
            ok="Certo: diferença de lei vira pretexto de ódio, não zelo neutro.",
            wrong={
                "b": "Hamã não descreve um censo piedoso e imparcial.",
                "c": "O texto não apresenta o povo como ameaça militar explícita.",
                "d": "Não há aqui um convite à conversão das leis judaicas.",
            },
            options=opts(
                ("a", "Tratar diferença de lei como pretexto de ódio ao povo."),
                ("b", "Ver a fala de Hamã como censo piedoso e imparcial."),
                ("c", "Ler o povo como exército pronto contra Assuero."),
                ("d", "Entender o versículo como convite à conversão das leis."),
            ),
            correct="a",
        ),
        dict(
            diff="profundezas",
            skill="interpret",
            type="order",
            nn="04",
            question="Qual sequência revela o sentido de Ester 3:8?",
            ok="Certo: o sentido vai da dispersão à divergência e à intolerância pedida.",
            wrong={
                "b": "Essa ordem não revela o movimento acusatório do texto.",
                "c": "Começar pelo pedido final esconde como o ódio se veste.",
            },
            options=opts(
                ("a", "Há um povo espalhado e disperso por entre os povos"),
                ("b", "não convém ao rei tolerá-lo"),
                ("c", "as suas leis divergem das de todos os povos"),
            ),
            correct="a",
            correctOrder=["a", "c", "b"],
        ),
        dict(
            diff="profundezas",
            skill="interpret",
            type="complete",
            nn="05",
            question='Complete a frase: "e as suas ___ divergem das de todos os povos."',
            ok='Certo: são as "leis" do povo que Hamã diz divergirem.',
            wrong={
                "b": "Províncias localiza o povo, não o que diverge.",
                "c": "Reino é o domínio de Assuero, não o sujeito de divergem.",
            },
            options=opts(("a", "leis"), ("b", "províncias"), ("c", "reino")),
            correct="a",
            template="e as suas ___ divergem das de todos os povos.",
        ),
        dict(
            diff="profundezas",
            skill="interpret",
            type="connect",
            nn="06",
            question="O que Ester 3:8 comunica que se liga a este contexto?",
            ok="Certo: a lei diversa é usada como pretexto para excluir.",
            wrong={
                "a": "Hamã não busca proteger o povo sob o rei.",
                "c": "O versículo não é um tratado de harmonia entre povos.",
            },
            options=opts(
                ("a", "Proteção piedosa do povo"),
                ("b", "Lei diversa usada como pretexto"),
                ("c", "Harmonia entre todos os povos"),
            ),
            correct="b",
            passageA={"ref": "Ester 3:8", "text": "as suas leis divergem das de todos os povos"},
            passageB={
                "ref": "Contexto",
                "text": "O plano de Hamã é apagar um povo cuja lei diverge — ódio vestido de lealdade ao rei.",
            },
        ),
    ],
)

# ---------------------------------------------------------------------------
# M3 Ester 4:16
# ---------------------------------------------------------------------------
P3 = (
    "Vai ajuntar todos os judeus que se acham em Susã, e jejuai por mim; não comais, "
    "nem bebais por três dias, nem de noite nem de dia. Da mesma maneira, também eu e "
    "minhas criadas jejuaremos. Depois, irei ter com o rei, ainda que isso não é segundo "
    "a lei; se perecer, pereci."
)
LO3 = (
    "Ver que Ester pede jejum de três dias e se dispõe a ir ao rei mesmo contra a lei."
)
bank += mission(
    "ester-livramento-01-jejuar-e-agir",
    "Ester 4:16",
    P3,
    LO3,
    ["Ester 4:16"],
    [
        dict(
            diff="semente",
            skill="observe",
            type="true_false",
            nn="01",
            question="Ester pede que os judeus de Susã jejuem por ela, sem comer nem beber por três dias.",
            ok="Certo: o versículo manda ajuntar, jejuar e não comer nem beber três dias.",
            wrong={"false": "Releia Ester 4:16: jejum de três dias, de noite e de dia."},
            options=tf_opts(),
            correct="true",
        ),
        dict(
            diff="semente",
            skill="observe",
            type="tap",
            nn="02",
            question='Em Ester 4:16, toque a palavra que falta em "todos os judeus que se acham em ___"?',
            ok='Exato: o jejum reúne os judeus que estão em "Susã".',
            wrong={
                "b": "Lei aparece no risco de ir ao rei, não neste lugar.",
                "c": "Rei é a quem ela irá depois, não o local do ajuntamento.",
            },
            options=opts(("a", "Susã"), ("b", "lei"), ("c", "rei")),
            correct="a",
            template="todos os judeus que se acham em ___",
        ),
        dict(
            diff="semente",
            skill="observe",
            type="choice",
            nn="03",
            question="O que Ester declara que fará depois do jejum?",
            ok="Certo: ela irá ao rei, ainda que isso não seja segundo a lei.",
            wrong={
                "a": "O texto não diz que ela fugirá de Susã.",
                "b": "Não há pedido de decreto novo antes de ir.",
                "c": "Ela não envia só as criadas no seu lugar.",
            },
            options=opts(
                ("a", "Ela fugirá de Susã com as criadas."),
                ("b", "Ela pedirá um decreto novo antes de ir."),
                ("c", "Ela enviará só as criadas ao palácio."),
                ("d", "Ela irá ao rei, ainda que isso não seja segundo a lei."),
            ),
            correct="d",
        ),
        dict(
            diff="semente",
            skill="observe",
            type="order",
            nn="04",
            question="Qual sequência mostra a ordem dos fatos em Ester 4:16?",
            ok="Certo: ajuntar e jejuar, três dias, depois ir ao rei mesmo sob risco.",
            wrong={
                "b": "Essa peça não ocupa este lugar na fala de Ester.",
                "c": "O risco de perecer fecha o texto, não o abre.",
            },
            options=opts(
                ("a", "Vai ajuntar todos os judeus que se acham em Susã, e jejuai por mim"),
                ("b", "não comais, nem bebais por três dias, nem de noite nem de dia"),
                ("c", "irei ter com o rei, ainda que isso não é segundo a lei"),
            ),
            correct="a",
            correctOrder=["a", "b", "c"],
        ),
        dict(
            diff="semente",
            skill="observe",
            type="complete",
            nn="05",
            question='Complete a frase: "irei ter com o rei, ainda que isso não é segundo a ___."',
            ok='Certo: ir ao rei não é segundo a "lei".',
            wrong={
                "a": "Susã é a cidade do jejum, não o termo desta cláusula.",
                "c": "Criadas jejuam com ela, mas não preenchem esta lacuna.",
            },
            options=opts(("a", "Susã"), ("b", "lei"), ("c", "criadas")),
            correct="b",
            template="irei ter com o rei, ainda que isso não é segundo a ___.",
        ),
        dict(
            diff="semente",
            skill="observe",
            type="connect",
            nn="06",
            question="O que Ester 4:16 comunica que se liga a este contexto?",
            ok="Certo: o jejum precede o risco de entrar no palácio.",
            wrong={
                "b": "O texto não descreve recusa de Ester em agir.",
                "c": "Não há aqui um jejum sem qualquer passo seguinte.",
            },
            options=opts(
                ("a", "Jejum antes de arriscar a vida"),
                ("b", "Recusa de Ester em agir"),
                ("c", "Jejum sem passo seguinte"),
            ),
            correct="a",
            passageA={"ref": "Ester 4:16", "text": "jejuai por mim; não comais, nem bebais por três dias"},
            passageB={
                "ref": "Contexto",
                "text": "Jejuar e agir: Ester arrisca a vida depois de três dias de jejum — fé que entra no palácio.",
            },
        ),
        dict(
            diff="caminhada",
            skill="understand",
            type="true_false",
            nn="01",
            question="Ester decide ir ao rei somente depois de obter autorização legal explícita.",
            ok="Certo: ela irá ainda que isso não seja segundo a lei.",
            wrong={"true": "Ester 4:16 diz o contrário: irá mesmo contra a lei."},
            options=tf_opts(),
            correct="false",
        ),
        dict(
            diff="caminhada",
            skill="understand",
            type="tap",
            nn="02",
            question='Em Ester 4:16, toque a palavra que falta em "não comais, nem bebais por três ___"?',
            ok='Exato: o jejum dura três "dias".',
            wrong={
                "a": "Criadas jejuam com ela, mas não medem o tempo aqui.",
                "c": "Judeus são os que jejum, não a unidade de tempo.",
            },
            options=opts(("a", "criadas"), ("b", "dias"), ("c", "judeus")),
            correct="b",
            template="não comais, nem bebais por três ___",
        ),
        dict(
            diff="caminhada",
            skill="understand",
            type="choice",
            nn="03",
            question="Como jejum e ação se relacionam em Ester 4:16?",
            ok="Certo: o jejum prepara a ida ao rei, não a substitui.",
            wrong={
                "b": "O texto não apresenta o jejum como fim da história.",
                "c": "Ela não transfere o risco só às criadas.",
                "d": "Não há recusa de entrar no palácio após o jejum.",
            },
            options=opts(
                ("a", "O jejum prepara a ida ao rei; não a substitui."),
                ("b", "O jejum encerra a crise sem nenhum passo seguinte."),
                ("c", "Só as criadas assumem o risco no lugar de Ester."),
                ("d", "Ester recusa entrar no palácio depois de jejuar."),
            ),
            correct="a",
        ),
        dict(
            diff="caminhada",
            skill="understand",
            type="order",
            nn="04",
            question="Como se encadeiam os eventos de Ester 4:16?",
            ok="Certo: primeiro o jejum conjunto, depois a ida ao rei sob risco.",
            wrong={
                "a": "Ir ao rei não abre a fala; vem depois do jejum.",
                "c": "Essa ordem quebra o encadeamento do versículo.",
            },
            options=opts(
                ("a", "irei ter com o rei, ainda que isso não é segundo a lei"),
                ("b", "jejuai por mim; não comais, nem bebais por três dias"),
                ("c", "também eu e minhas criadas jejuaremos"),
            ),
            correct="b",
            correctOrder=["b", "c", "a"],
        ),
        dict(
            diff="caminhada",
            skill="understand",
            type="complete",
            nn="05",
            question='Complete a frase: "se ___, pereci."',
            ok='Certo: Ester conclui "se perecer, pereci".',
            wrong={
                "a": "Jejuaremos é a ação das criadas, não esta cláusula.",
                "c": "Ajuntar é a ordem inicial, não o verbo do risco.",
            },
            options=opts(("a", "jejuaremos"), ("b", "perecer"), ("c", "ajuntar")),
            correct="b",
            template="se ___, pereci.",
        ),
        dict(
            diff="caminhada",
            skill="understand",
            type="connect",
            nn="06",
            question="O que Ester 4:16 comunica que se liga a este contexto?",
            ok="Certo: a fé jejua e depois entra no palácio.",
            wrong={
                "a": "O texto não descreve fuga para fora de Susã.",
                "b": "Não há aqui um decreto já garantido antes de ir.",
            },
            options=opts(
                ("a", "Fuga segura para fora de Susã"),
                ("b", "Decreto já garantido pelo rei"),
                ("c", "Fé que entra no palácio"),
            ),
            correct="c",
            passageA={"ref": "Ester 4:16", "text": "Depois, irei ter com o rei, ainda que isso não é segundo a lei"},
            passageB={
                "ref": "Contexto",
                "text": "Jejuar e agir: Ester arrisca a vida depois de três dias de jejum — fé que entra no palácio.",
            },
        ),
        dict(
            diff="profundezas",
            skill="interpret",
            type="true_false",
            nn="01",
            question="O jejum de Ester não substitui a ação: depois de três dias, ela se dispõe a ir ao rei sob risco de morte.",
            ok="Certo: jejum e risco de perecer estão juntos no mesmo plano.",
            wrong={"false": "Ester 4:16 une jejum, ida ao rei e 'se perecer, pereci'."},
            options=tf_opts(),
            correct="true",
        ),
        dict(
            diff="profundezas",
            skill="interpret",
            type="tap",
            nn="02",
            question='Em Ester 4:16, toque a palavra que falta em "também eu e minhas ___ jejuaremos"?',
            ok='Exato: Ester e suas "criadas" também jejum.',
            wrong={
                "b": "Judeus são o povo ajuntado, não o par desta frase.",
                "c": "Lei regula a ida ao rei, não quem jejua com ela.",
            },
            options=opts(("a", "criadas"), ("b", "judeus"), ("c", "lei")),
            correct="a",
            template="também eu e minhas ___ jejuaremos",
        ),
        dict(
            diff="profundezas",
            skill="interpret",
            type="choice",
            nn="03",
            question="O que o risco de Ester 4:16 ensina sobre fé no palácio?",
            ok="Certo: fé jejua e age; não é fatalismo nem recusa do perigo.",
            wrong={
                "a": "O texto não trata o jejum como mágica sem ida ao rei.",
                "c": "Ester não nega o perigo; ela o nomeia.",
                "d": "Não há aqui um culto ao palácio como salvador.",
            },
            options=opts(
                ("a", "O jejum dispensa qualquer passo seguinte no palácio."),
                ("b", "Fé jejua e depois arrisca a vida; não é fatalismo vazio."),
                ("c", "Ester ignora o perigo e trata a lei como irrelevante."),
                ("d", "O palácio é o salvador, e o jejum é só etiqueta real."),
            ),
            correct="b",
        ),
        dict(
            diff="profundezas",
            skill="interpret",
            type="order",
            nn="04",
            question="Qual sequência revela o sentido de Ester 4:16?",
            ok="Certo: o sentido vai do jejum conjunto à ida ilegal e ao risco assumido.",
            wrong={
                "a": "Começar pelo risco esconde o jejum que o prepara.",
                "c": "Essa ordem não revela o movimento de fé do texto.",
            },
            options=opts(
                ("a", "se perecer, pereci"),
                ("b", "jejuai por mim; não comais, nem bebais por três dias"),
                ("c", "irei ter com o rei, ainda que isso não é segundo a lei"),
            ),
            correct="b",
            correctOrder=["b", "c", "a"],
        ),
        dict(
            diff="profundezas",
            skill="interpret",
            type="complete",
            nn="05",
            question='Complete a frase: "Depois, irei ter com o ___, ainda que isso não é segundo a lei."',
            ok='Certo: o destino da ação é o "rei".',
            wrong={
                "a": "Dia mede o jejum, não a pessoa a quem ela irá.",
                "c": "Susã é o lugar do ajuntamento, não o destinatário da ida.",
            },
            options=opts(("a", "dia"), ("b", "rei"), ("c", "Susã")),
            correct="b",
            template="Depois, irei ter com o ___, ainda que isso não é segundo a lei.",
        ),
        dict(
            diff="profundezas",
            skill="interpret",
            type="connect",
            nn="06",
            question="O que Ester 4:16 comunica que se liga a este contexto?",
            ok="Certo: o risco vem depois do jejum, não no lugar dele.",
            wrong={
                "a": "O texto não descreve segurança jurídica prévia.",
                "c": "Não há aqui um jejum que cancele a responsabilidade de Ester.",
            },
            options=opts(
                ("a", "Segurança jurídica antes de agir"),
                ("b", "Risco depois do jejum"),
                ("c", "Jejum que cancela a responsabilidade"),
            ),
            correct="b",
            passageA={"ref": "Ester 4:16", "text": "se perecer, pereci"},
            passageB={
                "ref": "Contexto",
                "text": "Jejuar e agir: Ester arrisca a vida depois de três dias de jejum — fé que entra no palácio.",
            },
        ),
    ],
)

# ---------------------------------------------------------------------------
# M4 Ester 9:22
# ---------------------------------------------------------------------------
P4 = (
    "como os dias em que os judeus tiveram descanso dos seus inimigos e como o mês que "
    "se lhes mudou de tristeza em alegria e de pranto em festim, a fim de que os fizessem "
    "dias de banquetes e de alegria, em que enviassem quinhões uns aos outros e dádivas aos pobres."
)
LO4 = (
    "Reconhecer que Purim marca descanso dos inimigos e inversão de tristeza em alegria, com partilha."
)
bank += mission(
    "ester-livramento-02-purim",
    "Ester 9:22",
    P4,
    LO4,
    ["Ester 9:22"],
    [
        dict(
            diff="semente",
            skill="observe",
            type="true_false",
            nn="01",
            question="O texto fala de dias em que os judeus tiveram descanso dos seus inimigos.",
            ok="Certo: Ester 9:22 abre com esse descanso dos inimigos.",
            wrong={"false": "Releia o versículo: os judeus tiveram descanso dos inimigos."},
            options=tf_opts(),
            correct="true",
        ),
        dict(
            diff="semente",
            skill="observe",
            type="tap",
            nn="02",
            question='Em Ester 9:22, toque a palavra que falta em "mudou de tristeza em ___"?',
            ok='Exato: a tristeza se muda em "alegria".',
            wrong={
                "b": "Pobres recebem dádivas, mas não preenchem esta inversão.",
                "c": "Inimigos são de quem houve descanso, não o termo desta troca.",
            },
            options=opts(("a", "alegria"), ("b", "pobres"), ("c", "inimigos")),
            correct="a",
            template="mudou de tristeza em ___",
        ),
        dict(
            diff="semente",
            skill="observe",
            type="choice",
            nn="03",
            question="O que Ester 9:22 afirma sobre o mês lembrado?",
            ok="Certo: o mês mudou de tristeza em alegria e de pranto em festim.",
            wrong={
                "a": "O texto fala de descanso, não de luto permanente.",
                "b": "Há dádivas aos pobres, não silêncio sobre eles.",
                "d": "Não descreve apenas jejum sem festa.",
            },
            options=opts(
                ("a", "Foi um mês de luto permanente sem festa."),
                ("b", "Os pobres foram excluídos de qualquer partilha."),
                ("c", "Mudou de tristeza em alegria e de pranto em festim."),
                ("d", "Foi só jejum, sem banquetes nem quinhões."),
            ),
            correct="c",
        ),
        dict(
            diff="semente",
            skill="observe",
            type="order",
            nn="04",
            question="Qual sequência mostra a ordem dos fatos em Ester 9:22?",
            ok="Certo: descanso, inversão da tristeza, depois banquetes e partilha.",
            wrong={
                "b": "Essa peça não vem neste lugar do versículo.",
                "c": "As dádivas fecham o texto, não o abrem.",
            },
            options=opts(
                ("a", "os judeus tiveram descanso dos seus inimigos"),
                ("b", "o mês que se lhes mudou de tristeza em alegria e de pranto em festim"),
                ("c", "enviassem quinhões uns aos outros e dádivas aos pobres"),
            ),
            correct="a",
            correctOrder=["a", "b", "c"],
        ),
        dict(
            diff="semente",
            skill="observe",
            type="complete",
            nn="05",
            question='Complete a frase: "enviassem quinhões uns aos outros e dádivas aos ___."',
            ok='Certo: as dádivas são enviadas aos "pobres".',
            wrong={
                "a": "Alegria é o tom da festa, não o destinatário das dádivas.",
                "c": "Inimigos são de quem houve descanso, não quem recebe dádivas.",
            },
            options=opts(("a", "alegria"), ("b", "pobres"), ("c", "inimigos")),
            correct="b",
            template="enviassem quinhões uns aos outros e dádivas aos ___.",
        ),
        dict(
            diff="semente",
            skill="observe",
            type="connect",
            nn="06",
            question="O que Ester 9:22 comunica que se liga a este contexto?",
            ok="Certo: a inversão se festeja partilhando, inclusive com os pobres.",
            wrong={
                "b": "O texto não descreve luto sem festa.",
                "c": "Não há aqui uma memória só privada, sem partilha.",
            },
            options=opts(
                ("a", "Inversão que se festeja partilhando"),
                ("b", "Luto sem festa alguma"),
                ("c", "Memória só privada e fechada"),
            ),
            correct="a",
            passageA={"ref": "Ester 9:22", "text": "de tristeza em alegria e de pranto em festim"},
            passageB={
                "ref": "Contexto",
                "text": "Purim festeja a inversão: tristeza em alegria, e o povo lembra partilhando com os pobres.",
            },
        ),
        dict(
            diff="caminhada",
            skill="understand",
            type="true_false",
            nn="01",
            question="O texto descreve esses dias apenas como luto obrigatório, sem banquetes nem dádivas.",
            ok="Certo: fala de banquetes, alegria, quinhões e dádivas aos pobres.",
            wrong={"true": "Ester 9:22 manda banquetes, alegria e dádivas, não só luto."},
            options=tf_opts(),
            correct="false",
        ),
        dict(
            diff="caminhada",
            skill="understand",
            type="tap",
            nn="02",
            question='Em Ester 9:22, toque a palavra que falta em "de pranto em ___"?',
            ok='Exato: o pranto se muda em "festim".',
            wrong={
                "a": "Descanso é o que tiveram dos inimigos, não esta inversão.",
                "c": "Mês localiza o tempo, não o termo que substitui o pranto.",
            },
            options=opts(("a", "descanso"), ("b", "festim"), ("c", "mês")),
            correct="b",
            template="de pranto em ___",
        ),
        dict(
            diff="caminhada",
            skill="understand",
            type="choice",
            nn="03",
            question="O que a memória de Ester 9:22 exige além da festa?",
            ok="Certo: a alegria inclui quinhões e dádivas aos pobres.",
            wrong={
                "a": "O texto não reduz a memória a um jejum secreto.",
                "c": "Não manda apagar o nome dos pobres da festa.",
                "d": "Não há ordem de isolamento sem partilha.",
            },
            options=opts(
                ("a", "Que o povo jejuasse em segredo, sem festa."),
                ("b", "Que enviassem quinhões e dádivas também aos pobres."),
                ("c", "Que apagassem o nome dos pobres da festa."),
                ("d", "Que cada casa celebrasse isolada, sem partilha."),
            ),
            correct="b",
        ),
        dict(
            diff="caminhada",
            skill="understand",
            type="order",
            nn="04",
            question="Como se encadeiam os eventos de Ester 9:22?",
            ok="Certo: do descanso à inversão, e da inversão à partilha.",
            wrong={
                "a": "As dádivas não abrem o versículo.",
                "c": "Essa ordem embaralha o encadeamento da memória.",
            },
            options=opts(
                ("a", "enviassem quinhões uns aos outros e dádivas aos pobres"),
                ("b", "os judeus tiveram descanso dos seus inimigos"),
                ("c", "mudou de tristeza em alegria e de pranto em festim"),
            ),
            correct="b",
            correctOrder=["b", "c", "a"],
        ),
        dict(
            diff="caminhada",
            skill="understand",
            type="complete",
            nn="05",
            question='Complete a frase: "em que enviassem ___ uns aos outros e dádivas aos pobres."',
            ok='Certo: enviam "quinhões" uns aos outros.',
            wrong={
                "a": "Festim nomeia a festa, não o que se envia entre si.",
                "c": "Pranto é o que se inverte, não o que se envia.",
            },
            options=opts(("a", "festim"), ("b", "quinhões"), ("c", "pranto")),
            correct="b",
            template="em que enviassem ___ uns aos outros e dádivas aos pobres.",
        ),
        dict(
            diff="caminhada",
            skill="understand",
            type="connect",
            nn="06",
            question="O que Ester 9:22 comunica que se liga a este contexto?",
            ok="Certo: a alegria da inversão inclui os pobres.",
            wrong={
                "a": "O texto não descreve festa só da corte.",
                "b": "Não há aqui uma memória que exclui a partilha.",
            },
            options=opts(
                ("a", "Festa exclusiva da corte real"),
                ("b", "Memória sem partilha alguma"),
                ("c", "Alegria que inclui os pobres"),
            ),
            correct="c",
            passageA={"ref": "Ester 9:22", "text": "enviassem quinhões uns aos outros e dádivas aos pobres"},
            passageB={
                "ref": "Contexto",
                "text": "Purim festeja a inversão: tristeza em alegria, e o povo lembra partilhando com os pobres.",
            },
        ),
        dict(
            diff="profundezas",
            skill="interpret",
            type="true_false",
            nn="01",
            question="Purim não é só alívio: a inversão se celebra com partilha, inclusive dádivas aos pobres.",
            ok="Certo: o texto une festa, quinhões e dádivas aos pobres.",
            wrong={"false": "Ester 9:22 amarra a alegria à partilha com os pobres."},
            options=tf_opts(),
            correct="true",
        ),
        dict(
            diff="profundezas",
            skill="interpret",
            type="tap",
            nn="02",
            question='Em Ester 9:22, toque a palavra que falta em "dias de ___ e de alegria"?',
            ok='Exato: os dias são de "banquetes" e de alegria.',
            wrong={
                "b": "Pobres recebem dádivas, mas não nomeiam estes dias aqui.",
                "c": "Inimigos marcam o descanso anterior, não este par com alegria.",
            },
            options=opts(("a", "banquetes"), ("b", "pobres"), ("c", "inimigos")),
            correct="a",
            template="dias de ___ e de alegria",
        ),
        dict(
            diff="profundezas",
            skill="interpret",
            type="choice",
            nn="03",
            question="Qual sentido de Purim Ester 9:22 sustenta?",
            ok="Certo: a memória do livramento se molda na partilha com os pobres.",
            wrong={
                "a": "O texto não reduz Purim a vingança sem festa.",
                "b": "Não descreve uma festa que esquece os pobres.",
                "c": "Não há aqui um luto que substitui o festim.",
            },
            options=opts(
                ("a", "Purim é só vingança, sem alegria nem partilha."),
                ("b", "A festa apaga os pobres para honrar só a corte."),
                ("c", "O pranto deve substituir o festim para sempre."),
                ("d", "A inversão se lembra festejando e partilhando com os pobres."),
            ),
            correct="d",
        ),
        dict(
            diff="profundezas",
            skill="interpret",
            type="order",
            nn="04",
            question="Qual sequência revela o sentido de Ester 9:22?",
            ok="Certo: o sentido vai do descanso à inversão e da inversão à partilha.",
            wrong={
                "b": "Essa ordem não revela o movimento da memória.",
                "c": "Começar pelas dádivas esconde o descanso que as fundamenta.",
            },
            options=opts(
                ("a", "os judeus tiveram descanso dos seus inimigos"),
                ("b", "enviassem quinhões uns aos outros e dádivas aos pobres"),
                ("c", "mudou de tristeza em alegria e de pranto em festim"),
            ),
            correct="a",
            correctOrder=["a", "c", "b"],
        ),
        dict(
            diff="profundezas",
            skill="interpret",
            type="complete",
            nn="05",
            question='Complete a frase: "os judeus tiveram descanso dos seus ___."',
            ok='Certo: o descanso é dos "inimigos".',
            wrong={
                "b": "Pobres recebem dádivas, não são de quem se tem descanso.",
                "c": "Banquetes descrevem a festa, não este complemento.",
            },
            options=opts(("a", "inimigos"), ("b", "pobres"), ("c", "banquetes")),
            correct="a",
            template="os judeus tiveram descanso dos seus ___.",
        ),
        dict(
            diff="profundezas",
            skill="interpret",
            type="connect",
            nn="06",
            question="O que Ester 9:22 comunica que se liga a este contexto?",
            ok="Certo: lembrar o livramento inclui partilhar o que se recebeu.",
            wrong={
                "a": "O texto não descreve uma festa que esquece o pobre.",
                "c": "Não há aqui uma inversão só interior, sem gesto comunitário.",
            },
            options=opts(
                ("a", "Festa que esquece o pobre"),
                ("b", "Memória que partilha o livramento"),
                ("c", "Inversão só interior e privada"),
            ),
            correct="b",
            passageA={"ref": "Ester 9:22", "text": "dias de banquetes e de alegria"},
            passageB={
                "ref": "Contexto",
                "text": "Purim festeja a inversão: tristeza em alegria, e o povo lembra partilhando com os pobres.",
            },
        ),
    ],
)

# ---------------------------------------------------------------------------
# M5 Ester 4:14 — TB termina em pergunta; V/F só afirmações
# ---------------------------------------------------------------------------
P5 = (
    "Pois, se de todo te calares agora, de outra parte se levantará socorro e livramento "
    "para os judeus, mas tu e a casa de teu pai perecereis; quem sabe se não foste elevada "
    "a rainha para tal tempo como este?"
)
LO5 = (
    "Compreender que o livramento pode vir de outra parte, e que Ester pode ter sido elevada para aquele tempo."
)
bank += mission(
    "ester-livramento-03-desafio-providencia",
    "Ester 4:14",
    P5,
    LO5,
    ["Ester 4:14"],
    [
        dict(
            diff="semente",
            skill="observe",
            type="true_false",
            nn="01",
            question="Mardoqueu afirma que, se Ester se calar, de outra parte se levantará socorro e livramento para os judeus.",
            ok="Certo: o texto diz que o socorro se levantará de outra parte.",
            wrong={"false": "Releia Ester 4:14: o livramento não depende só do silêncio dela."},
            options=tf_opts(),
            correct="true",
        ),
        dict(
            diff="semente",
            skill="observe",
            type="tap",
            nn="02",
            question='Em Ester 4:14, toque a palavra que falta em "se de todo te ___ agora"?',
            ok='Exato: a hipótese é "se de todo te calares agora".',
            wrong={
                "b": "Rainha é o ofício dela, não o verbo desta cláusula.",
                "c": "Judeus recebem o livramento, não preenchem este verbo.",
            },
            options=opts(("a", "calares"), ("b", "rainha"), ("c", "judeus")),
            correct="a",
            template="se de todo te ___ agora",
        ),
        dict(
            diff="semente",
            skill="observe",
            type="choice",
            nn="03",
            question="O que Ester 4:14 afirma sobre Ester e a casa de seu pai?",
            ok="Certo: se ela se calar, ela e a casa de seu pai perecerão.",
            wrong={
                "b": "O texto não promete promoção da casa de seu pai.",
                "c": "Não diz que o silêncio a torna rainha de novo.",
                "d": "Não há aqui isenção de risco para a família.",
            },
            options=opts(
                ("a", "Se ela se calar, ela e a casa de seu pai perecerão."),
                ("b", "A casa de seu pai será promovida no palácio."),
                ("c", "O silêncio a tornará rainha de outra nação."),
                ("d", "Nenhum risco alcança a família se ela se calar."),
            ),
            correct="a",
        ),
        dict(
            diff="semente",
            skill="observe",
            type="order",
            nn="04",
            question="Qual sequência mostra a ordem dos fatos em Ester 4:14?",
            ok="Certo: silêncio, socorro de outra parte, e o risco da casa paterna.",
            wrong={
                "b": "Essa peça não ocupa este lugar no versículo.",
                "c": "A elevação a rainha fecha o texto, não o abre.",
            },
            options=opts(
                ("a", "se de todo te calares agora"),
                ("b", "de outra parte se levantará socorro e livramento para os judeus"),
                ("c", "tu e a casa de teu pai perecereis"),
            ),
            correct="a",
            correctOrder=["a", "b", "c"],
        ),
        dict(
            diff="semente",
            skill="observe",
            type="complete",
            nn="05",
            question='Complete a frase: "quem sabe se não foste elevada a ___ para tal tempo como este?"',
            ok='Certo: ela foi elevada a "rainha" para tal tempo.',
            wrong={
                "a": "Judeus são o povo a livrar, não o ofício dela.",
                "c": "Pai refere-se à casa que pode perecer, não a este título.",
            },
            options=opts(("a", "judeus"), ("b", "rainha"), ("c", "pai")),
            correct="b",
            template="quem sabe se não foste elevada a ___ para tal tempo como este?",
        ),
        dict(
            diff="semente",
            skill="observe",
            type="connect",
            nn="06",
            question="O que Ester 4:14 comunica que se liga a este contexto?",
            ok="Certo: o texto convoca Ester a não se calar.",
            wrong={
                "b": "O versículo não recomenda silêncio como virtude.",
                "c": "Não apresenta o palácio como fim em si mesmo.",
            },
            options=opts(
                ("a", "Chamado a não calar"),
                ("b", "Silêncio como virtude real"),
                ("c", "Palácio como fim em si"),
            ),
            correct="a",
            passageA={"ref": "Ester 4:14", "text": "se de todo te calares agora"},
            passageB={
                "ref": "Contexto",
                "text": "Providência: quem sabe se não foste rainha para este tempo — Deus livra, e chama a não calar.",
            },
        ),
        dict(
            diff="caminhada",
            skill="understand",
            type="true_false",
            nn="01",
            question="O texto afirma que o livramento dos judeus depende só de Ester, sem outra possibilidade de socorro.",
            ok="Certo: de outra parte se levantará socorro e livramento.",
            wrong={"true": "Ester 4:14 diz que o socorro pode vir de outra parte."},
            options=tf_opts(),
            correct="false",
        ),
        dict(
            diff="caminhada",
            skill="understand",
            type="tap",
            nn="02",
            question='Em Ester 4:14, toque a palavra que falta em "se levantará socorro e ___ para os judeus"?',
            ok='Exato: além de socorro, o texto fala de "livramento".',
            wrong={
                "a": "Pai refere-se à casa que pode perecer, não a este par.",
                "c": "Tempo fecha o versículo, não o que se levanta para os judeus.",
            },
            options=opts(("a", "pai"), ("b", "livramento"), ("c", "tempo")),
            correct="b",
            template="se levantará socorro e ___ para os judeus",
        ),
        dict(
            diff="caminhada",
            skill="understand",
            type="choice",
            nn="03",
            question="Como Ester 4:14 relaciona o trono de Ester e aquele momento?",
            ok="Certo: ela pode ter sido elevada a rainha para aquele tempo.",
            wrong={
                "a": "O texto não trata o trono como acaso vazio.",
                "b": "Não diz que a coroa a isenta de falar.",
                "d": "Não reduz a rainha a um enfeite sem vocação.",
            },
            options=opts(
                ("a", "O trono é acaso vazio, sem relação com aquele tempo."),
                ("b", "A coroa a isenta de falar em favor do povo."),
                ("c", "Ela pode ter sido elevada a rainha para aquele tempo."),
                ("d", "Ser rainha a torna só enfeite, sem vocação alguma."),
            ),
            correct="c",
        ),
        dict(
            diff="caminhada",
            skill="understand",
            type="order",
            nn="04",
            question="Como se encadeiam os eventos de Ester 4:14?",
            ok="Certo: o silêncio, o socorro de outra parte e o risco da casa.",
            wrong={
                "a": "Essa ordem embaralha o encadeamento da fala.",
                "c": "O risco da casa não abre o argumento.",
            },
            options=opts(
                ("a", "tu e a casa de teu pai perecereis"),
                ("b", "se de todo te calares agora"),
                ("c", "de outra parte se levantará socorro e livramento para os judeus"),
            ),
            correct="b",
            correctOrder=["b", "c", "a"],
        ),
        dict(
            diff="caminhada",
            skill="understand",
            type="complete",
            nn="05",
            question='Complete a frase: "tu e a casa de teu pai ___."',
            ok='Certo: a consequência nomeada é "perecereis".',
            wrong={
                "a": "Calares é a hipótese inicial, não este verbo da casa.",
                "c": "Elevada descreve Ester, não o destino da casa do pai.",
            },
            options=opts(("a", "calares"), ("b", "perecereis"), ("c", "elevada")),
            correct="b",
            template="tu e a casa de teu pai ___.",
        ),
        dict(
            diff="caminhada",
            skill="understand",
            type="connect",
            nn="06",
            question="O que Ester 4:14 comunica que se liga a este contexto?",
            ok="Certo: a rainha pode ter sido posta ali para aquele tempo.",
            wrong={
                "a": "O texto não trata o trono como prêmio vazio.",
                "b": "Não apresenta o silêncio como estratégia sábia.",
            },
            options=opts(
                ("a", "Trono como prêmio vazio"),
                ("b", "Silêncio como estratégia sábia"),
                ("c", "Rainha para este tempo"),
            ),
            correct="c",
            passageA={"ref": "Ester 4:14", "text": "quem sabe se não foste elevada a rainha para tal tempo como este?"},
            passageB={
                "ref": "Contexto",
                "text": "Providência: quem sabe se não foste rainha para este tempo — Deus livra, e chama a não calar.",
            },
        ),
        dict(
            diff="profundezas",
            skill="interpret",
            type="true_false",
            nn="01",
            question="O silêncio de Ester seria irrelevante, pois o texto não menciona risco para ela nem para a casa de seu pai.",
            ok="Certo: o texto diz que ela e a casa de seu pai pereceriam.",
            wrong={"true": "Ester 4:14 liga o silêncio ao risco de perecer, não à irrelevância."},
            options=tf_opts(),
            correct="false",
        ),
        dict(
            diff="profundezas",
            skill="interpret",
            type="tap",
            nn="02",
            question='Em Ester 4:14, toque a palavra que falta em "para tal ___ como este"?',
            ok='Exato: ela pode ter sido elevada para tal "tempo".',
            wrong={
                "a": "Pai refere-se à casa em risco, não a esta palavra.",
                "b": "Socorro é o que se levanta de outra parte, não esta lacuna.",
            },
            options=opts(("a", "pai"), ("b", "socorro"), ("c", "tempo")),
            correct="c",
            template="para tal ___ como este",
        ),
        dict(
            diff="profundezas",
            skill="interpret",
            type="choice",
            nn="03",
            question="Qual leitura de providência Ester 4:14 sustenta?",
            ok="Certo: Deus pode livrar por outro caminho e ainda chama a não calar.",
            wrong={
                "a": "O texto não ensina que Ester é a única fonte de livramento.",
                "c": "Não trata o silêncio como fé madura.",
                "d": "Não reduz a coroa a acaso sem vocação.",
            },
            options=opts(
                ("a", "Ester é a única fonte possível de livramento dos judeus."),
                ("b", "Deus pode livrar por outro caminho e ainda chama a não calar."),
                ("c", "Calar-se é a forma mais madura de confiar no palácio."),
                ("d", "A coroa é acaso puro, sem chamado para aquele tempo."),
            ),
            correct="b",
        ),
        dict(
            diff="profundezas",
            skill="interpret",
            type="order",
            nn="04",
            question="Qual sequência revela o sentido de Ester 4:14?",
            ok="Certo: o sentido vai do silêncio ao livramento de outra parte e ao chamado do tempo.",
            wrong={
                "a": "Começar pelo tempo esconde o aviso contra calar.",
                "c": "Essa ordem não revela o movimento de providência do texto.",
            },
            options=opts(
                ("a", "quem sabe se não foste elevada a rainha para tal tempo como este"),
                ("b", "se de todo te calares agora"),
                ("c", "de outra parte se levantará socorro e livramento para os judeus"),
            ),
            correct="b",
            correctOrder=["b", "c", "a"],
        ),
        dict(
            diff="profundezas",
            skill="interpret",
            type="complete",
            nn="05",
            question='Complete a frase: "de outra ___ se levantará socorro e livramento para os judeus."',
            ok='Certo: o socorro se levantará de outra "parte".',
            wrong={
                "b": "Rainha é o ofício de Ester, não o lugar deste socorro.",
                "c": "Tempo fecha o versículo, não o complemento de outra.",
            },
            options=opts(("a", "parte"), ("b", "rainha"), ("c", "tempo")),
            correct="a",
            template="de outra ___ se levantará socorro e livramento para os judeus.",
        ),
        dict(
            diff="profundezas",
            skill="interpret",
            type="connect",
            nn="06",
            question="O que Ester 4:14 comunica que se liga a este contexto?",
            ok="Certo: o livramento convoca Ester a agir, não a calar.",
            wrong={
                "a": "O texto não ensina destino fechado sem chamado.",
                "c": "Não apresenta o silêncio como fé no palácio.",
            },
            options=opts(
                ("a", "Destino fechado sem chamado"),
                ("b", "Livramento que convoca a agir"),
                ("c", "Silêncio como fé no palácio"),
            ),
            correct="b",
            passageA={"ref": "Ester 4:14", "text": "de outra parte se levantará socorro e livramento para os judeus"},
            passageB={
                "ref": "Contexto",
                "text": "Providência: quem sabe se não foste rainha para este tempo — Deus livra, e chama a não calar.",
            },
        ),
    ],
)

assert len(bank) == 90, len(bank)
OUT.write_text(json.dumps(bank, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
print(f"Wrote {OUT} ({len(bank)} questions)")
