#!/usr/bin/env python3
"""Gera perguntas-v2/reis.json (7 missões × 18). Trail reis."""
import json
from pathlib import Path

OUT = Path(__file__).with_name("reis.json")


def q(
    trail,
    section,
    diff,
    skill,
    typ,
    nn,
    verse_ref,
    lo,
    evidence,
    question,
    feedback_correct,
    feedback_wrong,
    options,
    correct,
    passage,
    **extra,
):
    short = {"semente": "sem", "caminhada": "cam", "profundezas": "pro"}[diff]
    item = {
        "difficulty": diff,
        "skill": skill,
        "verseRef": verse_ref,
        "learningObjective": lo,
        "evidence": evidence,
        "type": typ,
        "question": question,
        "prompt": question,
        "cue": question,
        "feedbackCorrect": feedback_correct,
        "feedbackWrong": feedback_wrong,
        "options": options,
        "correctOptionId": correct,
        "correctAnswer": correct,
        "passageText": passage,
        "trail": trail,
        "section": section,
        "id": f"{trail}-{short}-{section}-{nn}",
    }
    item.update(extra)
    assert len(feedback_correct) <= 100, (len(feedback_correct), feedback_correct)
    return item


def tf_opts():
    return [{"id": "true", "text": "Verdadeiro"}, {"id": "false", "text": "Falso"}]


def opts(*pairs):
    return [{"id": i, "text": t} for i, t in pairs]


def mission(section, verse, passage, lo, evidence, items):
    out = []
    for spec in items:
        extra = {}
        for k in ("template", "correctOrder", "passageA", "passageB"):
            if k in spec:
                extra[k] = spec[k]
        out.append(
            q(
                "reis",
                section,
                spec["diff"],
                spec["skill"],
                spec["type"],
                spec["nn"],
                verse,
                lo,
                evidence,
                spec["question"],
                spec["ok"],
                spec["wrong"],
                spec["options"],
                spec["correct"],
                passage,
                **extra,
            )
        )
    return out


bank = []

# ---------------------------------------------------------------------------
# M1 — 1 Reis 3:9 — sabedoria e o templo
# ---------------------------------------------------------------------------
P1 = (
    "Dá, pois, ao teu servo um coração dócil para poder julgar ao teu povo "
    "e para poder discernir entre o bem e o mal. Por que quem poderá julgar "
    "a este teu povo tão grande?"
)
LO1 = "Reconhecer que Salomão pede a Deus um coração dócil para julgar o povo."
INS1 = "Salomão pede coração dócil para julgar."

bank += mission(
    "reis-salomao-01-sabedoria-e-o-templo",
    "1 Reis 3:9",
    P1,
    LO1,
    ["1 Reis 3:9"],
    [
        # SEMENTE
        dict(
            diff="semente",
            skill="observe",
            type="true_false",
            nn="01",
            question="Salomão pede a Deus um coração dócil para julgar o povo.",
            ok="Certo: o pedido é por um coração dócil para julgar.",
            wrong={"false": "O texto registra exatamente esse pedido."},
            options=tf_opts(),
            correct="true",
        ),
        dict(
            diff="semente",
            skill="observe",
            type="tap",
            nn="02",
            question='Em 1 Reis 3:9, toque a palavra que falta em "um coração ___ para poder julgar"?',
            ok='Exato: coração "dócil" para julgar.',
            wrong={
                "b": "Servo é quem pede; a lacuna pede dócil.",
                "c": "Povo é quem será julgado; aqui falta dócil.",
            },
            options=opts(("a", "dócil"), ("b", "servo"), ("c", "povo")),
            correct="a",
            template="um coração ___ para poder julgar",
        ),
        dict(
            diff="semente",
            skill="observe",
            type="choice",
            nn="03",
            question="O que Salomão pede explicitamente em 1 Reis 3:9?",
            ok="Certo: pede coração dócil para julgar e discernir.",
            wrong={
                "b": "O texto não registra pedido de riqueza.",
                "c": "Não há pedido de longa vida neste versículo.",
                "d": "Vitória militar não é o pedido aqui.",
            },
            options=opts(
                ("a", "Um coração dócil para julgar e discernir o bem e o mal"),
                ("b", "Riquezas e ouro para o reino"),
                ("c", "Longa vida para o rei"),
                ("d", "Vitória sobre os inimigos"),
            ),
            correct="a",
        ),
        dict(
            diff="semente",
            skill="observe",
            type="order",
            nn="04",
            question="Qual sequência mostra a ordem dos fatos em 1 Reis 3:9?",
            ok="Certo: pedido, propósito de julgar, depois o discernimento.",
            wrong={
                "b": "O pedido do coração dócil abre o versículo.",
                "c": "Releia a ordem do pedido de Salomão.",
            },
            options=opts(
                ("a", "Dá ao teu servo um coração dócil"),
                ("b", "para poder julgar ao teu povo"),
                ("c", "e para poder discernir entre o bem e o mal"),
            ),
            correct="a",
            correctOrder=["a", "b", "c"],
        ),
        dict(
            diff="semente",
            skill="observe",
            type="complete",
            nn="05",
            question='Complete: "para poder ___ entre o bem e o mal."',
            ok='Certo: "discernir" entre o bem e o mal.',
            wrong={
                "a": "Julgar é outro verbo do versículo; aqui é discernir.",
                "c": "Dócil qualifica o coração, não completa esta frase.",
            },
            options=opts(("a", "julgar"), ("b", "discernir"), ("c", "dócil")),
            correct="b",
            template="para poder ___ entre o bem e o mal.",
        ),
        dict(
            diff="semente",
            skill="observe",
            type="connect",
            nn="06",
            question="O que 1 Reis 3:9 comunica que se liga a este contexto?",
            ok="Certo: Salomão pede coração dócil para julgar.",
            wrong={
                "a": "O texto não registra pedido de riquezas.",
                "c": "Não há aqui pedido de exército ou poder.",
            },
            options=opts(
                ("a", "Pedido de riquezas"),
                ("b", "Coração dócil para julgar"),
                ("c", "Pedido de poder militar"),
            ),
            correct="b",
            passageA={"ref": "1 Reis 3:9", "text": P1},
            passageB={"ref": "Contexto", "text": INS1},
        ),
        # CAMINHADA
        dict(
            diff="caminhada",
            skill="understand",
            type="true_false",
            nn="01",
            question="O coração dócil que Salomão pede serve para julgar o povo e discernir o bem e o mal.",
            ok="Certo: o pedido une julgamento e discernimento.",
            wrong={"false": "O texto liga coração dócil a julgar e discernir."},
            options=tf_opts(),
            correct="true",
        ),
        dict(
            diff="caminhada",
            skill="understand",
            type="tap",
            nn="02",
            question='Em 1 Reis 3:9, toque a palavra que falta em "para poder ___ ao teu povo"?',
            ok='Exato: para poder "julgar" ao teu povo.',
            wrong={
                "a": "Discernir aparece depois; aqui o verbo é julgar.",
                "c": "Dócil qualifica o coração, não este verbo.",
            },
            options=opts(("a", "discernir"), ("b", "julgar"), ("c", "dócil")),
            correct="b",
            template="para poder ___ ao teu povo",
        ),
        dict(
            diff="caminhada",
            skill="understand",
            type="choice",
            nn="03",
            question="Como o pedido de Salomão liga coração dócil e governo do povo?",
            ok="Certo: o coração dócil habilita a julgar com discernimento.",
            wrong={
                "a": "O texto não reduz o pedido a eloquência.",
                "c": "Não há pedido de força física aqui.",
                "d": "Riqueza não é o meio de julgamento no versículo.",
            },
            options=opts(
                ("a", "O coração dócil serve só para falar bem em público"),
                ("b", "O coração dócil habilita a julgar e discernir o bem e o mal"),
                ("c", "O coração dócil garante força militar ao rei"),
                ("d", "O coração dócil multiplica as riquezas do reino"),
            ),
            correct="b",
        ),
        dict(
            diff="caminhada",
            skill="understand",
            type="order",
            nn="04",
            question="Como se encadeiam os eventos de 1 Reis 3:9?",
            ok="Certo: pedido, julgamento do povo, discernimento do bem e do mal.",
            wrong={
                "b": "O discernimento vem depois do julgamento no pedido.",
                "c": "Releia o encadeamento do pedido.",
            },
            options=opts(
                ("a", "Dá ao teu servo um coração dócil"),
                ("b", "para poder julgar ao teu povo"),
                ("c", "e para poder discernir entre o bem e o mal"),
            ),
            correct="a",
            correctOrder=["a", "b", "c"],
        ),
        dict(
            diff="caminhada",
            skill="understand",
            type="complete",
            nn="05",
            question='Complete: "Dá, pois, ao teu ___ um coração dócil."',
            ok='Certo: "servo" — Salomão se apresenta assim.',
            wrong={
                "b": "Povo é quem será julgado; aqui é servo.",
                "c": "Dócil qualifica o coração, não este lugar.",
            },
            options=opts(("a", "servo"), ("b", "povo"), ("c", "dócil")),
            correct="a",
            template="Dá, pois, ao teu ___ um coração dócil.",
        ),
        dict(
            diff="caminhada",
            skill="understand",
            type="connect",
            nn="06",
            question="O que 1 Reis 3:9 comunica que se liga a este contexto?",
            ok="Certo: o pedido une docilidade e discernimento para julgar.",
            wrong={
                "a": "O texto não prioriza fama pessoal.",
                "c": "Não há pedido de autonomia sem Deus.",
            },
            options=opts(
                ("a", "Busca de fama pessoal"),
                ("b", "Docilidade para julgar bem"),
                ("c", "Autonomia sem depender de Deus"),
            ),
            correct="b",
            passageA={"ref": "1 Reis 3:9", "text": P1},
            passageB={"ref": "Contexto", "text": INS1},
        ),
        # PROFUNDZAS
        dict(
            diff="profundezas",
            skill="interpret",
            type="true_false",
            nn="01",
            question="Salomão reconhece que só Deus pode capacitar alguém a julgar um povo tão grande.",
            ok="Certo: o pedido e a pergunta final mostram essa dependência.",
            wrong={"false": "A pergunta final revela a incapacidade humana de julgar sozinho."},
            options=tf_opts(),
            correct="true",
        ),
        dict(
            diff="profundezas",
            skill="interpret",
            type="tap",
            nn="02",
            question='Em 1 Reis 3:9, toque a palavra que falta em "discernir entre o ___ e o mal"?',
            ok='Exato: entre o "bem" e o mal.',
            wrong={
                "b": "Povo é o objeto do julgamento; aqui falta bem.",
                "c": "Dócil qualifica o coração, não esta oposição.",
            },
            options=opts(("a", "bem"), ("b", "povo"), ("c", "dócil")),
            correct="a",
            template="discernir entre o ___ e o mal",
        ),
        dict(
            diff="profundezas",
            skill="interpret",
            type="choice",
            nn="03",
            question="O que o pedido de Salomão revela sobre a natureza do governo segundo Deus?",
            ok="Certo: governar exige discernimento dado por Deus, não autossuficiência.",
            wrong={
                "a": "O texto não exalta a sabedoria natural do rei.",
                "c": "Não há aqui redução do governo a força.",
                "d": "O pedido não busca popularidade.",
            },
            options=opts(
                ("a", "O rei já possui, por si, toda a sabedoria necessária"),
                ("b", "Julgar o povo exige coração dócil e discernimento de Deus"),
                ("c", "O poder militar basta para governar com justiça"),
                ("d", "O rei deve buscar primeiro a aprovação do povo"),
            ),
            correct="b",
        ),
        dict(
            diff="profundezas",
            skill="interpret",
            type="order",
            nn="04",
            question="Qual sequência revela o sentido de 1 Reis 3:9?",
            ok="Certo: pedido humilde, serviço ao povo, discernimento moral.",
            wrong={
                "b": "O discernimento fecha o sentido do pedido.",
                "c": "Releia a lógica teológica do pedido.",
            },
            options=opts(
                ("a", "Dá ao teu servo um coração dócil"),
                ("b", "para poder julgar ao teu povo"),
                ("c", "e para poder discernir entre o bem e o mal"),
            ),
            correct="a",
            correctOrder=["a", "b", "c"],
        ),
        dict(
            diff="profundezas",
            skill="interpret",
            type="complete",
            nn="05",
            question='Complete: "Por que quem poderá ___ a este teu povo tão grande?"',
            ok='Certo: "julgar" — a pergunta expõe a grandeza da tarefa.',
            wrong={
                "b": "Discernir aparece antes; aqui o verbo é julgar.",
                "c": "Dócil não completa esta pergunta.",
            },
            options=opts(("a", "julgar"), ("b", "discernir"), ("c", "dócil")),
            correct="a",
            template="Por que quem poderá ___ a este teu povo tão grande?",
        ),
        dict(
            diff="profundezas",
            skill="interpret",
            type="connect",
            nn="06",
            question="O que 1 Reis 3:9 comunica que se liga a este contexto?",
            ok="Certo: governar exige coração dócil dado por Deus.",
            wrong={
                "a": "O texto não celebra autossuficiência real.",
                "c": "Não há aqui prioridade de riqueza sobre discernimento.",
            },
            options=opts(
                ("a", "Autossuficiência do rei"),
                ("b", "Dependência de Deus para julgar"),
                ("c", "Riqueza acima do discernimento"),
            ),
            correct="b",
            passageA={"ref": "1 Reis 3:9", "text": P1},
            passageB={"ref": "Contexto", "text": INS1},
        ),
    ],
)

# ---------------------------------------------------------------------------
# M2 — 1 Reis 11:4 — o coração dividido
# ---------------------------------------------------------------------------
P2 = (
    "Sendo já velho, suas mulheres perverteram-lhe o coração para seguir "
    "outros deuses; e o seu coração não foi perfeito para com Jeová, seu "
    "Deus, como o fora o coração de Davi, seu pai."
)
LO2 = "Reconhecer que as mulheres de Salomão perverteram seu coração; ele não permaneceu perfeito com Jeová."
INS2 = "Coração dividido: mulheres pervertem; não permanece perfeito."

bank += mission(
    "reis-salomao-02-o-coracao-dividido",
    "1 Reis 11:4",
    P2,
    LO2,
    ["1 Reis 11:4"],
    [
        dict(
            diff="semente",
            skill="observe",
            type="true_false",
            nn="01",
            question="As mulheres de Salomão perverteram-lhe o coração para seguir outros deuses.",
            ok="Certo: o texto afirma essa perversão do coração.",
            wrong={"false": "1 Reis 11:4 registra exatamente isso."},
            options=tf_opts(),
            correct="true",
        ),
        dict(
            diff="semente",
            skill="observe",
            type="tap",
            nn="02",
            question='Em 1 Reis 11:4, toque a palavra que falta em "suas mulheres ___-lhe o coração"?',
            ok='Exato: "perverteram"-lhe o coração.',
            wrong={
                "b": "Velho situa a idade; o verbo é perverteram.",
                "c": "Deuses é o alvo; aqui falta o verbo.",
            },
            options=opts(("a", "perverteram"), ("b", "velho"), ("c", "deuses")),
            correct="a",
            template="suas mulheres ___-lhe o coração",
        ),
        dict(
            diff="semente",
            skill="observe",
            type="choice",
            nn="03",
            question="O que 1 Reis 11:4 afirma sobre o coração de Salomão?",
            ok="Certo: não foi perfeito para com Jeová, ao contrário de Davi.",
            wrong={
                "b": "O texto não diz que o coração permaneceu íntegro.",
                "c": "Não há afirmação de fidelidade exclusiva a Jeová.",
                "d": "O texto não nega a comparação com Davi.",
            },
            options=opts(
                ("a", "Não foi perfeito para com Jeová, como o de Davi"),
                ("b", "Permaneceu íntegro até o fim da vida"),
                ("c", "Seguiu somente a Jeová, sem outros deuses"),
                ("d", "Superou o coração de Davi, seu pai"),
            ),
            correct="a",
        ),
        dict(
            diff="semente",
            skill="observe",
            type="order",
            nn="04",
            question="Qual sequência mostra a ordem dos fatos em 1 Reis 11:4?",
            ok="Certo: velhice, perversão pelas mulheres, contraste com Davi.",
            wrong={
                "b": "A velhice abre o relato antes da perversão.",
                "c": "Releia a ordem do versículo.",
            },
            options=opts(
                ("a", "Sendo já velho"),
                ("b", "suas mulheres perverteram-lhe o coração para seguir outros deuses"),
                ("c", "o seu coração não foi perfeito para com Jeová, como o de Davi"),
            ),
            correct="a",
            correctOrder=["a", "b", "c"],
        ),
        dict(
            diff="semente",
            skill="observe",
            type="complete",
            nn="05",
            question='Complete: "o seu coração não foi ___ para com Jeová."',
            ok='Certo: não foi "perfeito" para com Jeová.',
            wrong={
                "a": "Velho situa a idade; aqui a palavra é perfeito.",
                "c": "Deuses é o alvo da perversão, não esta lacuna.",
            },
            options=opts(("a", "velho"), ("b", "perfeito"), ("c", "deuses")),
            correct="b",
            template="o seu coração não foi ___ para com Jeová.",
        ),
        dict(
            diff="semente",
            skill="observe",
            type="connect",
            nn="06",
            question="O que 1 Reis 11:4 comunica que se liga a este contexto?",
            ok="Certo: coração dividido — mulheres pervertem; não permanece perfeito.",
            wrong={
                "a": "O texto não celebra fidelidade plena de Salomão.",
                "c": "Não há aqui reforma cultual bem-sucedida.",
            },
            options=opts(
                ("a", "Fidelidade plena a Jeová"),
                ("b", "Coração dividido e imperfeito"),
                ("c", "Reforma cultual vitoriosa"),
            ),
            correct="b",
            passageA={"ref": "1 Reis 11:4", "text": P2},
            passageB={"ref": "Contexto", "text": INS2},
        ),
        dict(
            diff="caminhada",
            skill="understand",
            type="true_false",
            nn="01",
            question="A perversão do coração de Salomão leva-o a seguir outros deuses, ao contrário de Davi.",
            ok="Certo: o texto liga perversão, idolatria e contraste com Davi.",
            wrong={"false": "1 Reis 11:4 une esses três elementos."},
            options=tf_opts(),
            correct="true",
        ),
        dict(
            diff="caminhada",
            skill="understand",
            type="tap",
            nn="02",
            question='Em 1 Reis 11:4, toque a palavra que falta em "para seguir outros ___"?',
            ok='Exato: outros "deuses".',
            wrong={
                "a": "Mulheres são quem pervertem; a lacuna pede deuses.",
                "c": "Coração é o que é pervertido; aqui falta deuses.",
            },
            options=opts(("a", "mulheres"), ("b", "deuses"), ("c", "coração")),
            correct="b",
            template="para seguir outros ___",
        ),
        dict(
            diff="caminhada",
            skill="understand",
            type="choice",
            nn="03",
            question="Como 1 Reis 11:4 relaciona as mulheres de Salomão e sua relação com Jeová?",
            ok="Certo: elas pervertem o coração; ele deixa de ser perfeito com Jeová.",
            wrong={
                "a": "O texto não diz que as mulheres o fortaleceram na fé.",
                "c": "Não há afirmação de neutralidade religiosa.",
                "d": "O contraste com Davi mostra perda, não ganho.",
            },
            options=opts(
                ("a", "As mulheres o confirmaram na fidelidade a Jeová"),
                ("b", "As mulheres perverteram o coração; ele não ficou perfeito com Jeová"),
                ("c", "As mulheres não influenciaram a religião do rei"),
                ("d", "As mulheres o fizeram superar o coração de Davi"),
            ),
            correct="b",
        ),
        dict(
            diff="caminhada",
            skill="understand",
            type="order",
            nn="04",
            question="Como se encadeiam os eventos de 1 Reis 11:4?",
            ok="Certo: velhice, perversão idolátrica, imperfeição perante Jeová.",
            wrong={
                "b": "A comparação com Davi fecha o contraste.",
                "c": "Releia o encadeamento causal do versículo.",
            },
            options=opts(
                ("a", "Sendo já velho"),
                ("b", "suas mulheres perverteram-lhe o coração para seguir outros deuses"),
                ("c", "o seu coração não foi perfeito para com Jeová, como o de Davi"),
            ),
            correct="a",
            correctOrder=["a", "b", "c"],
        ),
        dict(
            diff="caminhada",
            skill="understand",
            type="complete",
            nn="05",
            question='Complete: "como o fora o coração de ___, seu pai."',
            ok='Certo: "Davi", seu pai.',
            wrong={
                "b": "Jeová é o Deus; aqui o nome é Davi.",
                "c": "Salomão é o sujeito; a comparação é com Davi.",
            },
            options=opts(("a", "Davi"), ("b", "Jeová"), ("c", "Salomão")),
            correct="a",
            template="como o fora o coração de ___, seu pai.",
        ),
        dict(
            diff="caminhada",
            skill="understand",
            type="connect",
            nn="06",
            question="O que 1 Reis 11:4 comunica que se liga a este contexto?",
            ok="Certo: influência idolátrica divide o coração do rei.",
            wrong={
                "a": "O texto não celebra lealdade exclusiva.",
                "c": "Não há aqui maturidade espiritual crescente.",
            },
            options=opts(
                ("a", "Lealdade exclusiva a Jeová"),
                ("b", "Influência que divide o coração"),
                ("c", "Maturidade espiritual crescente"),
            ),
            correct="b",
            passageA={"ref": "1 Reis 11:4", "text": P2},
            passageB={"ref": "Contexto", "text": INS2},
        ),
        dict(
            diff="profundezas",
            skill="interpret",
            type="true_false",
            nn="01",
            question="O contraste com Davi mostra que Salomão deixou de manter um coração íntegro perante Jeová.",
            ok="Certo: o texto mede Salomão pela fidelidade do pai.",
            wrong={"false": "A comparação com Davi expõe a falha do coração."},
            options=tf_opts(),
            correct="true",
        ),
        dict(
            diff="profundezas",
            skill="interpret",
            type="tap",
            nn="02",
            question='Em 1 Reis 11:4, toque a palavra que falta em "não foi ___ para com Jeová"?',
            ok='Exato: não foi "perfeito".',
            wrong={
                "b": "Velho situa a idade; aqui falta perfeito.",
                "c": "Deuses é o alvo da perversão, não esta lacuna.",
            },
            options=opts(("a", "perfeito"), ("b", "velho"), ("c", "deuses")),
            correct="a",
            template="não foi ___ para com Jeová",
        ),
        dict(
            diff="profundezas",
            skill="interpret",
            type="choice",
            nn="03",
            question="O que 1 Reis 11:4 ensina sobre o perigo de um coração dividido?",
            ok="Certo: vínculos que pervertem o coração afastam da fidelidade a Jeová.",
            wrong={
                "a": "O texto não trata a idolatria como detalhe menor.",
                "c": "A velhice não justifica a divisão do coração.",
                "d": "O contraste com Davi mostra perda, não progresso.",
            },
            options=opts(
                ("a", "Seguir outros deuses é detalhe secundário na vida do rei"),
                ("b", "Influências que pervertem o coração quebram a fidelidade a Jeová"),
                ("c", "A velhice torna inevitável e inocente a divisão do coração"),
                ("d", "Dividir o coração com outros deuses aperfeiçoa a fé de Davi"),
            ),
            correct="b",
        ),
        dict(
            diff="profundezas",
            skill="interpret",
            type="order",
            nn="04",
            question="Qual sequência revela o sentido de 1 Reis 11:4?",
            ok="Certo: vulnerabilidade, perversão idolátrica, falha perante Jeová.",
            wrong={
                "b": "A falha perante Jeová fecha o sentido do relato.",
                "c": "Releia a lógica teológica do versículo.",
            },
            options=opts(
                ("a", "Sendo já velho"),
                ("b", "suas mulheres perverteram-lhe o coração para seguir outros deuses"),
                ("c", "o seu coração não foi perfeito para com Jeová, como o de Davi"),
            ),
            correct="a",
            correctOrder=["a", "b", "c"],
        ),
        dict(
            diff="profundezas",
            skill="interpret",
            type="complete",
            nn="05",
            question='Complete: "suas mulheres perverteram-lhe o ___ para seguir outros deuses."',
            ok='Certo: o "coração" é o que é pervertido.',
            wrong={
                "b": "Pai é Davi; aqui a palavra é coração.",
                "c": "Deus é Jeová; a lacuna pede coração.",
            },
            options=opts(("a", "coração"), ("b", "pai"), ("c", "Deus")),
            correct="a",
            template="suas mulheres perverteram-lhe o ___ para seguir outros deuses.",
        ),
        dict(
            diff="profundezas",
            skill="interpret",
            type="connect",
            nn="06",
            question="O que 1 Reis 11:4 comunica que se liga a este contexto?",
            ok="Certo: coração dividido não permanece perfeito com Jeová.",
            wrong={
                "a": "O texto não afirma perseverança íntegra.",
                "c": "Não há aqui progresso espiritual sob idolatria.",
            },
            options=opts(
                ("a", "Perseverança íntegra até o fim"),
                ("b", "Divisão que quebra a perfeição"),
                ("c", "Progresso espiritual sob idolatria"),
            ),
            correct="b",
            passageA={"ref": "1 Reis 11:4", "text": P2},
            passageB={"ref": "Contexto", "text": INS2},
        ),
    ],
)

# ---------------------------------------------------------------------------
# M3 — 1 Reis 12:16 — norte e sul
# ---------------------------------------------------------------------------
P3 = (
    "Vendo o povo que o rei não lhe dava ouvidos, respondeu-lhe: Que parte "
    "temos nós em Davi? Nem temos herança no filho de Jessé. Às vossas "
    "tendas, ó Israel! Agora, cuida da tua casa, ó Davi! Assim, Israel se "
    "foi para as suas tendas."
)
LO3 = "Reconhecer que o reino se parte: Israel se vai para as suas tendas."
INS3 = "Reino se parte: Israel às tendas."

bank += mission(
    "reis-dividido-01-norte-e-sul",
    "1 Reis 12:16",
    P3,
    LO3,
    ["1 Reis 12:16"],
    [
        dict(
            diff="semente",
            skill="observe",
            type="true_false",
            nn="01",
            question="O povo responde que não tem parte em Davi e se vai para as suas tendas.",
            ok="Certo: o texto registra essa ruptura e a ida às tendas.",
            wrong={"false": "1 Reis 12:16 afirma exatamente isso."},
            options=tf_opts(),
            correct="true",
        ),
        dict(
            diff="semente",
            skill="observe",
            type="tap",
            nn="02",
            question='Em 1 Reis 12:16, toque a palavra que falta em "Às vossas ___, ó Israel!"?',
            ok='Exato: às vossas "tendas".',
            wrong={
                "b": "Davi é o nome rejeitado; a lacuna pede tendas.",
                "c": "Herança é o que negam; aqui falta tendas.",
            },
            options=opts(("a", "tendas"), ("b", "Davi"), ("c", "herança")),
            correct="a",
            template="Às vossas ___, ó Israel!",
        ),
        dict(
            diff="semente",
            skill="observe",
            type="choice",
            nn="03",
            question="O que o povo declara explicitamente em 1 Reis 12:16?",
            ok="Certo: nega parte em Davi e herança no filho de Jessé.",
            wrong={
                "b": "O texto não registra renovação da lealdade.",
                "c": "Não há pedido de união sob Roboão aqui.",
                "d": "O povo se afasta, não permanece.",
            },
            options=opts(
                ("a", "Não tem parte em Davi nem herança no filho de Jessé"),
                ("b", "Renova a lealdade à casa de Davi"),
                ("c", "Pede que o rei continue a unir todo Israel"),
                ("d", "Permanece junto do rei na capital"),
            ),
            correct="a",
        ),
        dict(
            diff="semente",
            skill="observe",
            type="order",
            nn="04",
            question="Qual sequência mostra a ordem dos fatos em 1 Reis 12:16?",
            ok="Certo: rejeição, convocação às tendas, Israel se vai.",
            wrong={
                "b": "A rejeição de Davi vem antes da ida às tendas.",
                "c": "Releia a ordem do versículo.",
            },
            options=opts(
                ("a", "Que parte temos nós em Davi? Nem herança no filho de Jessé"),
                ("b", "Às vossas tendas, ó Israel! Agora, cuida da tua casa, ó Davi"),
                ("c", "Assim, Israel se foi para as suas tendas"),
            ),
            correct="a",
            correctOrder=["a", "b", "c"],
        ),
        dict(
            diff="semente",
            skill="observe",
            type="complete",
            nn="05",
            question='Complete: "Nem temos ___ no filho de Jessé."',
            ok='Certo: nem têm "herança" no filho de Jessé.',
            wrong={
                "a": "Tendas vem depois; aqui a palavra é herança.",
                "c": "Davi é o nome rejeitado; a lacuna pede herança.",
            },
            options=opts(("a", "tendas"), ("b", "herança"), ("c", "Davi")),
            correct="b",
            template="Nem temos ___ no filho de Jessé.",
        ),
        dict(
            diff="semente",
            skill="observe",
            type="connect",
            nn="06",
            question="O que 1 Reis 12:16 comunica que se liga a este contexto?",
            ok="Certo: o reino se parte — Israel às tendas.",
            wrong={
                "a": "O texto não celebra união sob Davi.",
                "c": "Não há aqui restauração da monarquia unida.",
            },
            options=opts(
                ("a", "União sob a casa de Davi"),
                ("b", "Ruptura: Israel às tendas"),
                ("c", "Restauração da monarquia unida"),
            ),
            correct="b",
            passageA={"ref": "1 Reis 12:16", "text": P3},
            passageB={"ref": "Contexto", "text": INS3},
        ),
        dict(
            diff="caminhada",
            skill="understand",
            type="true_false",
            nn="01",
            question="A recusa do rei em ouvir o povo resulta na ruptura: Israel se vai para as suas tendas.",
            ok="Certo: o texto liga a falta de ouvidos à cisão.",
            wrong={"false": "1 Reis 12:16 abre com o rei que não dava ouvidos."},
            options=tf_opts(),
            correct="true",
        ),
        dict(
            diff="caminhada",
            skill="understand",
            type="tap",
            nn="02",
            question='Em 1 Reis 12:16, toque a palavra que falta em "Que ___ temos nós em Davi?"?',
            ok='Exato: que "parte" temos nós em Davi.',
            wrong={
                "b": "Herança vem na frase seguinte; aqui é parte.",
                "c": "Tendas é o destino; a lacuna pede parte.",
            },
            options=opts(("a", "parte"), ("b", "herança"), ("c", "tendas")),
            correct="a",
            template="Que ___ temos nós em Davi?",
        ),
        dict(
            diff="caminhada",
            skill="understand",
            type="choice",
            nn="03",
            question="Como 1 Reis 12:16 liga a atitude do rei à resposta de Israel?",
            ok="Certo: sem ouvidos do rei, o povo rompe e se retira às tendas.",
            wrong={
                "a": "O povo não celebra a escuta do rei.",
                "c": "Não há reforço da lealdade dinástica aqui.",
                "d": "A resposta é ruptura, não petição diplomática prolongada.",
            },
            options=opts(
                ("a", "O povo celebra que o rei finalmente o escutou"),
                ("b", "Sem ser ouvido, o povo rejeita Davi e se retira às tendas"),
                ("c", "Israel reforça a lealdade à casa de Jessé"),
                ("d", "O povo apenas pede mais tempo para negociar"),
            ),
            correct="b",
        ),
        dict(
            diff="caminhada",
            skill="understand",
            type="order",
            nn="04",
            question="Como se encadeiam os eventos de 1 Reis 12:16?",
            ok="Certo: rejeição da dinastia, convocação às tendas, partida de Israel.",
            wrong={
                "b": "A partida fecha o movimento de ruptura.",
                "c": "Releia o encadeamento do versículo.",
            },
            options=opts(
                ("a", "Que parte temos nós em Davi? Nem herança no filho de Jessé"),
                ("b", "Às vossas tendas, ó Israel! Agora, cuida da tua casa, ó Davi"),
                ("c", "Assim, Israel se foi para as suas tendas"),
            ),
            correct="a",
            correctOrder=["a", "b", "c"],
        ),
        dict(
            diff="caminhada",
            skill="understand",
            type="complete",
            nn="05",
            question='Complete: "Assim, Israel se foi para as suas ___."',
            ok='Certo: para as suas "tendas".',
            wrong={
                "b": "Casa é o que Davi deve cuidar; aqui é tendas.",
                "c": "Herança é o que negam; a lacuna pede tendas.",
            },
            options=opts(("a", "tendas"), ("b", "casa"), ("c", "herança")),
            correct="a",
            template="Assim, Israel se foi para as suas ___.",
        ),
        dict(
            diff="caminhada",
            skill="understand",
            type="connect",
            nn="06",
            question="O que 1 Reis 12:16 comunica que se liga a este contexto?",
            ok="Certo: a cisão política nasce da rejeição da casa de Davi.",
            wrong={
                "a": "O texto não celebra continuidade dinástica.",
                "c": "Não há aqui reconciliação imediata.",
            },
            options=opts(
                ("a", "Continuidade da dinastia unida"),
                ("b", "Cisão: Israel rejeita Davi"),
                ("c", "Reconciliação imediata do reino"),
            ),
            correct="b",
            passageA={"ref": "1 Reis 12:16", "text": P3},
            passageB={"ref": "Contexto", "text": INS3},
        ),
        dict(
            diff="profundezas",
            skill="interpret",
            type="true_false",
            nn="01",
            question="A frase “cuida da tua casa, ó Davi” marca a separação entre Israel e a dinastia davidica.",
            ok="Certo: o povo deixa Davi com a própria casa e se retira.",
            wrong={"false": "Essa convocação expressa a ruptura do reino."},
            options=tf_opts(),
            correct="true",
        ),
        dict(
            diff="profundezas",
            skill="interpret",
            type="tap",
            nn="02",
            question='Em 1 Reis 12:16, toque a palavra que falta em "Nem temos herança no filho de ___"?',
            ok='Exato: filho de "Jessé".',
            wrong={
                "b": "Davi é o nome próprio; aqui a linhagem é Jessé.",
                "c": "Israel é quem se vai; a lacuna pede Jessé.",
            },
            options=opts(("a", "Jessé"), ("b", "Davi"), ("c", "Israel")),
            correct="a",
            template="Nem temos herança no filho de ___",
        ),
        dict(
            diff="profundezas",
            skill="interpret",
            type="choice",
            nn="03",
            question="O que a ruptura de 1 Reis 12:16 revela sobre a unidade do reino?",
            ok="Certo: sem ouvidos do rei, a unidade sob Davi se desfaz.",
            wrong={
                "a": "O texto não afirma que a unidade se fortaleceu.",
                "c": "Israel não permanece sob a casa de Davi.",
                "d": "A ida às tendas é separação, não reforma cultual.",
            },
            options=opts(
                ("a", "A unidade sob Davi se fortalece apesar do rei"),
                ("b", "Sem ser ouvido, o povo desfaz a unidade sob Davi"),
                ("c", "Israel permanece fiel à casa de Jessé"),
                ("d", "A ida às tendas é só uma reforma cultual pacífica"),
            ),
            correct="b",
        ),
        dict(
            diff="profundezas",
            skill="interpret",
            type="order",
            nn="04",
            question="Qual sequência revela o sentido de 1 Reis 12:16?",
            ok="Certo: rejeição dinástica, convocação à separação, partida efetiva.",
            wrong={
                "b": "A partida efetiva fecha o sentido da cisão.",
                "c": "Releia a lógica da ruptura no versículo.",
            },
            options=opts(
                ("a", "Que parte temos nós em Davi? Nem herança no filho de Jessé"),
                ("b", "Às vossas tendas, ó Israel! Agora, cuida da tua casa, ó Davi"),
                ("c", "Assim, Israel se foi para as suas tendas"),
            ),
            correct="a",
            correctOrder=["a", "b", "c"],
        ),
        dict(
            diff="profundezas",
            skill="interpret",
            type="complete",
            nn="05",
            question='Complete: "Agora, cuida da tua ___, ó Davi!"',
            ok='Certo: cuida da tua "casa".',
            wrong={
                "b": "Tendas é o destino de Israel; aqui é casa.",
                "c": "Parte é o que negam; a lacuna pede casa.",
            },
            options=opts(("a", "casa"), ("b", "tendas"), ("c", "parte")),
            correct="a",
            template="Agora, cuida da tua ___, ó Davi!",
        ),
        dict(
            diff="profundezas",
            skill="interpret",
            type="connect",
            nn="06",
            question="O que 1 Reis 12:16 comunica que se liga a este contexto?",
            ok="Certo: o reino se parte quando Israel se vai às tendas.",
            wrong={
                "a": "O texto não celebra a permanência unida.",
                "c": "Não há aqui restauração imediata sob Davi.",
            },
            options=opts(
                ("a", "Permanência do reino unido"),
                ("b", "Partilha: Israel às tendas"),
                ("c", "Restauração imediata sob Davi"),
            ),
            correct="b",
            passageA={"ref": "1 Reis 12:16", "text": P3},
            passageB={"ref": "Contexto", "text": INS3},
        ),
    ],
)

# ---------------------------------------------------------------------------
# M4 — 1 Reis 18:21 — Elias no Carmelo
# ---------------------------------------------------------------------------
P4 = (
    "Elias, chegando-se a todo o povo, disse: Até quando claudicareis para "
    "duas partes? Se Jeová é Deus, segui-o; se, porém, Baal o é, segui-o. "
    "O povo não lhe respondeu palavra."
)
LO4 = "Reconhecer o desafio de Elias: se Jeová é Deus, segui-o."
INS4 = "Se Jeová é Deus, segui-o."

bank += mission(
    "reis-dividido-02-elias-no-carmelo",
    "1 Reis 18:21",
    P4,
    LO4,
    ["1 Reis 18:21"],
    [
        dict(
            diff="semente",
            skill="observe",
            type="true_false",
            nn="01",
            question="Elias diz ao povo que, se Jeová é Deus, devem segui-lo.",
            ok="Certo: esse é o desafio explícito de Elias.",
            wrong={"false": "O texto registra exatamente esse desafio."},
            options=tf_opts(),
            correct="true",
        ),
        dict(
            diff="semente",
            skill="observe",
            type="tap",
            nn="02",
            question='Em 1 Reis 18:21, toque a palavra que falta em "Se Jeová é Deus, ___-o"?',
            ok='Exato: "segui"-o.',
            wrong={
                "b": "Baal é a alternativa; o verbo é segui.",
                "c": "Povo é quem ouve; a lacuna pede segui.",
            },
            options=opts(("a", "segui"), ("b", "Baal"), ("c", "povo")),
            correct="a",
            template="Se Jeová é Deus, ___-o",
        ),
        dict(
            diff="semente",
            skill="observe",
            type="choice",
            nn="03",
            question="O que Elias propõe explicitamente ao povo em 1 Reis 18:21?",
            ok="Certo: seguir Jeová se ele é Deus, ou Baal se este o for.",
            wrong={
                "b": "O texto não recomenda claudicar entre dois lados.",
                "c": "Não há ordem de silêncio como solução.",
                "d": "Elias não celebra a idolatria de Baal.",
            },
            options=opts(
                ("a", "Seguir Jeová se ele é Deus; ou Baal, se este o for"),
                ("b", "Continuar claudicando entre as duas partes"),
                ("c", "Ficar em silêncio e não escolher lado nenhum"),
                ("d", "Adorar Baal e abandonar Jeová de uma vez"),
            ),
            correct="a",
        ),
        dict(
            diff="semente",
            skill="observe",
            type="order",
            nn="04",
            question="Qual sequência mostra a ordem dos fatos em 1 Reis 18:21?",
            ok="Certo: pergunta, desafio de seguir, silêncio do povo.",
            wrong={
                "b": "O silêncio do povo fecha o versículo.",
                "c": "Releia a ordem do desafio de Elias.",
            },
            options=opts(
                ("a", "Até quando claudicareis para duas partes?"),
                ("b", "Se Jeová é Deus, segui-o; se Baal o é, segui-o"),
                ("c", "O povo não lhe respondeu palavra"),
            ),
            correct="a",
            correctOrder=["a", "b", "c"],
        ),
        dict(
            diff="semente",
            skill="observe",
            type="complete",
            nn="05",
            question='Complete: "Até quando ___ para duas partes?"',
            ok='Certo: "claudicareis" para duas partes.',
            wrong={
                "b": "Segui é o verbo do desafio; aqui é claudicareis.",
                "c": "Baal é a alternativa; a lacuna pede claudicareis.",
            },
            options=opts(("a", "claudicareis"), ("b", "segui"), ("c", "Baal")),
            correct="a",
            template="Até quando ___ para duas partes?",
        ),
        dict(
            diff="semente",
            skill="observe",
            type="connect",
            nn="06",
            question="O que 1 Reis 18:21 comunica que se liga a este contexto?",
            ok="Certo: se Jeová é Deus, segui-o.",
            wrong={
                "a": "O texto não recomenda permanência na indecisão.",
                "c": "Não há aqui celebração de Baal.",
            },
            options=opts(
                ("a", "Permanecer entre duas partes"),
                ("b", "Se Jeová é Deus, segui-o"),
                ("c", "Seguir Baal sem hesitar"),
            ),
            correct="b",
            passageA={"ref": "1 Reis 18:21", "text": P4},
            passageB={"ref": "Contexto", "text": INS4},
        ),
        dict(
            diff="caminhada",
            skill="understand",
            type="true_false",
            nn="01",
            question="Elias confronta o povo por claudicar entre duas partes em vez de seguir um só Deus.",
            ok="Certo: o desafio ataca a indecisão entre Jeová e Baal.",
            wrong={"false": "A pergunta sobre claudicar aponta a divisão."},
            options=tf_opts(),
            correct="true",
        ),
        dict(
            diff="caminhada",
            skill="understand",
            type="tap",
            nn="02",
            question='Em 1 Reis 18:21, toque a palavra que falta em "se, porém, ___ o é, segui-o"?',
            ok='Exato: se "Baal" o é, segui-o.',
            wrong={
                "a": "Jeová é a primeira opção; aqui a alternativa é Baal.",
                "c": "Povo é quem ouve; a lacuna pede Baal.",
            },
            options=opts(("a", "Jeová"), ("b", "Baal"), ("c", "povo")),
            correct="b",
            template="se, porém, ___ o é, segui-o",
        ),
        dict(
            diff="caminhada",
            skill="understand",
            type="choice",
            nn="03",
            question="Como Elias liga a identidade de Deus à resposta do povo?",
            ok="Certo: quem for Deus deve ser seguido — sem claudicar.",
            wrong={
                "a": "Elias não tolera a indecisão permanente.",
                "c": "O silêncio do povo não é apresentado como virtude.",
                "d": "O desafio exige escolha, não sincretismo.",
            },
            options=opts(
                ("a", "O povo pode claudicar indefinidamente entre os dois"),
                ("b", "Se Jeová ou Baal for Deus, o povo deve segui-lo"),
                ("c", "O silêncio do povo basta como resposta fiel"),
                ("d", "Seguir ambos ao mesmo tempo é a solução correta"),
            ),
            correct="b",
        ),
        dict(
            diff="caminhada",
            skill="understand",
            type="order",
            nn="04",
            question="Como se encadeiam os eventos de 1 Reis 18:21?",
            ok="Certo: denúncia da indecisão, desafio de seguir, silêncio.",
            wrong={
                "b": "O silêncio do povo fecha o encadeamento.",
                "c": "Releia a sequência do confronto.",
            },
            options=opts(
                ("a", "Até quando claudicareis para duas partes?"),
                ("b", "Se Jeová é Deus, segui-o; se Baal o é, segui-o"),
                ("c", "O povo não lhe respondeu palavra"),
            ),
            correct="a",
            correctOrder=["a", "b", "c"],
        ),
        dict(
            diff="caminhada",
            skill="understand",
            type="complete",
            nn="05",
            question='Complete: "O povo não lhe respondeu ___."',
            ok='Certo: não respondeu "palavra".',
            wrong={
                "b": "Partes é o objeto do claudicar; aqui é palavra.",
                "c": "Deus é o sujeito do desafio; a lacuna pede palavra.",
            },
            options=opts(("a", "palavra"), ("b", "partes"), ("c", "Deus")),
            correct="a",
            template="O povo não lhe respondeu ___.",
        ),
        dict(
            diff="caminhada",
            skill="understand",
            type="connect",
            nn="06",
            question="O que 1 Reis 18:21 comunica que se liga a este contexto?",
            ok="Certo: a fé exige seguir Jeová, não claudicar.",
            wrong={
                "a": "O texto não recomenda neutralidade.",
                "c": "Não há aqui defesa do culto a Baal.",
            },
            options=opts(
                ("a", "Neutralidade entre Jeová e Baal"),
                ("b", "Seguir Jeová sem claudicar"),
                ("c", "Defesa do culto a Baal"),
            ),
            correct="b",
            passageA={"ref": "1 Reis 18:21", "text": P4},
            passageB={"ref": "Contexto", "text": INS4},
        ),
        dict(
            diff="profundezas",
            skill="interpret",
            type="true_false",
            nn="01",
            question="O silêncio do povo diante de Elias expõe a falta de resposta clara à pergunta sobre quem é Deus.",
            ok="Certo: o povo não responde palavra ao desafio.",
            wrong={"false": "O versículo termina com o silêncio do povo."},
            options=tf_opts(),
            correct="true",
        ),
        dict(
            diff="profundezas",
            skill="interpret",
            type="tap",
            nn="02",
            question='Em 1 Reis 18:21, toque a palavra que falta em "claudicareis para duas ___"?',
            ok='Exato: duas "partes".',
            wrong={
                "b": "Palavra é o que o povo não responde; aqui é partes.",
                "c": "Segui é o verbo do desafio; a lacuna pede partes.",
            },
            options=opts(("a", "partes"), ("b", "palavra"), ("c", "segui")),
            correct="a",
            template="claudicareis para duas ___",
        ),
        dict(
            diff="profundezas",
            skill="interpret",
            type="choice",
            nn="03",
            question="O que o desafio de Elias revela sobre a fidelidade a Deus?",
            ok="Certo: fidelidade exige escolha clara — Jeová ou Baal, não ambos.",
            wrong={
                "a": "O texto condena a indecisão, não a recomenda.",
                "c": "Silêncio não equivale a fidelidade no relato.",
                "d": "Elias não trata Baal e Jeová como iguais.",
            },
            options=opts(
                ("a", "Claudicar entre dois deuses é uma forma aceitável de fé"),
                ("b", "Fidelidade exige escolha clara: seguir o verdadeiro Deus"),
                ("c", "O silêncio do povo prova que a escolha é desnecessária"),
                ("d", "Jeová e Baal podem ser seguidos com a mesma lealdade"),
            ),
            correct="b",
        ),
        dict(
            diff="profundezas",
            skill="interpret",
            type="order",
            nn="04",
            question="Qual sequência revela o sentido de 1 Reis 18:21?",
            ok="Certo: denúncia da divisão, exigência de seguir, exposição do silêncio.",
            wrong={
                "b": "O silêncio expõe a resposta do povo.",
                "c": "Releia a lógica teológica do desafio.",
            },
            options=opts(
                ("a", "Até quando claudicareis para duas partes?"),
                ("b", "Se Jeová é Deus, segui-o; se Baal o é, segui-o"),
                ("c", "O povo não lhe respondeu palavra"),
            ),
            correct="a",
            correctOrder=["a", "b", "c"],
        ),
        dict(
            diff="profundezas",
            skill="interpret",
            type="complete",
            nn="05",
            question='Complete: "Se ___ é Deus, segui-o."',
            ok='Certo: se "Jeová" é Deus, segui-o.',
            wrong={
                "b": "Baal é a alternativa; aqui o nome é Jeová.",
                "c": "Elias é quem fala; a lacuna pede Jeová.",
            },
            options=opts(("a", "Jeová"), ("b", "Baal"), ("c", "Elias")),
            correct="a",
            template="Se ___ é Deus, segui-o.",
        ),
        dict(
            diff="profundezas",
            skill="interpret",
            type="connect",
            nn="06",
            question="O que 1 Reis 18:21 comunica que se liga a este contexto?",
            ok="Certo: a identidade de Deus exige seguimento exclusivo.",
            wrong={
                "a": "O texto não celebra a indecisão.",
                "c": "Não há aqui sincretismo como ideal.",
            },
            options=opts(
                ("a", "Indecisão como virtude religiosa"),
                ("b", "Seguimento exclusivo do verdadeiro Deus"),
                ("c", "Sincretismo entre Jeová e Baal"),
            ),
            correct="b",
            passageA={"ref": "1 Reis 18:21", "text": P4},
            passageB={"ref": "Contexto", "text": INS4},
        ),
    ],
)

# ---------------------------------------------------------------------------
# M5 — 1 Reis 18:21 — desafio fidelidade (mesmo TB; variar; connect pode tecer 11:4)
# ---------------------------------------------------------------------------
P5 = P4  # mesmo texto TB
P5_CONNECT = (
    "Elias, chegando-se a todo o povo, disse: Até quando claudicareis para "
    "duas partes? Se Jeová é Deus, segui-o; se, porém, Baal o é, segui-o. "
    "O povo não lhe respondeu palavra. Sendo já velho, suas mulheres "
    "perverteram-lhe o coração para seguir outros deuses; e o seu coração "
    "não foi perfeito para com Jeová, seu Deus, como o fora o coração de "
    "Davi, seu pai."
)
LO5 = "Reconhecer o desafio de fidelidade: Jeová ou Baal — sem claudicar."
INS5 = "Fidelidade: Jeová ou Baal."

bank += mission(
    "reis-dividido-03-desafio-fidelidade",
    "1 Reis 18:21",
    P5,
    LO5,
    ["1 Reis 18:21"],
    [
        dict(
            diff="semente",
            skill="observe",
            type="true_false",
            nn="01",
            question="Elias pergunta até quando o povo claudicará para duas partes.",
            ok="Certo: essa é a pergunta inicial de Elias ao povo.",
            wrong={"false": "O texto abre com essa pergunta sobre claudicar."},
            options=tf_opts(),
            correct="true",
        ),
        dict(
            diff="semente",
            skill="observe",
            type="tap",
            nn="02",
            question='Em 1 Reis 18:21, toque a palavra que falta em "Até quando claudicareis para ___ partes"?',
            ok='Exato: "duas" partes.',
            wrong={
                "b": "Palavra é o que falta na resposta; aqui é duas.",
                "c": "Segui é o verbo do desafio; a lacuna pede duas.",
            },
            options=opts(("a", "duas"), ("b", "palavra"), ("c", "segui")),
            correct="a",
            template="Até quando claudicareis para ___ partes",
        ),
        dict(
            diff="semente",
            skill="observe",
            type="choice",
            nn="03",
            question="Qual alternativa Elias coloca diante do povo?",
            ok="Certo: Jeová ou Baal — cada um, se for Deus, deve ser seguido.",
            wrong={
                "b": "O texto não recomenda adorar os dois juntos.",
                "c": "Não há terceira opção de deuses estrangeiros aqui.",
                "d": "Elias não pede adiamento da escolha.",
            },
            options=opts(
                ("a", "Jeová ou Baal: siga aquele que for Deus"),
                ("b", "Adorar Jeová e Baal ao mesmo tempo"),
                ("c", "Escolher qualquer deus das nações vizinhas"),
                ("d", "Adiar a decisão para outra geração"),
            ),
            correct="a",
        ),
        dict(
            diff="semente",
            skill="observe",
            type="order",
            nn="04",
            question="Qual sequência mostra a ordem dos fatos em 1 Reis 18:21?",
            ok="Certo: chegada de Elias, desafio, silêncio do povo.",
            wrong={
                "b": "O silêncio vem depois do desafio.",
                "c": "Releia a ordem do versículo.",
            },
            options=opts(
                ("a", "Elias, chegando-se a todo o povo, disse"),
                ("b", "Se Jeová é Deus, segui-o; se Baal o é, segui-o"),
                ("c", "O povo não lhe respondeu palavra"),
            ),
            correct="a",
            correctOrder=["a", "b", "c"],
        ),
        dict(
            diff="semente",
            skill="observe",
            type="complete",
            nn="05",
            question='Complete: "se, porém, Baal o é, ___-o."',
            ok='Certo: "segui"-o — a mesma exigência vale para ambos.',
            wrong={
                "b": "Claudicareis é o problema; aqui o verbo é segui.",
                "c": "Partes descreve a divisão; a lacuna pede segui.",
            },
            options=opts(("a", "segui"), ("b", "claudicareis"), ("c", "partes")),
            correct="a",
            template="se, porém, Baal o é, ___-o.",
        ),
        dict(
            diff="semente",
            skill="observe",
            type="connect",
            nn="06",
            question="O que 1 Reis 18:21 comunica que se liga a este contexto?",
            ok="Certo: fidelidade — Jeová ou Baal.",
            wrong={
                "a": "O texto não recomenda coração dividido.",
                "c": "Não há aqui celebração da indecisão.",
            },
            options=opts(
                ("a", "Coração dividido entre deuses"),
                ("b", "Fidelidade: Jeová ou Baal"),
                ("c", "Indecisão como caminho seguro"),
            ),
            correct="b",
            passageA={"ref": "1 Reis 18:21", "text": P5},
            passageB={"ref": "Contexto", "text": INS5},
        ),
        dict(
            diff="caminhada",
            skill="understand",
            type="true_false",
            nn="01",
            question="O desafio de Elias exige que o povo deixe de claudicar e siga um só lado.",
            ok="Certo: a alternativa Jeová/Baal exclui a indecisão.",
            wrong={"false": "O confronto ataca o claudicar entre duas partes."},
            options=tf_opts(),
            correct="true",
        ),
        dict(
            diff="caminhada",
            skill="understand",
            type="tap",
            nn="02",
            question='Em 1 Reis 18:21, toque a palavra que falta em "Se ___ é Deus, segui-o"?',
            ok='Exato: se "Jeová" é Deus.',
            wrong={
                "b": "Baal é a segunda opção; aqui o nome é Jeová.",
                "c": "Elias é o profeta; a lacuna pede Jeová.",
            },
            options=opts(("a", "Jeová"), ("b", "Baal"), ("c", "Elias")),
            correct="a",
            template="Se ___ é Deus, segui-o",
        ),
        dict(
            diff="caminhada",
            skill="understand",
            type="choice",
            nn="03",
            question="Como o desafio de Elias define a fidelidade do povo?",
            ok="Certo: fidelidade é seguir o verdadeiro Deus, sem duas partes.",
            wrong={
                "a": "Claudicar é o problema denunciado, não a solução.",
                "c": "O silêncio não substitui a escolha.",
                "d": "O texto não recomenda cultos paralelos.",
            },
            options=opts(
                ("a", "Fidelidade permite claudicar entre Jeová e Baal"),
                ("b", "Fidelidade é seguir o verdadeiro Deus sem dividir-se"),
                ("c", "Fidelidade se prova pelo silêncio diante do profeta"),
                ("d", "Fidelidade aceita cultos paralelos a Jeová e Baal"),
            ),
            correct="b",
        ),
        dict(
            diff="caminhada",
            skill="understand",
            type="order",
            nn="04",
            question="Como se encadeiam os eventos de 1 Reis 18:21?",
            ok="Certo: denúncia do claudicar, exigência de seguir, silêncio.",
            wrong={
                "b": "O silêncio fecha a cena do desafio.",
                "c": "Releia o encadeamento do confronto.",
            },
            options=opts(
                ("a", "Até quando claudicareis para duas partes?"),
                ("b", "Se Jeová é Deus, segui-o; se Baal o é, segui-o"),
                ("c", "O povo não lhe respondeu palavra"),
            ),
            correct="a",
            correctOrder=["a", "b", "c"],
        ),
        dict(
            diff="caminhada",
            skill="understand",
            type="complete",
            nn="05",
            question='Complete: "Até quando claudicareis para duas ___?"',
            ok='Certo: duas "partes".',
            wrong={
                "b": "Palavra é o silêncio do povo; aqui é partes.",
                "c": "Deus é o sujeito do desafio; a lacuna pede partes.",
            },
            options=opts(("a", "partes"), ("b", "palavra"), ("c", "Deus")),
            correct="a",
            template="Até quando claudicareis para duas ___?",
        ),
        dict(
            diff="caminhada",
            skill="understand",
            type="connect",
            nn="06",
            question="O que 1 Reis 18:21 comunica que se liga a este contexto?",
            ok="Certo: coração dividido (11:4) e claudicar (18:21) se opõem à fidelidade.",
            wrong={
                "a": "O texto não celebra perfeição do coração dividido.",
                "c": "Não há aqui defesa do culto a Baal.",
            },
            options=opts(
                ("a", "Coração perfeito sob idolatria"),
                ("b", "Fidelidade contra coração dividido"),
                ("c", "Lealdade a Baal como solução"),
            ),
            correct="b",
            passageA={
                "ref": "1 Reis 18:21",
                "text": "Se Jeová é Deus, segui-o; se, porém, Baal o é, segui-o.",
            },
            passageB={
                "ref": "Contexto",
                "text": "Fidelidade: Jeová ou Baal — sem o coração dividido de 1 Reis 11:4.",
            },
        ),
        dict(
            diff="profundezas",
            skill="interpret",
            type="true_false",
            nn="01",
            question="Claudicar entre Jeová e Baal é incompatível com a fidelidade que Elias exige.",
            ok="Certo: o desafio exclui a divisão entre duas partes.",
            wrong={"false": "Elias exige seguir um, não claudicar entre dois."},
            options=tf_opts(),
            correct="true",
        ),
        dict(
            diff="profundezas",
            skill="interpret",
            type="tap",
            nn="02",
            question='Em 1 Reis 18:21, toque a palavra que falta em "O povo não lhe respondeu ___"?',
            ok='Exato: não respondeu "palavra".',
            wrong={
                "b": "Partes descreve a divisão; aqui é palavra.",
                "c": "Segui é o verbo do desafio; a lacuna pede palavra.",
            },
            options=opts(("a", "palavra"), ("b", "partes"), ("c", "segui")),
            correct="a",
            template="O povo não lhe respondeu ___",
        ),
        dict(
            diff="profundezas",
            skill="interpret",
            type="choice",
            nn="03",
            question="O que o desafio de fidelidade em 1 Reis 18:21 exige do leitor?",
            ok="Certo: escolha exclusiva — Jeová ou Baal, sem coração dividido.",
            wrong={
                "a": "O texto condena a indecisão permanente.",
                "c": "Sincretismo é o problema, não a solução.",
                "d": "Silêncio não basta como fidelidade.",
            },
            options=opts(
                ("a", "Manter a indecisão até ver qual deus vence"),
                ("b", "Escolher com exclusividade: seguir o verdadeiro Deus"),
                ("c", "Combinar Jeová e Baal num culto único"),
                ("d", "Responder com silêncio e evitar qualquer compromisso"),
            ),
            correct="b",
        ),
        dict(
            diff="profundezas",
            skill="interpret",
            type="order",
            nn="04",
            question="Qual sequência revela o sentido de 1 Reis 18:21?",
            ok="Certo: denúncia da divisão, exigência de seguir, exposição do silêncio.",
            wrong={
                "b": "O silêncio fecha a revelação da resposta do povo.",
                "c": "Releia a lógica do desafio de fidelidade.",
            },
            options=opts(
                ("a", "Até quando claudicareis para duas partes?"),
                ("b", "Se Jeová é Deus, segui-o; se Baal o é, segui-o"),
                ("c", "O povo não lhe respondeu palavra"),
            ),
            correct="a",
            correctOrder=["a", "b", "c"],
        ),
        dict(
            diff="profundezas",
            skill="interpret",
            type="complete",
            nn="05",
            question='Complete: "Se Jeová é ___, segui-o."',
            ok='Certo: se Jeová é "Deus", segui-o.',
            wrong={
                "b": "Baal é a alternativa; aqui a palavra é Deus.",
                "c": "Povo é quem ouve; a lacuna pede Deus.",
            },
            options=opts(("a", "Deus"), ("b", "Baal"), ("c", "povo")),
            correct="a",
            template="Se Jeová é ___, segui-o.",
        ),
        dict(
            diff="profundezas",
            skill="interpret",
            type="connect",
            nn="06",
            question="O que 1 Reis 18:21 comunica que se liga a este contexto?",
            ok="Certo: fidelidade a Jeová exclui o coração pervertido por outros deuses.",
            wrong={
                "a": "O texto não celebra a perversão do coração.",
                "c": "Não há aqui defesa de seguir outros deuses.",
            },
            options=opts(
                ("a", "Coração pervertido como virtude"),
                ("b", "Fidelidade contra outros deuses"),
                ("c", "Seguir outros deuses com Jeová"),
            ),
            correct="b",
            passageA={
                "ref": "1 Reis 18:21 / 11:4",
                "text": P5_CONNECT,
            },
            passageB={"ref": "Contexto", "text": INS5},
        ),
    ],
)

# Fix M5 connect profundezas: tap words must be in passageText — P5 is used as
# mission passage; connect passageA can have extra text. But tap options must
# exist in mission passageText (P5). Already OK for taps.
# For profundezas connect, passageText on the question is still P5 from mission().
# That's fine — passageA can differ.

# ---------------------------------------------------------------------------
# M6 — 2 Reis 17:7–8 — queda de Samaria
# ---------------------------------------------------------------------------
P6 = (
    "Assim sucedeu porque os filhos de Israel tinham pecado contra Jeová, "
    "seu Deus, que os tirou da terra do Egito, de debaixo da mão de Faraó, "
    "rei do Egito, e haviam temido a outros deuses e andado nos estatutos "
    "das nações que Jeová expulsou de diante dos filhos de Israel e nos "
    "que os reis de Israel estabeleceram."
)
LO6 = "Reconhecer que Samaria cai porque Israel pecou e temeu outros deuses."
INS6 = "Samaria cai por pecar e temer outros deuses."

bank += mission(
    "reis-queda-reis-01-queda-de-samaria",
    "2 Reis 17:7–8",
    P6,
    LO6,
    ["2 Reis 17:7", "2 Reis 17:8"],
    [
        dict(
            diff="semente",
            skill="observe",
            type="true_false",
            nn="01",
            question="Os filhos de Israel tinham pecado contra Jeová e haviam temido a outros deuses.",
            ok="Certo: o texto afirma pecado e temor a outros deuses.",
            wrong={"false": "2 Reis 17:7–8 registra exatamente isso."},
            options=tf_opts(),
            correct="true",
        ),
        dict(
            diff="semente",
            skill="observe",
            type="tap",
            nn="02",
            question='Em 2 Reis 17:7–8, toque a palavra que falta em "tinham ___ contra Jeová, seu Deus"?',
            ok='Exato: tinham "pecado" contra Jeová.',
            wrong={
                "b": "Temido aparece depois; aqui o verbo é pecado.",
                "c": "Egito é a terra da saída; a lacuna pede pecado.",
            },
            options=opts(("a", "pecado"), ("b", "temido"), ("c", "Egito")),
            correct="a",
            template="tinham ___ contra Jeová, seu Deus",
        ),
        dict(
            diff="semente",
            skill="observe",
            type="choice",
            nn="03",
            question="O que 2 Reis 17:7–8 afirma como causa do que sucedeu?",
            ok="Certo: pecaram contra Jeová e temeram outros deuses.",
            wrong={
                "b": "O texto não atribui a queda a fidelidade.",
                "c": "Não há aqui celebração dos estatutos de Jeová.",
                "d": "A causa não é a saída do Egito em si.",
            },
            options=opts(
                ("a", "Pecaram contra Jeová e temeram outros deuses"),
                ("b", "Permaneceram fiéis a Jeová até o fim"),
                ("c", "Seguiram só os estatutos que Jeová deu"),
                ("d", "Foram punidos por terem saído do Egito"),
            ),
            correct="a",
        ),
        dict(
            diff="semente",
            skill="observe",
            type="order",
            nn="04",
            question="Qual sequência mostra a ordem dos fatos em 2 Reis 17:7–8?",
            ok="Certo: pecado, temor a outros deuses, andar nos estatutos das nações.",
            wrong={
                "b": "O pecado abre a explicação causal.",
                "c": "Releia a ordem do relato.",
            },
            options=opts(
                ("a", "os filhos de Israel tinham pecado contra Jeová, seu Deus"),
                ("b", "e haviam temido a outros deuses"),
                ("c", "e andado nos estatutos das nações"),
            ),
            correct="a",
            correctOrder=["a", "b", "c"],
        ),
        dict(
            diff="semente",
            skill="observe",
            type="complete",
            nn="05",
            question='Complete: "e haviam ___ a outros deuses."',
            ok='Certo: haviam "temido" a outros deuses.',
            wrong={
                "a": "Pecado abre o relato; aqui o verbo é temido.",
                "c": "Egito é a terra da libertação; a lacuna pede temido.",
            },
            options=opts(("a", "pecado"), ("b", "temido"), ("c", "Egito")),
            correct="b",
            template="e haviam ___ a outros deuses.",
        ),
        dict(
            diff="semente",
            skill="observe",
            type="connect",
            nn="06",
            question="O que 2 Reis 17:7–8 comunica que se liga a este contexto?",
            ok="Certo: Samaria cai por pecar e temer outros deuses.",
            wrong={
                "a": "O texto não celebra fidelidade preservada.",
                "c": "Não há aqui inocência de Israel.",
            },
            options=opts(
                ("a", "Fidelidade preservada em Samaria"),
                ("b", "Queda por pecar e temer outros deuses"),
                ("c", "Inocência de Israel perante Jeová"),
            ),
            correct="b",
            passageA={"ref": "2 Reis 17:7–8", "text": P6},
            passageB={"ref": "Contexto", "text": INS6},
        ),
        dict(
            diff="caminhada",
            skill="understand",
            type="true_false",
            nn="01",
            question="Israel pecou contra o Deus que o tirou do Egito e andou nos estatutos das nações.",
            ok="Certo: o texto une libertação, pecado e imitação das nações.",
            wrong={"false": "2 Reis 17:7–8 liga esses elementos."},
            options=tf_opts(),
            correct="true",
        ),
        dict(
            diff="caminhada",
            skill="understand",
            type="tap",
            nn="02",
            question='Em 2 Reis 17:7–8, toque a palavra que falta em "andado nos ___ das nações"?',
            ok='Exato: nos "estatutos" das nações.',
            wrong={
                "b": "Deuses é o objeto do temor; aqui é estatutos.",
                "c": "Egito é a terra da saída; a lacuna pede estatutos.",
            },
            options=opts(("a", "estatutos"), ("b", "deuses"), ("c", "Egito")),
            correct="a",
            template="andado nos ___ das nações",
        ),
        dict(
            diff="caminhada",
            skill="understand",
            type="choice",
            nn="03",
            question="Como 2 Reis 17:7–8 liga a história da libertação ao pecado de Israel?",
            ok="Certo: pecaram contra o Deus que os tirou do Egito.",
            wrong={
                "a": "O texto não diz que esqueceram a saída do Egito por acidente neutro.",
                "c": "Não há fidelidade aos estatutos de Jeová aqui.",
                "d": "A causa não é a falta de reis.",
            },
            options=opts(
                ("a", "Israel manteve gratidão plena ao Deus do êxodo"),
                ("b", "Pecaram contra o Deus que os tirou do Egito e temeram outros deuses"),
                ("c", "Seguiram fielmente os estatutos que Jeová estabeleceu"),
                ("d", "A queda veio porque Israel nunca teve reis"),
            ),
            correct="b",
        ),
        dict(
            diff="caminhada",
            skill="understand",
            type="order",
            nn="04",
            question="Como se encadeiam os eventos de 2 Reis 17:7–8?",
            ok="Certo: pecado contra o Libertador, temor idolátrico, estatutos das nações.",
            wrong={
                "b": "Os estatutos das nações fecham a cadeia de infidelidade.",
                "c": "Releia o encadeamento causal.",
            },
            options=opts(
                ("a", "os filhos de Israel tinham pecado contra Jeová, seu Deus"),
                ("b", "e haviam temido a outros deuses"),
                ("c", "e andado nos estatutos das nações"),
            ),
            correct="a",
            correctOrder=["a", "b", "c"],
        ),
        dict(
            diff="caminhada",
            skill="understand",
            type="complete",
            nn="05",
            question='Complete: "que os tirou da terra do ___."',
            ok='Certo: terra do "Egito".',
            wrong={
                "b": "Faraó é o rei; aqui o lugar é Egito.",
                "c": "Nações são as expulsas; a lacuna pede Egito.",
            },
            options=opts(("a", "Egito"), ("b", "Faraó"), ("c", "nações")),
            correct="a",
            template="que os tirou da terra do ___.",
        ),
        dict(
            diff="caminhada",
            skill="understand",
            type="connect",
            nn="06",
            question="O que 2 Reis 17:7–8 comunica que se liga a este contexto?",
            ok="Certo: a queda se explica pela infidelidade idolátrica.",
            wrong={
                "a": "O texto não celebra lealdade ao êxodo.",
                "c": "Não há aqui inocência política de Israel.",
            },
            options=opts(
                ("a", "Lealdade contínua ao Deus do êxodo"),
                ("b", "Infidelidade que explica a queda"),
                ("c", "Inocência política de Samaria"),
            ),
            correct="b",
            passageA={"ref": "2 Reis 17:7–8", "text": P6},
            passageB={"ref": "Contexto", "text": INS6},
        ),
        dict(
            diff="profundezas",
            skill="interpret",
            type="true_false",
            nn="01",
            question="A queda de Samaria é apresentada como consequência do pecado e do temor a outros deuses.",
            ok="Certo: o texto explica o que sucedeu por essa causa.",
            wrong={"false": "Assim sucedeu porque pecaram e temeram outros deuses."},
            options=tf_opts(),
            correct="true",
        ),
        dict(
            diff="profundezas",
            skill="interpret",
            type="tap",
            nn="02",
            question='Em 2 Reis 17:7–8, toque a palavra que falta em "temido a outros ___"?',
            ok='Exato: outros "deuses".',
            wrong={
                "b": "Estatutos é o que seguem depois; aqui é deuses.",
                "c": "Nações são as expulsas; a lacuna pede deuses.",
            },
            options=opts(("a", "deuses"), ("b", "estatutos"), ("c", "nações")),
            correct="a",
            template="temido a outros ___",
        ),
        dict(
            diff="profundezas",
            skill="interpret",
            type="choice",
            nn="03",
            question="O que 2 Reis 17:7–8 ensina sobre a responsabilidade de Israel na queda?",
            ok="Certo: a queda resulta do pecado e da imitação das nações.",
            wrong={
                "a": "O texto não isenta Israel de culpa.",
                "c": "Os estatutos das nações são o caminho da queda, não da fidelidade.",
                "d": "A libertação do Egito agrava, não cancela, a responsabilidade.",
            },
            options=opts(
                ("a", "Israel caiu sem qualquer culpa própria"),
                ("b", "Pecado e temor a outros deuses explicam a queda"),
                ("c", "Seguir os estatutos das nações era fidelidade a Jeová"),
                ("d", "Ter sido tirado do Egito isenta Israel de julgamento"),
            ),
            correct="b",
        ),
        dict(
            diff="profundezas",
            skill="interpret",
            type="order",
            nn="04",
            question="Qual sequência revela o sentido de 2 Reis 17:7–8?",
            ok="Certo: pecado contra o Libertador, idolatria, imitação das nações.",
            wrong={
                "b": "A imitação das nações fecha o sentido da queda.",
                "c": "Releia a lógica teológica do relato.",
            },
            options=opts(
                ("a", "os filhos de Israel tinham pecado contra Jeová, seu Deus"),
                ("b", "e haviam temido a outros deuses"),
                ("c", "e andado nos estatutos das nações"),
            ),
            correct="a",
            correctOrder=["a", "b", "c"],
        ),
        dict(
            diff="profundezas",
            skill="interpret",
            type="complete",
            nn="05",
            question='Complete: "Assim sucedeu porque os filhos de Israel tinham ___ contra Jeová."',
            ok='Certo: tinham "pecado" contra Jeová.',
            wrong={
                "b": "Temido aparece depois; aqui é pecado.",
                "c": "Andado refere-se aos estatutos; a lacuna pede pecado.",
            },
            options=opts(("a", "pecado"), ("b", "temido"), ("c", "andado")),
            correct="a",
            template="Assim sucedeu porque os filhos de Israel tinham ___ contra Jeová.",
        ),
        dict(
            diff="profundezas",
            skill="interpret",
            type="connect",
            nn="06",
            question="O que 2 Reis 17:7–8 comunica que se liga a este contexto?",
            ok="Certo: a queda de Samaria é julgamento por idolatria.",
            wrong={
                "a": "O texto não trata a queda como acaso.",
                "c": "Não há aqui recompensa por fidelidade.",
            },
            options=opts(
                ("a", "Queda como acaso histórico"),
                ("b", "Julgamento por pecar e temer outros deuses"),
                ("c", "Recompensa por fidelidade a Jeová"),
            ),
            correct="b",
            passageA={"ref": "2 Reis 17:7–8", "text": P6},
            passageB={"ref": "Contexto", "text": INS6},
        ),
    ],
)

# ---------------------------------------------------------------------------
# M7 — 2 Reis 25:21 — queda de Jerusalém
# ---------------------------------------------------------------------------
P7 = (
    "O rei da Babilônia os feriu e matou em Ribla, na terra de Hamate. "
    "Assim, Judá foi levado cativo para fora da sua terra."
)
LO7 = "Reconhecer que Judá foi levado cativo para fora da sua terra."
INS7 = "Judá cativo fora da terra."

bank += mission(
    "reis-queda-reis-02-queda-de-jerusalem",
    "2 Reis 25:21",
    P7,
    LO7,
    ["2 Reis 25:21"],
    [
        dict(
            diff="semente",
            skill="observe",
            type="true_false",
            nn="01",
            question="Judá foi levado cativo para fora da sua terra.",
            ok="Certo: o texto afirma o cativeiro de Judá.",
            wrong={"false": "2 Reis 25:21 registra exatamente isso."},
            options=tf_opts(),
            correct="true",
        ),
        dict(
            diff="semente",
            skill="observe",
            type="tap",
            nn="02",
            question='Em 2 Reis 25:21, toque a palavra que falta em "Judá foi levado ___ para fora da sua terra"?',
            ok='Exato: levado "cativo".',
            wrong={
                "b": "Ribla é o lugar da execução; aqui é cativo.",
                "c": "Hamate situa a terra; a lacuna pede cativo.",
            },
            options=opts(("a", "cativo"), ("b", "Ribla"), ("c", "Hamate")),
            correct="a",
            template="Judá foi levado ___ para fora da sua terra",
        ),
        dict(
            diff="semente",
            skill="observe",
            type="choice",
            nn="03",
            question="O que 2 Reis 25:21 afirma sobre Judá?",
            ok="Certo: foi levado cativo para fora da sua terra.",
            wrong={
                "b": "O texto não diz que Judá permaneceu na terra.",
                "c": "Não há vitória de Judá sobre a Babilônia.",
                "d": "O cativeiro é para fora, não repatriação.",
            },
            options=opts(
                ("a", "Foi levado cativo para fora da sua terra"),
                ("b", "Permaneceu livre em sua própria terra"),
                ("c", "Derrotou o rei da Babilônia em Ribla"),
                ("d", "Foi repatriado imediatamente a Jerusalém"),
            ),
            correct="a",
        ),
        dict(
            diff="semente",
            skill="observe",
            type="order",
            nn="04",
            question="Qual sequência mostra a ordem dos fatos em 2 Reis 25:21?",
            ok="Certo: execução em Ribla, depois o cativeiro de Judá.",
            wrong={
                "b": "A execução em Ribla precede o cativeiro.",
                "c": "Releia a ordem do versículo.",
            },
            options=opts(
                ("a", "O rei da Babilônia os feriu e matou em Ribla"),
                ("b", "na terra de Hamate"),
                ("c", "Assim, Judá foi levado cativo para fora da sua terra"),
            ),
            correct="a",
            correctOrder=["a", "b", "c"],
        ),
        dict(
            diff="semente",
            skill="observe",
            type="complete",
            nn="05",
            question='Complete: "O rei da ___ os feriu e matou em Ribla."',
            ok='Certo: rei da "Babilônia".',
            wrong={
                "b": "Hamate é a terra; aqui o reino é Babilônia.",
                "c": "Judá é o povo cativo; a lacuna pede Babilônia.",
            },
            options=opts(("a", "Babilônia"), ("b", "Hamate"), ("c", "Judá")),
            correct="a",
            template="O rei da ___ os feriu e matou em Ribla.",
        ),
        dict(
            diff="semente",
            skill="observe",
            type="connect",
            nn="06",
            question="O que 2 Reis 25:21 comunica que se liga a este contexto?",
            ok="Certo: Judá cativo fora da terra.",
            wrong={
                "a": "O texto não celebra permanência na terra.",
                "c": "Não há aqui libertação imediata.",
            },
            options=opts(
                ("a", "Permanência livre na terra"),
                ("b", "Judá cativo fora da terra"),
                ("c", "Libertação imediata de Judá"),
            ),
            correct="b",
            passageA={"ref": "2 Reis 25:21", "text": P7},
            passageB={"ref": "Contexto", "text": INS7},
        ),
        dict(
            diff="caminhada",
            skill="understand",
            type="true_false",
            nn="01",
            question="O rei da Babilônia fere e mata em Ribla; em seguida Judá é levado cativo.",
            ok="Certo: o texto encadeia a execução e o cativeiro.",
            wrong={"false": "2 Reis 25:21 une esses dois movimentos."},
            options=tf_opts(),
            correct="true",
        ),
        dict(
            diff="caminhada",
            skill="understand",
            type="tap",
            nn="02",
            question='Em 2 Reis 25:21, toque a palavra que falta em "os feriu e matou em ___"?',
            ok='Exato: em "Ribla".',
            wrong={
                "b": "Hamate é a terra; o lugar da morte é Ribla.",
                "c": "Judá é o povo; a lacuna pede Ribla.",
            },
            options=opts(("a", "Ribla"), ("b", "Hamate"), ("c", "Judá")),
            correct="a",
            template="os feriu e matou em ___",
        ),
        dict(
            diff="caminhada",
            skill="understand",
            type="choice",
            nn="03",
            question="Como 2 Reis 25:21 liga a ação do rei da Babilônia ao destino de Judá?",
            ok="Certo: após ferir e matar em Ribla, Judá é levado cativo.",
            wrong={
                "a": "O texto não registra libertação.",
                "c": "Judá não permanece na terra.",
                "d": "Não há aliança de paz aqui.",
            },
            options=opts(
                ("a", "O rei da Babilônia liberta Judá e o envia para casa"),
                ("b", "Após ferir e matar em Ribla, Judá é levado cativo"),
                ("c", "Judá permanece seguro dentro da sua terra"),
                ("d", "O rei da Babilônia firma aliança de paz com Judá"),
            ),
            correct="b",
        ),
        dict(
            diff="caminhada",
            skill="understand",
            type="order",
            nn="04",
            question="Como se encadeiam os eventos de 2 Reis 25:21?",
            ok="Certo: execução em Ribla, localização em Hamate, cativeiro de Judá.",
            wrong={
                "b": "O cativeiro fecha o encadeamento.",
                "c": "Releia a sequência do versículo.",
            },
            options=opts(
                ("a", "O rei da Babilônia os feriu e matou em Ribla"),
                ("b", "na terra de Hamate"),
                ("c", "Assim, Judá foi levado cativo para fora da sua terra"),
            ),
            correct="a",
            correctOrder=["a", "b", "c"],
        ),
        dict(
            diff="caminhada",
            skill="understand",
            type="complete",
            nn="05",
            question='Complete: "na terra de ___."',
            ok='Certo: terra de "Hamate".',
            wrong={
                "b": "Ribla é a cidade; aqui a terra é Hamate.",
                "c": "Babilônia é o reino; a lacuna pede Hamate.",
            },
            options=opts(("a", "Hamate"), ("b", "Ribla"), ("c", "Babilônia")),
            correct="a",
            template="na terra de ___.",
        ),
        dict(
            diff="caminhada",
            skill="understand",
            type="connect",
            nn="06",
            question="O que 2 Reis 25:21 comunica que se liga a este contexto?",
            ok="Certo: o desfecho é o cativeiro de Judá fora da terra.",
            wrong={
                "a": "O texto não celebra restauração imediata.",
                "c": "Não há aqui vitória militar de Judá.",
            },
            options=opts(
                ("a", "Restauração imediata na terra"),
                ("b", "Cativeiro de Judá fora da terra"),
                ("c", "Vitória militar de Judá"),
            ),
            correct="b",
            passageA={"ref": "2 Reis 25:21", "text": P7},
            passageB={"ref": "Contexto", "text": INS7},
        ),
        dict(
            diff="profundezas",
            skill="interpret",
            type="true_false",
            nn="01",
            question="O cativeiro de Judá para fora da terra marca o desfecho da queda de Jerusalém.",
            ok="Certo: o versículo fecha com Judá levado cativo.",
            wrong={"false": "Assim, Judá foi levado cativo para fora da sua terra."},
            options=tf_opts(),
            correct="true",
        ),
        dict(
            diff="profundezas",
            skill="interpret",
            type="tap",
            nn="02",
            question='Em 2 Reis 25:21, toque a palavra que falta em "para fora da sua ___"?',
            ok='Exato: fora da sua "terra".',
            wrong={
                "b": "Cativo descreve o estado; aqui é terra.",
                "c": "Ribla é o lugar da morte; a lacuna pede terra.",
            },
            options=opts(("a", "terra"), ("b", "cativo"), ("c", "Ribla")),
            correct="a",
            template="para fora da sua ___",
        ),
        dict(
            diff="profundezas",
            skill="interpret",
            type="choice",
            nn="03",
            question="O que o desfecho de 2 Reis 25:21 revela sobre Judá?",
            ok="Certo: perde a terra — é levado cativo para fora.",
            wrong={
                "a": "O texto não afirma preservação da terra.",
                "c": "Não há repatriação neste versículo.",
                "d": "Ribla é lugar de morte, não de restauração.",
            },
            options=opts(
                ("a", "Judá preserva a posse da terra apesar da Babilônia"),
                ("b", "Judá perde a terra: é levado cativo para fora"),
                ("c", "Judá é repatriado após a execução em Ribla"),
                ("d", "Judá transforma Ribla em nova capital segura"),
            ),
            correct="b",
        ),
        dict(
            diff="profundezas",
            skill="interpret",
            type="order",
            nn="04",
            question="Qual sequência revela o sentido de 2 Reis 25:21?",
            ok="Certo: violência em Ribla, localização, cativeiro fora da terra.",
            wrong={
                "b": "O cativeiro fecha o sentido da queda.",
                "c": "Releia a lógica do desfecho.",
            },
            options=opts(
                ("a", "O rei da Babilônia os feriu e matou em Ribla"),
                ("b", "na terra de Hamate"),
                ("c", "Assim, Judá foi levado cativo para fora da sua terra"),
            ),
            correct="a",
            correctOrder=["a", "b", "c"],
        ),
        dict(
            diff="profundezas",
            skill="interpret",
            type="complete",
            nn="05",
            question='Complete: "Assim, ___ foi levado cativo para fora da sua terra."',
            ok='Certo: "Judá" foi levado cativo.',
            wrong={
                "b": "Babilônia é o poder opressor; aqui é Judá.",
                "c": "Ribla é o lugar; a lacuna pede Judá.",
            },
            options=opts(("a", "Judá"), ("b", "Babilônia"), ("c", "Ribla")),
            correct="a",
            template="Assim, ___ foi levado cativo para fora da sua terra.",
        ),
        dict(
            diff="profundezas",
            skill="interpret",
            type="connect",
            nn="06",
            question="O que 2 Reis 25:21 comunica que se liga a este contexto?",
            ok="Certo: o fim é o cativeiro — Judá fora da terra.",
            wrong={
                "a": "O texto não celebra permanência na terra.",
                "c": "Não há aqui triunfo de Judá sobre a Babilônia.",
            },
            options=opts(
                ("a", "Permanência definitiva na terra"),
                ("b", "Cativeiro: Judá fora da terra"),
                ("c", "Triunfo de Judá sobre a Babilônia"),
            ),
            correct="b",
            passageA={"ref": "2 Reis 25:21", "text": P7},
            passageB={"ref": "Contexto", "text": INS7},
        ),
    ],
)

# M5 profundezas connect: ensure tap words from 11:4 are available if we use
# them — we used P5_CONNECT only in passageA, not as mission passageText.
# User said: "may weave 11:4 in connect if tap words in passageText"
# For caminhada/profundezas connect we wove 11:4 in passageB/passageA text.
# Optionally update M5 mission passage for connect-only questions — already OK.

assert len(bank) == 126, len(bank)

OUT.write_text(json.dumps(bank, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
print(f"Wrote {OUT} ({len(bank)} questions)")
