#!/usr/bin/env python3
"""Generate _part_genesis-12-50-a.json — first 10 missions (180 questions)."""
import json
from pathlib import Path

TRAIL = "genesis-12-50"
OUT = Path(__file__).parent / "_part_genesis-12-50-a.json"

TF = [
    {"id": "true", "text": "Verdadeiro"},
    {"id": "false", "text": "Falso"},
]


def qid(section, short, nn):
    return f"{TRAIL}-{short}-{section}-{nn:02d}"


def base(section, verse_ref, lo, evidence, difficulty, skill, typ, nn, short, **kw):
    question = kw.pop("question")
    obj = {
        "id": qid(section, short, nn),
        "trail": TRAIL,
        "section": section,
        "difficulty": difficulty,
        "type": typ,
        "skill": skill,
        "question": question,
        "prompt": question,
        "cue": question,
        "verseRef": verse_ref,
        "learningObjective": lo,
        "evidence": evidence,
        "feedbackCorrect": kw.pop("feedbackCorrect"),
        "feedbackWrong": kw.pop("feedbackWrong"),
        "options": kw.pop("options"),
        "correctOptionId": kw.pop("correctOptionId"),
        "correctAnswer": kw.pop("correctAnswer", None),
        "passageText": kw.pop("passageText"),
    }
    if obj["correctAnswer"] is None:
        obj["correctAnswer"] = obj["correctOptionId"]
    obj.update(kw)
    return obj


def mission(m):
    """Build 18 questions from mission dict with per-mode content."""
    section = m["section"]
    vr = m["verse_ref"]
    tb = m["tb"]
    lo = m["lo"]
    evidence = m["evidence"]
    insight = m["insight"]
    out = []

    for mode in ("semente", "caminhada", "profundezas"):
        short = {"semente": "sem", "caminhada": "cam", "profundezas": "pro"}[mode]
        skill = {"semente": "observe", "caminhada": "understand", "profundezas": "interpret"}[mode]
        c = m[mode]

        # 01 true_false
        out.append(
            base(
                section, vr, lo, evidence, mode, skill, "true_false", 1, short,
                question=c["tf_q"],
                feedbackCorrect=c["tf_ok"],
                feedbackWrong=c["tf_wrong"],
                options=TF,
                correctOptionId=c["tf_ans"],
                passageText=tb,
            )
        )

        # 02 tap
        tap_opts = [{"id": o["id"], "text": o["text"]} for o in c["tap_opts"]]
        out.append(
            base(
                section, vr, lo, evidence, mode, skill, "tap", 2, short,
                question=f'Em {vr}, toque a palavra que falta em "{c["tap_template"]}"?',
                feedbackCorrect=c["tap_ok"],
                feedbackWrong=c["tap_wrong"],
                options=tap_opts,
                correctOptionId=c["tap_ans"],
                passageText=tb,
                template=c["tap_template"],
            )
        )

        # 03 choice
        out.append(
            base(
                section, vr, lo, evidence, mode, skill, "choice", 3, short,
                question=c["choice_q"],
                feedbackCorrect=c["choice_ok"],
                feedbackWrong=c["choice_wrong"],
                options=c["choice_opts"],
                correctOptionId=c["choice_ans"],
                passageText=tb,
            )
        )

        # 04 order
        out.append(
            base(
                section, vr, lo, evidence, mode, skill, "order", 4, short,
                question=c["order_q"],
                feedbackCorrect=c["order_ok"],
                feedbackWrong=c["order_wrong"],
                options=c["order_opts"],
                correctOptionId=c["order_opts"][0]["id"],
                correctOrder=c["order_correct"],
                passageText=tb,
            )
        )

        # 05 complete
        out.append(
            base(
                section, vr, lo, evidence, mode, skill, "complete", 5, short,
                question=f'Complete {vr}: "{c["comp_template"]}".',
                feedbackCorrect=c["comp_ok"],
                feedbackWrong=c["comp_wrong"],
                options=c["comp_opts"],
                correctOptionId=c["comp_ans"],
                passageText=tb,
                template=c["comp_template"],
            )
        )

        # 06 connect
        out.append(
            base(
                section, vr, lo, evidence, mode, skill, "connect", 6, short,
                question=f"O que {vr} comunica que se liga a este contexto?",
                feedbackCorrect=c["conn_ok"],
                feedbackWrong=c["conn_wrong"],
                options=c["conn_opts"],
                correctOptionId=c["conn_ans"],
                passageText=tb,
                passageA={"ref": vr, "text": c["conn_a"]},
                passageB={"ref": "Contexto", "text": insight},
            )
        )

    return out


# ---------------------------------------------------------------------------
# Mission content
# ---------------------------------------------------------------------------

MISSIONS = []

# ===== 1. gen12-01-chamado =====
TB1 = "Ora, disse Jeová a Abrão: Sai-te da tua terra, da tua parentela e da casa de teu pai para a terra que te mostrarei; farei de ti uma grande nação, e te abençoarei, e engrandecerei o teu nome. Sê tu uma bênção."
MISSIONS.append({
    "section": "gen12-01-chamado",
    "verse_ref": "Gênesis 12:1–2",
    "tb": TB1,
    "insight": "O chamado: sair e ser bênção.",
    "lo": "Reconhecer que Jeová chama Abrão a sair e a ser bênção para as nações.",
    "evidence": ["Gênesis 12:1", "Gênesis 12:2"],
    "semente": {
        "tf_q": "Jeová manda Abrão sair da sua terra, da parentela e da casa de seu pai.",
        "tf_ans": "true",
        "tf_ok": "Certo: o chamado começa com sair da terra e da casa.",
        "tf_wrong": {"false": "O texto ordena Abrão a sair da terra e da parentela."},
        "tap_template": "Sai-te da tua ___, da tua parentela e da casa de teu pai",
        "tap_opts": [{"id": "a", "text": "terra"}, {"id": "b", "text": "nação"}, {"id": "c", "text": "bênção"}],
        "tap_ans": "a",
        "tap_ok": "Exato: Abrão deve sair da sua terra.",
        "tap_wrong": {"b": "Nação é a promessa, não o que ele deixa.", "c": "Bênção é o chamado final, não a lacuna."},
        "choice_q": "Segundo Gênesis 12:1–2, o que Jeová promete fazer de Abrão?",
        "choice_opts": [
            {"id": "a", "text": "Uma grande nação, com nome engrandecido"},
            {"id": "b", "text": "Um rei sobre o Egito desde já"},
            {"id": "c", "text": "Um sacerdote no templo de Salém"},
            {"id": "d", "text": "Um juiz das cidades da planície"},
        ],
        "choice_ans": "a",
        "choice_ok": "Certo: Jeová fará dele grande nação e engrandecerá o nome.",
        "choice_wrong": {
            "b": "O texto não fala de reinado no Egito.",
            "c": "Não há menção a sacerdócio aqui.",
            "d": "O chamado não o nomeia juiz das cidades.",
        },
        "order_q": "Qual é a ordem dos fatos em Gênesis 12:1–2?",
        "order_opts": [
            {"id": "a", "text": "Jeová manda Abrão sair da terra e da parentela"},
            {"id": "b", "text": "Promete fazer dele grande nação e abençoá-lo"},
            {"id": "c", "text": "Ordena: Sê tu uma bênção"},
        ],
        "order_correct": ["a", "b", "c"],
        "order_ok": "Certo: sair, promessa e ser bênção.",
        "order_wrong": {"b": "Reordene conforme o fluxo do chamado.", "c": "A bênção final vem depois da promessa."},
        "comp_template": "Sê tu uma ___",
        "comp_opts": [{"id": "a", "text": "bênção"}, {"id": "b", "text": "nação"}, {"id": "c", "text": "parentela"}],
        "comp_ans": "a",
        "comp_ok": "Certo: Abrão deve ser uma bênção.",
        "comp_wrong": {"b": "Nação é a promessa; a lacuna é bênção.", "c": "Parentela é o que ele deixa."},
        "conn_a": "Sê tu uma bênção",
        "conn_opts": [
            {"id": "a", "text": "Sair e ser bênção"},
            {"id": "b", "text": "Ficar na terra natal"},
            {"id": "c", "text": "Buscar fama própria"},
        ],
        "conn_ans": "a",
        "conn_ok": "Certo: o chamado une sair e ser bênção.",
        "conn_wrong": {"b": "O texto manda sair, não ficar.", "c": "O nome é engrandecido por Jeová, não por ambição."},
    },
    "caminhada": {
        "tf_q": "O chamado de Abrão limita-se a deixar a terra, sem qualquer missão de bênção.",
        "tf_ans": "false",
        "tf_ok": "Certo: Jeová também ordena que ele seja bênção.",
        "tf_wrong": {"true": "O texto une saída e vocação de bênção."},
        "tap_template": "farei de ti uma grande ___, e te abençoarei",
        "tap_opts": [{"id": "a", "text": "nação"}, {"id": "b", "text": "casa"}, {"id": "c", "text": "parentela"}],
        "tap_ans": "a",
        "tap_ok": "Exato: a promessa é uma grande nação.",
        "tap_wrong": {"b": "Casa é o que ele deixa.", "c": "Parentela também fica para trás."},
        "choice_q": "Como se relacionam a saída de Abrão e a promessa de Jeová?",
        "choice_opts": [
            {"id": "a", "text": "A saída é condição para a bênção prometida"},
            {"id": "b", "text": "A bênção vem sem Abrão precisar sair"},
            {"id": "c", "text": "Abrão sai para conquistar terras inimigas"},
            {"id": "d", "text": "A promessa anula qualquer missão de bênção"},
        ],
        "choice_ans": "a",
        "choice_ok": "Certo: sair abre caminho à nação e à bênção.",
        "choice_wrong": {
            "b": "O chamado começa com a ordem de sair.",
            "c": "Não há conquista militar neste trecho.",
            "d": "Jeová ordena: Sê tu uma bênção.",
        },
        "order_q": "Como se encadeiam os eventos de Gênesis 12:1–2?",
        "order_opts": [
            {"id": "a", "text": "Ordem de deixar terra, parentela e casa"},
            {"id": "b", "text": "Promessa de nação, bênção e nome grande"},
            {"id": "c", "text": "Chamado a ser ele mesmo uma bênção"},
        ],
        "order_correct": ["a", "b", "c"],
        "order_ok": "Certo: deixa, recebe promessa, torna-se bênção.",
        "order_wrong": {"b": "Siga a ordem do discurso de Jeová.", "c": "Ser bênção fecha o encadeamento."},
        "comp_template": "engrandecerei o teu ___",
        "comp_opts": [{"id": "a", "text": "nome"}, {"id": "b", "text": "pai"}, {"id": "c", "text": "terra"}],
        "comp_ans": "a",
        "comp_ok": "Certo: Jeová engrandecerá o nome de Abrão.",
        "comp_wrong": {"b": "Pai é o que ele deixa para trás.", "c": "Terra é destino, não esta lacuna."},
        "conn_a": "farei de ti uma grande nação, e te abençoarei",
        "conn_opts": [
            {"id": "b", "text": "Promessa após a saída"},
            {"id": "a", "text": "Retorno à parentela"},
            {"id": "c", "text": "Fim de qualquer aliança"},
        ],
        "conn_ans": "b",
        "conn_ok": "Certo: a bênção segue o chamado a sair.",
        "conn_wrong": {"a": "Ele deixa a parentela, não volta a ela.", "c": "O texto inaugura promessa, não a encerra."},
    },
    "profundezas": {
        "tf_q": "Ser bênção mostra que o chamado de Abrão olha além dele mesmo, para outros.",
        "tf_ans": "true",
        "tf_ok": "Certo: a bênção aponta o alcance do chamado.",
        "tf_wrong": {"false": "Sê tu uma bênção amplia o chamado para além de Abrão."},
        "tap_template": "para a terra que te ___",
        "tap_opts": [{"id": "a", "text": "mostrarei"}, {"id": "b", "text": "abençoarei"}, {"id": "c", "text": "engrandecerei"}],
        "tap_ans": "a",
        "tap_ok": "Exato: a terra é a que Jeová mostrará.",
        "tap_wrong": {"b": "Abençoarei refere-se a Abrão.", "c": "Engrandecerei refere-se ao nome."},
        "choice_q": "Qual leitura teológica o chamado de Abrão prepara no leitor?",
        "choice_opts": [
            {"id": "a", "text": "Deus inicia uma história de bênção pelas nações"},
            {"id": "b", "text": "Abrão é chamado só para benefício próprio"},
            {"id": "c", "text": "A fé dispensa qualquer saída concreta"},
            {"id": "d", "text": "O nome grande substitui a obediência"},
        ],
        "choice_ans": "a",
        "choice_ok": "Certo: sair e ser bênção abrem a história das nações.",
        "choice_wrong": {
            "b": "Sê tu uma bênção aponta além do eu.",
            "c": "O chamado exige saída real.",
            "d": "O nome é prometido junto com a obediência.",
        },
        "order_q": "Qual sequência revela o sentido de Gênesis 12:1–2?",
        "order_opts": [
            {"id": "a", "text": "Abrão deixa o centro familiar conhecido"},
            {"id": "b", "text": "Jeová promete nação, bênção e nome"},
            {"id": "c", "text": "Abrão é enviado a ser bênção"},
        ],
        "order_correct": ["a", "b", "c"],
        "order_ok": "Certo: desprendimento, promessa e missão de bênção.",
        "order_wrong": {"b": "A missão de bênção fecha o sentido.", "c": "Começa pelo deixar o conhecido."},
        "comp_template": "da casa de teu ___ para a terra que te mostrarei",
        "comp_opts": [{"id": "a", "text": "pai"}, {"id": "b", "text": "nome"}, {"id": "c", "text": "nação"}],
        "comp_ans": "a",
        "comp_ok": "Certo: ele deixa a casa do pai.",
        "comp_wrong": {"b": "Nome é o que será engrandecido.", "c": "Nação é a promessa futura."},
        "conn_a": "Sai-te da tua terra… Sê tu uma bênção",
        "conn_opts": [
            {"id": "c", "text": "Vocação que abençoa outros"},
            {"id": "a", "text": "Chamado só ao isolamento"},
            {"id": "b", "text": "Promessa sem qualquer custo"},
        ],
        "conn_ans": "c",
        "conn_ok": "Certo: sair e abençoar formam o sentido do chamado.",
        "conn_wrong": {"a": "Ser bênção impede leitura só isolada.", "b": "Há custo: deixar terra e casa."},
    },
})

# ===== 2. gen12-02-egito-e-lot =====
TB2 = "Disse Abrão a Ló: Não haja contenda entre mim e ti, e entre os meus pastores e os teus, porque somos irmãos. Porventura, não está toda a terra diante de ti? Rogo-te que te apartes de mim: se tu fores para a esquerda, eu irei para a direita; porém, se tu fores para a direita, eu irei para a esquerda."
MISSIONS.append({
    "section": "gen12-02-egito-e-lot",
    "verse_ref": "Gênesis 13:8–9",
    "tb": TB2,
    "insight": "Abrão cede a Ló a escolha da terra.",
    "lo": "Ver que Abrão evita contenda e cede a Ló a escolha da terra.",
    "evidence": ["Gênesis 13:8", "Gênesis 13:9"],
    "semente": {
        "tf_q": "Abrão pede a Ló que não haja contenda entre eles, porque são irmãos.",
        "tf_ans": "true",
        "tf_ok": "Certo: Abrão invoca o laço de irmãos contra a contenda.",
        "tf_wrong": {"false": "O texto registra exatamente esse pedido."},
        "tap_template": "Não haja ___ entre mim e ti",
        "tap_opts": [{"id": "a", "text": "contenda"}, {"id": "b", "text": "terra"}, {"id": "c", "text": "direita"}],
        "tap_ans": "a",
        "tap_ok": "Exato: Abrão rejeita a contenda.",
        "tap_wrong": {"b": "Terra está diante deles; a lacuna é contenda.", "c": "Direita é opção de caminho."},
        "choice_q": "O que Abrão oferece a Ló em Gênesis 13:8–9?",
        "choice_opts": [
            {"id": "a", "text": "Que Ló escolha a direção e Abrão vá à outra"},
            {"id": "b", "text": "Que Ló fique e Abrão tome toda a terra"},
            {"id": "c", "text": "Que os pastores decidam pela força"},
            {"id": "d", "text": "Que ambos voltem à terra de Harã"},
        ],
        "choice_ans": "a",
        "choice_ok": "Certo: Abrão deixa Ló escolher esquerda ou direita.",
        "choice_wrong": {
            "b": "Abrão cede a escolha, não a monopoliza.",
            "c": "Ele quer paz, não disputa pela força.",
            "d": "Não há retorno a Harã neste trecho.",
        },
        "order_q": "Qual é a ordem dos fatos em Gênesis 13:8–9?",
        "order_opts": [
            {"id": "a", "text": "Abrão rejeita a contenda entre irmãos"},
            {"id": "b", "text": "Afirma que toda a terra está diante de Ló"},
            {"id": "c", "text": "Propõe que Ló escolha o lado e ele o outro"},
        ],
        "order_correct": ["a", "b", "c"],
        "order_ok": "Certo: paz, terra aberta e escolha cedida.",
        "order_wrong": {"b": "Siga a ordem do diálogo.", "c": "A proposta de escolha fecha o trecho."},
        "comp_template": "porque somos ___",
        "comp_opts": [{"id": "a", "text": "irmãos"}, {"id": "b", "text": "pastores"}, {"id": "c", "text": "inimigos"}],
        "comp_ans": "a",
        "comp_ok": "Certo: o motivo é serem irmãos.",
        "comp_wrong": {"b": "Pastores estão na contenda, não nesta lacuna.", "c": "O texto afirma irmãos, não inimigos."},
        "conn_a": "Rogo-te que te apartes de mim: se tu fores para a esquerda, eu irei para a direita",
        "conn_opts": [
            {"id": "a", "text": "Abrão cede a escolha"},
            {"id": "b", "text": "Abrão toma a melhor terra"},
            {"id": "c", "text": "Ló deve ceder a Abrão"},
        ],
        "conn_ans": "a",
        "conn_ok": "Certo: Abrão cede a Ló a escolha da terra.",
        "conn_wrong": {"b": "Ele não se apropria primeiro.", "c": "Quem cede a escolha é Abrão."},
    },
    "caminhada": {
        "tf_q": "Abrão resolve a tensão com Ló impondo a direção que ele mesmo prefere.",
        "tf_ans": "false",
        "tf_ok": "Certo: Abrão deixa Ló escolher o caminho.",
        "tf_wrong": {"true": "O texto mostra Abrão cedendo a escolha a Ló."},
        "tap_template": "entre os meus ___ e os teus",
        "tap_opts": [{"id": "a", "text": "pastores"}, {"id": "b", "text": "irmãos"}, {"id": "c", "text": "esquerda"}],
        "tap_ans": "a",
        "tap_ok": "Exato: a contenda também envolve os pastores.",
        "tap_wrong": {"b": "Irmãos explica o laço, não esta lacuna.", "c": "Esquerda é lado da escolha."},
        "choice_q": "O que a proposta de Abrão revela sobre a relação com Ló?",
        "choice_opts": [
            {"id": "a", "text": "Prefere a paz entre irmãos à disputa pela terra"},
            {"id": "b", "text": "Usa a parentela para obrigar Ló a sair"},
            {"id": "c", "text": "Nega que haja terra suficiente para ambos"},
            {"id": "d", "text": "Transfere aos pastores a decisão final"},
        ],
        "choice_ans": "a",
        "choice_ok": "Certo: a paz fraterna pesa mais que a disputa.",
        "choice_wrong": {
            "b": "Abrão roga, não obriga.",
            "c": "Ele diz que toda a terra está diante de Ló.",
            "d": "A proposta é entre Abrão e Ló.",
        },
        "order_q": "Como se encadeiam os eventos de Gênesis 13:8–9?",
        "order_opts": [
            {"id": "a", "text": "Pedido para cessar a contenda"},
            {"id": "b", "text": "Lembrete de que são irmãos"},
            {"id": "c", "text": "Oferta de separação com escolha livre a Ló"},
        ],
        "order_correct": ["a", "b", "c"],
        "order_ok": "Certo: cessar contenda, irmãos, escolha cedida.",
        "order_wrong": {"b": "A oferta de escolha vem no fim.", "c": "Começa pelo fim da contenda."},
        "comp_template": "não está toda a ___ diante de ti?",
        "comp_opts": [{"id": "a", "text": "terra"}, {"id": "b", "text": "contenda"}, {"id": "c", "text": "direita"}],
        "comp_ans": "a",
        "comp_ok": "Certo: toda a terra está diante de Ló.",
        "comp_wrong": {"b": "Contenda é o que Abrão rejeita.", "c": "Direita é um dos lados."},
        "conn_a": "Não haja contenda entre mim e ti… porque somos irmãos",
        "conn_opts": [
            {"id": "b", "text": "Paz acima da disputa"},
            {"id": "a", "text": "Vitória pela contenda"},
            {"id": "c", "text": "Negação do laço fraterno"},
        ],
        "conn_ans": "b",
        "conn_ok": "Certo: Abrão põe a paz acima da disputa pela terra.",
        "conn_wrong": {"a": "Ele rejeita a contenda.", "c": "O texto afirma: somos irmãos."},
    },
    "profundezas": {
        "tf_q": "Ao ceder a escolha, Abrão mostra confiança de que a promessa não depende de tomar a melhor parcela.",
        "tf_ans": "true",
        "tf_ok": "Certo: ceder a terra revela confiança na promessa.",
        "tf_wrong": {"false": "Abrão não luta pela melhor fatia; confia e cede."},
        "tap_template": "eu irei para a ___",
        "tap_opts": [{"id": "a", "text": "direita"}, {"id": "b", "text": "contenda"}, {"id": "c", "text": "esquerda"}],
        "tap_ans": "a",
        "tap_ok": "Exato: se Ló for à esquerda, Abrão vai à direita.",
        "tap_wrong": {"b": "Contenda é o que ele evita.", "c": "Esquerda é o lado de Ló nesta hipótese."},
        "choice_q": "Que sentido teológico a cessão de Abrão a Ló prepara?",
        "choice_opts": [
            {"id": "a", "text": "A promessa de Deus não exige agarrar a melhor terra"},
            {"id": "b", "text": "A fé exige sempre ocupar o melhor território"},
            {"id": "c", "text": "Irmãos devem resolver tudo pela disputa"},
            {"id": "d", "text": "A terra prometida depende só da escolha de Ló"},
        ],
        "choice_ans": "a",
        "choice_ok": "Certo: Abrão pode ceder porque a promessa é de Jeová.",
        "choice_wrong": {
            "b": "Ele cede a escolha, não agarra o melhor.",
            "c": "O texto rejeita a contenda.",
            "d": "A promessa a Abrão não passa pela escolha de Ló.",
        },
        "order_q": "Qual sequência revela o sentido de Gênesis 13:8–9?",
        "order_opts": [
            {"id": "a", "text": "Rejeição da contenda entre irmãos"},
            {"id": "b", "text": "Reconhecimento da terra abundante"},
            {"id": "c", "text": "Cessão generosa da escolha a Ló"},
        ],
        "order_correct": ["a", "b", "c"],
        "order_ok": "Certo: paz, abundância e generosidade.",
        "order_wrong": {"b": "A cessão fecha o sentido.", "c": "Começa pela rejeição da contenda."},
        "comp_template": "Rogo-te que te ___ de mim",
        "comp_opts": [{"id": "a", "text": "apartes"}, {"id": "b", "text": "abençoes"}, {"id": "c", "text": "contendas"}],
        "comp_ans": "a",
        "comp_ok": "Certo: Abrão pede que Ló se aparte.",
        "comp_wrong": {"b": "Não há pedido de bênção aqui.", "c": "Ele rejeita contenda; a lacuna é apartes."},
        "conn_a": "se tu fores para a esquerda, eu irei para a direita",
        "conn_opts": [
            {"id": "c", "text": "Confiança que cede"},
            {"id": "a", "text": "Ambíção pela melhor terra"},
            {"id": "b", "text": "Medo de dividir o espaço"},
        ],
        "conn_ans": "c",
        "conn_ok": "Certo: ceder a escolha revela confiança.",
        "conn_wrong": {"a": "Abrão não agarra a melhor parcela.", "b": "Ele afirma que toda a terra está diante."},
    },
})

# ===== 3. gen12-03-melquisedeque =====
TB3 = "Melquisedeque, rei de Salém, trouxe pão e vinho: este era sacerdote do Deus Altíssimo. Abençoou a Abrão e disse: Bendito seja Abrão pelo Deus Altíssimo, Criador do céu e da terra! E bendito seja o Deus Altíssimo, que entregou os teus inimigos às tuas mãos! Abrão deu-lhe o dízimo de tudo."
MISSIONS.append({
    "section": "gen12-03-melquisedeque",
    "verse_ref": "Gênesis 14:18–20",
    "tb": TB3,
    "insight": "Melquisedeque: pão, vinho e bênção do Deus Altíssimo.",
    "lo": "Identificar Melquisedeque como sacerdote que abençoa Abrão em nome do Deus Altíssimo.",
    "evidence": ["Gênesis 14:18", "Gênesis 14:19", "Gênesis 14:20"],
    "semente": {
        "tf_q": "Melquisedeque, rei de Salém, era sacerdote do Deus Altíssimo.",
        "tf_ans": "true",
        "tf_ok": "Certo: o texto o apresenta como sacerdote do Deus Altíssimo.",
        "tf_wrong": {"false": "Gênesis 14:18 afirma esse sacerdócio."},
        "tap_template": "trouxe pão e ___",
        "tap_opts": [{"id": "a", "text": "vinho"}, {"id": "b", "text": "dízimo"}, {"id": "c", "text": "inimigos"}],
        "tap_ans": "a",
        "tap_ok": "Exato: Melquisedeque trouxe pão e vinho.",
        "tap_wrong": {"b": "Dízimo é o que Abrão dá depois.", "c": "Inimigos foram entregues às mãos de Abrão."},
        "choice_q": "O que Abrão faz em relação a Melquisedeque?",
        "choice_opts": [
            {"id": "a", "text": "Dá-lhe o dízimo de tudo"},
            {"id": "b", "text": "Recusa a bênção do sacerdote"},
            {"id": "c", "text": "Nomeia Melquisedeque rei de Egito"},
            {"id": "d", "text": "Entrega-lhe os inimigos capturados"},
        ],
        "choice_ans": "a",
        "choice_ok": "Certo: Abrão deu-lhe o dízimo de tudo.",
        "choice_wrong": {
            "b": "Melquisedeque abençoa Abrão; Abrão responde com dízimo.",
            "c": "Melquisedeque já é rei de Salém.",
            "d": "Quem entregou os inimigos foi o Deus Altíssimo.",
        },
        "order_q": "Qual é a ordem dos fatos em Gênesis 14:18–20?",
        "order_opts": [
            {"id": "a", "text": "Melquisedeque traz pão e vinho"},
            {"id": "b", "text": "Abençoa Abrão pelo Deus Altíssimo"},
            {"id": "c", "text": "Abrão lhe dá o dízimo de tudo"},
        ],
        "order_correct": ["a", "b", "c"],
        "order_ok": "Certo: pão e vinho, bênção, dízimo.",
        "order_wrong": {"b": "O dízimo vem depois da bênção.", "c": "Começa com pão e vinho."},
        "comp_template": "sacerdote do Deus ___",
        "comp_opts": [{"id": "a", "text": "Altíssimo"}, {"id": "b", "text": "Salém"}, {"id": "c", "text": "Abrão"}],
        "comp_ans": "a",
        "comp_ok": "Certo: sacerdote do Deus Altíssimo.",
        "comp_wrong": {"b": "Salém é a cidade do rei.", "c": "Abrão recebe a bênção."},
        "conn_a": "trouxe pão e vinho… Bendito seja Abrão pelo Deus Altíssimo",
        "conn_opts": [
            {"id": "a", "text": "Pão, vinho e bênção"},
            {"id": "b", "text": "Guerra sem bênção"},
            {"id": "c", "text": "Recusa do dízimo"},
        ],
        "conn_ans": "a",
        "conn_ok": "Certo: pão, vinho e bênção marcam o encontro.",
        "conn_wrong": {"b": "Há bênção explícita no texto.", "c": "Abrão dá o dízimo."},
    },
    "caminhada": {
        "tf_q": "A bênção de Melquisedeque atribui a vitória de Abrão ao próprio Abrão, sem mencionar Deus.",
        "tf_ans": "false",
        "tf_ok": "Certo: a bênção louva o Deus Altíssimo, que entregou os inimigos.",
        "tf_wrong": {"true": "O texto bendiz a Deus por entregar os inimigos."},
        "tap_template": "Abrão deu-lhe o ___ de tudo",
        "tap_opts": [{"id": "a", "text": "dízimo"}, {"id": "b", "text": "pão"}, {"id": "c", "text": "vinho"}],
        "tap_ans": "a",
        "tap_ok": "Exato: Abrão deu o dízimo de tudo.",
        "tap_wrong": {"b": "Pão foi trazido por Melquisedeque.", "c": "Vinho também veio com Melquisedeque."},
        "choice_q": "Como a bênção liga Abrão ao Deus Altíssimo?",
        "choice_opts": [
            {"id": "a", "text": "Abrão é bendito pelo Criador que lhe deu a vitória"},
            {"id": "b", "text": "Abrão é exaltado como criador do céu e da terra"},
            {"id": "c", "text": "Melquisedeque atribui a vitória aos deuses de Salém"},
            {"id": "d", "text": "A bênção ignora qualquer ação divina na batalha"},
        ],
        "choice_ans": "a",
        "choice_ok": "Certo: o Criador bendiz Abrão e entregou os inimigos.",
        "choice_wrong": {
            "b": "Criador do céu e da terra é o Deus Altíssimo.",
            "c": "A bênção é em nome do Deus Altíssimo.",
            "d": "O texto louva Deus pela entrega dos inimigos.",
        },
        "order_q": "Como se encadeiam os eventos de Gênesis 14:18–20?",
        "order_opts": [
            {"id": "a", "text": "Apresentação do sacerdote-rei com pão e vinho"},
            {"id": "b", "text": "Bênção a Abrão e louvor ao Deus Altíssimo"},
            {"id": "c", "text": "Resposta de Abrão com o dízimo"},
        ],
        "order_correct": ["a", "b", "c"],
        "order_ok": "Certo: encontro, bênção e dízimo.",
        "order_wrong": {"b": "O dízimo responde à bênção.", "c": "Começa com pão e vinho."},
        "comp_template": "Criador do céu e da ___",
        "comp_opts": [{"id": "a", "text": "terra"}, {"id": "b", "text": "Salém"}, {"id": "c", "text": "vitória"}],
        "comp_ans": "a",
        "comp_ok": "Certo: Criador do céu e da terra.",
        "comp_wrong": {"b": "Salém é a cidade.", "c": "Vitória é o resultado da entrega divina."},
        "conn_a": "bendito seja o Deus Altíssimo, que entregou os teus inimigos às tuas mãos",
        "conn_opts": [
            {"id": "b", "text": "Vitória creditada a Deus"},
            {"id": "a", "text": "Vitória só de Abrão"},
            {"id": "c", "text": "Bênção sem referência a Deus"},
        ],
        "conn_ans": "b",
        "conn_ok": "Certo: a vitória é atribuída ao Deus Altíssimo.",
        "conn_wrong": {"a": "O texto louva Deus pela entrega.", "c": "A bênção nomeia o Deus Altíssimo."},
    },
    "profundezas": {
        "tf_q": "O encontro com Melquisedeque mostra Abrão reconhecendo um sacerdócio maior, respondendo com dízimo.",
        "tf_ans": "true",
        "tf_ok": "Certo: Abrão recebe a bênção e oferece o dízimo.",
        "tf_wrong": {"false": "A bênção sacerdotal e o dízimo marcam o reconhecimento."},
        "tap_template": "rei de ___, trouxe pão e vinho",
        "tap_opts": [{"id": "a", "text": "Salém"}, {"id": "b", "text": "pão"}, {"id": "c", "text": "vinho"}],
        "tap_ans": "a",
        "tap_ok": "Exato: Melquisedeque é rei de Salém.",
        "tap_wrong": {"b": "Pão é o que ele trouxe, não o reino.", "c": "Vinho acompanha o pão, não nomeia a cidade."},
        "choice_q": "Que implicação o episódio de Melquisedeque deixa no leitor?",
        "choice_opts": [
            {"id": "a", "text": "A vitória e a bênção vêm do Deus Altíssimo, não do herói só"},
            {"id": "b", "text": "Abrão dispensa qualquer mediação sacerdotal"},
            {"id": "c", "text": "O dízimo prova que Abrão é superior a Deus"},
            {"id": "d", "text": "Pão e vinho servem só de banquete secular"},
        ],
        "choice_ans": "a",
        "choice_ok": "Certo: Deus Altíssimo é a fonte da vitória e da bênção.",
        "choice_wrong": {
            "b": "Abrão recebe a bênção do sacerdote.",
            "c": "O dízimo honra o sacerdote de Deus.",
            "d": "O gesto acompanha bênção sacerdotal.",
        },
        "order_q": "Qual sequência revela o sentido de Gênesis 14:18–20?",
        "order_opts": [
            {"id": "a", "text": "Sacerdócio do Deus Altíssimo se apresenta"},
            {"id": "b", "text": "Bênção atribui a vitória a Deus"},
            {"id": "c", "text": "Abrão responde com o dízimo"},
        ],
        "order_correct": ["a", "b", "c"],
        "order_ok": "Certo: sacerdócio, atribuição a Deus, resposta de Abrão.",
        "order_wrong": {"b": "O dízimo fecha o sentido.", "c": "Começa com o sacerdote-rei."},
        "comp_template": "entregou os teus ___ às tuas mãos",
        "comp_opts": [{"id": "a", "text": "inimigos"}, {"id": "b", "text": "dízimos"}, {"id": "c", "text": "pães"}],
        "comp_ans": "a",
        "comp_ok": "Certo: Deus entregou os inimigos às mãos de Abrão.",
        "comp_wrong": {"b": "Dízimo é a oferta de Abrão.", "c": "Pão foi trazido por Melquisedeque."},
        "conn_a": "Abrão deu-lhe o dízimo de tudo",
        "conn_opts": [
            {"id": "c", "text": "Resposta à bênção sacerdotal"},
            {"id": "a", "text": "Pagamento a um rei pagão"},
            {"id": "b", "text": "Recusa da mediação divina"},
        ],
        "conn_ans": "c",
        "conn_ok": "Certo: o dízimo responde à bênção do Deus Altíssimo.",
        "conn_wrong": {"a": "Melquisedeque é sacerdote do Deus Altíssimo.", "b": "Abrão acolhe a bênção."},
    },
})

# ===== 4. gen12-04-alianca-estrelas =====
TB4 = "Fez-lhe sair para fora e disse: Olha para o céu e conta as estrelas, se as poderes contar; e disse-lhe: Assim será a tua semente. Creu Abrão em Jeová, que lhe imputou isto como justiça."
MISSIONS.append({
    "section": "gen12-04-alianca-estrelas",
    "verse_ref": "Gênesis 15:5–6",
    "tb": TB4,
    "insight": "Estrelas e fé: Abrão creu e lhe foi imputado por justiça.",
    "lo": "Associar a promessa das estrelas à fé de Abrão, imputada como justiça.",
    "evidence": ["Gênesis 15:5", "Gênesis 15:6"],
    "semente": {
        "tf_q": "Jeová diz a Abrão que a sua semente será como as estrelas do céu.",
        "tf_ans": "true",
        "tf_ok": "Certo: Assim será a tua semente, após olhar as estrelas.",
        "tf_wrong": {"false": "O texto compara a semente às estrelas."},
        "tap_template": "Olha para o céu e conta as ___",
        "tap_opts": [{"id": "a", "text": "estrelas"}, {"id": "b", "text": "justiça"}, {"id": "c", "text": "semente"}],
        "tap_ans": "a",
        "tap_ok": "Exato: Abrão deve contar as estrelas.",
        "tap_wrong": {"b": "Justiça é o que lhe é imputado depois.", "c": "Semente é a promessa, não o que se conta."},
        "choice_q": "O que acontece depois que Abrão crê em Jeová?",
        "choice_opts": [
            {"id": "a", "text": "Isto lhe é imputado como justiça"},
            {"id": "b", "text": "Jeová anula a promessa da semente"},
            {"id": "c", "text": "Abrão recebe imediatamente um filho"},
            {"id": "d", "text": "As estrelas deixam de ser o sinal"},
        ],
        "choice_ans": "a",
        "choice_ok": "Certo: a fé é imputada como justiça.",
        "choice_wrong": {
            "b": "A promessa é afirmada, não anulada.",
            "c": "O texto não registra o nascimento aqui.",
            "d": "As estrelas ilustram a semente prometida.",
        },
        "order_q": "Qual é a ordem dos fatos em Gênesis 15:5–6?",
        "order_opts": [
            {"id": "a", "text": "Jeová faz Abrão olhar e contar as estrelas"},
            {"id": "b", "text": "Promete: Assim será a tua semente"},
            {"id": "c", "text": "Abrão crê e isto lhe é imputado como justiça"},
        ],
        "order_correct": ["a", "b", "c"],
        "order_ok": "Certo: estrelas, promessa e fé justificada.",
        "order_wrong": {"b": "A fé vem após a promessa.", "c": "Começa pelo olhar ao céu."},
        "comp_template": "Creu Abrão em ___",
        "comp_opts": [{"id": "a", "text": "Jeová"}, {"id": "b", "text": "estrelas"}, {"id": "c", "text": "semente"}],
        "comp_ans": "a",
        "comp_ok": "Certo: Abrão creu em Jeová.",
        "comp_wrong": {"b": "Estrelas são o sinal visual.", "c": "Semente é o conteúdo da promessa."},
        "conn_a": "Creu Abrão em Jeová, que lhe imputou isto como justiça",
        "conn_opts": [
            {"id": "a", "text": "Fé imputada por justiça"},
            {"id": "b", "text": "Fé rejeitada por Jeová"},
            {"id": "c", "text": "Contagem sem promessa"},
        ],
        "conn_ans": "a",
        "conn_ok": "Certo: crer leva à justiça imputada.",
        "conn_wrong": {"b": "Jeová imputa a fé como justiça.", "c": "As estrelas ilustram a semente."},
    },
    "caminhada": {
        "tf_q": "A justiça de Abrão neste trecho vem de ele ter contado todas as estrelas sem falhar.",
        "tf_ans": "false",
        "tf_ok": "Certo: a justiça é imputada porque Abrão creu, não por contar todas.",
        "tf_wrong": {"true": "O texto liga justiça à fé, não à contagem completa."},
        "tap_template": "Assim será a tua ___",
        "tap_opts": [{"id": "a", "text": "semente"}, {"id": "b", "text": "justiça"}, {"id": "c", "text": "céu"}],
        "tap_ans": "a",
        "tap_ok": "Exato: a semente será como as estrelas.",
        "tap_wrong": {"b": "Justiça é o que é imputado.", "c": "Céu é onde estão as estrelas."},
        "choice_q": "Qual relação o texto estabelece entre promessa, fé e justiça?",
        "choice_opts": [
            {"id": "a", "text": "Abrão crê na promessa e isso lhe é contado como justiça"},
            {"id": "b", "text": "A justiça precede qualquer fé na promessa"},
            {"id": "c", "text": "A fé de Abrão substitui a necessidade de promessa"},
            {"id": "d", "text": "Só a contagem das estrelas produz justiça"},
        ],
        "choice_ans": "a",
        "choice_ok": "Certo: crer na palavra de Jeová é imputado como justiça.",
        "choice_wrong": {
            "b": "Primeiro a promessa; depois a fé e a imputação.",
            "c": "A fé se apoia na promessa das estrelas.",
            "d": "O texto destaca o crer, não a contagem perfeita.",
        },
        "order_q": "Como se encadeiam os eventos de Gênesis 15:5–6?",
        "order_opts": [
            {"id": "a", "text": "Convite a olhar o céu e as estrelas"},
            {"id": "b", "text": "Palavra: a semente será assim"},
            {"id": "c", "text": "Fé de Abrão imputada como justiça"},
        ],
        "order_correct": ["a", "b", "c"],
        "order_ok": "Certo: ver, ouvir a promessa e crer.",
        "order_wrong": {"b": "A imputação fecha o encadeamento.", "c": "Começa pelo olhar ao céu."},
        "comp_template": "lhe imputou isto como ___",
        "comp_opts": [{"id": "a", "text": "justiça"}, {"id": "b", "text": "estrelas"}, {"id": "c", "text": "céu"}],
        "comp_ans": "a",
        "comp_ok": "Certo: foi imputado como justiça.",
        "comp_wrong": {"b": "Estrelas ilustram a semente.", "c": "Céu é o lugar do sinal."},
        "conn_a": "Olha para o céu e conta as estrelas… Assim será a tua semente",
        "conn_opts": [
            {"id": "b", "text": "Promessa que gera fé"},
            {"id": "a", "text": "Promessa sem resposta"},
            {"id": "c", "text": "Fé sem qualquer palavra"},
        ],
        "conn_ans": "b",
        "conn_ok": "Certo: a palavra sobre as estrelas gera a fé.",
        "conn_wrong": {"a": "Abrão crê na promessa.", "c": "A fé responde à palavra de Jeová."},
    },
    "profundezas": {
        "tf_q": "O texto apresenta a justiça de Abrão como dom imputado por Jeová mediante a fé, não como conquista humana.",
        "tf_ans": "true",
        "tf_ok": "Certo: Jeová imputa a fé como justiça.",
        "tf_wrong": {"false": "Imputar justiça pela fé exclui conquista própria."},
        "tap_template": "se as poderes ___",
        "tap_opts": [{"id": "a", "text": "contar"}, {"id": "b", "text": "Olha"}, {"id": "c", "text": "semente"}],
        "tap_ans": "a",
        "tap_ok": "Exato: se as poderes contar.",
        "tap_wrong": {"b": "Olha é o verbo do convite, não desta lacuna.", "c": "Semente é a promessa, não o verbo."},
        "choice_q": "Que leitura teológica Gênesis 15:5–6 prepara no leitor?",
        "choice_opts": [
            {"id": "a", "text": "A justiça diante de Deus nasce de crer na sua palavra"},
            {"id": "b", "text": "A justiça se mede pelo número de estrelas contadas"},
            {"id": "c", "text": "A fé de Abrão torna desnecessária a promessa divina"},
            {"id": "d", "text": "Só obras visíveis podem ser imputadas como justiça"},
        ],
        "choice_ans": "a",
        "choice_ok": "Certo: crer na palavra é o caminho da justiça imputada.",
        "choice_wrong": {
            "b": "O sinal é ilustrativo; a chave é a fé.",
            "c": "A fé se apoia na promessa.",
            "d": "O texto imputa a fé, não uma obra visível.",
        },
        "order_q": "Qual sequência revela o sentido de Gênesis 15:5–6?",
        "order_opts": [
            {"id": "a", "text": "Sinal das estrelas aponta a semente"},
            {"id": "b", "text": "Abrão crê na palavra de Jeová"},
            {"id": "c", "text": "Jeová imputa essa fé como justiça"},
        ],
        "order_correct": ["a", "b", "c"],
        "order_ok": "Certo: sinal, fé e justiça imputada.",
        "order_wrong": {"b": "A imputação fecha o sentido.", "c": "Começa pelo sinal das estrelas."},
        "comp_template": "Fez-lhe sair para ___ e disse",
        "comp_opts": [{"id": "a", "text": "fora"}, {"id": "b", "text": "dentro"}, {"id": "c", "text": "justiça"}],
        "comp_ans": "a",
        "comp_ok": "Certo: fez-lhe sair para fora.",
        "comp_wrong": {"b": "O texto diz para fora.", "c": "Justiça vem após a fé."},
        "conn_a": "Creu Abrão em Jeová, que lhe imputou isto como justiça",
        "conn_opts": [
            {"id": "c", "text": "Justiça pela fé"},
            {"id": "a", "text": "Justiça pelas obras"},
            {"id": "b", "text": "Fé sem imputação"},
        ],
        "conn_ans": "c",
        "conn_ok": "Certo: o trecho resume justiça pela fé.",
        "conn_wrong": {"a": "Não há lista de obras aqui.", "b": "Jeová imputa a fé como justiça."},
    },
})

# ===== 5. gen12-05-agar-ismael =====
TB5 = "Disse-lhe ainda mais o Anjo de Jeová: Eis que concebeste e darás à luz um filho, a quem chamarás Ismael, porque Jeová ouviu a tua aflição. Ele será como um jumento selvagem entre os homens; a sua mão será contra todos, e a mão de todos, contra ele: ao oriente de todos os seus irmãos habitará."
MISSIONS.append({
    "section": "gen12-05-agar-ismael",
    "verse_ref": "Gênesis 16:11–12",
    "tb": TB5,
    "insight": "Agar ouve: Ismael nascerá — Deus vê a aflita.",
    "lo": "Perceber que Jeová ouve a aflição de Agar e anuncia o nascimento de Ismael.",
    "evidence": ["Gênesis 16:11", "Gênesis 16:12"],
    "semente": {
        "tf_q": "O Anjo de Jeová anuncia a Agar que ela dará à luz um filho chamado Ismael.",
        "tf_ans": "true",
        "tf_ok": "Certo: o nome Ismael é anunciado à Agar.",
        "tf_wrong": {"false": "O texto ordena chamar o filho Ismael."},
        "tap_template": "a quem chamarás ___",
        "tap_opts": [{"id": "a", "text": "Ismael"}, {"id": "b", "text": "Jeová"}, {"id": "c", "text": "Anjo"}],
        "tap_ans": "a",
        "tap_ok": "Exato: o filho se chamará Ismael.",
        "tap_wrong": {"b": "Jeová ouviu a aflição; o nome do filho é Ismael.", "c": "Anjo é quem anuncia, não o nome do filho."},
        "choice_q": "Por que o filho deve chamar-se Ismael, segundo o texto?",
        "choice_opts": [
            {"id": "a", "text": "Porque Jeová ouviu a aflição de Agar"},
            {"id": "b", "text": "Porque Agar escolheu o nome sozinha"},
            {"id": "c", "text": "Porque o menino será sacerdote em Salém"},
            {"id": "d", "text": "Porque ele herdará a terra de Canaã só"},
        ],
        "choice_ans": "a",
        "choice_ok": "Certo: Ismael liga-se a Jeová ter ouvido a aflição.",
        "choice_wrong": {
            "b": "O nome vem da palavra do Anjo.",
            "c": "Não há sacerdócio neste anúncio.",
            "d": "O texto descrebe outro destino para Ismael.",
        },
        "order_q": "Qual é a ordem dos fatos em Gênesis 16:11–12?",
        "order_opts": [
            {"id": "a", "text": "Anúncio da concepção e do nome Ismael"},
            {"id": "b", "text": "Motivo: Jeová ouviu a aflição"},
            {"id": "c", "text": "Descrição do caráter e da habitação de Ismael"},
        ],
        "order_correct": ["a", "b", "c"],
        "order_ok": "Certo: nome, motivo e destino de Ismael.",
        "order_wrong": {"b": "O caráter vem depois do motivo.", "c": "Começa pelo anúncio do filho."},
        "comp_template": "Jeová ouviu a tua ___",
        "comp_opts": [{"id": "a", "text": "aflição"}, {"id": "b", "text": "vitória"}, {"id": "c", "text": "semente"}],
        "comp_ans": "a",
        "comp_ok": "Certo: Jeová ouviu a aflição de Agar.",
        "comp_wrong": {"b": "Não há vitória neste anúncio.", "c": "Semente não é a palavra desta lacuna."},
        "conn_a": "porque Jeová ouviu a tua aflição",
        "conn_opts": [
            {"id": "a", "text": "Deus vê a aflita"},
            {"id": "b", "text": "Deus ignora Agar"},
            {"id": "c", "text": "Ismael sem motivo"},
        ],
        "conn_ans": "a",
        "conn_ok": "Certo: o nome marca que Deus ouviu a aflita.",
        "conn_wrong": {"b": "Jeová ouviu a aflição.", "c": "O texto dá o motivo do nome."},
    },
    "caminhada": {
        "tf_q": "O anúncio a Agar limita-se ao nome do filho, sem qualquer descrição do seu futuro.",
        "tf_ans": "false",
        "tf_ok": "Certo: o texto também descreve o caráter e a habitação de Ismael.",
        "tf_wrong": {"true": "Há descrição de Ismael como jumento selvagem e sua habitação."},
        "tap_template": "como um jumento ___ entre os homens",
        "tap_opts": [{"id": "a", "text": "selvagem"}, {"id": "b", "text": "aflição"}, {"id": "c", "text": "oriente"}],
        "tap_ans": "a",
        "tap_ok": "Exato: como um jumento selvagem.",
        "tap_wrong": {"b": "Aflição explica o nome, não esta lacuna.", "c": "Oriente descreve a habitação, não o jumento."},
        "choice_q": "O que o nome Ismael comunica no encadeamento do anúncio?",
        "choice_opts": [
            {"id": "a", "text": "Liga o nascimento ao fato de Deus ter ouvido Agar"},
            {"id": "b", "text": "Serve só de título militar sem ligação à aflição"},
            {"id": "c", "text": "Substitui qualquer palavra sobre o caráter do filho"},
            {"id": "d", "text": "Anula a descrição de sua relação com os irmãos"},
        ],
        "choice_ans": "a",
        "choice_ok": "Certo: o nome explica-se pela aflição ouvida.",
        "choice_wrong": {
            "b": "O texto liga o nome à aflição ouvida.",
            "c": "Há descrição do caráter em seguida.",
            "d": "O texto fala da habitação ao oriente dos irmãos.",
        },
        "order_q": "Como se encadeiam os eventos de Gênesis 16:11–12?",
        "order_opts": [
            {"id": "a", "text": "Promessa do filho e do nome"},
            {"id": "b", "text": "Explicação: Jeová ouviu a aflição"},
            {"id": "c", "text": "Retrato de Ismael entre os homens e irmãos"},
        ],
        "order_correct": ["a", "b", "c"],
        "order_ok": "Certo: filho, motivo e retrato.",
        "order_wrong": {"b": "O retrato fecha o anúncio.", "c": "Começa pelo filho e o nome."},
        "comp_template": "a mão de todos, contra ___",
        "comp_opts": [{"id": "a", "text": "ele"}, {"id": "b", "text": "Agar"}, {"id": "c", "text": "Jeová"}],
        "comp_ans": "a",
        "comp_ok": "Certo: a mão de todos contra ele.",
        "comp_wrong": {"b": "A frase refere-se a Ismael.", "c": "Jeová é quem ouviu a aflição."},
        "conn_a": "Eis que concebeste e darás à luz um filho, a quem chamarás Ismael",
        "conn_opts": [
            {"id": "b", "text": "Nascimento ouvido por Deus"},
            {"id": "a", "text": "Silêncio diante da aflição"},
            {"id": "c", "text": "Rejeição definitiva de Agar"},
        ],
        "conn_ans": "b",
        "conn_ok": "Certo: Ismael nasce porque Deus ouviu Agar.",
        "conn_wrong": {"a": "Jeová ouviu a aflição.", "c": "Há anúncio de nascimiento e cuidado."},
    },
    "profundezas": {
        "tf_q": "Mesmo na aflição de Agar, o texto apresenta Jeová como quem ouve e nomeia o futuro do filho.",
        "tf_ans": "true",
        "tf_ok": "Certo: Deus ouve a aflita e define o nome e o destino.",
        "tf_wrong": {"false": "Ouvir a aflição e nomear Ismael mostram cuidado divino."},
        "tap_template": "ao ___ de todos os seus irmãos habitará",
        "tap_opts": [{"id": "a", "text": "oriente"}, {"id": "b", "text": "homens"}, {"id": "c", "text": "filho"}],
        "tap_ans": "a",
        "tap_ok": "Exato: habitará ao oriente dos irmãos.",
        "tap_wrong": {"b": "Homens aparece antes; a lacuna é oriente.", "c": "Filho é o anúncio inicial, não esta lacuna."},
        "choice_q": "Que implicação teológica o anúncio a Agar deixa?",
        "choice_opts": [
            {"id": "a", "text": "Deus não abandona a aflita; ouve e fala o futuro"},
            {"id": "b", "text": "Aflição prova que Deus se cala para sempre"},
            {"id": "c", "text": "Só os livres de sofrimento recebem palavra divina"},
            {"id": "d", "text": "O nome Ismael nega qualquer atenção de Jeová"},
        ],
        "choice_ans": "a",
        "choice_ok": "Certo: ouvir a aflição é o centro do anúncio.",
        "choice_wrong": {
            "b": "Jeová ouviu e falou.",
            "c": "Agar aflita recebe a palavra.",
            "d": "Ismael significa que Deus ouviu.",
        },
        "order_q": "Qual sequência revela o sentido de Gênesis 16:11–12?",
        "order_opts": [
            {"id": "a", "text": "Deus vê a aflição de Agar"},
            {"id": "b", "text": "Nomeia o filho Ismael"},
            {"id": "c", "text": "Descreve o caminho difícil de Ismael"},
        ],
        "order_correct": ["a", "b", "c"],
        "order_ok": "Certo: ouvir, nomear e traçar o destino.",
        "order_wrong": {"b": "O destino fecha o sentido.", "c": "Começa pelo ouvir a aflição."},
        "comp_template": "a sua mão será contra ___",
        "comp_opts": [{"id": "a", "text": "todos"}, {"id": "b", "text": "Agar"}, {"id": "c", "text": "Anjo"}],
        "comp_ans": "a",
        "comp_ok": "Certo: a mão será contra todos.",
        "comp_wrong": {"b": "A frase descreve Ismael entre os homens.", "c": "Anjo é quem anuncia."},
        "conn_a": "Jeová ouviu a tua aflição",
        "conn_opts": [
            {"id": "c", "text": "Deus ouve a aflita"},
            {"id": "a", "text": "Deus esquece Agar"},
            {"id": "b", "text": "Aflição sem resposta"},
        ],
        "conn_ans": "c",
        "conn_ok": "Certo: o insight é Deus ver e ouvir a aflita.",
        "conn_wrong": {"a": "O texto diz que Jeová ouviu.", "b": "Há anúncio e nome em resposta."},
    },
})

# ===== 6. gen12-06-circuncisao =====
TB6 = "O teu nome não se chamará mais Abrão, mas Abraão será o teu nome; pois te hei posto por pai de uma multidão de nações."
MISSIONS.append({
    "section": "gen12-06-circuncisao",
    "verse_ref": "Gênesis 17:5",
    "tb": TB6,
    "insight": "Abrão vira Abraão: pai de multidão de nações.",
    "lo": "Reconhecer a mudança de Abrão para Abraão como sinal de pai de muitas nações.",
    "evidence": ["Gênesis 17:5"],
    "semente": {
        "tf_q": "Jeová muda o nome de Abrão para Abraão.",
        "tf_ans": "true",
        "tf_ok": "Certo: não se chamará mais Abrão, mas Abraão.",
        "tf_wrong": {"false": "O texto declara a mudança de nome."},
        "tap_template": "mas ___ será o teu nome",
        "tap_opts": [{"id": "a", "text": "Abraão"}, {"id": "b", "text": "Abrão"}, {"id": "c", "text": "pai"}],
        "tap_ans": "a",
        "tap_ok": "Exato: o novo nome é Abraão.",
        "tap_wrong": {"b": "Abrão é o nome que deixa de valer.", "c": "Pai explica o motivo, não o nome novo."},
        "choice_q": "Por que o nome passa a ser Abraão, segundo o texto?",
        "choice_opts": [
            {"id": "a", "text": "Porque Deus o pôs por pai de uma multidão de nações"},
            {"id": "b", "text": "Porque Abrão pediu um nome mais curto"},
            {"id": "c", "text": "Porque ele deixou de ser pai de alguém"},
            {"id": "d", "text": "Porque o nome Abrão significava rei do Egito"},
        ],
        "choice_ans": "a",
        "choice_ok": "Certo: Abraão marca o pai de multidão de nações.",
        "choice_wrong": {
            "b": "A mudança vem da palavra de Jeová.",
            "c": "O texto amplia a paternidade.",
            "d": "Não há essa etimologia no versículo.",
        },
        "order_q": "Qual é a ordem dos fatos em Gênesis 17:5?",
        "order_opts": [
            {"id": "a", "text": "Anúncio de que Abrão não será mais o nome"},
            {"id": "b", "text": "Declaração do novo nome: Abraão"},
            {"id": "c", "text": "Motivo: pai de uma multidão de nações"},
        ],
        "order_correct": ["a", "b", "c"],
        "order_ok": "Certo: fim do nome antigo, novo nome e motivo.",
        "order_wrong": {"b": "O motivo fecha o versículo.", "c": "Começa pela negação do nome antigo."},
        "comp_template": "pai de uma ___ de nações",
        "comp_opts": [{"id": "a", "text": "multidão"}, {"id": "b", "text": "tribo"}, {"id": "c", "text": "casa"}],
        "comp_ans": "a",
        "comp_ok": "Certo: pai de uma multidão de nações.",
        "comp_wrong": {"b": "O texto diz multidão.", "c": "Casa não completa esta frase."},
        "conn_a": "Abraão será o teu nome; pois te hei posto por pai de uma multidão de nações",
        "conn_opts": [
            {"id": "a", "text": "Nome e paternidade ampliada"},
            {"id": "b", "text": "Nome sem qualquer significado"},
            {"id": "c", "text": "Fim da promessa às nações"},
        ],
        "conn_ans": "a",
        "conn_ok": "Certo: Abraão significa a paternidade ampliada.",
        "conn_wrong": {"b": "O texto explica o nome.", "c": "O nome aponta multidão de nações."},
    },
    "caminhada": {
        "tf_q": "A mudança de nome ocorre sem ligação com a vocação de Abrão perante as nações.",
        "tf_ans": "false",
        "tf_ok": "Certo: o novo nome explica-se pela paternidade das nações.",
        "tf_wrong": {"true": "O texto liga Abraão a pai de multidão de nações."},
        "tap_template": "não se chamará mais ___",
        "tap_opts": [{"id": "a", "text": "Abrão"}, {"id": "b", "text": "Abraão"}, {"id": "c", "text": "nações"}],
        "tap_ans": "a",
        "tap_ok": "Exato: não se chamará mais Abrão.",
        "tap_wrong": {"b": "Abraão é o nome novo.", "c": "Nações entram no motivo."},
        "choice_q": "Como o novo nome se relaciona com a identidade de Abrão?",
        "choice_opts": [
            {"id": "a", "text": "Marca uma identidade ampliada: pai de muitas nações"},
            {"id": "b", "text": "Apaga qualquer papel de Abrão na história"},
            {"id": "c", "text": "Reduz Abrão a chefe de uma só família"},
            {"id": "d", "text": "Substitui a aliança por um título político local"},
        ],
        "choice_ans": "a",
        "choice_ok": "Certo: Abraão amplia a identidade para as nações.",
        "choice_wrong": {
            "b": "O nome reforça a vocação, não a apaga.",
            "c": "Multidão de nações amplia, não reduz.",
            "d": "O foco é paternidade das nações, não cargo local.",
        },
        "order_q": "Como se encadeiam os eventos de Gênesis 17:5?",
        "order_opts": [
            {"id": "a", "text": "Negação do nome Abrão"},
            {"id": "b", "text": "Afirmação do nome Abraão"},
            {"id": "c", "text": "Explicação pela multidão de nações"},
        ],
        "order_correct": ["a", "b", "c"],
        "order_ok": "Certo: troca de nome e motivo.",
        "order_wrong": {"b": "A explicação fecha o encadeamento.", "c": "Começa pela negação do nome antigo."},
        "comp_template": "te hei posto por ___ de uma multidão de nações",
        "comp_opts": [{"id": "a", "text": "pai"}, {"id": "b", "text": "rei"}, {"id": "c", "text": "servo"}],
        "comp_ans": "a",
        "comp_ok": "Certo: posto por pai de uma multidão.",
        "comp_wrong": {"b": "O texto diz pai, não rei.", "c": "Servo não completa esta frase."},
        "conn_a": "O teu nome não se chamará mais Abrão, mas Abraão será o teu nome",
        "conn_opts": [
            {"id": "b", "text": "Identidade redefinida por Deus"},
            {"id": "a", "text": "Nome escolhido ao acaso"},
            {"id": "c", "text": "Retorno ao nome Abrão"},
        ],
        "conn_ans": "b",
        "conn_ok": "Certo: Deus redefine o nome e a vocação.",
        "conn_wrong": {"a": "Há motivo explícito no texto.", "c": "Abrão deixa de ser o nome."},
    },
    "profundezas": {
        "tf_q": "O novo nome Abraão prepara o leitor para uma aliança com alcance além de um só clã.",
        "tf_ans": "true",
        "tf_ok": "Certo: multidão de nações amplia o horizonte da aliança.",
        "tf_wrong": {"false": "Pai de multidão de nações aponta além de um clã."},
        "tap_template": "multidão de ___",
        "tap_opts": [{"id": "a", "text": "nações"}, {"id": "b", "text": "Abrão"}, {"id": "c", "text": "nome"}],
        "tap_ans": "a",
        "tap_ok": "Exato: multidão de nações.",
        "tap_wrong": {"b": "Abrão é o nome antigo.", "c": "Nome é o que muda; a lacuna é nações."},
        "choice_q": "Que sentido teológico a troca de nome carrega?",
        "choice_opts": [
            {"id": "a", "text": "Deus redefine a pessoa conforme a promessa às nações"},
            {"id": "b", "text": "O nome novo cancela a promessa anterior"},
            {"id": "c", "text": "A identidade humana fica fora do alcance de Deus"},
            {"id": "d", "text": "Só títulos humanos podem mudar uma vocação"},
        ],
        "choice_ans": "a",
        "choice_ok": "Certo: o nome novo expressa a promessa divina.",
        "choice_wrong": {
            "b": "O nome reforça a promessa ampliada.",
            "c": "Deus mesmo muda o nome.",
            "d": "Aqui quem muda é Jeová.",
        },
        "order_q": "Qual sequência revela o sentido de Gênesis 17:5?",
        "order_opts": [
            {"id": "a", "text": "Deus desfaz o nome limitado Abrão"},
            {"id": "b", "text": "Confere o nome Abraão"},
            {"id": "c", "text": "Liga o nome à paternidade das nações"},
        ],
        "order_correct": ["a", "b", "c"],
        "order_ok": "Certo: desfazer, renomear e ampliar a vocação.",
        "order_wrong": {"b": "A ligação às nações fecha o sentido.", "c": "Começa pelo fim do nome Abrão."},
        "comp_template": "Abraão será o teu ___",
        "comp_opts": [{"id": "a", "text": "nome"}, {"id": "b", "text": "filho"}, {"id": "c", "text": "servo"}],
        "comp_ans": "a",
        "comp_ok": "Certo: Abraão será o teu nome.",
        "comp_wrong": {"b": "Filho não completa esta frase.", "c": "Servo não é a palavra do texto."},
        "conn_a": "pai de uma multidão de nações",
        "conn_opts": [
            {"id": "c", "text": "Pai de muitas nações"},
            {"id": "a", "text": "Pai de uma só casa"},
            {"id": "b", "text": "Fim da descendência"},
        ],
        "conn_ans": "c",
        "conn_ok": "Certo: o insight é a paternidade ampliada.",
        "conn_wrong": {"a": "O texto fala de multidão de nações.", "b": "Há expansão, não fim."},
    },
})

# ===== 7. gen12-07-sodoma =====
TB7 = "Longe de ti fazeres tal coisa, que mates os justos com os ímpios, de sorte que sejam os justos como os ímpios; seja isto longe de ti: não fará justiça o Juiz de toda a terra?"
MISSIONS.append({
    "section": "gen12-07-sodoma",
    "verse_ref": "Gênesis 18:25",
    "tb": TB7,
    "insight": "Abraão intercede: o Juiz de toda a terra fará justiça?",
    "lo": "Ver Abraão intercedendo para que o Juiz de toda a terra não trate justos como ímpios.",
    "evidence": ["Gênesis 18:25"],
    "semente": {
        "tf_q": "Abraão afirma que está longe de Deus matar os justos com os ímpios.",
        "tf_ans": "true",
        "tf_ok": "Certo: Longe de ti fazeres tal coisa, diz Abraão.",
        "tf_wrong": {"false": "O texto registra essa afirmação de Abraão."},
        "tap_template": "que mates os ___ com os ímpios",
        "tap_opts": [{"id": "a", "text": "justos"}, {"id": "b", "text": "ímpios"}, {"id": "c", "text": "Juiz"}],
        "tap_ans": "a",
        "tap_ok": "Exato: não matar os justos com os ímpios.",
        "tap_wrong": {"b": "Ímpios é o outro polo da frase.", "c": "Juiz é o título de Deus no fim."},
        "choice_q": "Como Abraão se dirige a Deus neste versículo?",
        "choice_opts": [
            {"id": "a", "text": "Como Juiz de toda a terra, que fará justiça"},
            {"id": "b", "text": "Como um rei local sem autoridade moral"},
            {"id": "c", "text": "Como alguém indiferente a justos e ímpios"},
            {"id": "d", "text": "Como um deus que prefere destruir os justos"},
        ],
        "choice_ans": "a",
        "choice_ok": "Certo: Abraão invoca o Juiz de toda a terra.",
        "choice_wrong": {
            "b": "O título é Juiz de toda a terra.",
            "c": "Abraão espera justiça, não indiferença.",
            "d": "Ele rejeita tratar justos como ímpios.",
        },
        "order_q": "Qual é a ordem dos fatos em Gênesis 18:25?",
        "order_opts": [
            {"id": "a", "text": "Rejeição de matar justos com ímpios"},
            {"id": "b", "text": "Recusa de igualar justos aos ímpios"},
            {"id": "c", "text": "Apelo: o Juiz de toda a terra fará justiça"},
        ],
        "order_correct": ["a", "b", "c"],
        "order_ok": "Certo: rejeição, distinção e apelo à justiça.",
        "order_wrong": {"b": "O apelo ao Juiz fecha o versículo.", "c": "Começa por longe de ti."},
        "comp_template": "o Juiz de toda a ___",
        "comp_opts": [{"id": "a", "text": "terra"}, {"id": "b", "text": "cidade"}, {"id": "c", "text": "casa"}],
        "comp_ans": "a",
        "comp_ok": "Certo: Juiz de toda a terra.",
        "comp_wrong": {"b": "O texto diz terra.", "c": "Casa não completa esta frase."},
        "conn_a": "não fará justiça o Juiz de toda a terra?",
        "conn_opts": [
            {"id": "a", "text": "Intercessão pela justiça"},
            {"id": "b", "text": "Pedido de injustiça"},
            {"id": "c", "text": "Silêncio sem apelo"},
        ],
        "conn_ans": "a",
        "conn_ok": "Certo: Abraão intercede apelando à justiça de Deus.",
        "conn_wrong": {"b": "Ele rejeita a injustiça.", "c": "Há apelo explícito."},
    },
    "caminhada": {
        "tf_q": "Abraão aceita sem questionar que justos e ímpios sejam tratados do mesmo modo.",
        "tf_ans": "false",
        "tf_ok": "Certo: ele insiste que isso esteja longe de Deus.",
        "tf_wrong": {"true": "Abraão rejeita igualar justos e ímpios."},
        "tap_template": "sejam os justos como os ___",
        "tap_opts": [{"id": "a", "text": "ímpios"}, {"id": "b", "text": "justos"}, {"id": "c", "text": "terra"}],
        "tap_ans": "a",
        "tap_ok": "Exato: não sejam os justos como os ímpios.",
        "tap_wrong": {"b": "Justos é o primeiro termo, não esta lacuna.", "c": "Terra aparece no título do Juiz."},
        "choice_q": "Qual lógica Abraão usa ao interceder?",
        "choice_opts": [
            {"id": "a", "text": "O caráter justo de Deus impede confundir justos e ímpios"},
            {"id": "b", "text": "Deus deve destruir todos para manter a ordem"},
            {"id": "c", "text": "Justiça divina não se aplica a cidades humanas"},
            {"id": "d", "text": "Os ímpios merecem o mesmo trato que os justos"},
        ],
        "choice_ans": "a",
        "choice_ok": "Certo: a justiça do Juiz exige distinção.",
        "choice_wrong": {
            "b": "Abraão rejeita matar justos com ímpios.",
            "c": "Ele chama Deus de Juiz de toda a terra.",
            "d": "Ele recusa essa igualdade.",
        },
        "order_q": "Como se encadeiam os eventos de Gênesis 18:25?",
        "order_opts": [
            {"id": "a", "text": "Protesto contra destruir justos com ímpios"},
            {"id": "b", "text": "Insistência em não igualá-los"},
            {"id": "c", "text": "Convocação do Juiz a fazer justiça"},
        ],
        "order_correct": ["a", "b", "c"],
        "order_ok": "Certo: protesto, distinção e apelo.",
        "order_wrong": {"b": "O apelo ao Juiz fecha o raciocínio.", "c": "Começa pelo longe de ti."},
        "comp_template": "Longe de ti fazeres tal ___",
        "comp_opts": [{"id": "a", "text": "coisa"}, {"id": "b", "text": "justiça"}, {"id": "c", "text": "terra"}],
        "comp_ans": "a",
        "comp_ok": "Certo: Longe de ti fazeres tal coisa.",
        "comp_wrong": {"b": "Justiça é o que Abraão espera.", "c": "Terra aparece no título do Juiz."},
        "conn_a": "Longe de ti fazeres tal coisa, que mates os justos com os ímpios",
        "conn_opts": [
            {"id": "b", "text": "Apelo ao Juiz justo"},
            {"id": "a", "text": "Aceitação da confusão moral"},
            {"id": "c", "text": "Negação de qualquer juiz"},
        ],
        "conn_ans": "b",
        "conn_ok": "Certo: Abraão apela ao Juiz justo.",
        "conn_wrong": {"a": "Ele rejeita confundir justos e ímpios.", "c": "Ele nomeia o Juiz de toda a terra."},
    },
    "profundezas": {
        "tf_q": "A intercessão de Abraão parte da confiança de que o Juiz de toda a terra age com justiça.",
        "tf_ans": "true",
        "tf_ok": "Certo: o apelo pressupõe o caráter justo de Deus.",
        "tf_wrong": {"false": "Abraão intercede porque confia na justiça do Juiz."},
        "tap_template": "não fará ___ o Juiz de toda a terra",
        "tap_opts": [{"id": "a", "text": "justiça"}, {"id": "b", "text": "coisa"}, {"id": "c", "text": "sorte"}],
        "tap_ans": "a",
        "tap_ok": "Exato: não fará justiça o Juiz…?",
        "tap_wrong": {"b": "Coisa aparece em 'tal coisa', não aqui.", "c": "Sorte está em 'de sorte que', não nesta lacuna."},
        "choice_q": "Que implicação teológica a pergunta de Abraão prepara?",
        "choice_opts": [
            {"id": "a", "text": "A fé ousa interceder porque confia no caráter justo de Deus"},
            {"id": "b", "text": "Interceder é duvidar de que Deus seja Juiz"},
            {"id": "c", "text": "Justos e ímpios devem sempre ter o mesmo fim"},
            {"id": "d", "text": "A justiça divina não alcança a terra"},
        ],
        "choice_ans": "a",
        "choice_ok": "Certo: interceder apoia-se no Juiz justo.",
        "choice_wrong": {
            "b": "O título Juiz afirma, não nega, a justiça.",
            "c": "Abraão rejeita esse igualamento.",
            "d": "Ele fala do Juiz de toda a terra.",
        },
        "order_q": "Qual sequência revela o sentido de Gênesis 18:25?",
        "order_opts": [
            {"id": "a", "text": "Abraão rejeita a injustiça de misturar justos e ímpios"},
            {"id": "b", "text": "Afirma a diferença entre justos e ímpios"},
            {"id": "c", "text": "Apela ao Juiz de toda a terra"},
        ],
        "order_correct": ["a", "b", "c"],
        "order_ok": "Certo: rejeição, distinção e apelo confiante.",
        "order_wrong": {"b": "O apelo fecha o sentido.", "c": "Começa pela rejeição."},
        "comp_template": "mates os justos com os ___",
        "comp_opts": [{"id": "a", "text": "ímpios"}, {"id": "b", "text": "juízes"}, {"id": "c", "text": "anjos"}],
        "comp_ans": "a",
        "comp_ok": "Certo: justos com os ímpios.",
        "comp_wrong": {"b": "Juiz é o título de Deus.", "c": "Anjos não estão nesta frase."},
        "conn_a": "seja isto longe de ti: não fará justiça o Juiz de toda a terra?",
        "conn_opts": [
            {"id": "c", "text": "Juiz justo interpelado"},
            {"id": "a", "text": "Juiz indiferente"},
            {"id": "b", "text": "Fim da intercessão"},
        ],
        "conn_ans": "c",
        "conn_ok": "Certo: Abraão interpela o Juiz justo.",
        "conn_wrong": {"a": "Ele espera justiça, não indiferença.", "b": "O versículo é a intercessão."},
    },
})

# ===== 8. gen12-08-isaque-nasce =====
TB8 = "Jeová visitou a Sara, como dissera, e fez-lhe como tinha falado. Ela concebeu e deu à luz a Abraão, na sua velhice, um filho, ao tempo determinado, de que Deus lhe tinha falado."
MISSIONS.append({
    "section": "gen12-08-isaque-nasce",
    "verse_ref": "Gênesis 21:1–2",
    "tb": TB8,
    "insight": "Jeová visita Sara: Isaque nasce no tempo dito.",
    "lo": "Afirmar que Jeová cumpre a palavra: Sara concebe e dá à luz no tempo determinado.",
    "evidence": ["Gênesis 21:1", "Gênesis 21:2"],
    "semente": {
        "tf_q": "Jeová visitou a Sara, como dissera, e fez-lhe como tinha falado.",
        "tf_ans": "true",
        "tf_ok": "Certo: o texto abre com a visita fiel de Jeová.",
        "tf_wrong": {"false": "Gênesis 21:1 afirma exatamente isso."},
        "tap_template": "Jeová ___ a Sara, como dissera",
        "tap_opts": [{"id": "a", "text": "visitou"}, {"id": "b", "text": "concebeu"}, {"id": "c", "text": "falado"}],
        "tap_ans": "a",
        "tap_ok": "Exato: Jeová visitou a Sara.",
        "tap_wrong": {"b": "Quem concebeu foi Sara.", "c": "Falado refere-se à palavra cumprida."},
        "choice_q": "Quando Sara dá à luz o filho, segundo o texto?",
        "choice_opts": [
            {"id": "a", "text": "Na velhice, ao tempo determinado por Deus"},
            {"id": "b", "text": "Na juventude, antes de qualquer promessa"},
            {"id": "c", "text": "No Egito, sem palavra prévia de Deus"},
            {"id": "d", "text": "Imediatamente após a saída de Harã"},
        ],
        "choice_ans": "a",
        "choice_ok": "Certo: na velhice, no tempo determinado.",
        "choice_wrong": {
            "b": "O texto situa o nascimento na velhice.",
            "c": "Há cumprimento do que Deus falara.",
            "d": "Não é esse o tempo indicado aqui.",
        },
        "order_q": "Qual é a ordem dos fatos em Gênesis 21:1–2?",
        "order_opts": [
            {"id": "a", "text": "Jeová visita Sara conforme falara"},
            {"id": "b", "text": "Sara concebe"},
            {"id": "c", "text": "Dá à luz um filho na velhice, no tempo dito"},
        ],
        "order_correct": ["a", "b", "c"],
        "order_ok": "Certo: visita, concepção e nascimento no tempo.",
        "order_wrong": {"b": "O nascimento fecha a sequência.", "c": "Começa pela visita de Jeová."},
        "comp_template": "ao tempo ___, de que Deus lhe tinha falado",
        "comp_opts": [{"id": "a", "text": "determinado"}, {"id": "b", "text": "esquecido"}, {"id": "c", "text": "adiado"}],
        "comp_ans": "a",
        "comp_ok": "Certo: ao tempo determinado.",
        "comp_wrong": {"b": "O texto diz determinado.", "c": "Adiado não está no versículo."},
        "conn_a": "ao tempo determinado, de que Deus lhe tinha falado",
        "conn_opts": [
            {"id": "a", "text": "Nascimento no tempo dito"},
            {"id": "b", "text": "Promessa sem cumprimento"},
            {"id": "c", "text": "Visita sem filho"},
        ],
        "conn_ans": "a",
        "conn_ok": "Certo: Isaque nasce no tempo que Deus falara.",
        "conn_wrong": {"b": "Jeová fez como tinha falado.", "c": "Há concepção e nascimento."},
    },
    "caminhada": {
        "tf_q": "O nascimento do filho de Sara ocorre à parte da palavra prévia de Deus.",
        "tf_ans": "false",
        "tf_ok": "Certo: o texto insiste no cumprimento do que Deus falara.",
        "tf_wrong": {"true": "Há visita e tempo determinado conforme a palavra."},
        "tap_template": "Ela ___ e deu à luz a Abraão",
        "tap_opts": [{"id": "a", "text": "concebeu"}, {"id": "b", "text": "visitou"}, {"id": "c", "text": "falado"}],
        "tap_ans": "a",
        "tap_ok": "Exato: ela concebeu e deu à luz.",
        "tap_wrong": {"b": "Quem visitou foi Jeová.", "c": "Falado refere-se à palavra de Deus."},
        "choice_q": "Como o texto liga a visita de Jeová ao nascimento?",
        "choice_opts": [
            {"id": "a", "text": "A visita cumpre a palavra; depois vem a concepção e o parto"},
            {"id": "b", "text": "O parto ocorre e só depois Deus fala pela primeira vez"},
            {"id": "c", "text": "A visita substitui qualquer necessidade de filho"},
            {"id": "d", "text": "Sara concebe sem qualquer relação com a visita"},
        ],
        "choice_ans": "a",
        "choice_ok": "Certo: visita fiel, depois concepção e nascimento.",
        "choice_wrong": {
            "b": "A palavra já fora dita; agora se cumpre.",
            "c": "Há filho no tempo determinado.",
            "d": "A sequência une visita e concepção.",
        },
        "order_q": "Como se encadeiam os eventos de Gênesis 21:1–2?",
        "order_opts": [
            {"id": "a", "text": "Cumprimento da palavra pela visita"},
            {"id": "b", "text": "Concepção de Sara"},
            {"id": "c", "text": "Nascimento na velhice no tempo marcado"},
        ],
        "order_correct": ["a", "b", "c"],
        "order_ok": "Certo: cumprimento, concepção e nascimento.",
        "order_wrong": {"b": "O nascimento fecha o encadeamento.", "c": "Começa pelo cumprimento da palavra."},
        "comp_template": "na sua ___, um filho",
        "comp_opts": [{"id": "a", "text": "velhice"}, {"id": "b", "text": "juventude"}, {"id": "c", "text": "viagem"}],
        "comp_ans": "a",
        "comp_ok": "Certo: na sua velhice, um filho.",
        "comp_wrong": {"b": "O texto diz velhice.", "c": "Viagem não completa esta frase."},
        "conn_a": "Jeová visitou a Sara, como dissera, e fez-lhe como tinha falado",
        "conn_opts": [
            {"id": "b", "text": "Palavra cumprida em Sara"},
            {"id": "a", "text": "Palavra esquecida por Deus"},
            {"id": "c", "text": "Visita sem efeito algum"},
        ],
        "conn_ans": "b",
        "conn_ok": "Certo: Jeová cumpre em Sara o que falara.",
        "conn_wrong": {"a": "O texto diz como dissera.", "c": "Há concepção e filho."},
    },
    "profundezas": {
        "tf_q": "O nascimento na velhice, no tempo determinado, mostra a fidelidade de Deus à própria palavra.",
        "tf_ans": "true",
        "tf_ok": "Certo: tempo e velhice sublinham o cumprimento fiel.",
        "tf_wrong": {"false": "Como dissera / tempo determinado apontam fidelidade."},
        "tap_template": "fez-lhe como tinha ___",
        "tap_opts": [{"id": "a", "text": "falado"}, {"id": "b", "text": "visitou"}, {"id": "c", "text": "concebeu"}],
        "tap_ans": "a",
        "tap_ok": "Exato: fez-lhe como tinha falado.",
        "tap_wrong": {"b": "Visitou é a ação inicial de Jeová.", "c": "Concebeu é a ação de Sara."},
        "choice_q": "Que leitura teológica o nascimento de Isaque prepara?",
        "choice_opts": [
            {"id": "a", "text": "Deus cumpre a promessa mesmo quando o tempo humano parece tarde"},
            {"id": "b", "text": "Promessas divinas dependem só da força da juventude"},
            {"id": "c", "text": "A visita de Jeová é simbólica, sem filho real"},
            {"id": "d", "text": "O tempo determinado é escolhido por Sara, não por Deus"},
        ],
        "choice_ans": "a",
        "choice_ok": "Certo: a velhice e o tempo dito exaltam a fidelidade de Deus.",
        "choice_wrong": {
            "b": "O nascimento ocorre na velhice.",
            "c": "Há concepção e parto reais.",
            "d": "O tempo é o de que Deus falara.",
        },
        "order_q": "Qual sequência revela o sentido de Gênesis 21:1–2?",
        "order_opts": [
            {"id": "a", "text": "Deus age conforme a palavra dita"},
            {"id": "b", "text": "Sara concebe na velhice"},
            {"id": "c", "text": "O filho nasce no tempo determinado"},
        ],
        "order_correct": ["a", "b", "c"],
        "order_ok": "Certo: fidelidade, concepção e tempo cumprido.",
        "order_wrong": {"b": "O tempo determinado fecha o sentido.", "c": "Começa pela ação conforme a palavra."},
        "comp_template": "deu à luz a ___",
        "comp_opts": [{"id": "a", "text": "Abraão"}, {"id": "b", "text": "Ismael"}, {"id": "c", "text": "Ló"}],
        "comp_ans": "a",
        "comp_ok": "Certo: deu à luz a Abraão um filho.",
        "comp_wrong": {"b": "Ismael não é o filho deste versículo.", "c": "Ló não aparece aqui."},
        "conn_a": "ao tempo determinado, de que Deus lhe tinha falado",
        "conn_opts": [
            {"id": "c", "text": "Fidelidade no tempo certo"},
            {"id": "a", "text": "Atraso sem sentido"},
            {"id": "b", "text": "Promessa abandonada"},
        ],
        "conn_ans": "c",
        "conn_ok": "Certo: o tempo dito revela fidelidade.",
        "conn_wrong": {"a": "É tempo determinado, não sem sentido.", "b": "Jeová fez como falara."},
    },
})

# ===== 9. gen12-09-moria =====
TB9 = "Continuou o anjo: Não estendas a mão sobre o mancebo e não lhe faças nada; pois, agora, sei que tu temes a Deus, visto que não me negaste teu filho, teu único filho."
MISSIONS.append({
    "section": "gen12-09-moria",
    "verse_ref": "Gênesis 22:12",
    "tb": TB9,
    "insight": "Moriá: agora sei que temes a Deus — não retenhas o filho.",
    "lo": "Compreender que em Moriá Abraão prova temer a Deus ao não reter o filho único.",
    "evidence": ["Gênesis 22:12"],
    "semente": {
        "tf_q": "O anjo manda Abraão não estender a mão sobre o mancebo nem lhe fazer nada.",
        "tf_ans": "true",
        "tf_ok": "Certo: a ordem detém a mão de Abraão.",
        "tf_wrong": {"false": "O texto ordena não estender a mão nem fazer nada."},
        "tap_template": "Não estendas a mão sobre o ___",
        "tap_opts": [{"id": "a", "text": "mancebo"}, {"id": "b", "text": "anjo"}, {"id": "c", "text": "filho"}],
        "tap_ans": "a",
        "tap_ok": "Exato: não estendas a mão sobre o mancebo.",
        "tap_wrong": {"b": "Quem fala é o anjo.", "c": "Filho aparece depois; aqui a palavra é mancebo."},
        "choice_q": "O que o anjo declara ter reconhecido em Abraão?",
        "choice_opts": [
            {"id": "a", "text": "Que ele teme a Deus, pois não negou o filho único"},
            {"id": "b", "text": "Que ele teme perder terras e gado"},
            {"id": "c", "text": "Que ele recusou oferecer o filho"},
            {"id": "d", "text": "Que ele não conhece a Deus"},
        ],
        "choice_ans": "a",
        "choice_ok": "Certo: o temor a Deus aparece em não negar o filho.",
        "choice_wrong": {
            "b": "O critério é o filho, não bens.",
            "c": "O texto diz que não negou o filho.",
            "d": "O anjo afirma que ele teme a Deus.",
        },
        "order_q": "Qual é a ordem dos fatos em Gênesis 22:12?",
        "order_opts": [
            {"id": "a", "text": "Ordem de não tocar no mancebo"},
            {"id": "b", "text": "Declaração: agora sei que temes a Deus"},
            {"id": "c", "text": "Motivo: não negaste teu filho único"},
        ],
        "order_correct": ["a", "b", "c"],
        "order_ok": "Certo: detenção, reconhecimento e motivo.",
        "order_wrong": {"b": "O motivo fecha o versículo.", "c": "Começa pela ordem de parar."},
        "comp_template": "não me negaste teu filho, teu ___ filho",
        "comp_opts": [{"id": "a", "text": "único"}, {"id": "b", "text": "mais velho"}, {"id": "c", "text": "adotivo"}],
        "comp_ans": "a",
        "comp_ok": "Certo: teu único filho.",
        "comp_wrong": {"b": "O texto diz único.", "c": "Adotivo não está no versículo."},
        "conn_a": "agora, sei que tu temes a Deus, visto que não me negaste teu filho",
        "conn_opts": [
            {"id": "a", "text": "Temor que não retém"},
            {"id": "b", "text": "Temor que recusa Deus"},
            {"id": "c", "text": "Oferta sem qualquer custo"},
        ],
        "conn_ans": "a",
        "conn_ok": "Certo: temer a Deus aparece em não reter o filho.",
        "conn_wrong": {"b": "O temor une Abraão a Deus.", "c": "O filho único é o custo."},
    },
    "caminhada": {
        "tf_q": "O reconhecimento do temor a Deus ocorre depois que Abraão nega entregar o filho.",
        "tf_ans": "false",
        "tf_ok": "Certo: o temor é visto porque ele não negou o filho.",
        "tf_wrong": {"true": "O texto diz: não me negaste teu filho."},
        "tap_template": "sei que tu ___ a Deus",
        "tap_opts": [{"id": "a", "text": "temes"}, {"id": "b", "text": "negaste"}, {"id": "c", "text": "faças"}],
        "tap_ans": "a",
        "tap_ok": "Exato: sei que tu temes a Deus.",
        "tap_wrong": {"b": "Negaste refere-se ao filho.", "c": "Faças está na ordem de não fazer nada."},
        "choice_q": "Como se relacionam a ordem de parar e o reconhecimento do temor?",
        "choice_opts": [
            {"id": "a", "text": "A detenção revela que a prova do temor já foi dada"},
            {"id": "b", "text": "A detenção prova que Abraão falhou na fé"},
            {"id": "c", "text": "O temor só existiria se o filho tivesse morrido"},
            {"id": "d", "text": "O anjo ignora a disposição de Abraão"},
        ],
        "choice_ans": "a",
        "choice_ok": "Certo: parar mostra que o temor já ficou evidente.",
        "choice_wrong": {
            "b": "O anjo afirma o temor, não a falha.",
            "c": "Não negar o filho bastou.",
            "d": "O anjo reconhece explicitamente o temor.",
        },
        "order_q": "Como se encadeiam os eventos de Gênesis 22:12?",
        "order_opts": [
            {"id": "a", "text": "Interrupção do gesto sobre o mancebo"},
            {"id": "b", "text": "Reconhecimento do temor a Deus"},
            {"id": "c", "text": "Evidência: o filho único não foi retido"},
        ],
        "order_correct": ["a", "b", "c"],
        "order_ok": "Certo: parar, reconhecer e fundamentar.",
        "order_wrong": {"b": "A evidência do filho fecha o encadeamento.", "c": "Começa pela interrupção."},
        "comp_template": "não lhe faças ___",
        "comp_opts": [{"id": "a", "text": "nada"}, {"id": "b", "text": "festa"}, {"id": "c", "text": "altar"}],
        "comp_ans": "a",
        "comp_ok": "Certo: não lhe faças nada.",
        "comp_wrong": {"b": "Festa não está no versículo.", "c": "Altar não completa esta lacuna."},
        "conn_a": "Não estendas a mão sobre o mancebo… pois, agora, sei que tu temes a Deus",
        "conn_opts": [
            {"id": "b", "text": "Prova concluída no temor"},
            {"id": "a", "text": "Prova ainda incompleta"},
            {"id": "c", "text": "Negação do filho único"},
        ],
        "conn_ans": "b",
        "conn_ok": "Certo: a prova do temor está concluída.",
        "conn_wrong": {"a": "Agora sei indica reconhecimento.", "c": "Ele não negou o filho."},
    },
    "profundezas": {
        "tf_q": "Em Moriá, temer a Deus significa não reter o que há de mais precioso quando Deus pede.",
        "tf_ans": "true",
        "tf_ok": "Certo: o filho único não retido revela o temor.",
        "tf_wrong": {"false": "Não me negaste teu filho define o temor."},
        "tap_template": "visto que não me ___ teu filho",
        "tap_opts": [{"id": "a", "text": "negaste"}, {"id": "b", "text": "temes"}, {"id": "c", "text": "estendas"}],
        "tap_ans": "a",
        "tap_ok": "Exato: não me negaste teu filho.",
        "tap_wrong": {"b": "Temes é o reconhecimento do anjo.", "c": "Estendas está na ordem de parar a mão."},
        "choice_q": "Que implicação teológica Moriá deixa no leitor?",
        "choice_opts": [
            {"id": "a", "text": "O temor a Deus se prova na disposição de não reter o filho"},
            {"id": "b", "text": "Deus deseja a morte do filho como fim em si"},
            {"id": "c", "text": "A fé dispensa qualquer prova de temor"},
            {"id": "d", "text": "O anjo contradiz o temor que Abraão demonstra"},
        ],
        "choice_ans": "a",
        "choice_ok": "Certo: não reter o filho único é o critério do temor.",
        "choice_wrong": {
            "b": "O anjo impede o gesto final.",
            "c": "Há reconhecimento explícito do temor.",
            "d": "O anjo afirma o temor.",
        },
        "order_q": "Qual sequência revela o sentido de Gênesis 22:12?",
        "order_opts": [
            {"id": "a", "text": "Deus detém a mão de Abraão"},
            {"id": "b", "text": "Declara o temor reconhecido"},
            {"id": "c", "text": "Aponta o filho único não retido"},
        ],
        "order_correct": ["a", "b", "c"],
        "order_ok": "Certo: detenção, temor e evidência do filho.",
        "order_wrong": {"b": "A evidência fecha o sentido.", "c": "Começa pela detenção."},
        "comp_template": "agora, sei que tu temes a ___",
        "comp_opts": [{"id": "a", "text": "Deus"}, {"id": "b", "text": "mancebo"}, {"id": "c", "text": "anjo"}],
        "comp_ans": "a",
        "comp_ok": "Certo: temes a Deus.",
        "comp_wrong": {"b": "Mancebo é o filho.", "c": "Anjo é quem fala."},
        "conn_a": "não me negaste teu filho, teu único filho",
        "conn_opts": [
            {"id": "c", "text": "Filho não retido"},
            {"id": "a", "text": "Filho negado a Deus"},
            {"id": "b", "text": "Temor sem qualquer prova"},
        ],
        "conn_ans": "c",
        "conn_ok": "Certo: o insight é não reter o filho.",
        "conn_wrong": {"a": "Ele não negou o filho.", "b": "Há prova explícita no texto."},
    },
})

# ===== 10. gen12-boss-abraao =====
TB10 = "Chamou Abraão àquele lugar Jeová-Jiré; donde, até o dia de hoje, se diz: No monte de Jeová se provê."
MISSIONS.append({
    "section": "gen12-boss-abraao",
    "verse_ref": "Gênesis 22:14",
    "tb": TB10,
    "insight": "Jeová proverá — o nome do monte resume a fé de Abraão.",
    "lo": "Reconhecer que Abraão nomeia o lugar Jeová-Jiré: no monte de Jeová se provê.",
    "evidence": ["Gênesis 22:14"],
    "semente": {
        "tf_q": "Abraão chamou àquele lugar Jeová-Jiré.",
        "tf_ans": "true",
        "tf_ok": "Certo: o nome do lugar é Jeová-Jiré.",
        "tf_wrong": {"false": "O texto registra esse nome dado por Abraão."},
        "tap_template": "Chamou Abraão àquele lugar ___",
        "tap_opts": [{"id": "a", "text": "Jeová-Jiré"}, {"id": "b", "text": "monte"}, {"id": "c", "text": "hoje"}],
        "tap_ans": "a",
        "tap_ok": "Exato: o lugar chama-se Jeová-Jiré.",
        "tap_wrong": {"b": "Monte entra no ditado, não no nome dado.", "c": "Hoje marca a memória do ditado."},
        "choice_q": "O que se diz, até o dia de hoje, sobre o monte?",
        "choice_opts": [
            {"id": "a", "text": "No monte de Jeová se provê"},
            {"id": "b", "text": "No monte de Jeová se esquece"},
            {"id": "c", "text": "No monte ninguém encontra provisão"},
            {"id": "d", "text": "O monte permanece sem nome"},
        ],
        "choice_ans": "a",
        "choice_ok": "Certo: No monte de Jeová se provê.",
        "choice_wrong": {
            "b": "O ditado é se provê, não se esquece.",
            "c": "O texto afirma a provisão.",
            "d": "Abraão nomeia o lugar.",
        },
        "order_q": "Qual é a ordem dos fatos em Gênesis 22:14?",
        "order_opts": [
            {"id": "a", "text": "Abraão nomeia o lugar Jeová-Jiré"},
            {"id": "b", "text": "O nome gera um ditado até hoje"},
            {"id": "c", "text": "O ditado: No monte de Jeová se provê"},
        ],
        "order_correct": ["a", "b", "c"],
        "order_ok": "Certo: nome, memória e ditado da provisão.",
        "order_wrong": {"b": "O ditado fecha o versículo.", "c": "Começa pelo nome Jeová-Jiré."},
        "comp_template": "No monte de Jeová se ___",
        "comp_opts": [{"id": "a", "text": "provê"}, {"id": "b", "text": "esconde"}, {"id": "c", "text": "fecha"}],
        "comp_ans": "a",
        "comp_ok": "Certo: no monte de Jeová se provê.",
        "comp_wrong": {"b": "O texto diz se provê.", "c": "Fecha não completa a frase."},
        "conn_a": "Jeová-Jiré… No monte de Jeová se provê",
        "conn_opts": [
            {"id": "a", "text": "Jeová proverá"},
            {"id": "b", "text": "Jeová abandona"},
            {"id": "c", "text": "Monte sem memória"},
        ],
        "conn_ans": "a",
        "conn_ok": "Certo: o nome resume que Jeová proverá.",
        "conn_wrong": {"b": "O ditado é se provê.", "c": "Há memória até o dia de hoje."},
    },
    "caminhada": {
        "tf_q": "O nome Jeová-Jiré fica restrito a Abraão, sem gerar memória para depois.",
        "tf_ans": "false",
        "tf_ok": "Certo: até o dia de hoje se diz o ditado do monte.",
        "tf_wrong": {"true": "O texto fala da memória contínua do nome."},
        "tap_template": "até o dia de ___, se diz",
        "tap_opts": [{"id": "a", "text": "hoje"}, {"id": "b", "text": "monte"}, {"id": "c", "text": "lugar"}],
        "tap_ans": "a",
        "tap_ok": "Exato: até o dia de hoje.",
        "tap_wrong": {"b": "Monte entra no ditado final.", "c": "Lugar é o que Abraão nomeia."},
        "choice_q": "O que a nomeação do monte comunica sobre a experiência de Abraão?",
        "choice_opts": [
            {"id": "a", "text": "A fé de Abraão vira memória: Deus proveu e proverá"},
            {"id": "b", "text": "O monte serve só de marco geográfico sem fé"},
            {"id": "c", "text": "Abraão esconde o que Deus fez no lugar"},
            {"id": "d", "text": "O ditado nega qualquer provisão divina"},
        ],
        "choice_ans": "a",
        "choice_ok": "Certo: o nome e o ditado eternizam a provisão.",
        "choice_wrong": {
            "b": "O nome carrega o significado da provisão.",
            "c": "Ele nomeia e o ditado permanece.",
            "d": "Se provê afirma a provisão.",
        },
        "order_q": "Como se encadeiam os eventos de Gênesis 22:14?",
        "order_opts": [
            {"id": "a", "text": "Abraão dá o nome Jeová-Jiré"},
            {"id": "b", "text": "O nome permanece na memória do povo"},
            {"id": "c", "text": "O ditado resume a provisão no monte"},
        ],
        "order_correct": ["a", "b", "c"],
        "order_ok": "Certo: nomear, lembrar e resumir a provisão.",
        "order_wrong": {"b": "O ditado fecha o encadeamento.", "c": "Começa pelo nome."},
        "comp_template": "Chamou ___ àquele lugar Jeová-Jiré",
        "comp_opts": [{"id": "a", "text": "Abraão"}, {"id": "b", "text": "Isaque"}, {"id": "c", "text": "Ismael"}],
        "comp_ans": "a",
        "comp_ok": "Certo: Abraão nomeia o lugar.",
        "comp_wrong": {"b": "Isaque não nomeia aqui.", "c": "Ismael não aparece neste versículo."},
        "conn_a": "donde, até o dia de hoje, se diz: No monte de Jeová se provê",
        "conn_opts": [
            {"id": "b", "text": "Memória da provisão"},
            {"id": "a", "text": "Esquecimento do monte"},
            {"id": "c", "text": "Nome sem ditado"},
        ],
        "conn_ans": "b",
        "conn_ok": "Certo: o ditado guarda a memória da provisão.",
        "conn_wrong": {"a": "Há memória até hoje.", "c": "O texto traz o ditado."},
    },
    "profundezas": {
        "tf_q": "Jeová-Jiré resume a fé de Abraão: o Deus que proveu no monte continua a prover.",
        "tf_ans": "true",
        "tf_ok": "Certo: o nome e o ditado condensam essa fé.",
        "tf_wrong": {"false": "O monte de Jeová se provê expressa a fé contínua."},
        "tap_template": "No monte de ___ se provê",
        "tap_opts": [{"id": "a", "text": "Jeová"}, {"id": "b", "text": "Abraão"}, {"id": "c", "text": "lugar"}],
        "tap_ans": "a",
        "tap_ok": "Exato: no monte de Jeová se provê.",
        "tap_wrong": {"b": "Abraão nomeia; o monte é de Jeová.", "c": "Lugar é o que recebe o nome."},
        "choice_q": "Que implicação teológica o nome Jeová-Jiré deixa?",
        "choice_opts": [
            {"id": "a", "text": "A fé confessa Deus como provedor, não só um evento passado"},
            {"id": "b", "text": "A provisão divina ficou presa ao passado de Abraão"},
            {"id": "c", "text": "O nome do monte exclui qualquer memória de fé"},
            {"id": "d", "text": "Prover é obra humana atribuída a Jeová por engano"},
        ],
        "choice_ans": "a",
        "choice_ok": "Certo: até hoje se diz — a provisão permanece confessada.",
        "choice_wrong": {
            "b": "O ditado prolonga a memória.",
            "c": "Há memória explícita.",
            "d": "O texto atribui a provisão a Jeová.",
        },
        "order_q": "Qual sequência revela o sentido de Gênesis 22:14?",
        "order_opts": [
            {"id": "a", "text": "Abraão confessa a provisão no nome do lugar"},
            {"id": "b", "text": "A confissão torna-se tradição viva"},
            {"id": "c", "text": "O ditado resume: no monte Jeová se provê"},
        ],
        "order_correct": ["a", "b", "c"],
        "order_ok": "Certo: confessar, lembrar e resumir a fé.",
        "order_wrong": {"b": "O ditado fecha o sentido.", "c": "Começa pela nomeação."},
        "comp_template": "àquele lugar Jeová-___",
        "comp_opts": [{"id": "a", "text": "Jiré"}, {"id": "b", "text": "Nissi"}, {"id": "c", "text": "Shalom"}],
        "comp_ans": "a",
        "comp_ok": "Certo: Jeová-Jiré.",
        "comp_wrong": {"b": "Nissi não está neste versículo.", "c": "Shalom não completa o nome aqui."},
        "conn_a": "Jeová-Jiré… No monte de Jeová se provê",
        "conn_opts": [
            {"id": "c", "text": "Fé resumida no nome"},
            {"id": "a", "text": "Fé sem provisão"},
            {"id": "b", "text": "Nome vazio de sentido"},
        ],
        "conn_ans": "c",
        "conn_ok": "Certo: o nome do monte resume a fé de Abraão.",
        "conn_wrong": {"a": "Se provê afirma a provisão.", "b": "O ditado explica o nome."},
    },
})


def main():
    all_q = []
    for m in MISSIONS:
        all_q.extend(mission(m))
    assert len(MISSIONS) == 10, len(MISSIONS)
    assert len(all_q) == 180, len(all_q)
    OUT.write_text(json.dumps(all_q, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
    print(f"Wrote {OUT} with {len(all_q)} questions")


if __name__ == "__main__":
    main()
