#!/usr/bin/env python3
"""Gera perguntas-v2/juizes.json (6 missões × 18)."""
import json
from pathlib import Path

OUT = Path(__file__).with_name("juizes.json")


def q(
    trail,
    section,
    diff,
    skill,
    typ,
    nn,
    verse_ref,
    lo,
    evidence,
    question,
    feedback_correct,
    feedback_wrong,
    options,
    correct,
    passage,
    **extra,
):
    short = {"semente": "sem", "caminhada": "cam", "profundezas": "pro"}[diff]
    item = {
        "difficulty": diff,
        "skill": skill,
        "verseRef": verse_ref,
        "learningObjective": lo,
        "evidence": evidence,
        "type": typ,
        "question": question,
        "prompt": question,
        "cue": question,
        "feedbackCorrect": feedback_correct,
        "feedbackWrong": feedback_wrong,
        "options": options,
        "correctOptionId": correct,
        "correctAnswer": correct,
        "passageText": passage,
        "trail": trail,
        "section": section,
        "id": f"{trail}-{short}-{section}-{nn}",
    }
    item.update(extra)
    assert len(feedback_correct) <= 100, (len(feedback_correct), feedback_correct)
    for o in options:
        assert len(o["text"]) <= 90 or typ in ("order", "true_false", "connect"), (
            typ,
            len(o["text"]),
            o["text"],
        )
    if typ == "choice":
        for o in options:
            assert len(o["text"]) <= 90, (len(o["text"]), o["text"])
    return item


def tf_opts():
    return [{"id": "true", "text": "Verdadeiro"}, {"id": "false", "text": "Falso"}]


def opts(*pairs):
    return [{"id": i, "text": t} for i, t in pairs]


def mission(section, verse, passage, lo, evidence, items):
    out = []
    for spec in items:
        extra = {}
        for k in ("template", "correctOrder", "passageA", "passageB"):
            if k in spec:
                extra[k] = spec[k]
        out.append(
            q(
                "juizes",
                section,
                spec["diff"],
                spec["skill"],
                spec["type"],
                spec["nn"],
                verse,
                lo,
                evidence,
                spec["question"],
                spec["ok"],
                spec["wrong"],
                spec["options"],
                spec["correct"],
                passage,
                **extra,
            )
        )
    return out


bank = []

# ---------------------------------------------------------------------------
# M1 Juízes 21:25 — cada um fazia o que bem lhe parecia
# ---------------------------------------------------------------------------
P1 = "Naqueles dias, não havia rei em Israel: cada um fazia o que bem lhe parecia."
LO1 = "Reconhecer que, sem rei, cada um era a própria lei — o refrão do caos moral em Juízes."
INS1 = "Sem rei, cada um era lei: o caos moral é o refrão do livro."

bank += mission(
    "juizes-ciclo-01-cada-um-fazia-o-que-",
    "Juízes 21:25",
    P1,
    LO1,
    ["Juízes 21:25"],
    [
        # --- SEMENTE ---
        dict(
            diff="semente",
            skill="observe",
            type="true_false",
            nn="01",
            question="Naqueles dias, não havia rei em Israel.",
            ok="Certo: o versículo afirma a ausência de rei.",
            wrong={"false": "Juízes 21:25 abre dizendo que não havia rei."},
            options=tf_opts(),
            correct="true",
        ),
        dict(
            diff="semente",
            skill="observe",
            type="tap",
            nn="02",
            question='Em Juízes 21:25, toque a palavra que falta em "não havia ___ em Israel"?',
            ok='Exato: não havia "rei" em Israel.',
            wrong={
                "b": "Dias situa o tempo; a lacuna pede rei.",
                "c": "Israel é o povo; aqui falta a palavra rei.",
            },
            options=opts(("a", "rei"), ("b", "dias"), ("c", "Israel")),
            correct="a",
            template="não havia ___ em Israel",
        ),
        dict(
            diff="semente",
            skill="observe",
            type="choice",
            nn="03",
            question="O que Juízes 21:25 afirma de modo explícito?",
            ok="Certo: cada um fazia o que bem lhe parecia.",
            wrong={
                "a": "O texto não menciona um rei justo reinando.",
                "b": "Não há lei escrita citada aqui.",
                "c": "O versículo não fala de templo reconstruído.",
            },
            options=opts(
                ("a", "Havia um rei justo que guiava todo o povo."),
                ("b", "Cada tribo seguia a lei escrita de Moisés."),
                ("c", "O templo em Jerusalém estava restaurado."),
                ("d", "Cada um fazia o que bem lhe parecia."),
            ),
            correct="d",
        ),
        dict(
            diff="semente",
            skill="observe",
            type="order",
            nn="04",
            question="Qual sequência mostra a ordem dos fatos em Juízes 21:25?",
            ok="Certo: dias sem rei, depois cada um fazendo o que lhe parecia.",
            wrong={
                "b": "A ausência de rei vem antes da conduta individual.",
                "c": "Releia a ordem do versículo.",
            },
            options=opts(
                ("a", "Naqueles dias"),
                ("b", "não havia rei em Israel"),
                ("c", "cada um fazia o que bem lhe parecia"),
            ),
            correct="a",
            correctOrder=["a", "b", "c"],
        ),
        dict(
            diff="semente",
            skill="observe",
            type="complete",
            nn="05",
            question='Complete: "cada um fazia o que bem lhe ___."',
            ok='Certo: cada um fazia o que bem lhe "parecia".',
            wrong={
                "a": "Rei é o que faltava; aqui a palavra é parecia.",
                "c": "Dias situa o tempo, não completa esta frase.",
            },
            options=opts(("a", "rei"), ("b", "parecia"), ("c", "dias")),
            correct="b",
            template="cada um fazia o que bem lhe ___.",
        ),
        dict(
            diff="semente",
            skill="observe",
            type="connect",
            nn="06",
            question="O que Juízes 21:25 comunica que se liga a este contexto?",
            ok="Certo: sem rei, cada um vira lei — caos moral como refrão.",
            wrong={
                "a": "O texto não celebra ordem sob um rei presente.",
                "c": "Não há aqui reforma cultual coletiva.",
            },
            options=opts(
                ("a", "Ordem sob um rei justo"),
                ("b", "Caos moral sem rei"),
                ("c", "Reforma cultual coletiva"),
            ),
            correct="b",
            passageA={"ref": "Juízes 21:25", "text": P1},
            passageB={"ref": "Contexto", "text": INS1},
        ),
        # --- CAMINHADA ---
        dict(
            diff="caminhada",
            skill="understand",
            type="true_false",
            nn="01",
            question="A ausência de rei em Israel resulta em cada um seguir o próprio critério.",
            ok="Certo: sem rei, cada um fazia o que bem lhe parecia.",
            wrong={"false": "O versículo liga a falta de rei à conduta individual."},
            options=tf_opts(),
            correct="true",
        ),
        dict(
            diff="caminhada",
            skill="understand",
            type="tap",
            nn="02",
            question='Em Juízes 21:25, toque a palavra que falta em "cada um ___ o que bem lhe parecia"?',
            ok='Exato: cada um "fazia" o que bem lhe parecia.',
            wrong={
                "a": "Rei é o que faltava; aqui o verbo é fazia.",
                "c": "Parecia fecha a frase; a lacuna pede fazia.",
            },
            options=opts(("a", "rei"), ("b", "fazia"), ("c", "parecia")),
            correct="b",
            template="cada um ___ o que bem lhe parecia",
        ),
        dict(
            diff="caminhada",
            skill="understand",
            type="choice",
            nn="03",
            question="Como Juízes 21:25 liga a falta de rei à conduta do povo?",
            ok="Certo: sem autoridade comum, cada um vira medida de si mesmo.",
            wrong={
                "a": "O texto não descreve obediência unânime.",
                "b": "Não há conselho de anciãos governando aqui.",
                "d": "O versículo não fala de aliança renovada.",
            },
            options=opts(
                ("a", "Sem rei, o povo obedece unânime à lei."),
                ("b", "Um conselho de anciãos governa no lugar do rei."),
                ("c", "Sem rei, cada um toma a si mesmo por medida."),
                ("d", "A falta de rei gera aliança renovada imediata."),
            ),
            correct="c",
        ),
        dict(
            diff="caminhada",
            skill="understand",
            type="order",
            nn="04",
            question="Como se encadeiam os eventos de Juízes 21:25?",
            ok="Certo: o tempo, a ausência de rei e então a conduta individual.",
            wrong={
                "a": "A conduta individual não abre o versículo.",
                "c": "Releia o encadeamento do texto.",
            },
            options=opts(
                ("a", "cada um fazia o que bem lhe parecia"),
                ("b", "Naqueles dias"),
                ("c", "não havia rei em Israel"),
            ),
            correct="b",
            correctOrder=["b", "c", "a"],
        ),
        dict(
            diff="caminhada",
            skill="understand",
            type="complete",
            nn="05",
            question='Complete: "Naqueles dias, não havia ___ em Israel."',
            ok='Certo: não havia "rei" em Israel.',
            wrong={
                "b": "Parecia fecha a conduta; aqui falta rei.",
                "c": "Fazia é o verbo da conduta, não o sujeito ausente.",
            },
            options=opts(("a", "rei"), ("b", "parecia"), ("c", "fazia")),
            correct="a",
            template="Naqueles dias, não havia ___ em Israel.",
        ),
        dict(
            diff="caminhada",
            skill="understand",
            type="connect",
            nn="06",
            question="O que Juízes 21:25 comunica que se liga a este contexto?",
            ok="Certo: autonomia moral sem rei produz o refrão do caos.",
            wrong={
                "a": "O texto não aponta unidade sob a Torah.",
                "b": "Não há aqui monarquia davídica estabelecida.",
            },
            options=opts(
                ("a", "Unidade sob a Torah escrita"),
                ("b", "Monarquia davídica estabelecida"),
                ("c", "Autonomia moral sem rei"),
            ),
            correct="c",
            passageA={"ref": "Juízes 21:25", "text": P1},
            passageB={"ref": "Contexto", "text": INS1},
        ),
        # --- PROFUNDezas ---
        dict(
            diff="profundezas",
            skill="interpret",
            type="true_false",
            nn="01",
            question="Juízes 21:25 apresenta o critério individual como sinal de fidelidade à aliança.",
            ok="Certo: o verso marca caos moral, não fidelidade.",
            wrong={"true": "Fazer o que bem lhe parecia é diagnóstico de desordem, não de fidelidade."},
            options=tf_opts(),
            correct="false",
        ),
        dict(
            diff="profundezas",
            skill="interpret",
            type="tap",
            nn="02",
            question='Em Juízes 21:25, toque a palavra que falta em "o que bem lhe ___"?',
            ok='Exato: o que bem lhe "parecia" — o critério é subjetivo.',
            wrong={
                "a": "Rei é o que faltava; aqui a palavra é parecia.",
                "b": "Fazia é o verbo anterior; a lacuna pede parecia.",
            },
            options=opts(("a", "rei"), ("b", "fazia"), ("c", "parecia")),
            correct="c",
            template="o que bem lhe ___",
        ),
        dict(
            diff="profundezas",
            skill="interpret",
            type="choice",
            nn="03",
            question="Qual leitura teológica Juízes 21:25 sustenta sobre Israel sem rei?",
            ok="Certo: sem autoridade comum, o povo vira lei de si mesmo.",
            wrong={
                "a": "O texto não celebra liberdade como bênção.",
                "c": "Não há aqui maturidade espiritual elogiada.",
                "d": "O versículo não descreve culto puro restaurado.",
            },
            options=opts(
                ("a", "A liberdade individual é a bênção máxima da aliança."),
                ("b", "Sem rei, cada um vira lei — e isso revela caos moral."),
                ("c", "Israel prova maturidade espiritual sem liderança."),
                ("d", "A falta de rei garante culto puro e unido."),
            ),
            correct="b",
        ),
        dict(
            diff="profundezas",
            skill="interpret",
            type="order",
            nn="04",
            question="Qual sequência revela o sentido de Juízes 21:25?",
            ok="Certo: tempo sem rei, ausência de rei, critério individual.",
            wrong={
                "b": "Essa peça não fecha o sentido do versículo.",
                "c": "Releia a progressão do texto.",
            },
            options=opts(
                ("a", "Naqueles dias"),
                ("b", "não havia rei em Israel"),
                ("c", "cada um fazia o que bem lhe parecia"),
            ),
            correct="a",
            correctOrder=["a", "b", "c"],
        ),
        dict(
            diff="profundezas",
            skill="interpret",
            type="complete",
            nn="05",
            question='Complete: "___ um fazia o que bem lhe parecia."',
            ok='Certo: "cada" um fazia o que bem lhe parecia.',
            wrong={
                "b": "Rei é o ausente; aqui a palavra é cada.",
                "c": "Israel é o cenário; a lacuna pede cada.",
            },
            options=opts(("a", "cada"), ("b", "rei"), ("c", "Israel")),
            correct="a",
            template="___ um fazia o que bem lhe parecia.",
        ),
        dict(
            diff="profundezas",
            skill="interpret",
            type="connect",
            nn="06",
            question="O que Juízes 21:25 comunica que se liga a este contexto?",
            ok="Certo: o refrão do livro é o caos quando cada um é lei.",
            wrong={
                "a": "O texto não aponta rei messiânico já entronizado.",
                "b": "Não há aqui obediência coletiva à Torah.",
            },
            options=opts(
                ("a", "Rei messiânico já entronizado"),
                ("b", "Obediência coletiva à Torah"),
                ("c", "Refrão do caos moral"),
            ),
            correct="c",
            passageA={"ref": "Juízes 21:25", "text": P1},
            passageB={"ref": "Contexto", "text": INS1},
        ),
    ],
)

# ---------------------------------------------------------------------------
# M2 Juízes 2:16 — Jeová suscita juízes
# ---------------------------------------------------------------------------
P2 = "Jeová suscitou juízes, que os livraram da mão dos que os despojavam."
LO2 = "Ver que Jeová suscita juízes que livram — graça no meio da apostasia."
INS2 = "Jeová suscita juízes que livram — graça no meio da apostasia."

bank += mission(
    "juizes-ciclo-02-deus-levanta-juizes",
    "Juízes 2:16",
    P2,
    LO2,
    ["Juízes 2:16"],
    [
        dict(
            diff="semente",
            skill="observe",
            type="true_false",
            nn="01",
            question="Jeová suscitou juízes que livraram Israel da mão dos despojadores.",
            ok="Certo: o versículo afirma exatamente isso.",
            wrong={"false": "Juízes 2:16 diz que Jeová suscitou juízes que livraram."},
            options=tf_opts(),
            correct="true",
        ),
        dict(
            diff="semente",
            skill="observe",
            type="tap",
            nn="02",
            question='Em Juízes 2:16, toque a palavra que falta em "Jeová ___ juízes"?',
            ok='Exato: Jeová "suscitou" juízes.',
            wrong={
                "b": "Juízes é o objeto; a lacuna pede o verbo suscitou.",
                "c": "Livraram vem depois; aqui falta suscitou.",
            },
            options=opts(("a", "suscitou"), ("b", "juízes"), ("c", "livraram")),
            correct="a",
            template="Jeová ___ juízes",
        ),
        dict(
            diff="semente",
            skill="observe",
            type="choice",
            nn="03",
            question="O que Juízes 2:16 afirma diretamente sobre os juízes?",
            ok="Certo: eles livraram Israel da mão dos que os despojavam.",
            wrong={
                "b": "O texto não diz que o povo escolheu os juízes.",
                "c": "Não há coroação de rei neste versículo.",
                "d": "O texto não atribui o livramento a alianças estrangeiras.",
            },
            options=opts(
                ("a", "Os juízes livraram Israel dos que os despojavam."),
                ("b", "O povo elegeu juízes por voto das tribos."),
                ("c", "Jeová coroou um rei permanente em Israel."),
                ("d", "Os juízes firmaram pacto com os despojadores."),
            ),
            correct="a",
        ),
        dict(
            diff="semente",
            skill="observe",
            type="order",
            nn="04",
            question="Qual sequência mostra a ordem dos fatos em Juízes 2:16?",
            ok="Certo: Jeová suscita, depois os juízes livram dos despojadores.",
            wrong={
                "b": "O livramento vem depois da suscitação.",
                "c": "Releia a ordem do versículo.",
            },
            options=opts(
                ("a", "Jeová suscitou juízes"),
                ("b", "que os livraram"),
                ("c", "da mão dos que os despojavam"),
            ),
            correct="a",
            correctOrder=["a", "b", "c"],
        ),
        dict(
            diff="semente",
            skill="observe",
            type="complete",
            nn="05",
            question='Complete: "que os ___ da mão dos que os despojavam."',
            ok='Certo: os juízes "livraram" Israel.',
            wrong={
                "a": "Suscitou é a ação de Jeová; aqui o verbo é livraram.",
                "c": "Juízes é o objeto suscitado, não este verbo.",
            },
            options=opts(("a", "suscitou"), ("b", "livraram"), ("c", "juízes")),
            correct="b",
            template="que os ___ da mão dos que os despojavam.",
        ),
        dict(
            diff="semente",
            skill="observe",
            type="connect",
            nn="06",
            question="O que Juízes 2:16 comunica que se liga a este contexto?",
            ok="Certo: Jeová suscita livradores — graça no meio da crise.",
            wrong={
                "a": "O texto não fala de mérito do povo.",
                "c": "Não há abandono definitivo de Israel aqui.",
            },
            options=opts(
                ("a", "Mérito do povo que se salva"),
                ("b", "Graça que suscita juízes"),
                ("c", "Abandono definitivo de Israel"),
            ),
            correct="b",
            passageA={"ref": "Juízes 2:16", "text": P2},
            passageB={"ref": "Contexto", "text": INS2},
        ),
        dict(
            diff="caminhada",
            skill="understand",
            type="true_false",
            nn="01",
            question="Os juízes surgem por iniciativa própria, sem ação de Jeová.",
            ok="Certo: o texto diz que Jeová os suscitou.",
            wrong={"true": "Juízes 2:16 atribui a suscitação a Jeová, não ao povo."},
            options=tf_opts(),
            correct="false",
        ),
        dict(
            diff="caminhada",
            skill="understand",
            type="tap",
            nn="02",
            question='Em Juízes 2:16, toque a palavra que falta em "da mão dos que os ___"?',
            ok='Exato: dos que os "despojavam".',
            wrong={
                "a": "Suscitou é a ação de Jeová; aqui falta despojavam.",
                "b": "Livraram é o ato dos juízes, não o dos opressores.",
            },
            options=opts(("a", "suscitou"), ("b", "livraram"), ("c", "despojavam")),
            correct="c",
            template="da mão dos que os ___",
        ),
        dict(
            diff="caminhada",
            skill="understand",
            type="choice",
            nn="03",
            question="Como se relacionam a ação de Jeová e o livramento em Juízes 2:16?",
            ok="Certo: Jeová suscita; o livramento segue dessa iniciativa.",
            wrong={
                "a": "O texto não coloca o povo como primeiro agente.",
                "b": "Não há pacto com os despojadores.",
                "d": "O versículo não fala de rei permanente.",
            },
            options=opts(
                ("a", "O povo primeiro se arrepende; só então Jeová age."),
                ("b", "Os juízes negociam paz com os despojadores."),
                ("c", "Jeová suscita juízes, e estes livram Israel."),
                ("d", "Um rei permanente substitui os juízes no ato."),
            ),
            correct="c",
        ),
        dict(
            diff="caminhada",
            skill="understand",
            type="order",
            nn="04",
            question="Como se encadeiam os eventos de Juízes 2:16?",
            ok="Certo: suscitação, livramento e então a mão dos despojadores.",
            wrong={
                "a": "Os despojadores não abrem o versículo.",
                "c": "Releia o encadeamento.",
            },
            options=opts(
                ("a", "da mão dos que os despojavam"),
                ("b", "Jeová suscitou juízes"),
                ("c", "que os livraram"),
            ),
            correct="b",
            correctOrder=["b", "c", "a"],
        ),
        dict(
            diff="caminhada",
            skill="understand",
            type="complete",
            nn="05",
            question='Complete: "Jeová suscitou ___, que os livraram."',
            ok='Certo: Jeová suscitou "juízes".',
            wrong={
                "a": "Despojavam descreve os opressores, não os suscitados.",
                "c": "Mão é o instrumento da opressão, não o objeto.",
            },
            options=opts(("a", "despojavam"), ("b", "juízes"), ("c", "mão")),
            correct="b",
            template="Jeová suscitou ___, que os livraram.",
        ),
        dict(
            diff="caminhada",
            skill="understand",
            type="connect",
            nn="06",
            question="O que Juízes 2:16 comunica que se liga a este contexto?",
            ok="Certo: o livramento vem de Jeová que suscita, não do mérito.",
            wrong={
                "a": "O texto não atribui o livramento à força militar própria.",
                "b": "Não há abandono de Israel neste verso.",
            },
            options=opts(
                ("a", "Força militar própria de Israel"),
                ("b", "Abandono definitivo do povo"),
                ("c", "Livramento por graça suscitada"),
            ),
            correct="c",
            passageA={"ref": "Juízes 2:16", "text": P2},
            passageB={"ref": "Contexto", "text": INS2},
        ),
        dict(
            diff="profundezas",
            skill="interpret",
            type="true_false",
            nn="01",
            question="Em Juízes 2:16, o livramento revela graça de Jeová no meio da apostasia.",
            ok="Certo: Jeová suscita juízes que livram — graça ativa.",
            wrong={"false": "O verso mostra Jeová agindo para livrar, não só julgar."},
            options=tf_opts(),
            correct="true",
        ),
        dict(
            diff="profundezas",
            skill="interpret",
            type="tap",
            nn="02",
            question='Em Juízes 2:16, toque a palavra que falta em "___ suscitou juízes"?',
            ok='Exato: "Jeová" é quem suscita os juízes.',
            wrong={
                "b": "Juízes é o objeto; o sujeito é Jeová.",
                "c": "Livraram é a ação dos juízes, não o sujeito.",
            },
            options=opts(("a", "Jeová"), ("b", "juízes"), ("c", "livraram")),
            correct="a",
            template="___ suscitou juízes",
        ),
        dict(
            diff="profundezas",
            skill="interpret",
            type="choice",
            nn="03",
            question="Qual sentido teológico Juízes 2:16 prepara o leitor a ver?",
            ok="Certo: mesmo na apostasia, Jeová age por graça ao suscitar livradores.",
            wrong={
                "a": "O texto não diz que Israel se salvou sozinho.",
                "c": "Não há aqui recusa de livrar o povo.",
                "d": "O versículo não aponta rei eterno já reinando.",
            },
            options=opts(
                ("a", "Israel se salva por mérito próprio sem graça."),
                ("b", "Jeová ainda suscita livramento no meio da crise."),
                ("c", "Jeová se recusa a livrar quem caiu em apostasia."),
                ("d", "O livramento prova que o rei eterno já reinava."),
            ),
            correct="b",
        ),
        dict(
            diff="profundezas",
            skill="interpret",
            type="order",
            nn="04",
            question="Qual sequência revela o sentido de Juízes 2:16?",
            ok="Certo: Jeová age, juízes livram, opressores são a ameaça.",
            wrong={
                "b": "Essa peça não abre o sentido do verso.",
                "c": "Releia a progressão teológica.",
            },
            options=opts(
                ("a", "Jeová suscitou juízes"),
                ("b", "que os livraram"),
                ("c", "da mão dos que os despojavam"),
            ),
            correct="a",
            correctOrder=["a", "b", "c"],
        ),
        dict(
            diff="profundezas",
            skill="interpret",
            type="complete",
            nn="05",
            question='Complete: "da ___ dos que os despojavam."',
            ok='Certo: da "mão" dos que os despojavam.',
            wrong={
                "b": "Juízes são os livradores, não esta palavra.",
                "c": "Suscitou é o verbo de Jeová, não o instrumento.",
            },
            options=opts(("a", "mão"), ("b", "juízes"), ("c", "suscitou")),
            correct="a",
            template="da ___ dos que os despojavam.",
        ),
        dict(
            diff="profundezas",
            skill="interpret",
            type="connect",
            nn="06",
            question="O que Juízes 2:16 comunica que se liga a este contexto?",
            ok="Certo: graça que suscita juízes no meio da apostasia.",
            wrong={
                "a": "O texto não celebra autonomia do povo.",
                "b": "Não há abandono total de Israel neste verso.",
            },
            options=opts(
                ("a", "Autonomia do povo sem Deus"),
                ("b", "Abandono total de Israel"),
                ("c", "Graça no meio da apostasia"),
            ),
            correct="c",
            passageA={"ref": "Juízes 2:16", "text": P2},
            passageB={"ref": "Contexto", "text": INS2},
        ),
    ],
)

# ---------------------------------------------------------------------------
# M3 Juízes 4:8–9 — Débora e Baraque
# ---------------------------------------------------------------------------
P3 = (
    "Disse-lhe Baraque: Se vieres comigo, irei; mas, se não vieres comigo, não irei. "
    "Respondeu ela: Certamente irei contigo. Contudo, não será tua a glória na "
    "expedição em que vais; porque Jeová entregará a Sísera nas mãos duma mulher. "
    "Levantou-se Débora e foi com Baraque a Quedes."
)
LO3 = "Ver que Débora vai e Sísera cai na mão de uma mulher — Jeová salva como quer."
INS3 = "Débora vai; Sísera cai na mão de uma mulher — Jeová salva como quer."

bank += mission(
    "juizes-juizes-01-debora-e-baraque",
    "Juízes 4:8–9",
    P3,
    LO3,
    ["Juízes 4:8–9"],
    [
        dict(
            diff="semente",
            skill="observe",
            type="true_false",
            nn="01",
            question="Baraque diz a Débora que só irá se ela for com ele.",
            ok="Certo: Se vieres comigo, irei; se não, não irei.",
            wrong={"false": "Juízes 4:8 registra exatamente essa condição de Baraque."},
            options=tf_opts(),
            correct="true",
        ),
        dict(
            diff="semente",
            skill="observe",
            type="tap",
            nn="02",
            question='Em Juízes 4:8–9, toque a palavra que falta em "Se ___ comigo, irei"?',
            ok='Exato: "Se vieres comigo, irei".',
            wrong={
                "b": "Irei é a resposta condicionada; a lacuna pede vieres.",
                "c": "Glória vem depois; aqui falta vieres.",
            },
            options=opts(("a", "vieres"), ("b", "irei"), ("c", "glória")),
            correct="a",
            template="Se ___ comigo, irei",
        ),
        dict(
            diff="semente",
            skill="observe",
            type="choice",
            nn="03",
            question="O que Débora afirma sobre a glória da expedição?",
            ok="Certo: a glória não será de Baraque; Sísera cairá por uma mulher.",
            wrong={
                "a": "Ela não recusa ir; diz que certamente irá.",
                "b": "O texto não atribui a glória a Baraque.",
                "d": "Não há recusa de acompanhar Baraque.",
            },
            options=opts(
                ("a", "Ela recusa ir e manda Baraque sozinho."),
                ("b", "A glória da vitória será toda de Baraque."),
                ("c", "A glória não será dele; Sísera cairá por uma mulher."),
                ("d", "Ela manda Baraque esperar Sísera em casa."),
            ),
            correct="c",
        ),
        dict(
            diff="semente",
            skill="observe",
            type="order",
            nn="04",
            question="Qual sequência mostra a ordem dos fatos em Juízes 4:8–9?",
            ok="Certo: condição de Baraque, resposta de Débora, partida a Quedes.",
            wrong={
                "b": "A partida a Quedes fecha o trecho, não o abre.",
                "c": "Releia a ordem do diálogo.",
            },
            options=opts(
                ("a", "Baraque condiciona a ida à presença de Débora"),
                ("b", "Débora promete ir e anuncia que a glória não será dele"),
                ("c", "Débora se levanta e vai com Baraque a Quedes"),
            ),
            correct="a",
            correctOrder=["a", "b", "c"],
        ),
        dict(
            diff="semente",
            skill="observe",
            type="complete",
            nn="05",
            question='Complete: "Jeová entregará a Sísera nas mãos duma ___."',
            ok='Certo: nas mãos duma "mulher".',
            wrong={
                "a": "Glória é o que Baraque perderá; aqui a palavra é mulher.",
                "c": "Quedes é o destino; a lacuna pede mulher.",
            },
            options=opts(("a", "glória"), ("b", "mulher"), ("c", "Quedes")),
            correct="b",
            template="Jeová entregará a Sísera nas mãos duma ___.",
        ),
        dict(
            diff="semente",
            skill="observe",
            type="connect",
            nn="06",
            question="O que Juízes 4:8–9 comunica que se liga a este contexto?",
            ok="Certo: Débora vai e a vitória não segue o molde esperado.",
            wrong={
                "a": "O texto não garante glória a Baraque.",
                "c": "Não há recusa de Débora em ir.",
            },
            options=opts(
                ("a", "Glória garantida a Baraque"),
                ("b", "Jeová salva como quer"),
                ("c", "Recusa de Débora em ir"),
            ),
            correct="b",
            passageA={
                "ref": "Juízes 4:8–9",
                "text": "Jeová entregará a Sísera nas mãos duma mulher.",
            },
            passageB={"ref": "Contexto", "text": INS3},
        ),
        dict(
            diff="caminhada",
            skill="understand",
            type="true_false",
            nn="01",
            question="Débora aceita ir, mas anuncia que a glória da expedição não será de Baraque.",
            ok="Certo: ela vai e avisa que Sísera cairá por uma mulher.",
            wrong={"false": "Juízes 4:9 une a ida de Débora ao anúncio sobre a glória."},
            options=tf_opts(),
            correct="true",
        ),
        dict(
            diff="caminhada",
            skill="understand",
            type="tap",
            nn="02",
            question='Em Juízes 4:8–9, toque a palavra que falta em "não será tua a ___ na expedição"?',
            ok='Exato: não será tua a "glória".',
            wrong={
                "a": "Mulher é quem recebe Sísera; aqui falta glória.",
                "c": "Quedes é o destino; a lacuna pede glória.",
            },
            options=opts(("a", "mulher"), ("b", "glória"), ("c", "Quedes")),
            correct="b",
            template="não será tua a ___ na expedição",
        ),
        dict(
            diff="caminhada",
            skill="understand",
            type="choice",
            nn="03",
            question="Como o diálogo liga a condição de Baraque ao anúncio de Débora?",
            ok="Certo: ele condiciona a ida; ela vai e desloca a glória.",
            wrong={
                "a": "Ela não recusa; diz que certamente irá.",
                "b": "O texto não promete glória plena a Baraque.",
                "d": "Não há substituição de Baraque por outro general.",
            },
            options=opts(
                ("a", "Débora recusa ir e deixa Baraque sozinho."),
                ("b", "Ela promete a Baraque toda a glória da vitória."),
                ("c", "Ela vai, mas a glória não será dele — Sísera cai por mulher."),
                ("d", "Baraque é substituído por outro general em Quedes."),
            ),
            correct="c",
        ),
        dict(
            diff="caminhada",
            skill="understand",
            type="order",
            nn="04",
            question="Como se encadeiam os eventos de Juízes 4:8–9?",
            ok="Certo: condição, resposta com aviso, partida a Quedes.",
            wrong={
                "a": "A partida não abre o diálogo.",
                "c": "Releia o encadeamento.",
            },
            options=opts(
                ("a", "Débora se levanta e vai com Baraque a Quedes"),
                ("b", "Baraque condiciona a ida à presença de Débora"),
                ("c", "Débora promete ir e anuncia que a glória não será dele"),
            ),
            correct="b",
            correctOrder=["b", "c", "a"],
        ),
        dict(
            diff="caminhada",
            skill="understand",
            type="complete",
            nn="05",
            question='Complete: "Levantou-se Débora e foi com Baraque a ___."',
            ok='Certo: foram a "Quedes".',
            wrong={
                "a": "Sísera é o inimigo; o destino é Quedes.",
                "c": "Glória é o tema do aviso, não o lugar.",
            },
            options=opts(("a", "Sísera"), ("b", "Quedes"), ("c", "glória")),
            correct="b",
            template="Levantou-se Débora e foi com Baraque a ___.",
        ),
        dict(
            diff="caminhada",
            skill="understand",
            type="connect",
            nn="06",
            question="O que Juízes 4:8–9 comunica que se liga a este contexto?",
            ok="Certo: a vitória não segue o molde da glória de Baraque.",
            wrong={
                "a": "O texto não centra a glória em Baraque.",
                "b": "Não há recusa de Débora.",
            },
            options=opts(
                ("a", "Glória centrada em Baraque"),
                ("b", "Recusa de Débora em partir"),
                ("c", "Vitória fora do molde esperado"),
            ),
            correct="c",
            passageA={
                "ref": "Juízes 4:8–9",
                "text": "não será tua a glória na expedição em que vais",
            },
            passageB={"ref": "Contexto", "text": INS3},
        ),
        dict(
            diff="profundezas",
            skill="interpret",
            type="true_false",
            nn="01",
            question="O anúncio de Débora mostra que Jeová pode entregar a vitória por caminhos que retiram a glória humana esperada.",
            ok="Certo: Sísera cairá nas mãos de uma mulher — Jeová salva como quer.",
            wrong={"false": "O texto desloca a glória de Baraque para o modo de Jeová."},
            options=tf_opts(),
            correct="true",
        ),
        dict(
            diff="profundezas",
            skill="interpret",
            type="tap",
            nn="02",
            question='Em Juízes 4:8–9, toque a palavra que falta em "Jeová entregará a ___ nas mãos duma mulher"?',
            ok='Exato: Jeová entregará a "Sísera".',
            wrong={
                "b": "Débora vai com Baraque; o entregue é Sísera.",
                "c": "Baraque perde a glória; a lacuna pede Sísera.",
            },
            options=opts(("a", "Sísera"), ("b", "Débora"), ("c", "Baraque")),
            correct="a",
            template="Jeová entregará a ___ nas mãos duma mulher",
        ),
        dict(
            diff="profundezas",
            skill="interpret",
            type="choice",
            nn="03",
            question="Qual implicação teológica o anúncio de Débora sustenta?",
            ok="Certo: Jeová define o modo da vitória — e pode retirar a glória humana.",
            wrong={
                "a": "O texto não garante glória a Baraque pelo valor militar.",
                "c": "Débora não se recusa; ela vai.",
                "d": "Não há neutralidade de Jeová neste anúncio.",
            },
            options=opts(
                ("a", "A glória militar de Baraque está garantida por valor."),
                ("b", "Jeová salva como quer e pode deslocar a glória humana."),
                ("c", "Débora se recusa para proteger a honra de Baraque."),
                ("d", "Jeová permanece neutro na disputa com Sísera."),
            ),
            correct="b",
        ),
        dict(
            diff="profundezas",
            skill="interpret",
            type="order",
            nn="04",
            question="Qual sequência revela o sentido de Juízes 4:8–9?",
            ok="Certo: condição humana, aviso de Jeová, obediência no caminho.",
            wrong={
                "b": "Essa peça não fecha o sentido do trecho.",
                "c": "Releia a progressão.",
            },
            options=opts(
                ("a", "Baraque condiciona a ida à presença de Débora"),
                ("b", "Débora anuncia que a glória não será dele"),
                ("c", "Débora se levanta e vai com Baraque a Quedes"),
            ),
            correct="a",
            correctOrder=["a", "b", "c"],
        ),
        dict(
            diff="profundezas",
            skill="interpret",
            type="complete",
            nn="05",
            question='Complete: "Certamente ___ contigo."',
            ok='Certo: "Certamente irei contigo."',
            wrong={
                "b": "Vieres é a condição de Baraque; aqui Débora diz irei.",
                "c": "Glória é o tema do aviso, não este verbo.",
            },
            options=opts(("a", "irei"), ("b", "vieres"), ("c", "glória")),
            correct="a",
            template="Certamente ___ contigo.",
        ),
        dict(
            diff="profundezas",
            skill="interpret",
            type="connect",
            nn="06",
            question="O que Juízes 4:8–9 comunica que se liga a este contexto?",
            ok="Certo: Jeová salva como quer — Sísera cai na mão de uma mulher.",
            wrong={
                "a": "O texto não centra a glória em Baraque.",
                "b": "Não há abandono da expedição.",
            },
            options=opts(
                ("a", "Glória humana de Baraque"),
                ("b", "Abandono da expedição"),
                ("c", "Salvação no modo de Jeová"),
            ),
            correct="c",
            passageA={
                "ref": "Juízes 4:8–9",
                "text": "Jeová entregará a Sísera nas mãos duma mulher.",
            },
            passageB={"ref": "Contexto", "text": INS3},
        ),
    ],
)

# ---------------------------------------------------------------------------
# M4 Juízes 7:2 — Gideão
# ---------------------------------------------------------------------------
P4 = (
    "Disse Jeová a Gideão: Tens contigo gente demais para eu entregar os midianitas "
    "nas suas mãos, sem que Israel se glorie contra mim, dizendo: Foi a minha própria "
    "mão que me salvou."
)
LO4 = "Entender que gente demais impede a glória de Jeová — a salvação não é da mão de Israel."
INS4 = "Gente demais impede a glória de Jeová — a salvação não é da mão de Israel."

bank += mission(
    "juizes-juizes-02-gideao",
    "Juízes 7:2",
    P4,
    LO4,
    ["Juízes 7:2"],
    [
        dict(
            diff="semente",
            skill="observe",
            type="true_false",
            nn="01",
            question="Jeová diz a Gideão que há gente demais para entregar os midianitas.",
            ok="Certo: Tens contigo gente demais.",
            wrong={"false": "Juízes 7:2 abre com essa declaração de Jeová."},
            options=tf_opts(),
            correct="true",
        ),
        dict(
            diff="semente",
            skill="observe",
            type="tap",
            nn="02",
            question='Em Juízes 7:2, toque a palavra que falta em "Tens contigo gente ___ "?',
            ok='Exato: gente "demais".',
            wrong={
                "b": "Mão aparece no fim; aqui falta demais.",
                "c": "Gideão é o destinatário; a lacuna pede demais.",
            },
            options=opts(("a", "demais"), ("b", "mão"), ("c", "Gideão")),
            correct="a",
            template="Tens contigo gente ___",
        ),
        dict(
            diff="semente",
            skill="observe",
            type="choice",
            nn="03",
            question="O que Jeová quer evitar que Israel diga após a vitória?",
            ok='Certo: "Foi a minha própria mão que me salvou."',
            wrong={
                "a": "O texto não elogia o número de soldados.",
                "b": "Não há pedido para aumentar o exército.",
                "d": "Jeová não atribui a vitória aos midianitas.",
            },
            options=opts(
                ("a", "Que o exército era pequeno demais para vencer."),
                ("b", "Que Gideão deveria recrutar mais soldados."),
                ("c", "Que a própria mão de Israel o salvou."),
                ("d", "Que os midianitas entregaram a vitória de graça."),
            ),
            correct="c",
        ),
        dict(
            diff="semente",
            skill="observe",
            type="order",
            nn="04",
            question="Qual sequência mostra a ordem dos fatos em Juízes 7:2?",
            ok="Certo: gente demais, entrega dos midianitas, risco de glória humana.",
            wrong={
                "b": "A jactância humana fecha o verso, não o abre.",
                "c": "Releia a ordem.",
            },
            options=opts(
                ("a", "Tens contigo gente demais"),
                ("b", "para eu entregar os midianitas nas suas mãos"),
                ("c", "sem que Israel se glorie contra mim"),
            ),
            correct="a",
            correctOrder=["a", "b", "c"],
        ),
        dict(
            diff="semente",
            skill="observe",
            type="complete",
            nn="05",
            question='Complete: "Foi a minha própria ___ que me salvou."',
            ok='Certo: a própria "mão" que me salvou.',
            wrong={
                "a": "Demais descreve a gente; aqui a palavra é mão.",
                "c": "Gideão é o nome; a lacuna pede mão.",
            },
            options=opts(("a", "demais"), ("b", "mão"), ("c", "Gideão")),
            correct="b",
            template="Foi a minha própria ___ que me salvou.",
        ),
        dict(
            diff="semente",
            skill="observe",
            type="connect",
            nn="06",
            question="O que Juízes 7:2 comunica que se liga a este contexto?",
            ok="Certo: gente demais impede a glória de Jeová.",
            wrong={
                "a": "O texto não elogia o número como garantia.",
                "c": "Não há aqui salvação pela mão de Israel.",
            },
            options=opts(
                ("a", "Número como garantia de vitória"),
                ("b", "Glória de Jeová sem jactância"),
                ("c", "Salvação pela mão de Israel"),
            ),
            correct="b",
            passageA={
                "ref": "Juízes 7:2",
                "text": "Tens contigo gente demais para eu entregar os midianitas",
            },
            passageB={"ref": "Contexto", "text": INS4},
        ),
        dict(
            diff="caminhada",
            skill="understand",
            type="true_false",
            nn="01",
            question="Jeová reduz o exército para que Israel não se glorie contra ele.",
            ok="Certo: gente demais abriria espaço para a jactância humana.",
            wrong={"false": "O verso liga o excesso de gente ao risco de glória contra Jeová."},
            options=tf_opts(),
            correct="true",
        ),
        dict(
            diff="caminhada",
            skill="understand",
            type="tap",
            nn="02",
            question='Em Juízes 7:2, toque a palavra que falta em "sem que Israel se ___ contra mim"?',
            ok='Exato: sem que Israel se "glorie" contra mim.',
            wrong={
                "a": "Demais descreve a gente; aqui falta glorie.",
                "c": "Salvou fecha a jactância citada; a lacuna pede glorie.",
            },
            options=opts(("a", "demais"), ("b", "glorie"), ("c", "salvou")),
            correct="b",
            template="sem que Israel se ___ contra mim",
        ),
        dict(
            diff="caminhada",
            skill="understand",
            type="choice",
            nn="03",
            question="Por que gente demais impede o propósito de Jeová em Juízes 7:2?",
            ok="Certo: o excesso abriria espaço para Israel se gloriar da própria mão.",
            wrong={
                "a": "O texto não fala de falta de comida.",
                "b": "Não há medo de Gideão como motivo declarado.",
                "d": "Jeová não elogia o número como sinal de fé.",
            },
            options=opts(
                ("a", "Porque faltaria comida para tantos soldados."),
                ("b", "Porque Gideão temeria comandar um exército grande."),
                ("c", "Porque Israel poderia gloriar-se da própria mão."),
                ("d", "Porque o número grande prova a fé do povo."),
            ),
            correct="c",
        ),
        dict(
            diff="caminhada",
            skill="understand",
            type="order",
            nn="04",
            question="Como se encadeiam os eventos de Juízes 7:2?",
            ok="Certo: excesso de gente, entrega possível, risco de jactância.",
            wrong={
                "a": "A jactância citada não abre o verso.",
                "c": "Releia o encadeamento.",
            },
            options=opts(
                ("a", "Foi a minha própria mão que me salvou"),
                ("b", "Tens contigo gente demais"),
                ("c", "para eu entregar os midianitas nas suas mãos"),
            ),
            correct="b",
            correctOrder=["b", "c", "a"],
        ),
        dict(
            diff="caminhada",
            skill="understand",
            type="complete",
            nn="05",
            question='Complete: "para eu entregar os ___ nas suas mãos"',
            ok='Certo: entregar os "midianitas".',
            wrong={
                "a": "Gideão é o destinatário; o inimigo é midianitas.",
                "c": "Israel é o povo; a lacuna pede midianitas.",
            },
            options=opts(("a", "Gideão"), ("b", "midianitas"), ("c", "Israel")),
            correct="b",
            template="para eu entregar os ___ nas suas mãos",
        ),
        dict(
            diff="caminhada",
            skill="understand",
            type="connect",
            nn="06",
            question="O que Juízes 7:2 comunica que se liga a este contexto?",
            ok="Certo: a salvação não pode ser atribuída à mão de Israel.",
            wrong={
                "a": "O texto não elogia o número como mérito.",
                "b": "Não há aqui vitória pela força própria.",
            },
            options=opts(
                ("a", "Mérito do número de soldados"),
                ("b", "Vitória pela força própria"),
                ("c", "Salvação sem glória humana"),
            ),
            correct="c",
            passageA={
                "ref": "Juízes 7:2",
                "text": "Foi a minha própria mão que me salvou.",
            },
            passageB={"ref": "Contexto", "text": INS4},
        ),
        dict(
            diff="profundezas",
            skill="interpret",
            type="true_false",
            nn="01",
            question="Juízes 7:2 ensina que a salvação deve ser reconhecida como obra de Jeová, não da mão de Israel.",
            ok="Certo: o risco nomeado é a jactância da própria mão.",
            wrong={"false": "O verso existe para proteger a glória de Jeová."},
            options=tf_opts(),
            correct="true",
        ),
        dict(
            diff="profundezas",
            skill="interpret",
            type="tap",
            nn="02",
            question='Em Juízes 7:2, toque a palavra que falta em "Foi a minha própria mão que me ___"?',
            ok='Exato: "que me salvou".',
            wrong={
                "a": "Demais descreve a gente; aqui falta salvou.",
                "b": "Glorie é o verbo do risco; a lacuna pede salvou.",
            },
            options=opts(("a", "demais"), ("b", "glorie"), ("c", "salvou")),
            correct="c",
            template="Foi a minha própria mão que me ___",
        ),
        dict(
            diff="profundezas",
            skill="interpret",
            type="choice",
            nn="03",
            question="Qual sentido teológico Juízes 7:2 prepara sobre a vitória?",
            ok="Certo: Jeová molda os meios para que a glória não caiba a Israel.",
            wrong={
                "a": "O texto não celebra o número como sinal de bênção.",
                "c": "Não há salvação atribuída à mão humana.",
                "d": "Jeová não elogia a jactância de Israel.",
            },
            options=opts(
                ("a", "Quanto maior o exército, maior a bênção de Jeová."),
                ("b", "Jeová reduz os meios para guardar a própria glória."),
                ("c", "A mão de Israel é o verdadeiro agente da salvação."),
                ("d", "Israel deve gloriar-se da própria força após vencer."),
            ),
            correct="b",
        ),
        dict(
            diff="profundezas",
            skill="interpret",
            type="order",
            nn="04",
            question="Qual sequência revela o sentido de Juízes 7:2?",
            ok="Certo: excesso, entrega possível, risco da glória humana.",
            wrong={
                "b": "Essa peça não fecha o sentido.",
                "c": "Releia a progressão.",
            },
            options=opts(
                ("a", "Tens contigo gente demais"),
                ("b", "para eu entregar os midianitas nas suas mãos"),
                ("c", "sem que Israel se glorie contra mim"),
            ),
            correct="a",
            correctOrder=["a", "b", "c"],
        ),
        dict(
            diff="profundezas",
            skill="interpret",
            type="complete",
            nn="05",
            question='Complete: "Disse Jeová a ___: Tens contigo gente demais"',
            ok='Certo: Disse Jeová a "Gideão".',
            wrong={
                "b": "Israel é o povo; o destinatário é Gideão.",
                "c": "Midianitas são o inimigo; a lacuna pede Gideão.",
            },
            options=opts(("a", "Gideão"), ("b", "Israel"), ("c", "midianitas")),
            correct="a",
            template="Disse Jeová a ___: Tens contigo gente demais",
        ),
        dict(
            diff="profundezas",
            skill="interpret",
            type="connect",
            nn="06",
            question="O que Juízes 7:2 comunica que se liga a este contexto?",
            ok="Certo: a salvação não é da mão de Israel — glória de Jeová.",
            wrong={
                "a": "O texto não atribui a vitória ao número.",
                "b": "Não há jactância aprovada.",
            },
            options=opts(
                ("a", "Vitória pelo número de soldados"),
                ("b", "Jactância aprovada de Israel"),
                ("c", "Salvação sem mão humana"),
            ),
            correct="c",
            passageA={
                "ref": "Juízes 7:2",
                "text": "Foi a minha própria mão que me salvou.",
            },
            passageB={"ref": "Contexto", "text": INS4},
        ),
    ],
)

# ---------------------------------------------------------------------------
# M5 Juízes 16:28 — Sansão
# ---------------------------------------------------------------------------
P5 = (
    "Sansão clamou a Jeová e disse: Senhor Jeová, lembra-te de mim, e fortalece-me "
    "ainda esta vez, ó Deus, para que me vingue nos filisteus ao menos dum dos meus "
    "dois olhos."
)
LO5 = "Ver Sansão clamar ainda esta vez — força que volta como súplica a Jeová."
INS5 = "Sansão clama: ainda esta vez — força que volta como súplica."

bank += mission(
    "juizes-juizes-03-sansao",
    "Juízes 16:28",
    P5,
    LO5,
    ["Juízes 16:28"],
    [
        dict(
            diff="semente",
            skill="observe",
            type="true_false",
            nn="01",
            question="Sansão clamou a Jeová pedindo que se lembrasse dele e o fortalecesse.",
            ok="Certo: o versículo abre com esse clamor.",
            wrong={"false": "Juízes 16:28 registra o clamor de Sansão a Jeová."},
            options=tf_opts(),
            correct="true",
        ),
        dict(
            diff="semente",
            skill="observe",
            type="tap",
            nn="02",
            question='Em Juízes 16:28, toque a palavra que falta em "Sansão ___ a Jeová"?',
            ok='Exato: Sansão "clamou" a Jeová.',
            wrong={
                "b": "Fortalece-me é o pedido; a lacuna pede clamou.",
                "c": "Filisteus são o alvo; aqui falta clamou.",
            },
            options=opts(("a", "clamou"), ("b", "fortalece-me"), ("c", "filisteus")),
            correct="a",
            template="Sansão ___ a Jeová",
        ),
        dict(
            diff="semente",
            skill="observe",
            type="choice",
            nn="03",
            question="O que Sansão pede explicitamente em Juízes 16:28?",
            ok="Certo: que Jeová se lembre e o fortaleça ainda esta vez.",
            wrong={
                "a": "O texto não pede fuga silenciosa.",
                "c": "Não há pedido de novo nazireado ritual.",
                "d": "Ele não negocia trégua com os filisteus.",
            },
            options=opts(
                ("a", "Que o deixem fugir em silêncio do templo."),
                ("b", "Que Jeová se lembre e o fortaleça ainda esta vez."),
                ("c", "Que lhe devolvam o nazireado por um rito."),
                ("d", "Que os filisteus firmem trégua com Israel."),
            ),
            correct="b",
        ),
        dict(
            diff="semente",
            skill="observe",
            type="order",
            nn="04",
            question="Qual sequência mostra a ordem dos fatos em Juízes 16:28?",
            ok="Certo: clamor, pedido de força, propósito da vingança.",
            wrong={
                "b": "A vingança fecha o pedido, não o abre.",
                "c": "Releia a ordem.",
            },
            options=opts(
                ("a", "Sansão clamou a Jeová"),
                ("b", "lembra-te de mim, e fortalece-me ainda esta vez"),
                ("c", "para que me vingue nos filisteus"),
            ),
            correct="a",
            correctOrder=["a", "b", "c"],
        ),
        dict(
            diff="semente",
            skill="observe",
            type="complete",
            nn="05",
            question='Complete: "fortalece-me ainda esta ___, ó Deus"',
            ok='Certo: ainda esta "vez".',
            wrong={
                "a": "Clamou é o verbo inicial; aqui a palavra é vez.",
                "c": "Olhos fecha o pedido; a lacuna pede vez.",
            },
            options=opts(("a", "clamou"), ("b", "vez"), ("c", "olhos")),
            correct="b",
            template="fortalece-me ainda esta ___, ó Deus",
        ),
        dict(
            diff="semente",
            skill="observe",
            type="connect",
            nn="06",
            question="O que Juízes 16:28 comunica que se liga a este contexto?",
            ok="Certo: a força volta como súplica — ainda esta vez.",
            wrong={
                "a": "O texto não descreve força autônoma.",
                "c": "Não há silêncio de Sansão neste verso.",
            },
            options=opts(
                ("a", "Força autônoma sem oração"),
                ("b", "Força que volta como súplica"),
                ("c", "Silêncio final de Sansão"),
            ),
            correct="b",
            passageA={
                "ref": "Juízes 16:28",
                "text": "fortalece-me ainda esta vez, ó Deus",
            },
            passageB={"ref": "Contexto", "text": INS5},
        ),
        dict(
            diff="caminhada",
            skill="understand",
            type="true_false",
            nn="01",
            question="Sansão pede força própria, sem dirigir o pedido a Jeová.",
            ok="Certo: ele clama a Jeová — Senhor Jeová, lembra-te de mim.",
            wrong={"true": "O versículo é um clamor dirigido a Jeová, não força autônoma."},
            options=tf_opts(),
            correct="false",
        ),
        dict(
            diff="caminhada",
            skill="understand",
            type="tap",
            nn="02",
            question='Em Juízes 16:28, toque a palavra que falta em "lembra-te de mim, e ___ ainda esta vez"?',
            ok='Exato: "fortalece-me" ainda esta vez.',
            wrong={
                "a": "Clamou é o verbo inicial; aqui falta fortalece-me.",
                "c": "Vingue vem depois; a lacuna pede fortalece-me.",
            },
            options=opts(("a", "clamou"), ("b", "fortalece-me"), ("c", "vingue")),
            correct="b",
            template="lembra-te de mim, e ___ ainda esta vez",
        ),
        dict(
            diff="caminhada",
            skill="understand",
            type="choice",
            nn="03",
            question="Como o pedido de Sansão liga súplica e propósito em Juízes 16:28?",
            ok="Certo: pede memória e força para vingar-se nos filisteus.",
            wrong={
                "a": "Ele não pede fuga silenciosa.",
                "b": "Não há pedido de perdão ritual separado.",
                "d": "O alvo não é Israel, mas os filisteus.",
            },
            options=opts(
                ("a", "Pede fuga silenciosa sem enfrentar os filisteus."),
                ("b", "Pede perdão ritual sem pedir força."),
                ("c", "Pede que Jeová o lembre e fortaleça para a vingança."),
                ("d", "Pede força para vingar-se de Israel, não dos filisteus."),
            ),
            correct="c",
        ),
        dict(
            diff="caminhada",
            skill="understand",
            type="order",
            nn="04",
            question="Como se encadeiam os eventos de Juízes 16:28?",
            ok="Certo: clamor, pedido de força, propósito contra os filisteus.",
            wrong={
                "a": "A vingança não abre o verso.",
                "c": "Releia o encadeamento.",
            },
            options=opts(
                ("a", "para que me vingue nos filisteus"),
                ("b", "Sansão clamou a Jeová"),
                ("c", "fortalece-me ainda esta vez"),
            ),
            correct="b",
            correctOrder=["b", "c", "a"],
        ),
        dict(
            diff="caminhada",
            skill="understand",
            type="complete",
            nn="05",
            question='Complete: "para que me ___ nos filisteus"',
            ok='Certo: para que me "vingue" nos filisteus.',
            wrong={
                "a": "Clamou é o verbo inicial; aqui falta vingue.",
                "c": "Lembra-te é o outro pedido; a lacuna pede vingue.",
            },
            options=opts(("a", "clamou"), ("b", "vingue"), ("c", "lembra-te")),
            correct="b",
            template="para que me ___ nos filisteus",
        ),
        dict(
            diff="caminhada",
            skill="understand",
            type="connect",
            nn="06",
            question="O que Juízes 16:28 comunica que se liga a este contexto?",
            ok="Certo: o último ato passa pelo clamor — ainda esta vez.",
            wrong={
                "a": "O texto não mostra força sem oração.",
                "b": "Não há abandono do pedido a Jeová.",
            },
            options=opts(
                ("a", "Força sem oração final"),
                ("b", "Abandono do clamor a Jeová"),
                ("c", "Último ato como súplica"),
            ),
            correct="c",
            passageA={
                "ref": "Juízes 16:28",
                "text": "Senhor Jeová, lembra-te de mim, e fortalece-me ainda esta vez",
            },
            passageB={"ref": "Contexto", "text": INS5},
        ),
        dict(
            diff="profundezas",
            skill="interpret",
            type="true_false",
            nn="01",
            question="O clamor de Sansão mostra que a força final volta como súplica a Jeová, não como autonomia.",
            ok="Certo: ainda esta vez — força pedida a Deus.",
            wrong={"false": "O verso é súplica: Senhor Jeová, fortalece-me."},
            options=tf_opts(),
            correct="true",
        ),
        dict(
            diff="profundezas",
            skill="interpret",
            type="tap",
            nn="02",
            question='Em Juízes 16:28, toque a palavra que falta em "ao menos dum dos meus dois ___"?',
            ok='Exato: "olhos".',
            wrong={
                "a": "Filisteus são o alvo; aqui falta olhos.",
                "b": "Vez é o tempo do pedido; a lacuna pede olhos.",
            },
            options=opts(("a", "filisteus"), ("b", "vez"), ("c", "olhos")),
            correct="c",
            template="ao menos dum dos meus dois ___",
        ),
        dict(
            diff="profundezas",
            skill="interpret",
            type="choice",
            nn="03",
            question="Qual leitura teológica Juízes 16:28 sustenta sobre a força de Sansão?",
            ok="Certo: no fim, a força é pedida a Jeová — súplica, não autonomia.",
            wrong={
                "a": "O texto não celebra autonomia final.",
                "c": "Não há recusa de Jeová narrada neste verso.",
                "d": "O clamor não é dirigido aos filisteus.",
            },
            options=opts(
                ("a", "A força final prova autonomia total de Sansão."),
                ("b", "A força volta como súplica: ainda esta vez, ó Deus."),
                ("c", "Jeová se recusa a ouvir o clamor de Sansão."),
                ("d", "Sansão clama aos filisteus, não a Jeová."),
            ),
            correct="b",
        ),
        dict(
            diff="profundezas",
            skill="interpret",
            type="order",
            nn="04",
            question="Qual sequência revela o sentido de Juízes 16:28?",
            ok="Certo: clamor a Jeová, pedido de força, propósito da vingança.",
            wrong={
                "b": "Essa peça não fecha o sentido.",
                "c": "Releia a progressão.",
            },
            options=opts(
                ("a", "Sansão clamou a Jeová"),
                ("b", "fortalece-me ainda esta vez"),
                ("c", "para que me vingue nos filisteus"),
            ),
            correct="a",
            correctOrder=["a", "b", "c"],
        ),
        dict(
            diff="profundezas",
            skill="interpret",
            type="complete",
            nn="05",
            question='Complete: "Senhor Jeová, ___ de mim"',
            ok='Certo: "lembra-te" de mim.',
            wrong={
                "b": "Vingue vem depois; aqui falta lembra-te.",
                "c": "Clamou é o verbo narrativo; a lacuna pede lembra-te.",
            },
            options=opts(("a", "lembra-te"), ("b", "vingue"), ("c", "clamou")),
            correct="a",
            template="Senhor Jeová, ___ de mim",
        ),
        dict(
            diff="profundezas",
            skill="interpret",
            type="connect",
            nn="06",
            question="O que Juízes 16:28 comunica que se liga a este contexto?",
            ok="Certo: força que volta como súplica — ainda esta vez.",
            wrong={
                "a": "O texto não mostra autonomia final.",
                "b": "Não há silêncio sem clamor.",
            },
            options=opts(
                ("a", "Autonomia final sem Deus"),
                ("b", "Silêncio sem clamor"),
                ("c", "Súplica: ainda esta vez"),
            ),
            correct="c",
            passageA={
                "ref": "Juízes 16:28",
                "text": "fortalece-me ainda esta vez, ó Deus",
            },
            passageB={"ref": "Contexto", "text": INS5},
        ),
    ],
)

# ---------------------------------------------------------------------------
# M6 Juízes 2:18–19 — o ciclo (texto TB fornecido = 2:18)
# ---------------------------------------------------------------------------
P6 = (
    "Quando Jeová lhes suscitava juízes, ele era com o juiz, e os livrava da mão "
    "dos seus inimigos todos os dias do juiz; pois Jeová se arrependia em atenção "
    "ao gemer que lhes provocavam os que os oprimiam e apertavam."
)
LO6 = "Reconhecer o ciclo: Jeová se compadece do gemido e livra com o juiz."
INS6 = "O ciclo: Jeová se compadece do gemido e livra com o juiz."

bank += mission(
    "juizes-juizes-04-desafio-o-ciclo",
    "Juízes 2:18–19",
    P6,
    LO6,
    ["Juízes 2:18–19"],
    [
        dict(
            diff="semente",
            skill="observe",
            type="true_false",
            nn="01",
            question="Jeová era com o juiz e livrava o povo nos dias em que lhes suscitava juízes.",
            ok="Certo: ele era com o juiz e os livrava.",
            wrong={"false": "Juízes 2:18 afirma a presença de Jeová com o juiz."},
            options=tf_opts(),
            correct="true",
        ),
        dict(
            diff="semente",
            skill="observe",
            type="tap",
            nn="02",
            question='Em Juízes 2:18–19, toque a palavra que falta em "ele era com o ___"?',
            ok='Exato: ele era com o "juiz".',
            wrong={
                "b": "Gemer motiva o arrependimento; aqui falta juiz.",
                "c": "Inimigos são a ameaça; a lacuna pede juiz.",
            },
            options=opts(("a", "juiz"), ("b", "gemer"), ("c", "inimigos")),
            correct="a",
            template="ele era com o ___",
        ),
        dict(
            diff="semente",
            skill="observe",
            type="choice",
            nn="03",
            question="O que Juízes 2:18 afirma sobre o livramento enquanto havia juiz?",
            ok="Certo: livrava-os todos os dias do juiz.",
            wrong={
                "a": "O texto não limita o livramento a um único dia.",
                "b": "Não há abandono do juiz neste trecho.",
                "d": "Jeová não se recusa a livrar enquanto há juiz.",
            },
            options=opts(
                ("a", "O livramento durava só um dia de festa."),
                ("b", "Jeová abandonava o juiz no primeiro combate."),
                ("c", "Os livrava da mão dos inimigos todos os dias do juiz."),
                ("d", "Jeová se recusava a ouvir o gemer do povo."),
            ),
            correct="c",
        ),
        dict(
            diff="semente",
            skill="observe",
            type="order",
            nn="04",
            question="Qual sequência mostra a ordem dos fatos em Juízes 2:18–19?",
            ok="Certo: suscitação, presença e livramento, depois o gemer.",
            wrong={
                "b": "O gemer motiva o arrependimento no fim do trecho.",
                "c": "Releia a ordem.",
            },
            options=opts(
                ("a", "Jeová lhes suscitava juízes"),
                ("b", "ele era com o juiz e os livrava"),
                ("c", "Jeová se arrependia em atenção ao gemer"),
            ),
            correct="a",
            correctOrder=["a", "b", "c"],
        ),
        dict(
            diff="semente",
            skill="observe",
            type="complete",
            nn="05",
            question='Complete: "Jeová se arrependia em atenção ao ___ "',
            ok='Certo: em atenção ao "gemer".',
            wrong={
                "a": "Juiz é com quem Jeová estava; aqui falta gemer.",
                "c": "Inimigos provocam o gemer; a lacuna pede gemer.",
            },
            options=opts(("a", "juiz"), ("b", "gemer"), ("c", "inimigos")),
            correct="b",
            template="Jeová se arrependia em atenção ao ___",
        ),
        dict(
            diff="semente",
            skill="observe",
            type="connect",
            nn="06",
            question="O que Juízes 2:18–19 comunica que se liga a este contexto?",
            ok="Certo: Jeová se compadece do gemido e livra com o juiz.",
            wrong={
                "a": "O texto não descreve abandono total.",
                "c": "Não há indiferença ao gemer.",
            },
            options=opts(
                ("a", "Abandono total do povo"),
                ("b", "Compadecimento que livra"),
                ("c", "Indiferença ao gemer"),
            ),
            correct="b",
            passageA={
                "ref": "Juízes 2:18–19",
                "text": "Jeová se arrependia em atenção ao gemer",
            },
            passageB={"ref": "Contexto", "text": INS6},
        ),
        dict(
            diff="caminhada",
            skill="understand",
            type="true_false",
            nn="01",
            question="O livramento nos dias do juiz responde ao gemer causado pelos opressores.",
            ok="Certo: Jeová se arrependia em atenção ao gemer.",
            wrong={"false": "O texto liga gemer, arrependimento de Jeová e livramento."},
            options=tf_opts(),
            correct="true",
        ),
        dict(
            diff="caminhada",
            skill="understand",
            type="tap",
            nn="02",
            question='Em Juízes 2:18–19, toque a palavra que falta em "os livrava da mão dos seus ___"?',
            ok='Exato: dos seus "inimigos".',
            wrong={
                "a": "Juiz é o instrumento; aqui falta inimigos.",
                "c": "Gemer motiva Jeová; a lacuna pede inimigos.",
            },
            options=opts(("a", "juiz"), ("b", "inimigos"), ("c", "gemer")),
            correct="b",
            template="os livrava da mão dos seus ___",
        ),
        dict(
            diff="caminhada",
            skill="understand",
            type="choice",
            nn="03",
            question="Como se relacionam juiz, livramento e gemer em Juízes 2:18?",
            ok="Certo: Jeová está com o juiz, livra, e se compadece do gemer.",
            wrong={
                "a": "O texto não ignora o gemer.",
                "b": "Não há abandono do juiz no combate.",
                "d": "O livramento não é só um dia isolado.",
            },
            options=opts(
                ("a", "Jeová ignora o gemer e só julga o povo."),
                ("b", "O juiz luta sozinho, sem a presença de Jeová."),
                ("c", "Jeová está com o juiz, livra e se compadece do gemer."),
                ("d", "O livramento dura só o primeiro dia do juiz."),
            ),
            correct="c",
        ),
        dict(
            diff="caminhada",
            skill="understand",
            type="order",
            nn="04",
            question="Como se encadeiam os eventos de Juízes 2:18–19?",
            ok="Certo: suscitação, presença e livramento, atenção ao gemer.",
            wrong={
                "a": "O gemer não abre o trecho narrativo.",
                "c": "Releia o encadeamento.",
            },
            options=opts(
                ("a", "Jeová se arrependia em atenção ao gemer"),
                ("b", "Jeová lhes suscitava juízes"),
                ("c", "ele era com o juiz e os livrava"),
            ),
            correct="b",
            correctOrder=["b", "c", "a"],
        ),
        dict(
            diff="caminhada",
            skill="understand",
            type="complete",
            nn="05",
            question='Complete: "todos os ___ do juiz"',
            ok='Certo: todos os "dias" do juiz.',
            wrong={
                "b": "Gemer motiva Jeová; aqui falta dias.",
                "c": "Inimigos são a ameaça; a lacuna pede dias.",
            },
            options=opts(("a", "dias"), ("b", "gemer"), ("c", "inimigos")),
            correct="a",
            template="todos os ___ do juiz",
        ),
        dict(
            diff="caminhada",
            skill="understand",
            type="connect",
            nn="06",
            question="O que Juízes 2:18–19 comunica que se liga a este contexto?",
            ok="Certo: o ciclo passa pelo gemido e pelo juiz que livra.",
            wrong={
                "a": "O texto não aponta indiferença divina.",
                "b": "Não há abandono permanente neste trecho.",
            },
            options=opts(
                ("a", "Indiferença divina ao gemer"),
                ("b", "Abandono permanente de Israel"),
                ("c", "Ciclo de gemido e livramento"),
            ),
            correct="c",
            passageA={
                "ref": "Juízes 2:18–19",
                "text": "ele era com o juiz, e os livrava da mão dos seus inimigos",
            },
            passageB={"ref": "Contexto", "text": INS6},
        ),
        dict(
            diff="profundezas",
            skill="interpret",
            type="true_false",
            nn="01",
            question="Juízes 2:18 apresenta Jeová como indiferente ao sofrimento causado pelos opressores.",
            ok="Certo: ele se arrepende em atenção ao gemer — não é indiferença.",
            wrong={"true": "O texto afirma compadecimento diante do gemer, não indiferença."},
            options=tf_opts(),
            correct="false",
        ),
        dict(
            diff="profundezas",
            skill="interpret",
            type="tap",
            nn="02",
            question='Em Juízes 2:18–19, toque a palavra que falta em "Jeová se ___ em atenção ao gemer"?',
            ok='Exato: Jeová se "arrependia".',
            wrong={
                "b": "Suscitava abre o trecho; aqui falta arrependia.",
                "c": "Livrava é a ação com o juiz; a lacuna pede arrependia.",
            },
            options=opts(("a", "arrependia"), ("b", "suscitava"), ("c", "livrava")),
            correct="a",
            template="Jeová se ___ em atenção ao gemer",
        ),
        dict(
            diff="profundezas",
            skill="interpret",
            type="choice",
            nn="03",
            question="Qual sentido teológico o ciclo de Juízes 2:18 revela?",
            ok="Certo: Jeová se compadece do gemido e livra por meio do juiz.",
            wrong={
                "a": "O texto não mostra indiferença.",
                "c": "Não há abandono total enquanto há juiz.",
                "d": "O livramento não é mérito do povo sozinho.",
            },
            options=opts(
                ("a", "Jeová permanece indiferente ao gemer do povo."),
                ("b", "Jeová se compadece do gemido e livra com o juiz."),
                ("c", "Jeová abandona Israel enquanto o juiz vive."),
                ("d", "O povo se livra sozinho, sem a presença de Jeová."),
            ),
            correct="b",
        ),
        dict(
            diff="profundezas",
            skill="interpret",
            type="order",
            nn="04",
            question="Qual sequência revela o sentido de Juízes 2:18–19?",
            ok="Certo: Jeová suscita, está com o juiz, e se compadece do gemer.",
            wrong={
                "b": "Essa peça não fecha o sentido.",
                "c": "Releia a progressão.",
            },
            options=opts(
                ("a", "Jeová lhes suscitava juízes"),
                ("b", "ele era com o juiz e os livrava"),
                ("c", "Jeová se arrependia em atenção ao gemer"),
            ),
            correct="a",
            correctOrder=["a", "b", "c"],
        ),
        dict(
            diff="profundezas",
            skill="interpret",
            type="complete",
            nn="05",
            question='Complete: "os que os oprimiam e ___"',
            ok='Certo: oprimiam e "apertavam".',
            wrong={
                "b": "Gemer é o resultado; aqui falta apertavam.",
                "c": "Juiz é o instrumento; a lacuna pede apertavam.",
            },
            options=opts(("a", "apertavam"), ("b", "gemer"), ("c", "juiz")),
            correct="a",
            template="os que os oprimiam e ___",
        ),
        dict(
            diff="profundezas",
            skill="interpret",
            type="connect",
            nn="06",
            question="O que Juízes 2:18–19 comunica que se liga a este contexto?",
            ok="Certo: o ciclo é compadecimento e livramento com o juiz.",
            wrong={
                "a": "O texto não aponta indiferença.",
                "b": "Não há abandono enquanto o juiz vive.",
            },
            options=opts(
                ("a", "Indiferença ao sofrimento"),
                ("b", "Abandono nos dias do juiz"),
                ("c", "Compadecimento que livra"),
            ),
            correct="c",
            passageA={
                "ref": "Juízes 2:18–19",
                "text": "Jeová se arrependia em atenção ao gemer",
            },
            passageB={"ref": "Contexto", "text": INS6},
        ),
    ],
)

assert len(bank) == 108, len(bank)

# Mix check: T/F answers
tf_answers = [q["correctOptionId"] for q in bank if q["type"] == "true_false"]
assert "true" in tf_answers and "false" in tf_answers

# Mix check: choice correct ids
choice_ids = {q["correctOptionId"] for q in bank if q["type"] == "choice"}
assert len(choice_ids) >= 3, choice_ids

OUT.write_text(json.dumps(bank, ensure_ascii=False, indent=2) + "\n", encoding="utf-8")
print(f"Wrote {OUT} ({len(bank)} questions)")
