"""Dados das trilhas das epistolas gerais."""


def S(q_s, q_c, q_p, answer, wrong, verse):
    return {
        "q_s": q_s,
        "q_c": q_c,
        "q_p": q_p,
        "answer": answer,
        "wrong": wrong,
        "verse": verse,
    }


def M(slug, title, subtitle, intro, study, seeds, boss=False):
    return {
        "slug": slug,
        "title": title,
        "subtitle": subtitle,
        "intro": intro,
        "boss": boss,
        "study": study,
        "seeds": seeds,
    }


def T(ref, text, context, keyword, gloss, question, prompts):
    return {
        "passageRef": ref,
        "passageText": text,
        "context": context,
        "keyword": keyword,
        "keywordGloss": gloss,
        "focusQuestion": question,
        "reflectionPrompts": prompts,
    }


GERAIS = {
    "cartas-gerais": {
        "module": {
            "title": "Cartas Gerais",
            "icon": "mail",
            "section": "Novo Testamento",
        },
        "missions": [
            M("cg-01", "Uma fe que se espalha", "Conheca as cartas gerais",
              "Estas cartas falam a igrejas e crentes em muitos lugares. Elas chamam o povo de Deus a perseverar em uma fe viva.",
              T("1 Pedro 1:1-2", "Pedro, apostolo de Jesus Cristo, aos eleitos que sao forasteiros... graca e paz vos sejam multiplicadas.",
                "As cartas gerais receberam esse nome por nao serem dirigidas somente a uma cidade especifica. Hebreus, Tiago, 1 e 2 Pedro, 1, 2 e 3 Joao e Judas fortalecem a igreja em meio a desafios.",
                "eleitos", "Pessoas chamadas por Deus em Cristo, pertencentes ao seu povo.", "Como saber que pertencemos a Deus muda nossa maneira de viver?",
                ["Que pressao sua fe enfrenta hoje?", "Como voce pode encorajar outro cristao?", "Por que a igreja precisa de toda a Biblia?"]),
              [
                  S("Para quem muitas cartas gerais foram escritas?", "Qual e uma marca dessas cartas?", "Como elas servem a igreja hoje?", "Para crentes e igrejas em muitos lugares", ["Somente ao imperador romano", "Apenas a uma familia", "Exclusivamente aos sacerdotes"], "1 Pedro 1:1"),
                  S("Quem e chamado de forasteiro em 1 Pedro?", "O que essa imagem ensina?", "Como um cristao deve viver como forasteiro?", "O cristao que pertence a Deus neste mundo", ["Quem nunca viajou", "Somente os apostolos", "Quem deixou Israel"], "1 Pedro 1:1"),
                  S("Qual saudacao Pedro deseja aos leitores?", "De onde vem essa paz?", "Como voce pode buscar essa paz?", "Graca e paz multiplicadas", ["Riqueza e fama", "Vinganca e poder", "Silencio e isolamento"], "1 Pedro 1:2"),
                  S("As cartas gerais substituem os Evangelhos?", "Como os livros do NT se relacionam?", "Por que ler toda a Biblia?", "Nao, elas complementam o testemunho apostolico", ["Sim, os Evangelhos nao importam", "Sim, Paulo deve ser ignorado", "Nao, porque nao sao parte da Biblia"], "2 Pedro 3:15-16"),
                  S("Qual e o centro da fe ensinada nessas cartas?", "Quem sustenta o crente?", "Que verdade voce quer guardar?", "Jesus Cristo e sua obra salvadora", ["O esforco humano sozinho", "A tradicao sem Cristo", "O medo das pessoas"], "1 Pedro 1:18-19"),
              ]),
            M("cg-02", "Fe que aparece na vida", "Os grandes temas",
              "As cartas gerais unem doutrina e pratica: verdade, santidade, amor, perseveranca e defesa da fe caminham juntos.",
              T("Tiago 1:22", "Sede praticantes da palavra e nao somente ouvintes, enganando-vos a vos mesmos.",
                "Tiago resume um tema recorrente nas cartas gerais: a verdade recebida transforma atitudes, palavras, relacionamentos e esperanca.",
                "praticantes", "Pessoas que obedecem a Palavra, e nao apenas a escutam.", "Que area da sua vida precisa obedecer melhor ao que voce ja sabe?",
                ["Qual verdade biblica voce precisa praticar?", "Suas palavras refletem Cristo?", "Como a esperanca futura fortalece voce?"]),
              [
                  S("O que Tiago manda os crentes serem?", "Qual e o perigo de apenas ouvir?", "Que obediencia pratica voce pode dar hoje?", "Praticantes da Palavra", ["Criticos da Palavra", "Donos da Palavra", "Espectadores da Palavra"], "Tiago 1:22"),
                  S("Qual tema aparece em 1 Joao?", "Como o amor se relaciona com Deus?", "Como amar um irmao hoje?", "Amor aos irmaos", ["Indiferenca aos irmaos", "Orgulho espiritual", "Busca de prestigo"], "1 Joao 4:7"),
                  S("Que atitude 1 Pedro encoraja no sofrimento?", "Por que essa atitude e possivel?", "Como voce pode perseverar?", "Esperanca em Cristo", ["Desespero sem Deus", "Retaliacao", "Negacao da fe"], "1 Pedro 1:13"),
                  S("O que Judas manda os crentes fazerem?", "Por que a fe precisa ser defendida?", "Como defender a verdade com amor?", "Batalhar pela fe", ["Abandonar toda doutrina", "Seguir qualquer ensino", "Confiar em falsos mestres"], "Judas 1:3"),
                  S("Que tipo de sabedoria Tiago descreve como do alto?", "Qual fruto ela produz?", "Onde voce precisa dessa sabedoria?", "Pura, pacifica e cheia de misericordia", ["Invejosa e egoista", "Violenta e arrogante", "Astuta para o mal"], "Tiago 3:17"),
              ]),
            M("cg-boss", "Revisao: Cartas Gerais", "Guarde os temas principais",
              "Revise a identidade do povo de Deus e a fe que se torna visivel em uma vida santa.",
              None,
              [
                  S("Por que essas cartas sao chamadas gerais?", "Que alcance elas tiveram?", "Como isso fortalece sua leitura?", "Porque servem amplamente a igrejas e crentes", ["Porque nao tem autores", "Porque nao falam de Jesus", "Porque foram escritas em grego"], "1 Pedro 1:1"),
                  S("Qual resposta correta a Palavra produz?", "O que nao basta fazer?", "Como praticar a Palavra nesta semana?", "Obediencia de fe", ["Apenas ouvir sermoes", "Decorar sem viver", "Discutir sem amar"], "Tiago 1:22"),
                  S("Que virtude acompanha a verdade em 1 Joao?", "Por que ela importa?", "Como demonstrar essa virtude?", "Amor", ["Inveja", "Indiferenca", "Engano"], "1 Joao 4:7"),
                  S("O que sustenta o crente em provacoes?", "Em quem esta essa esperanca?", "Que promessa o anima?", "A esperanca em Cristo", ["O acaso", "O dinheiro", "A aprovacao humana"], "1 Pedro 1:3"),
                  S("Como a igreja deve lidar com a fe recebida?", "Qual e a postura de Judas?", "Como unir firmeza e misericordia?", "Guardando e defendendo a fe", ["Mudando-a conforme a moda", "Escondendo-a por medo", "Trocando-a por mitos"], "Judas 1:3"),
              ], True),
        ],
    },
    "hebreus": {
        "module": {"title": "Hebreus", "icon": "crown", "section": "Novo Testamento"},
        "missions": [
            M("hb-01", "Maior que os anjos e Moises", "O Filho fala com autoridade",
              "Hebreus apresenta Jesus como o Filho eterno, superior aos anjos e fiel sobre a casa de Deus.",
              T("Hebreus 1:3-4", "Ele, que e o resplendor da gloria e a expressao exata do seu Ser... se tornou tao superior aos anjos.",
                "Os destinatarios eram tentados a recuar. O autor mostra que Deus falou decisivamente por meio do Filho, cuja gloria ultrapassa toda criatura.",
                "resplendor", "Manifestacao radiante da gloria de Deus no Filho.", "O que a grandeza de Jesus muda em sua confianca nele?",
                ["Que ideia voce tem de Jesus?", "Onde voce precisa ouvir sua voz?", "Como honrar Cristo acima de tudo?"]),
              [
                  S("Quem e a expressao exata do Ser de Deus?", "O que isso revela sobre Jesus?", "Como essa verdade fortalece sua fe?", "Jesus, o Filho", ["Miguel, o anjo", "Moises", "Abraao"], "Hebreus 1:3"),
                  S("Jesus e comparado a quem em Hebreus 1?", "Quem e superior?", "Por que devemos adorar somente Cristo?", "Aos anjos; Jesus e superior", ["Aos reis; os reis sao superiores", "Aos profetas; eles sao superiores", "Aos sacerdotes; eles sao superiores"], "Hebreus 1:4"),
                  S("Quem foi fiel como servo na casa de Deus?", "Quem e Filho sobre a casa?", "Como voce permanece firme nessa casa?", "Moises foi servo; Cristo e Filho", ["Cristo foi servo; Moises Filho", "Anjos foram filhos", "Ninguem foi fiel"], "Hebreus 3:5-6"),
                  S("Por que devemos prestar mais atencao ao que ouvimos?", "Qual risco o texto cita?", "Que pratica ajuda voce a nao se desviar?", "Para nao nos desviarmos", ["Para nos sentirmos melhores", "Para evitar servir", "Para esquecer o evangelho"], "Hebreus 2:1"),
                  S("Quem conduz muitos filhos a gloria?", "Como ele foi aperfeicoado?", "Como Jesus ajuda voce no sofrimento?", "Jesus, por meio dos sofrimentos", ["Um anjo, por riquezas", "Moises, por leis", "O povo, por esforco"], "Hebreus 2:10"),
              ]),
            M("hb-02", "Nosso grande sumo sacerdote", "Jesus se compadece e intercede",
              "Jesus e o sacerdote perfeito: conhece nossa fraqueza, venceu o pecado e abriu acesso confiante a Deus.",
              T("Hebreus 4:14-16", "Temos um grande sumo sacerdote... Jesus, o Filho de Deus... achemos graca para socorro em ocasiao oportuna.",
                "Diferente dos sacerdotes leviticos pecadores, Cristo entrou na presenca de Deus e intercede por seu povo. Ele foi tentado, mas sem pecado.",
                "sumo sacerdote", "Representante que se aproxima de Deus em favor do povo; Cristo o faz perfeitamente.", "Como a compaixao de Jesus muda sua maneira de orar?",
                ["Em que fraqueza voce precisa de socorro?", "Voce se aproxima de Deus com confianca?", "Por que Jesus e suficiente?"]),
              [
                  S("Quem e nosso grande sumo sacerdote?", "Por que ele e grande?", "Como voce pode se aproximar de Deus?", "Jesus, o Filho de Deus", ["Arao", "Moises", "Um anjo"], "Hebreus 4:14"),
                  S("Jesus foi tentado de que modo?", "Que diferenca ha entre ele e nos?", "Como isso consola voce?", "Em todas as coisas, mas sem pecado", ["Nunca foi tentado", "Pecou muitas vezes", "Precisou ser salvo"], "Hebreus 4:15"),
                  S("Do que precisamos nos aproximar com confianca?", "O que encontramos ali?", "Por qual necessidade voce orara?", "Do trono da graca", ["Do tribunal do medo", "Do altar de idolos", "Do poder humano"], "Hebreus 4:16"),
                  S("Segundo Hebreus 7, Jesus vive para que?", "Por quem ele intercede?", "Como agradecer por sua intercessao?", "Interceder pelos que se achegam a Deus", ["Condenar os crentes", "Servir aos anjos", "Criar novas leis"], "Hebreus 7:25"),
                  S("Por que Jesus nao precisa oferecer sacrificio por si?", "Qual e sua condicao moral?", "Como sua santidade da seguranca?", "Porque ele e santo e sem pecado", ["Porque nunca morreu", "Porque era apenas homem", "Porque ignorou a Lei"], "Hebreus 7:26-27"),
              ]),
            M("hb-03", "Uma alianca melhor", "O sacrificio perfeito",
              "A nova alianca foi estabelecida pelo sangue de Cristo. Seu sacrificio unico perdoa e purifica os que creem.",
              T("Hebreus 9:12", "Nao por meio de sangue de bodes e de bezerros, mas pelo seu proprio sangue, entrou no Santo dos Santos, uma vez por todas.",
                "Os sacrificios antigos apontavam para a necessidade de expiacao, mas nao removiam definitivamente o pecado. Jesus cumpriu o que eles prefiguravam.",
                "alianca", "Relacao estabelecida por Deus com seu povo, fundada em suas promessas e mediada por Cristo.", "Por que o sacrificio de Jesus basta de uma vez por todas?",
                ["O que voce tenta acrescentar a obra de Cristo?", "Como o perdao gera gratidao?", "Que pecado voce precisa confessar?"]),
              [
                  S("Com que sangue Cristo entrou no Santo dos Santos?", "Quantas vezes ele o fez?", "Como responder a esse sacrificio?", "Com seu proprio sangue, uma vez por todas", ["Com sangue de animais, todo ano", "Com prata, duas vezes", "Sem sacrificio algum"], "Hebreus 9:12"),
                  S("O que o sangue de Cristo purifica?", "Para que finalidade?", "Como servir a Deus hoje?", "A consciencia para servirmos ao Deus vivo", ["Somente o corpo para orgulho", "A memoria para pecar", "A Lei para acabar"], "Hebreus 9:14"),
                  S("O que Jesus fez por um unico sacrificio?", "Por quanto tempo?", "Onde voce encontra seguranca?", "Aperfeicoou para sempre os santificados", ["Aperfeicoou os anjos", "Eliminou toda luta", "Salvou sem fe"], "Hebreus 10:14"),
                  S("Como devemos nos achegar a Deus?", "Com que tipo de coracao?", "Que habito de oracao voce cultivara?", "Com coracao sincero e plena certeza de fe", ["Com fingimento", "Com desespero sem Cristo", "Com orgulho"], "Hebreus 10:22"),
                  S("O que nao devemos abandonar?", "Por que a comunhao importa?", "Como encorajar sua igreja?", "A congregacao dos santos", ["A leitura biblica", "O trabalho honesto", "A obediencia a Cristo"], "Hebreus 10:25"),
              ]),
            M("hb-04", "A fe que persevera", "Uma nuvem de testemunhas",
              "A fe biblica confia nas promessas de Deus e persevera olhando firmemente para Jesus.",
              T("Hebreus 12:1-2", "Corramos, com perseveranca, a carreira que nos esta proposta, olhando firmemente para Jesus, autor e consumador da fe.",
                "Depois de lembrar testemunhas da fe, o autor chama os crentes a deixar o pecado e correr com os olhos em Cristo, que sofreu a cruz.",
                "perseveranca", "Constancia paciente para continuar obedecendo a Deus.", "Que peso ou pecado voce precisa deixar para correr melhor?",
                ["Quem inspira sua fe?", "Onde seus olhos tem ficado?", "Como voce pode perseverar esta semana?"]),
              [
                  S("O que e fe segundo Hebreus 11?", "Em que ela se apoia?", "Qual promessa de Deus voce abraça?", "A certeza de coisas que se esperam", ["A negacao da realidade", "A confianca em si mesmo", "O medo do futuro"], "Hebreus 11:1"),
                  S("Para quem devemos olhar na corrida da fe?", "Que papel Jesus tem?", "Como fixar os olhos nele?", "Para Jesus, autor e consumador da fe", ["Para nossos erros", "Para as multidoes", "Para anjos"], "Hebreus 12:2"),
                  S("O que deve ser deixado de lado?", "Por que isso importa?", "Que peso voce pode abandonar?", "Todo peso e o pecado que nos envolve", ["A Palavra de Deus", "A comunhao", "A esperanca"], "Hebreus 12:1"),
                  S("Como Deus disciplina seus filhos?", "Qual objetivo dessa disciplina?", "Como responder a uma correcao?", "Como um Pai que busca nosso bem", ["Como inimigo sem amor", "Para nos destruir", "Porque esqueceu de nos"], "Hebreus 12:6,10"),
                  S("Que reino recebemos?", "Como devemos servir a Deus?", "Que gratidao voce expressara?", "Um reino inabalavel, com reverencia", ["Um reino passageiro", "Um reino de medo", "Um reino conquistado por obras"], "Hebreus 12:28"),
              ]),
            M("hb-boss", "Revisao: Hebreus", "Cristo e superior e suficiente",
              "Revise a supremacia de Cristo, seu sacerdocio perfeito, sua nova alianca e o chamado a perseverar.",
              None,
              [
                  S("Quem e superior aos anjos?", "Por que ele e superior?", "Como voce o adora?", "Jesus Cristo, o Filho", ["Moises", "Arao", "Gabriel"], "Hebreus 1:4"),
                  S("Quem e nosso sumo sacerdote sem pecado?", "O que ele faz por nos?", "Que pedido voce levara a ele?", "Jesus", ["Davi", "Joao Batista", "Paulo"], "Hebreus 4:15"),
                  S("Quantas vezes Cristo ofereceu seu sacrificio?", "Por que isso e suficiente?", "Como descansar nessa obra?", "Uma vez por todas", ["Todos os dias", "Uma vez por ano", "Somente no futuro"], "Hebreus 9:12"),
                  S("Para quem devemos olhar ao perseverar?", "Que carreira corremos?", "Que passo fiel voce dara?", "Para Jesus, na carreira da fe", ["Para o passado", "Para os anjos", "Para a aprovacao humana"], "Hebreus 12:1-2"),
                  S("Sem fe e impossivel o que?", "A quem a fe agrada?", "Como buscar a Deus?", "Agradar a Deus", ["Agradar ao mundo", "Evitar todo sofrimento", "Salvar-se por obras"], "Hebreus 11:6"),
              ], True),
        ],
    },
    "tiago": {
        "module": {"title": "Tiago", "icon": "hammer", "section": "Novo Testamento"},
        "missions": [
            M("tg-01", "Fe que trabalha", "A fe viva se torna visivel",
              "Tiago confronta uma fe de palavras vazias. A verdadeira fe em Cristo produz obediencia e misericordia.",
              T("Tiago 2:17", "Assim tambem a fe, se nao tiver obras, por si so esta morta.",
                "Tiago nao ensina que somos salvos por merecimento. Ele ensina que a fe salvadora, que recebe a Cristo, nunca permanece sem fruto.",
                "obras", "Acoes de obediencia que evidenciam uma fe viva.", "Que fruto sua fe tem produzido?",
                ["Voce confia em Cristo?", "Que necessidade alguem perto de voce tem?", "Como unir fe e obediencia?"]),
              [
                  S("Como e a fe sem obras?", "O que obras mostram?", "Que obra de amor voce praticara?", "Morta", ["Mais madura", "Suficiente por si", "Superior a obediencia"], "Tiago 2:17"),
                  S("As obras compram a salvacao?", "Em quem somos justificados?", "Como responder a graca?", "Nao; somos salvos pela graca de Deus em Cristo", ["Sim, por esforco perfeito", "Sim, por riqueza", "Nao existe salvacao"], "Efesios 2:8-10"),
                  S("Que exemplo Tiago usa de fe obediente?", "O que ele fez?", "Como voce pode confiar e obedecer?", "Abraao, que obedeceu a Deus", ["Farao, que resistiu", "Judas, que traiu", "Pilatos, que lavou as maos"], "Tiago 2:21-23"),
                  S("Como tratar um irmao necessitado?", "Que resposta e insuficiente?", "Que ajuda pratica voce pode oferecer?", "Com misericordia e ajuda concreta", ["Com palavras sem acao", "Com desprezo", "Com exploracao"], "Tiago 2:15-16"),
                  S("Qual lei Tiago chama de lei regia?", "Como ela se cumpre?", "Quem voce pode amar melhor?", "Amar o proximo como a si mesmo", ["Vencer o proximo", "Julgar o proximo", "Ignorar o proximo"], "Tiago 2:8"),
              ]),
            M("tg-02", "Palavras e sabedoria", "Domine a lingua",
              "A lingua revela o coracao. A sabedoria que vem do alto forma palavras verdadeiras, pacificas e humildes.",
              T("Tiago 3:17", "A sabedoria, porem, la do alto e, primeiramente, pura; depois, pacifica, indulgente, tratavel, plena de misericordia.",
                "Tiago contrasta a ambicao egoista com a sabedoria dada por Deus. Ela produz paz e frutos de justica.",
                "sabedoria", "Capacidade de viver segundo a vontade de Deus.", "Que suas palavras revelam sobre a fonte de sua sabedoria?",
                ["Quando voce fala sem pensar?", "Como pedir sabedoria a Deus?", "Que conflito precisa de paz?"]),
              [
                  S("O que a lingua pode fazer apesar de pequena?", "Que imagem Tiago usa?", "Como voce pode frear suas palavras?", "Pode dirigir e causar grande dano", ["Nao tem influencia", "So pode elogiar", "Controla o clima"], "Tiago 3:5-6"),
                  S("De onde vem a sabedoria pura e pacifica?", "Qual fruto ela produz?", "Como buscar essa sabedoria?", "Do alto, de Deus", ["Da inveja", "Do egoismo", "Da ambicao amarga"], "Tiago 3:17"),
                  S("O que nao deve sair da mesma boca?", "Por que isso e incoerente?", "Que fala voce deve corrigir?", "Bencao e maldicao", ["Oracao e leitura", "Verdade e amor", "Louvor e gratidao"], "Tiago 3:10"),
                  S("O que acompanha a inveja e ambicao egoista?", "Qual e o resultado?", "Como combater isso no coracao?", "Confusao e toda especie de coisas ruins", ["Paz duradoura", "Sabedoria divina", "Comunhao perfeita"], "Tiago 3:16"),
                  S("Como se semeia o fruto da justica?", "Quem o semeia?", "Que passo de paz voce dara?", "Em paz, pelos que promovem a paz", ["Em brigas, pelos orgulhosos", "Em segredo, pelos ricos", "Em medo, pelos fortes"], "Tiago 3:18"),
              ]),
            M("tg-03", "Oracao, pobres e paciencia", "Viva dependente de Deus",
              "Tiago chama a igreja a honrar os pobres, planejar com humildade, esperar o Senhor e orar em toda circunstancia.",
              T("Tiago 5:16", "Confessai, pois, os vossos pecados uns aos outros e orai uns pelos outros, para serdes curados.",
                "A vida cristã nao e independente. A comunidade ora, confessa, socorre os necessitados e aguarda a vinda do Senhor.",
                "paciencia", "Perseveranca que espera confiantemente a acao de Deus.", "Como voce pode depender mais de Deus e de sua igreja?",
                ["Por quem voce precisa orar?", "Como tratar os pobres com honra?", "Que plano voce deve submeter a Deus?"]),
              [
                  S("Como Deus escolheu muitos pobres aos olhos do mundo?", "Do que eles sao herdeiros?", "Como honrar pessoas sem favoritismo?", "Ricos em fe e herdeiros do reino", ["Sem valor para Deus", "Incapazes de crer", "Excluidos da igreja"], "Tiago 2:5"),
                  S("O que devemos dizer ao fazer planos?", "O que isso reconhece?", "Que plano voce entregara a Deus?", "Se o Senhor quiser", ["Eu controlo tudo", "Nada importa", "Nunca farei planos"], "Tiago 4:15"),
                  S("Como o lavrador espera o fruto?", "O que o crente deve fazer?", "Onde precisa de paciencia?", "Com paciencia", ["Com desespero", "Com violencia", "Com indiferenca"], "Tiago 5:7"),
                  S("O que o aflito deve fazer?", "E o que esta alegre?", "Como sua situacao pode virar oracao?", "Orar; cantar louvores", ["Reclamar; calar", "Pecar; esconder", "Desistir; isolar-se"], "Tiago 5:13"),
                  S("A oracao de quem pode muito?", "Por que isso nao exalta a pessoa?", "Como orar com fe?", "Do justo, em sua eficacia", ["Do rico somente", "Do famoso somente", "De quem nunca erra"], "Tiago 5:16"),
              ]),
            M("tg-boss", "Revisao: Tiago", "Uma fe inteira",
              "Revise a fe frutifera, o dominio da lingua e a dependencia de Deus em oracao.",
              None,
              [
                  S("Qual fe Tiago chama de morta?", "O que falta a ela?", "Como sua fe se mostra?", "A fe sem obras", ["A fe que ama", "A fe em Cristo", "A fe que ora"], "Tiago 2:17"),
                  S("De onde vem a sabedoria boa?", "Como ela e?", "Que palavra sua pode ser mais pacifica?", "Do alto; pura e pacifica", ["Da inveja; agressiva", "Do egoismo; amarga", "Do medo; vingativa"], "Tiago 3:17"),
                  S("Que poder a lingua tem?", "Por que devemos vigia-la?", "Como falar com graca?", "Pode causar grande dano", ["Nenhum poder", "Apenas poder fisico", "Poder de salvar por si"], "Tiago 3:5-6"),
                  S("Como devemos fazer nossos planos?", "Quem governa o futuro?", "Qual decisao voce submete ao Senhor?", "Reconhecendo a vontade do Senhor", ["Confiando no controle humano", "Sem pensar nunca", "Consultando horoscopos"], "Tiago 4:15"),
                  S("O que o aflito deve fazer?", "A quem ele se dirige?", "Por quem voce orara hoje?", "Orar a Deus", ["Buscar vinganca", "Se afastar da igreja", "Confiar em amuletos"], "Tiago 5:13"),
              ], True),
        ],
    },
    "pedro": {
        "module": {"title": "1 e 2 Pedro", "icon": "anchor", "section": "Novo Testamento"},
        "missions": [
            M("pd-01", "Esperanca viva", "Nascidos de novo para uma heranca",
              "Pedro escreve a crentes em sofrimento e os ancora na ressurreicao de Jesus e na heranca guardada por Deus.",
              T("1 Pedro 1:3", "Bendito o Deus e Pai... que, segundo a sua muita misericordia, nos regenerou para uma viva esperanca, mediante a ressurreicao de Jesus Cristo.",
                "A identidade cristã comeca na misericordia de Deus. A ressurreicao garante uma esperanca que o sofrimento presente nao pode destruir.",
                "regenerou", "Deu nova vida espiritual por sua misericordia.", "Como a ressurreicao de Jesus sustenta voce em tempos dificeis?",
                ["Que sofrimento desafia sua esperanca?", "Qual heranca Deus promete?", "Como viver em santidade hoje?"]),
              [
                  S("Para que Deus nos regenerou?", "Por meio de que evento?", "Como cultivar essa esperanca?", "Para uma viva esperanca, pela ressurreicao de Jesus", ["Para medo, pela Lei", "Para riqueza, por obras", "Para isolamento, por anjos"], "1 Pedro 1:3"),
                  S("Onde esta guardada a heranca dos crentes?", "Ela pode perecer?", "Como isso consola voce?", "Nos ceus; ela e imperecivel", ["Na terra; ela acaba", "No dinheiro; ela aumenta", "No templo; ela muda"], "1 Pedro 1:4"),
                  S("Como devemos colocar nossa esperanca?", "Em que graca?", "Que expectativa eterna voce tem?", "Inteiramente na graca de Jesus Cristo", ["No sucesso pessoal", "Na opiniao alheia", "Na sorte"], "1 Pedro 1:13"),
                  S("Qual chamado Pedro faz aos filhos de Deus?", "Em que area?", "Que habito santo voce adotara?", "Sede santos em todo procedimento", ["Sede perfeitos por si", "Sede iguais ao mundo", "Sede secretos"], "1 Pedro 1:15"),
                  S("Com que fomos resgatados?", "De que nao fomos resgatados?", "Como agradecer pelo resgate?", "Com o precioso sangue de Cristo", ["Com prata ou ouro", "Com boas obras", "Com sabedoria humana"], "1 Pedro 1:18-19"),
              ]),
            M("pd-02", "Sofrer seguindo Cristo", "Esperanca em meio a provacao",
              "Pedro nao romantiza o sofrimento, mas mostra que o crente pode fazer o bem, confiar em Deus e seguir os passos de Cristo.",
              T("1 Pedro 2:21", "Cristo sofreu em vosso lugar, deixando-vos exemplo para seguirdes os seus passos.",
                "Os crentes dispersos enfrentavam hostilidade. Pedro aponta para Cristo, que sofreu injustamente sem revidar e entregou sua causa ao Pai justo.",
                "exemplo", "Modelo deixado por Cristo para a vida de seus seguidores.", "Como seguir Jesus quando voce e tratado injustamente?",
                ["Que resposta Cristo nao deu?", "A quem ele entregou sua causa?", "Como fazer o bem sob pressao?"]),
              [
                  S("Quem deixou exemplo no sofrimento?", "Que passos seguimos?", "Como imitar Cristo hoje?", "Cristo", ["Pedro", "Cesar", "Um anjo"], "1 Pedro 2:21"),
                  S("O que Cristo fez quando ultrajado?", "A quem ele se entregou?", "Como evitar revidar?", "Nao revidou e confiou no justo Juiz", ["Ameacou com vinganca", "Fugiu da cruz", "Negou a verdade"], "1 Pedro 2:23"),
                  S("Para que Cristo levou nossos pecados?", "Como devemos viver?", "Que pecado voce quer abandonar?", "Para morrermos para o pecado e vivermos para a justica", ["Para continuarmos pecando", "Para evitar amar", "Para servir idolos"], "1 Pedro 2:24"),
                  S("O que fazer ao sofrer segundo a vontade de Deus?", "A quem entregar a alma?", "Que bem voce continuara fazendo?", "Confiar-se ao fiel Criador e continuar fazendo o bem", ["Abandonar a fe", "Buscar vinganca", "Ocultar Cristo"], "1 Pedro 4:19"),
                  S("Que atitude devemos ter diante da ansiedade?", "Por que podemos fazer isso?", "Que ansiedade voce entregara?", "Lancá-la sobre Deus, pois ele cuida de nos", ["Guardá-la sozinhos", "Negá-la sem orar", "Entregá-la a idolos"], "1 Pedro 5:7"),
              ]),
            M("pd-03", "O Dia do Senhor", "A promessa nao falha",
              "Em 2 Pedro, a certeza da volta de Cristo chama a igreja a rejeitar falsos ensinos e viver em santidade.",
              T("2 Pedro 3:9", "Nao retarda o Senhor a sua promessa... mas e longanimo para convosco, nao querendo que nenhum pereca.",
                "Alguns zombavam da promessa da volta de Cristo. Pedro responde que Deus e fiel e paciente, e seu Dia vira.",
                "longanimo", "Paciente e tardio em irar-se, dando oportunidade de arrependimento.", "Como a paciencia de Deus deve moldar sua vida e sua missao?",
                ["Por que Deus parece demorar?", "Como viver aguardando o Dia?", "Quem precisa ouvir o evangelho?"]),
              [
                  S("O Senhor retarda sua promessa?", "O que ele demonstra?", "Como responder a sua paciencia?", "Nao; ele e longanimo", ["Sim; ele esqueceu", "Sim; ele perdeu poder", "Nao existe promessa"], "2 Pedro 3:9"),
                  S("Como vira o Dia do Senhor?", "Que imagem Pedro usa?", "Como viver preparado?", "Como ladrao", ["Com aviso de jornais", "Somente para os maus", "Sem consequencias"], "2 Pedro 3:10"),
                  S("Que tipo de pessoas devemos ser?", "Em que devemos viver?", "Que santidade praticar?", "Em santo procedimento e piedade", ["Em cinismo e medo", "Em luxo e orgulho", "Em negligencia"], "2 Pedro 3:11"),
                  S("O que aguardamos segundo a promessa?", "Quem habita nela?", "Como essa promessa anima voce?", "Novos ceus e nova terra, onde habita justica", ["Uma terra sem Deus", "Um reino de injustica", "A volta ao pecado"], "2 Pedro 3:13"),
                  S("Em que devemos crescer?", "De quem e a graca?", "Como voce crescera esta semana?", "Na graca e conhecimento de Jesus Cristo", ["No orgulho e poder", "No medo e duvida", "No isolamento"], "2 Pedro 3:18"),
              ]),
            M("pd-boss", "Revisao: Pedro", "Esperanca firme, vida santa",
              "Revise a nova vida, o sofrimento fiel e a espera ativa pela volta de Jesus.",
              None,
              [
                  S("Por que temos viva esperanca?", "Que fato a garante?", "Como essa esperanca muda seu dia?", "Pela ressurreicao de Jesus", ["Pela sorte", "Pelas riquezas", "Pelos anjos"], "1 Pedro 1:3"),
                  S("Como Cristo reagiu ao sofrimento injusto?", "Em quem confiou?", "Como voce pode fazer o bem?", "Nao revidou; confiou no justo Juiz", ["Buscou vinganca", "Negou a Deus", "Abandonou a cruz"], "1 Pedro 2:23"),
                  S("O que fazer com a ansiedade?", "Por que?", "Qual fardo voce entrega a Deus?", "Lancá-la sobre Deus, porque ele cuida de nos", ["Ocultá-la de Deus", "Transformá-la em ira", "Segui-la como guia"], "1 Pedro 5:7"),
                  S("Por que Deus e paciente?", "O que ele deseja?", "Como participar dessa missao?", "Para que pessoas se arrependam", ["Para que todos pequem", "Para cancelar sua promessa", "Para premiar zombadores"], "2 Pedro 3:9"),
                  S("O que aguardamos?", "Como viver enquanto esperamos?", "Que pratica de piedade voce fara?", "Novos ceus e nova terra; em santidade", ["O fim sem justica; em medo", "Riqueza eterna; em orgulho", "Anjos na terra; em silencio"], "2 Pedro 3:13"),
              ], True),
        ],
    },
    "cartas-joao": {
        "module": {"title": "Cartas de Joao", "icon": "heart", "section": "Novo Testamento"},
        "missions": [
            M("cj-01", "Luz e comunhao", "Ande na luz",
              "Joao anuncia a vida eterna revelada em Jesus e chama os crentes a andar na luz, confessando seus pecados.",
              T("1 Joao 1:7", "Se andarmos na luz, como ele esta na luz, temos comunhao uns com os outros, e o sangue de Jesus... nos purifica de todo pecado.",
                "A comunhao com Deus nao combina com esconder o pecado. A luz revela, e o sangue de Jesus purifica os que confessam.",
                "luz", "A santidade e a verdade de Deus, que expõem o pecado.", "O que significa andar na luz em vez de esconder seus pecados?",
                ["Que pecado voce precisa confessar?", "Como a luz fortalece a comunhao?", "Por que Jesus purifica?"]),
              [
                  S("Quem e luz?", "Que treva ha nele?", "Como refletir sua luz?", "Deus; nele nao ha treva nenhuma", ["Deus; ele tem pouca treva", "Os anjos; eles sao luz", "O homem; nele nao ha pecado"], "1 Joao 1:5"),
                  S("O que acontece se andamos na luz?", "Com quem temos comunhao?", "Como buscar comunhao sincera?", "Temos comunhao e somos purificados pelo sangue de Jesus", ["Ficamos sem pecado por nos mesmos", "Nao precisamos da igreja", "Podemos esconder o pecado"], "1 Joao 1:7"),
                  S("O que devemos fazer com nossos pecados?", "Como Deus responde?", "Que confissao voce precisa fazer?", "Confessá-los; ele perdoa e purifica", ["Negá-los; ele aprova", "Justificá-los; ele esquece", "Culpabilizar outros; ele pune"], "1 Joao 1:9"),
                  S("Quem e nosso Advogado junto ao Pai?", "Por quem ele propicia?", "Como essa verdade consola?", "Jesus Cristo, o Justo", ["Joao", "Um sacerdote humano", "Um anjo"], "1 Joao 2:1-2"),
                  S("Como sabemos que conhecemos a Deus?", "O que guardamos?", "Que mandamento voce obedecera?", "Guardando seus mandamentos", ["Ignorando sua Palavra", "Buscando sinais apenas", "Julgando os outros"], "1 Joao 2:3"),
              ]),
            M("cj-02", "Amor e verdade", "Permaneça em Cristo",
              "Joao ensina que o amor procede de Deus e que a igreja deve discernir falsos ensinos sobre Jesus Cristo.",
              T("1 Joao 4:7-8", "Amados, amemo-nos uns aos outros, porque o amor procede de Deus... Deus e amor.",
                "O amor cristao nasce do Deus que enviou seu Filho como propiciacao. Ao mesmo tempo, a igreja deve provar os espiritos e confessar o Cristo encarnado.",
                "propiciacao", "Sacrificio de Cristo que trata justamente o pecado e manifesta o amor de Deus.", "Como amor e verdade devem caminhar juntos em sua vida?",
                ["Quem Deus chama voce a amar?", "Que verdade sobre Jesus e essencial?", "Como discernir um ensino?"]),
              [
                  S("De onde procede o amor cristao?", "O que amar revela?", "Como amar de modo concreto?", "De Deus", ["Do medo", "Da autopromocao", "Da riqueza"], "1 Joao 4:7"),
                  S("Como Deus mostrou seu amor?", "Quem ele enviou?", "Como responder a esse amor?", "Enviando seu Filho como propiciacao pelos pecados", ["Enviando uma filosofia", "Enviando ouro", "Enviando apenas regras"], "1 Joao 4:10"),
                  S("O que devemos fazer com os espiritos?", "Por que?", "Como testar um ensino?", "Prová-los, porque ha falsos profetas", ["Aceitar todos", "Temê-los sem discernir", "Adorá-los"], "1 Joao 4:1"),
                  S("Que verdade sobre Jesus o espirito de Deus confessa?", "Por que isso importa?", "Como proteger essa confissao?", "Que Jesus Cristo veio em carne", ["Que Jesus era so ideia", "Que Jesus nao veio", "Que Jesus foi apenas anjo"], "1 Joao 4:2"),
                  S("O perfeito amor lança fora o que?", "Por que o medo e vencido?", "Onde voce precisa descansar no amor de Deus?", "O medo", ["A fe", "A obediencia", "A esperanca"], "1 Joao 4:18"),
              ]),
            M("cj-03", "Verdade que recebe e envia", "2 e 3 Joao",
              "As cartas curtas de Joao unem amor e verdade: acolher cooperadores fieis e rejeitar quem promove mentira e orgulho.",
              T("3 Joao 1:8", "Devemos, pois, acolher esses irmaos, para nos tornarmos cooperadores da verdade.",
                "2 Joao alerta contra apoiar falsos mestres. 3 Joao elogia Gaio por hospedar missionarios e repreende a ambicao de Diotrefes.",
                "cooperadores", "Pessoas que participam da obra do evangelho ao apoiar seus servos fieis.", "Como voce pode cooperar com a verdade sem apoiar o erro?",
                ["Quem voce pode encorajar?", "Como discernir hospitalidade?", "Que orgulho precisa ser rejeitado?"]),
              [
                  S("Em que Joao diz que devemos andar?", "Que mandamento isso inclui?", "Como andar na verdade hoje?", "Na verdade e no amor", ["No engano e no medo", "Na tradicao sem Cristo", "Na fama"], "2 Joao 1:4-6"),
                  S("O que 2 Joao alerta sobre muitos enganadores?", "Que verdade eles negam?", "Como guardar a doutrina de Cristo?", "Eles negam que Jesus Cristo veio em carne", ["Eles ensinam amor cristao", "Eles pregam arrependimento", "Eles honram os apostolos"], "2 Joao 1:7"),
                  S("Quem foi elogiado por receber os irmaos?", "Que tipo de obra ele apoiou?", "Como praticar hospitalidade fiel?", "Gaio; a obra da verdade", ["Diotrefes; a propria gloria", "Pilatos; a politica", "Herodes; o poder"], "3 Joao 1:5-8"),
                  S("Qual pecado de Diotrefes e destacado?", "Como ele tratava os irmaos?", "Como cultivar humildade?", "Queria ter a primazia", ["Queria servir em silencio", "Amava a verdade", "Apoiava missionarios"], "3 Joao 1:9-10"),
                  S("A quem devemos imitar?", "Qual principio Joao apresenta?", "Que bem voce imitara?", "O bem; quem faz o bem procede de Deus", ["O mal; ele e necessario", "Os enganadores", "O orgulho"], "3 Joao 1:11"),
              ]),
            M("cj-boss", "Revisao: Cartas de Joao", "Ande na luz e no amor",
              "Revise a comunhao na luz, o amor que vem de Deus e a firmeza na verdade de Cristo.",
              None,
              [
                  S("O que o sangue de Jesus faz?", "Quando a comunhao floresce?", "Que pecado voce confessara?", "Purifica de todo pecado quando andamos na luz", ["Oculta o pecado", "Premia o pecado", "Elimina a necessidade de confessar"], "1 Joao 1:7"),
                  S("Como Deus trata quem confessa pecados?", "Que duas acoes ele faz?", "Como voce respondera?", "Perdoa e purifica", ["Ignora e abandona", "Aprova e esconde", "Condena sem esperanca"], "1 Joao 1:9"),
                  S("De onde vem o amor?", "Como Deus o demonstrou?", "Quem voce amara?", "De Deus; enviando seu Filho", ["Do mundo; buscando fama", "Do medo; evitando pessoas", "Da Lei; sem Cristo"], "1 Joao 4:7-10"),
                  S("Que ensino sobre Jesus deve ser confessado?", "Contra que erro isso protege?", "Como voce guardara essa verdade?", "Que Jesus Cristo veio em carne", ["Que ele foi apenas homem comum", "Que ele nunca existiu", "Que ele era um anjo criado"], "1 Joao 4:2"),
                  S("Como apoiar a verdade em 3 Joao?", "Quem e cooperador da verdade?", "Como apoiar uma obra fiel?", "Acolhendo e sustentando servos fieis", ["Promovendo falsos mestres", "Buscando primazia", "Recusando toda comunhao"], "3 Joao 1:8"),
              ], True),
        ],
    },
    "judas": {
        "module": {"title": "Judas", "icon": "shield", "section": "Novo Testamento"},
        "missions": [
            M("jd-01", "Batalhe pela fe", "Vigie contra o engano",
              "Judas chama os crentes a permanecer na fe apostolica diante de pessoas que distorcem a graca para justificar pecado.",
              T("Judas 1:3", "Senti a necessidade de vos escrever, exortando-vos a batalhardes diligentemente pela fe que uma vez por todas foi entregue aos santos.",
                "A fe cristã nao e inventada por cada geracao. Ela foi entregue pelos apostolos e deve ser guardada com firmeza e amor.",
                "batalhardes", "Defender com empenho a verdade do evangelho.", "Como voce pode defender a fe sem se tornar agressivo ou orgulhoso?",
                ["Que verdade do evangelho voce precisa conhecer?", "Onde ha engano?", "Como falar a verdade em amor?"]),
              [
                  S("Pelo que Judas manda batalhar?", "A quem essa fe foi entregue?", "Como voce crescera no conhecimento dela?", "Pela fe entregue aos santos", ["Pela fama religiosa", "Pelas tradicoes humanas", "Pelo poder politico"], "Judas 1:3"),
                  S("O que alguns impios faziam com a graca?", "Que atitude isso revela?", "Como a graca ensina santidade?", "Transformavam-na em libertinagem", ["Usavam-na para servir", "Guardavam-na com amor", "Ensinavam arrependimento"], "Judas 1:4"),
                  S("Judas chama os crentes a lembrar de que?", "Por que lembrar importa?", "Que ensino biblico voce recordara?", "Das palavras dos apostolos", ["Dos boatos", "Dos sonhos pessoais", "Das modas"], "Judas 1:17"),
                  S("Quem causa divisoes segundo Judas?", "O que lhes falta?", "Como promover unidade verdadeira?", "Pessoas mundanas, sem o Espirito", ["Os que amam a verdade", "Os que oram", "Os que servem"], "Judas 1:19"),
                  S("Como os crentes devem edificar-se?", "Em que devem orar?", "Que pratica fortalece sua fe?", "Na santissima fe, orando no Espirito Santo", ["No orgulho, sem orar", "No medo, sem Biblia", "Na riqueza, sem igreja"], "Judas 1:20"),
              ]),
            M("jd-02", "Guardados no amor de Deus", "Misericordia e perseveranca",
              "A defesa da fe e feita com dependencia de Deus: orar, permanecer em seu amor, ter misericordia e esperar a vida eterna.",
              T("Judas 1:21", "Guardai-vos no amor de Deus, esperando a misericordia de nosso Senhor Jesus Cristo para a vida eterna.",
                "Judas equilibra responsabilidade e seguranca. Os crentes permanecem no amor de Deus, ajudam os que duvidam e confiam no Deus que pode guardá-los.",
                "misericordia", "Compaixao ativa para com quem necessita da graca de Deus.", "Como voce pode mostrar misericordia sem relativizar o pecado?",
                ["Quem precisa de sua ajuda?", "Como esperar a vida eterna?", "O que significa permanecer no amor de Deus?"]),
              [
                  S("Em que devemos nos guardar?", "O que esperamos de Jesus?", "Como permanecer no amor de Deus?", "No amor de Deus; sua misericordia para a vida eterna", ["No medo; castigo eterno", "Na fama; reconhecimento", "No pecado; liberdade"], "Judas 1:21"),
                  S("Como tratar alguns que estao na duvida?", "Que postura isso exige?", "Quem voce pode ouvir com paciencia?", "Com misericordia", ["Com desprezo", "Com zombaria", "Com isolamento"], "Judas 1:22"),
                  S("Como salvar outros?", "De que imagem Judas fala?", "Como advertir com amor?", "Arrebatando-os do fogo", ["Aprovando seu erro", "Ignorando seu perigo", "Condenando sem compaixao"], "Judas 1:23"),
                  S("Quem e poderoso para nos guardar de tropecar?", "Diante de quem ele nos apresenta?", "Como essa verdade gera confianca?", "Deus", ["Nosso proprio esforco", "Um anjo", "Nossa reputacao"], "Judas 1:24"),
                  S("A quem pertencem gloria e dominio?", "Por meio de quem?", "Como voce dara gloria a Deus?", "Ao unico Deus, nosso Salvador, por Jesus Cristo", ["Ao ser humano", "Aos falsos mestres", "Aos poderes deste mundo"], "Judas 1:25"),
              ]),
            M("jd-boss", "Revisao: Judas", "Firmeza com misericordia",
              "Revise o chamado para guardar a fe apostolica, permanecer no amor de Deus e socorrer pessoas com discernimento.",
              None,
              [
                  S("O que a igreja deve defender?", "De onde vem essa fe?", "Como voce a estudara?", "A fe entregue aos santos", ["A opiniao popular", "O engano religioso", "A liberdade para pecar"], "Judas 1:3"),
                  S("O que falsos mestres fazem com a graca?", "Por que isso e grave?", "Como a graca muda sua vida?", "Transformam-na em libertinagem", ["Transformam-na em santidade", "Pregam Cristo fielmente", "Servem aos necessitados"], "Judas 1:4"),
                  S("Como devemos tratar quem duvida?", "Qual virtude guia isso?", "Como voce demonstrara essa virtude?", "Com misericordia", ["Com dureza sem amor", "Com indiferença", "Com mentira"], "Judas 1:22"),
                  S("Em que devemos nos guardar?", "O que esperamos?", "Como permanecer nessa esperanca?", "No amor de Deus, esperando a misericordia de Jesus", ["No pecado, esperando sucesso", "No medo, esperando castigo", "Na fama, esperando aplauso"], "Judas 1:21"),
                  S("Quem pode nos guardar de tropecar?", "Qual resposta isso merece?", "Como voce confiara nele?", "Deus, nosso Salvador", ["Nossa forca", "Nossos lideres", "Nossa riqueza"], "Judas 1:24-25"),
              ], True),
        ],
    },
}
