#!/usr/bin/env python3
"""Dados para densificar Atos (~10) e Apocalipse (~8) no caminho Criação→NT."""

# Cada missão: slug, title, subtitle, intro, optional boss, study, seeds (5)
# seeds: verse, answer, wrong[3], q_s, q_c, q_p

ATOS = {
    "slug": "atos",
    "title": "Atos dos Apóstolos",
    "description": "Do Espírito em Jerusalém até o testemunho nos confins da terra.",
    "unlockAfter": "evangelhos",
    "modules": [
        {
            "title": "Jerusalém",
            "icon": "🔥",
            "section": "jerusalem",
            "missions": [
                {
                    "slug": "ato-01-ascensao",
                    "title": "A ascensão",
                    "subtitle": "Atos 1:1–11",
                    "intro": "Jesus sobe aos céus e promete o Espírito. A missão começa com espera obediente — não com pressa humana.",
                    "study": {
                        "passageRef": "Atos 1:8",
                        "passageText": "Mas recebereis poder, ao descer sobre vós o Espírito Santo, e ser-me-eis testemunhas tanto em Jerusalém como em toda a Judeia e Samaria e até aos confins da terra.",
                        "context": "Atos abre como continuidade do Evangelho: o Cristo ressuscitado prepara a igreja. A ascensão não é ausência — é entronização. O mapa da missão (Jerusalém → Judeia/Samaria → confins) organiza o livro inteiro. Antes do poder, há obediência: esperar a promessa do Pai.",
                        "keyword": "Testemunhas",
                        "keywordGloss": "Pessoas que apontam para Jesus com vida e palavra — capacitadas pelo Espírito.",
                        "focusQuestion": "Onde começa o meu testemunho — e até onde estou disposto a ir?",
                        "reflectionPrompts": [
                            "Esperar o Espírito antes de agir",
                            "Missão com mapa, não impulso",
                            "Cristo reinando no céu",
                        ],
                        "relatedVerses": [
                            {"reference": "Lucas 24:49", "reason": "Ficai na cidade até que do alto sejais revestidos de poder."},
                            {"reference": "Mateus 28:18–20", "reason": "A grande comissão ecoa o mapa de Atos 1:8."},
                            {"reference": "Salmo 110:1", "reason": "O Senhor entronizado — pano de fundo da ascensão."},
                        ],
                    },
                    "seeds": [
                        {"verse": "Atos 1:8", "answer": "Receber poder do Espírito e ser testemunhas", "wrong": ["Conquistar Roma pela força", "Abandonar Jerusalém imediatamente", "Esconder a fé"], "q_s": "O que Jesus promete antes de subir?", "q_c": "Qual é o alcance geográfico da missão em Atos 1:8?", "q_p": "Por que a ascensão não cancela a missão, mas a fundamenta?"},
                        {"verse": "Atos 1:4–5", "answer": "Esperar a promessa do Pai / batismo no Espírito", "wrong": ["Partir no mesmo dia sem oração", "Eleger um rei terreno", "Construir um templo novo"], "q_s": "O que os discípulos devem fazer antes de sair?", "q_c": "Qual promessa eles devem aguardar?", "q_p": "Como a espera obediente contradiz ativismo sem Deus?"},
                        {"verse": "Atos 1:9–11", "answer": "Jesus foi elevado e voltará do mesmo modo", "wrong": ["Jesus desapareceu para sempre", "Os anjos cancelaram a missão", "A nuvem significava juízo imediato"], "q_s": "O que acontece na ascensão?", "q_c": "Que esperança os anjos anunciam?", "q_p": "Como a volta de Cristo motiva testemunho agora?"},
                        {"verse": "Atos 1:8", "answer": "Jerusalém, Judeia e Samaria, confins da terra", "wrong": ["Só Jerusalém", "Só entre judeus", "Só após a volta de Cristo"], "q_s": "Qual a ordem do testemunho?", "q_c": "Por que Samaria entra no mapa?", "q_p": "O que o mapa revela sobre o coração missionário de Deus?"},
                        {"verse": "Atos 1:3", "answer": "Jesus deu muitas provas da ressurreição", "wrong": ["Os discípulos inventaram a história", "Não houve aparições", "Só Pedro viu Jesus"], "q_s": "Atos enfatiza o quê sobre o Cristo ressuscitado?", "q_c": "Por que as provas importam para a missão?", "q_p": "Como a ressurreição histórica sustenta o testemunho da igreja?"},
                    ],
                },
                {
                    "slug": "ato-02-pentecostes",
                    "title": "Pentecostes",
                    "subtitle": "Atos 2:1–41",
                    "intro": "O Espírito é derramado. Línguas, ousadia e o primeiro sermão público: Jesus é Senhor e Cristo.",
                    "study": {
                        "passageRef": "Atos 2:32–36",
                        "passageText": "A este Jesus Deus ressuscitou… Saiba, pois, com certeza… que a este Jesus, a quem vós crucificastes, Deus o fez Senhor e Cristo.",
                        "context": "Pentecostes cumpre a promessa e reverte Babel: povos ouvem as grandezas de Deus. Pedro interpreta a Escritura (Joel, Salmos) e centra tudo em Jesus. O resultado não é espetáculo vazio — é arrependimento, batismo e cerca de três mil adicionados. Poder do Espírito serve ao anúncio de Cristo.",
                        "keyword": "Espírito Santo",
                        "keywordGloss": "Presença de Deus que capacita a igreja a falar e viver o evangelho.",
                        "focusQuestion": "Minha busca de “poder” aponta para Cristo — ou para experiência sem cruz?",
                        "reflectionPrompts": [
                            "Ousadia no anúncio",
                            "Jesus é Senhor e Cristo",
                            "Arrependimento que gera igreja",
                        ],
                        "relatedVerses": [
                            {"reference": "Joel 2:28–32", "reason": "Pedro cita a promessa do derramamento do Espírito."},
                            {"reference": "Gênesis 11:7–9", "reason": "Babel espalhou em confusão; Pentecostes une na compreensão."},
                            {"reference": "1 Coríntios 12:3", "reason": "Ninguém pode dizer “Jesus é Senhor” senão pelo Espírito."},
                        ],
                    },
                    "seeds": [
                        {"verse": "Atos 2:4", "answer": "Ficaram cheios do Espírito Santo", "wrong": ["Fugiram de Jerusalém", "Elegeram um imperador", "Calaram-se por medo"], "q_s": "O que acontece em Pentecostes?", "q_c": "Qual o sinal principal descrito?", "q_p": "Como o enchimento do Espírito se liga à missão pública?"},
                        {"verse": "Atos 2:36", "answer": "Deus o fez Senhor e Cristo", "wrong": ["Jesus foi apenas um profeta", "Roma o reabilitou", "Os anjos o coroaram sem a cruz"], "q_s": "Qual a conclusão do sermão de Pedro?", "q_c": "O que significa chamar Jesus de Senhor e Cristo?", "q_p": "Por que a cruz e a ressurreição são o centro do anúncio?"},
                        {"verse": "Atos 2:37–38", "answer": "Arrependei-vos e cada um seja batizado", "wrong": ["Apenas admirem o milagre", "Comprem indulgências", "Voltem ao silêncio"], "q_s": "Qual a resposta pedida à multidão?", "q_c": "O que acompanha o arrependimento?", "q_p": "Como perdão e dom do Espírito se relacionam no chamado?"},
                        {"verse": "Atos 2:21", "answer": "Todo aquele que invocar o nome do Senhor será salvo", "wrong": ["Só a elite religiosa", "Só quem fala línguas", "Só judeus de Jerusalém"], "q_s": "Que promessa de Joel Pedro destaca?", "q_c": "Quem pode ser salvo?", "q_p": "Como Pentecostes antecipa a inclusão das nações?"},
                        {"verse": "Atos 2:41", "answer": "Cerca de três mil pessoas foram adicionadas", "wrong": ["Ninguém creu", "Apenas os doze", "A multidão linchou Pedro"], "q_s": "Qual o fruto numérico do dia?", "q_c": "O que isso mostra sobre a palavra pregada?", "q_p": "Como crescimento autêntico nasce de Cristo proclamado?"},
                    ],
                },
                {
                    "slug": "ato-03-comunhao",
                    "title": "A vida da comunidade",
                    "subtitle": "Atos 2:42–47",
                    "intro": "Ensino, comunhão, pão e orações — a missão flui de uma igreja que aprende e partilha a vida.",
                    "study": {
                        "passageRef": "Atos 2:42",
                        "passageText": "E perseveravam na doutrina dos apóstolos, e na comunhão, e no partir do pão, e nas orações.",
                        "context": "Após o milagre numérico, Lucas mostra o milagre comunitário: perseverança em quatro pilares. A igreja não é só evento de Pentecostes; é ritmo de formação, partilha, mesa e oração. Generosidade e louvor acompanham o favor do povo e o crescimento diário. Missão sem comunhão vira ativismo; comunhão sem doutrina vira clube.",
                        "keyword": "Comunhão",
                        "keywordGloss": "Vida compartilhada em Cristo — ensino, mesa, oração e bens em generosidade.",
                        "focusQuestion": "Qual dos quatro pilares (doutrina, comunhão, pão, oração) está mais fraco em você?",
                        "reflectionPrompts": [
                            "Perseverar juntos",
                            "Generosidade que testemunha",
                            "Formação + missão",
                        ],
                        "relatedVerses": [
                            {"reference": "Hebreus 10:24–25", "reason": "Não deixemos de congregar — estimular ao amor."},
                            {"reference": "1 João 1:3", "reason": "Comunhão uns com os outros e com o Pai e o Filho."},
                            {"reference": "Atos 4:32–35", "reason": "Unidade e partilha continuam no livro."},
                        ],
                    },
                    "seeds": [
                        {"verse": "Atos 2:42", "answer": "Doutrina, comunhão, partir do pão e orações", "wrong": ["Só louvor emocional", "Só obras sociais", "Só hierarquia romana"], "q_s": "Em que a igreja perseverava?", "q_c": "Por que os quatro pilares importam juntos?", "q_p": "O que acontece quando um pilar é abandonado?"},
                        {"verse": "Atos 2:44–45", "answer": "Partilhavam conforme a necessidade", "wrong": ["Guardavam tudo em segredo", "Exigiam pobreza obrigatória", "Ignoravam os necessitados"], "q_s": "Como tratavam os bens?", "q_c": "Qual o critério da partilha?", "q_p": "Como generosidade difere de coerção?"},
                        {"verse": "Atos 2:46–47", "answer": "Louvor, favor do povo e crescimento diário", "wrong": ["Isolamento total", "Revolta armada", "Fim da missão"], "q_s": "Qual o clima da comunidade?", "q_c": "O que o Senhor acrescentava?", "q_p": "Como testemunho comunitário atrai e confronta?"},
                        {"verse": "Atos 2:42", "answer": "Doutrina dos apóstolos", "wrong": ["Opiniões particulares sem raiz", "Filosofia grega pura", "Tradições sem Cristo"], "q_s": "Qual o conteúdo do ensino?", "q_c": "Por que a doutrina apostólica é base?", "q_p": "Como isso protege a igreja de deriva?"},
                        {"verse": "Atos 2:43", "answer": "Muitos prodígios e sinais pelos apóstolos", "wrong": ["Nenhum sinal", "Sinais sem mensagem", "Medo que impediu a fé"], "q_s": "O que acompanhava a vida da igreja?", "q_c": "Qual o lugar dos sinais?", "q_p": "Sinais servem a quê, segundo o relato?"},
                    ],
                },
                {
                    "slug": "ato-04-estevao",
                    "title": "Estêvão e a pressão",
                    "subtitle": "Atos 6–7",
                    "intro": "Serviço, sabedoria e martírio: a igreja aprende que o evangelho custa — e avança sob pressão.",
                    "study": {
                        "passageRef": "Atos 7:55–60",
                        "passageText": "Mas Estêvão, cheio do Espírito Santo… disse: Eis que vejo os céus abertos e o Filho do Homem… E apedrejavam Estêvão, que invocava e dizia: Senhor Jesus, recebe o meu espírito!",
                        "context": "Estêvão, escolhido para servir mesas, torna-se testemunha poderosa. Seu discurso relê a história de Israel e denuncia resistência ao Espírito. O martírio ecoa Jesus (perdão aos algozes) e introduz Saulo. A perseguição espalha a igreja — o mapa de 1:8 avança pelo sofrimento fiel.",
                        "keyword": "Martírio",
                        "keywordGloss": "Testemunho fiel até o custo extremo — não busca da morte, mas fidelidade sob fogo.",
                        "focusQuestion": "Estou disposto a permanecer fiel se o custo do evangelho subir?",
                        "reflectionPrompts": [
                            "Serviço e palavra andam juntos",
                            "Fidelidade sob pressão",
                            "Perdão no sofrimento",
                        ],
                        "relatedVerses": [
                            {"reference": "Lucas 23:34", "reason": "Estêvão ecoa o perdão de Jesus na cruz."},
                            {"reference": "Mateus 5:10–12", "reason": "Bem-aventurados os perseguidos por causa da justiça."},
                            {"reference": "Atos 8:1–4", "reason": "A perseguição espalha a palavra."},
                        ],
                    },
                    "seeds": [
                        {"verse": "Atos 6:3–5", "answer": "Homens cheios do Espírito e de sabedoria", "wrong": ["Só os mais ricos", "Só estrangeiros sem fé", "Só soldados"], "q_s": "Que critério guiou a escolha dos sete?", "q_c": "Por que caráter importa no serviço?", "q_p": "Como serviço prático e espiritualidade se unem?"},
                        {"verse": "Atos 6:10", "answer": "Não podiam resistir à sabedoria e ao Espírito", "wrong": ["Ele falava sem conteúdo", "Todos concordaram logo", "Ele recusou debater"], "q_s": "O que marcava o testemunho de Estêvão?", "q_c": "De onde vinha sua força?", "q_p": "Como o Espírito capacita em conflito?"},
                        {"verse": "Atos 7:51", "answer": "Resistis sempre ao Espírito Santo", "wrong": ["Israel sempre obedeceu", "O templo salva automaticamente", "A lei basta sem coração"], "q_s": "Qual a acusação central de Estêvão?", "q_c": "O que significa resistir ao Espírito?", "q_p": "Como religião sem obediência aparece hoje?"},
                        {"verse": "Atos 7:59–60", "answer": "Entrega o espírito e pede perdão aos algozes", "wrong": ["Amaldiçoa os inimigos", "Nega a Jesus", "Foge em silêncio"], "q_s": "Como Estêvão morre?", "q_c": "Que semelhança há com Jesus?", "q_p": "Por que o perdão no martírio é testemunho?"},
                        {"verse": "Atos 8:1", "answer": "Levantou-se grande perseguição; Saulo consentia", "wrong": ["A igreja ficou mais confortável", "Roma protegeu os cristãos", "Pedro cancelou a missão"], "q_s": "O que segue a morte de Estêvão?", "q_c": "Quem aparece no relato?", "q_p": "Como Deus usa perseguição no plano de Atos?"},
                    ],
                },
                {
                    "slug": "ato-boss-01",
                    "title": "Desafio: Jerusalém",
                    "subtitle": "Atos 1–7",
                    "intro": "Revise o nascimento da igreja: promessa, Espírito, comunhão e fidelidade sob fogo.",
                    "boss": True,
                    "seeds": [
                        {"verse": "Atos 1:8", "answer": "Espírito + testemunho até os confins", "wrong": ["Só milagres sem missão", "Só política", "Só isolamento"], "q_s": "Qual o programa de Atos 1:8?", "q_c": "O que capacita o testemunho?", "q_p": "Como os caps. 1–7 começam esse mapa?"},
                        {"verse": "Atos 2:36", "answer": "Jesus é Senhor e Cristo", "wrong": ["Jesus é só mestre moral", "César é Senhor", "A lei substitui Cristo"], "q_s": "Qual a confissão de Pentecostes?", "q_c": "Por que isso confronta poderes?", "q_p": "Como essa confissão molda a igreja?"},
                        {"verse": "Atos 2:42", "answer": "Quatro pilares da comunhão", "wrong": ["Apenas números", "Apenas emoção", "Apenas prédios"], "q_s": "O que sustenta a vida comunitária?", "q_c": "Por que perseverança importa?", "q_p": "Como formar comunidade missionária hoje?"},
                        {"verse": "Atos 7:55–60", "answer": "Estêvão fiel até a morte", "wrong": ["Estêvão renegou", "Não houve custo", "A missão parou"], "q_s": "O que o martírio revela?", "q_c": "Qual o padrão de fidelidade?", "q_p": "Como sofrimento e avanço do evangelho se relacionam?"},
                        {"verse": "Atos 1–7", "answer": "Do Espírito em Jerusalém à pressão que espalha", "wrong": ["Fim da igreja", "Vitória política imediata", "Abandono da palavra"], "q_s": "Qual o arco de Jerusalém?", "q_c": "O que Deus faz sob oposição?", "q_p": "Que lição carregar para a próxima etapa?"},
                    ],
                },
            ],
        },
        {
            "title": "Até os confins",
            "icon": "🌍",
            "section": "confins",
            "missions": [
                {
                    "slug": "ato-05-saulo",
                    "title": "Saulo encontrado",
                    "subtitle": "Atos 9:1–22",
                    "intro": "O perseguidor encontra o Senhor. Graça interrompe violência e chama um vaso para as nações.",
                    "study": {
                        "passageRef": "Atos 9:15–16",
                        "passageText": "Este é para mim um vaso escolhido para levar o meu nome perante os gentios… eu lhe mostrarei quanto deve padecer pelo meu nome.",
                        "context": "No caminho de Damasco, Jesus identifica-se com a igreja perseguida (“por que me persegues?”). A conversão de Saulo não é só experiência — é vocação: levar o Nome aos gentios, reis e Israel, com sofrimento no caminho. Ananias aprende a acolher o inimigo transformado. O evangelho cria testemunhas improváveis.",
                        "keyword": "Conversão",
                        "keywordGloss": "Virada radical a Cristo — nova identidade, nova missão, novo senhorio.",
                        "focusQuestion": "Há alguém que considero “impossível” demais para a graça de Deus?",
                        "reflectionPrompts": [
                            "Graça alcança inimigos",
                            "Chamado com custo",
                            "Acolher o transformado",
                        ],
                        "relatedVerses": [
                            {"reference": "1 Timóteo 1:15–16", "reason": "Paulo: exemplo de quem alcançou misericórdia."},
                            {"reference": "Gálatas 1:15–16", "reason": "Deus revelou o Filho para que o anunciasse entre gentios."},
                            {"reference": "Filipenses 3:7–8", "reason": "Tudo como perda diante de conhecer Cristo."},
                        ],
                    },
                    "seeds": [
                        {"verse": "Atos 9:4–5", "answer": "Jesus se identifica com a igreja perseguida", "wrong": ["Jesus ignora a perseguição", "Saulo ouve um eco vazio", "Anjos condenam sem graça"], "q_s": "O que Jesus pergunta a Saulo?", "q_c": "O que significa “por que me persegues?”", "q_p": "Como Cristo se une ao Seu corpo?"},
                        {"verse": "Atos 9:15", "answer": "Vaso escolhido para gentios, reis e Israel", "wrong": ["Chamado só para ficar em silêncio", "Missão só em Jerusalém", "Abandonar o Nome"], "q_s": "Qual o chamado de Saulo?", "q_c": "Para quem ele deve levar o Nome?", "q_p": "Como eleição e missão se conectam?"},
                        {"verse": "Atos 9:16", "answer": "Padecer pelo Nome", "wrong": ["Vida sem custo", "Riqueza garantida", "Popularidade imediata"], "q_s": "O que Deus mostra sobre o caminho de Saulo?", "q_c": "Por que sofrimento entra no chamado?", "q_p": "Como isso corrige evangelho de conforto?"},
                        {"verse": "Atos 9:17–18", "answer": "Ananias impõe as mãos; Saulo recupera a vista e é batizado", "wrong": ["Ananias recusa para sempre", "Saulo permanece cego e longe", "Não há batismo"], "q_s": "Como Ananias participa?", "q_c": "O que marca a nova vida de Saulo?", "q_p": "Por que a igreja precisa acolher convertidos?"},
                        {"verse": "Atos 9:20–22", "answer": "Logo pregava Jesus como Filho de Deus", "wrong": ["Ficou anos em silêncio absoluto", "Negou a fé", "Voltou a perseguir"], "q_s": "O que Saulo faz em seguida?", "q_c": "Qual a mensagem central?", "q_p": "Como graça gera testemunho público?"},
                    ],
                },
                {
                    "slug": "ato-06-gentios",
                    "title": "Porta aos gentios",
                    "subtitle": "Atos 10–11",
                    "intro": "Cornélio e Pedro: o Espírito derruba barreiras. O evangelho não é propriedade de um povo.",
                    "study": {
                        "passageRef": "Atos 10:34–35",
                        "passageText": "Na verdade, reconheço que Deus não faz acepção de pessoas; pelo contrário, em qualquer nação… é aceitável.",
                        "context": "Pedro precisa de visão e do Espírito para cruzar a porta de um gentio. Cornélio já temia a Deus; agora ouve Cristo. O Espírito cai sobre gentios como em Pentecostes — o critério não é etnia, é fé no Senhor Jesus. A igreja em Jerusalém precisa reconhecer a obra de Deus. Inclusão não é moda: é cumprimento da promessa a Abraão.",
                        "keyword": "Sem acepção",
                        "keywordGloss": "Deus não privilegia etnia ou status — aceita quem o teme e pratica justiça em Cristo.",
                        "focusQuestion": "Que fronteira cultural ou social ainda trato como “impura” demais para o evangelho?",
                        "reflectionPrompts": [
                            "Deus corrige preconceito",
                            "Mesmo Espírito, mesmos frutos",
                            "Promessa para as nações",
                        ],
                        "relatedVerses": [
                            {"reference": "Gênesis 12:3", "reason": "Em ti serão benditas todas as famílias da terra."},
                            {"reference": "Efésios 2:14–16", "reason": "Cristo derrubou a parede de separação."},
                            {"reference": "Atos 15:8–9", "reason": "Deus não fez distinção, purificando pela fé."},
                        ],
                    },
                    "seeds": [
                        {"verse": "Atos 10:15", "answer": "Não chames comum ao que Deus purificou", "wrong": ["Mantenha todas as barreiras", "Ignore a visão", "Só judeus são limpos"], "q_s": "O que a visão ensina a Pedro?", "q_c": "Sobre o que fala a ordem divina?", "q_p": "Como isso prepara o encontro com Cornélio?"},
                        {"verse": "Atos 10:34–35", "answer": "Deus não faz acepção de pessoas", "wrong": ["Deus prefere só uma etnia", "Status compra favor", "Gentios estão excluídos"], "q_s": "O que Pedro reconhece?", "q_c": "Quem é aceitável a Deus?", "q_p": "Como isso redefine pureza e missão?"},
                        {"verse": "Atos 10:43", "answer": "Remissão de pecados pelo nome de Jesus", "wrong": ["Pela circuncisão só", "Pelo dinheiro", "Pela cidadania romana"], "q_s": "O que todos os profetas testemunham?", "q_c": "Como se recebe perdão?", "q_p": "Por que o Nome de Jesus é o centro?"},
                        {"verse": "Atos 10:44–45", "answer": "O Espírito cai sobre os gentios", "wrong": ["Nada acontece", "Só Pedro recebe o Espírito", "Os gentios são rejeitados"], "q_s": "O que surpreende os judeus crentes?", "q_c": "Qual o paralelo com Pentecostes?", "q_p": "Como o Espírito valida a inclusão?"},
                        {"verse": "Atos 11:17–18", "answer": "Deus deu aos gentios o arrependimento para a vida", "wrong": ["Jerusalém rejeita para sempre", "Pedro é silenciado", "A missão para"], "q_s": "Como a igreja responde?", "q_c": "O que eles glorificam?", "q_p": "Que mudança de mentalidade isso exige?"},
                    ],
                },
                {
                    "slug": "ato-07-missoes",
                    "title": "Missão desde Antioquia",
                    "subtitle": "Atos 13–14",
                    "intro": "A igreja jejuando envia. A palavra corre entre as nações — com oposição e alegria.",
                    "study": {
                        "passageRef": "Atos 13:2–3",
                        "passageText": "Disse o Espírito Santo: Separai-me, agora, Barnabé e Saulo… Então, jejuando, e orando, e impondo sobre eles as mãos, os despediram.",
                        "context": "Antioquia torna-se base missionária: diversidade, ensino e escuta do Espírito. Enviar não é abandono — é participação na missão de Deus. Na viagem, Paulo anuncia Cristo em sinagogas e entre gentios; há fruto e perseguição. A igreja aprende: o Espírito envia, a palavra salva, o sofrimento acompanha.",
                        "keyword": "Envio",
                        "keywordGloss": "Separar e sustentar pessoas para anunciar Cristo além das fronteiras locais.",
                        "focusQuestion": "Minha comunidade só recebe — ou também envia?",
                        "reflectionPrompts": [
                            "Jejuar e ouvir o Espírito",
                            "Enviar é missão da igreja",
                            "Fruto e oposição juntos",
                        ],
                        "relatedVerses": [
                            {"reference": "Mateus 9:37–38", "reason": "Rogai ao Senhor da seara que mande trabalhadores."},
                            {"reference": "Romanos 10:14–15", "reason": "Como pregarão se não forem enviados?"},
                            {"reference": "Atos 14:27", "reason": "Relatam como Deus abrira a porta da fé aos gentios."},
                        ],
                    },
                    "seeds": [
                        {"verse": "Atos 13:2–3", "answer": "O Espírito manda separar Barnabé e Saulo", "wrong": ["A igreja decide sem oração", "Eles vão por turismo", "Ninguém é enviado"], "q_s": "Quem inicia o envio?", "q_c": "Como a igreja responde?", "q_p": "Que padrão de envio vemos aqui?"},
                        {"verse": "Atos 13:38–39", "answer": "Perdão e justificação em Jesus", "wrong": ["Justificação só pela lei de Moisés", "Salvação por obras da cidade", "Sem necessidade de Cristo"], "q_s": "O que Paulo anuncia?", "q_c": "O que a lei não pôde fazer?", "q_p": "Como justificação pela fé liberta?"},
                        {"verse": "Atos 13:47", "answer": "Luz para os gentios / salvação até a extremidade", "wrong": ["Só Israel", "Só Antioquia", "Fim da missão"], "q_s": "Qual comissão Isaías reforça?", "q_c": "Até onde vai a salvação?", "q_p": "Como isso ecoa Atos 1:8?"},
                        {"verse": "Atos 14:22", "answer": "Pelo muito tribulação entrar no Reino", "wrong": ["Sem sofrimento algum", "Reino só político", "Desistir na oposição"], "q_s": "O que Paulo ensina aos discípulos?", "q_c": "Qual o tom realista da missão?", "q_p": "Como preparar crentes para custo?"},
                        {"verse": "Atos 14:27", "answer": "Deus abrira a porta da fé aos gentios", "wrong": ["Paulo abrira sozinho", "A porta estava fechada", "Não houve relato"], "q_s": "O que a igreja ouve no retorno?", "q_c": "Quem recebe a glória?", "q_p": "Como prestar contas missionárias com humildade?"},
                    ],
                },
                {
                    "slug": "ato-08-roma",
                    "title": "Até Roma",
                    "subtitle": "Atos 28:16–31",
                    "intro": "Preso, mas não calado. O evangelho chega ao coração do Império — sem impedimento.",
                    "study": {
                        "passageRef": "Atos 28:30–31",
                        "passageText": "Paulo… pregava o Reino de Deus e… o senhorio de Jesus Cristo… sem impedimento algum.",
                        "context": "O livro não termina com soltura triunfal, mas com testemunho sob custódia. Roma não é fim da história — é sinal de que o mapa de 1:8 avançou. Houve naufrágio, julgamento e rejeição parcial em Israel; ainda assim a palavra corre. Atos deixa a igreja com um modelo: circunstâncias não cancelam a pregação do Reino.",
                        "keyword": "Sem impedimento",
                        "keywordGloss": "A palavra de Deus não está presa — mesmo quando o mensageiro está.",
                        "focusQuestion": "Que “prisão” tenho usado como desculpa para calar o evangelho?",
                        "reflectionPrompts": [
                            "Palavra não acorrentada",
                            "Reino anunciado em Roma",
                            "Fidelidade até o fim do livro",
                        ],
                        "relatedVerses": [
                            {"reference": "2 Timóteo 2:9", "reason": "Sofro… mas a palavra de Deus não está algemada."},
                            {"reference": "Filipenses 1:12–13", "reason": "Prisão avançou o evangelho."},
                            {"reference": "Atos 1:8", "reason": "Os confins começam a aparecer no horizonte romano."},
                        ],
                    },
                    "seeds": [
                        {"verse": "Atos 28:31", "answer": "Pregava o Reino e a Jesus sem impedimento", "wrong": ["Parou de pregar", "Negou a fé em Roma", "Só falou de política"], "q_s": "O que Paulo faz em Roma?", "q_c": "Qual o tom final de Atos?", "q_p": "Por que “sem impedimento” é teológico?"},
                        {"verse": "Atos 28:23", "answer": "Explicava o Reino pela Lei e pelos Profetas", "wrong": ["Ignorava as Escrituras", "Só usava filosofia", "Recusou diálogo"], "q_s": "Como Paulo persuadia?", "q_c": "Qual o conteúdo?", "q_p": "Como AT aponta para Cristo?"},
                        {"verse": "Atos 28:24", "answer": "Alguns creram; outros rejeitaram", "wrong": ["Todos creram", "Ninguém ouviu", "A missão falhou"], "q_s": "Qual a resposta em Roma?", "q_c": "O que isso ensina sobre pregação?", "q_p": "Como lidar com rejeição parcial?"},
                        {"verse": "Atos 28:28", "answer": "A salvação de Deus é enviada aos gentios", "wrong": ["Gentios excluídos", "Só Roma é salva", "Fim do envio"], "q_s": "O que Paulo declara?", "q_c": "Para quem a salvação é enviada?", "q_p": "Como isso fecha o arco aos confins?"},
                        {"verse": "Atos 1:8–28:31", "answer": "Do Espírito em Jerusalém ao testemunho em Roma", "wrong": ["A missão nunca saiu de Jerusalém", "Roma silenciou o evangelho", "Atos nega a comissão"], "q_s": "Qual o arco do livro?", "q_c": "O que se cumpriu parcialmente?", "q_p": "Que missão a igreja herda após Atos?"},
                    ],
                },
                {
                    "slug": "ato-boss-02",
                    "title": "Desafio: Até os confins",
                    "subtitle": "Atos 8–28",
                    "intro": "Revise o avanço: Saulo, gentios, envio e testemunho em Roma.",
                    "boss": True,
                    "seeds": [
                        {"verse": "Atos 9:15", "answer": "Vaso para gentios e reis", "wrong": ["Sem chamado", "Só perseguir", "Só Jerusalém"], "q_s": "Qual o chamado de Paulo?", "q_c": "Para quem?", "q_p": "Como graça gera missão?"},
                        {"verse": "Atos 10:34–45", "answer": "Gentios incluídos pelo Espírito", "wrong": ["Barreiras eternas", "Sem evangelho para nações", "Só circuncisão salva"], "q_s": "O que Cornélio prova?", "q_c": "Quem valida a inclusão?", "q_p": "Como isso cumpre a promessa?"},
                        {"verse": "Atos 13:2–3", "answer": "Igreja enviada pelo Espírito", "wrong": ["Missão só individual", "Sem oração", "Sem envio"], "q_s": "De onde sai a missão?", "q_c": "Qual o padrão de Antioquia?", "q_p": "Como sua igreja envia?"},
                        {"verse": "Atos 28:31", "answer": "Reino anunciado sem impedimento", "wrong": ["Palavra presa", "Fim da pregação", "Vitória só política"], "q_s": "Como Atos termina?", "q_c": "O que não está preso?", "q_p": "Que esperança isso dá sob pressão?"},
                        {"verse": "Atos 1:8", "answer": "O mapa avança apesar da oposição", "wrong": ["O mapa falhou", "Só milagres importam", "Roma cancelou 1:8"], "q_s": "O que o livro demonstra?", "q_c": "Qual o fio de Jerusalém a Roma?", "q_p": "Como continuar o mapa hoje?"},
                    ],
                },
            ],
        },
    ],
}

APOCALIPSE = {
    "slug": "apocalipse",
    "title": "Apocalipse",
    "description": "Revelação de Jesus: cartas, trono, conflito e nova criação.",
    "unlockAfter": "cartas-paulo",
    "modules": [
        {
            "title": "Cartas e trono",
            "icon": "👑",
            "section": "trono",
            "missions": [
                {
                    "slug": "apo-01-cartas",
                    "title": "Cartas às igrejas",
                    "subtitle": "Apocalipse 2–3",
                    "intro": "Jesus fala às sete igrejas: ânimo, correção e promessa aos que vencem.",
                    "study": {
                        "passageRef": "Apocalipse 2:7",
                        "passageText": "Quem tem ouvidos, ouça o que o Espírito diz às igrejas. Ao vencedor, dar-lhe-ei que se alimente da árvore da vida.",
                        "context": "Antes de visões cósmicas, Jesus pastoreia igrejas reais sob pressão (império, idolatria, acomodação). Cada carta combina conhecimento íntimo, elogio e/ou repreensão, chamado ao arrependimento e promessa ao vencedor. Ouvir o Espírito é questão de sobrevivência fiel — não de curiosidade apocalíptica.",
                        "keyword": "Vencedor",
                        "keywordGloss": "Quem persevera em Cristo sob pressão — fidelidade, não força isolada.",
                        "focusQuestion": "Que palavra Jesus falaria à sua igreja — e a você — hoje?",
                        "reflectionPrompts": [
                            "Ouvir o Espírito",
                            "Primeiro amor e perseverança",
                            "Promessa aos fiéis",
                        ],
                        "relatedVerses": [
                            {"reference": "Apocalipse 1:11", "reason": "Escreve às sete igrejas — comunicação pastoral."},
                            {"reference": "Hebreus 3:7–8", "reason": "Hoje, se ouvirdes a sua voz, não endureçais o coração."},
                            {"reference": "João 16:33", "reason": "No mundo tereis aflições; tende bom ânimo: eu venci."},
                        ],
                    },
                    "seeds": [
                        {"verse": "Apocalipse 2:7", "answer": "Ouvir o que o Espírito diz às igrejas", "wrong": ["Ignorar a correção", "Só buscar datas", "Silenciar a palavra"], "q_s": "Qual o refrão das cartas?", "q_c": "A quem o Espírito fala?", "q_p": "Por que ouvir precede vencer?"},
                        {"verse": "Apocalipse 2:4–5", "answer": "Abandonaram o primeiro amor; arrependam-se", "wrong": ["Estão perfeitos", "Não há chamado", "Só doutrina importa"], "q_s": "O que Éfeso esqueceu?", "q_c": "Qual o remédio?", "q_p": "Como ortodoxia sem amor falha?"},
                        {"verse": "Apocalipse 3:15–16", "answer": "Mornos — nem frios nem quentes", "wrong": ["Elogiados sem reserva", "Chamados a mais conforto", "Isentos de juízo"], "q_s": "Qual o problema de Laodiceia?", "q_c": "O que Jesus prefere a mornidão?", "q_p": "Como acomodação se disfarça de equilíbrio?"},
                        {"verse": "Apocalipse 3:20", "answer": "Está à porta e bate", "wrong": ["Abandonou a igreja", "Só julga sem convite", "Fecha a porta para sempre"], "q_s": "O que Jesus oferece?", "q_c": "Qual a imagem da comunhão?", "q_p": "Como arrependimento restaura comunhão?"},
                        {"verse": "Apocalipse 2–3", "answer": "Promessas ao vencedor em cada carta", "wrong": ["Sem esperança", "Só ameaça", "Vitória sem Cristo"], "q_s": "O que fecha cada carta?", "q_c": "Quem é o vencedor?", "q_p": "Como as promessas sustentam sob pressão?"},
                    ],
                },
                {
                    "slug": "apo-04-visao",
                    "title": "O Filho do Homem",
                    "subtitle": "Apocalipse 1:9–20",
                    "intro": "João vê Jesus glorioso no meio dos candeeiros: o Senhor da igreja.",
                    "study": {
                        "passageRef": "Apocalipse 1:17–18",
                        "passageText": "Não temas; eu sou o primeiro e o último… estive morto, mas eis que estou vivo… e tenho as chaves da morte e do inferno.",
                        "context": "Antes das cartas, a visão do Filho do Homem estabelece quem fala. Jesus caminha entre os candeeiros (igrejas). A glória assusta; a palavra “não temas” e a cruz/ressurreição consolam. Apocalipse não começa com o anticristo — começa com Cristo vivo e soberano sobre a igreja e sobre a morte.",
                        "keyword": "Filho do Homem",
                        "keywordGloss": "Título de soberania e presença — o Cristo glorificado que pastoreia suas igrejas.",
                        "focusQuestion": "Quando penso no futuro, vejo primeiro o medo — ou o Cristo vivo?",
                        "reflectionPrompts": [
                            "Cristo no meio da igreja",
                            "Não temas",
                            "Chaves da morte nele",
                        ],
                        "relatedVerses": [
                            {"reference": "Daniel 7:13–14", "reason": "O Filho do Homem recebe domínio eterno."},
                            {"reference": "Mateus 28:18", "reason": "Toda autoridade me foi dada."},
                            {"reference": "Hebreus 1:3", "reason": "Assentou-se à direita da Majestade."},
                        ],
                    },
                    "seeds": [
                        {"verse": "Apocalipse 1:12–13", "answer": "Jesus no meio dos sete candeeiros", "wrong": ["Longe das igrejas", "Só no céu distante", "Ausente do sofrimento"], "q_s": "Onde está o Filho do Homem?", "q_c": "O que os candeeiros representam?", "q_p": "Como isso consola igrejas sob pressão?"},
                        {"verse": "Apocalipse 1:17–18", "answer": "Não temas — estou vivo e tenho as chaves", "wrong": ["Temei sem esperança", "A morte tem a última palavra", "Jesus ainda está morto"], "q_s": "O que Jesus diz a João?", "q_c": "Qual sua vitória?", "q_p": "Por que as chaves mudam o medo?"},
                        {"verse": "Apocalipse 1:8", "answer": "Alfa e Ômega / o que é, era e há de vir", "wrong": ["Só passado", "Só futuro incerto", "Sem soberania"], "q_s": "Como Deus se apresenta?", "q_c": "O que isso diz sobre a história?", "q_p": "Como isso ancora esperança?"},
                        {"verse": "Apocalipse 1:19", "answer": "Escreve o que viste, o que é e o que há de vir", "wrong": ["Não escrevas", "Só especule datas", "Ignore as igrejas"], "q_s": "Qual a ordem a João?", "q_c": "Qual o escopo da revelação?", "q_p": "Como presente e futuro se ligam?"},
                        {"verse": "Apocalipse 1:20", "answer": "Candeeiros são as igrejas; estrelas, anjos/mensageiros", "wrong": ["Sem significado", "Só símbolos vazios", "Nações pagãs"], "q_s": "O que Jesus interpreta?", "q_c": "Por que a igreja está no centro?", "q_p": "Como ler símbolos com a chave do texto?"},
                    ],
                },
                {
                    "slug": "apo-02-cordeiro",
                    "title": "O Cordeiro no trono",
                    "subtitle": "Apocalipse 5",
                    "intro": "No centro do céu não está o medo — está o Cordeiro que foi morto e é digno.",
                    "study": {
                        "passageRef": "Apocalipse 5:9–10",
                        "passageText": "Digno és… porque foste morto e com o teu sangue compraste para Deus gente de toda tribo… e os constituíste reino e sacerdotes.",
                        "context": "Ninguém podia abrir o livro — João chora. Então aparece o Cordeiro como imolado: a vitória passa pela cruz. O culto celestial celebra redenção multiétnica. História e juízo estão sob o selo de quem morreu e ressuscitou. Apocalipse é livro de culto antes de ser mapa de pânico.",
                        "keyword": "Cordeiro",
                        "keywordGloss": "Cristo crucificado e exaltado — centro da história, do culto e da vitória.",
                        "focusQuestion": "Por que o Cordeiro morto é o mais digno de governar a história?",
                        "reflectionPrompts": [
                            "Vitória pela cruz",
                            "Culto ao Cordeiro",
                            "Povos comprados por sangue",
                        ],
                        "relatedVerses": [
                            {"reference": "Isaías 53:7", "reason": "Como cordeiro foi levado ao matadouro."},
                            {"reference": "João 1:29", "reason": "Eis o Cordeiro de Deus que tira o pecado do mundo."},
                            {"reference": "Filipenses 2:8–11", "reason": "Humilhou-se até a cruz — por isso Deus o exaltou."},
                        ],
                    },
                    "seeds": [
                        {"verse": "Apocalipse 5:5–6", "answer": "O Leão vence como Cordeiro imolado", "wrong": ["Um império abre o livro", "Ninguém é digno para sempre", "A força bruta governa"], "q_s": "Quem pode abrir o livro?", "q_c": "Qual a paradoxo Leão/Cordeiro?", "q_p": "Como a cruz redefine poder?"},
                        {"verse": "Apocalipse 5:9", "answer": "Comprados pelo sangue de toda tribo", "wrong": ["Só uma etnia", "Sem custo", "Auto-redenção"], "q_s": "O que o cântico declara?", "q_c": "Qual o alcance da redenção?", "q_p": "Como isso molda missão e culto?"},
                        {"verse": "Apocalipse 5:12", "answer": "Digno é o Cordeiro de receber poder e honra", "wrong": ["Digno é César", "Digno é o medo", "Ninguém é digno"], "q_s": "O que a multidão proclama?", "q_c": "O que o Cordeiro recebe?", "q_p": "Como culto confronta idolatria?"},
                        {"verse": "Apocalipse 5:4–5", "answer": "João chora; o ancião aponta o Leão/Cordeiro", "wrong": ["João celebra sem tensão", "Não há drama", "O livro fica fechado"], "q_s": "Qual a crise no capítulo?", "q_c": "Como a esperança entra?", "q_p": "Por que o choro importa na narrativa?"},
                        {"verse": "Apocalipse 5:10", "answer": "Reino e sacerdotes para Deus", "wrong": ["Escravos do Império", "Sem identidade", "Só espectadores"], "q_s": "O que os redimidos se tornam?", "q_c": "Qual a vocação do povo?", "q_p": "Como reinar com Cristo se vive agora?"},
                    ],
                },
                {
                    "slug": "apo-boss-01",
                    "title": "Desafio: Cartas e trono",
                    "subtitle": "Apocalipse 1–5",
                    "intro": "Revise: Jesus pastoreia, reina e o Cordeiro é digno.",
                    "boss": True,
                    "seeds": [
                        {"verse": "Apocalipse 1:17–18", "answer": "Cristo vivo com as chaves", "wrong": ["Medo no centro", "Morte soberana", "Igreja abandonada"], "q_s": "Quem abre o livro de Apocalipse?", "q_c": "Qual a primeira palavra às igrejas?", "q_p": "Como isso ancora o resto?"},
                        {"verse": "Apocalipse 2–3", "answer": "Ouvir, arrepender-se, vencer", "wrong": ["Ignorar correção", "Só especular", "Sem promessa"], "q_s": "Qual o padrão das cartas?", "q_c": "O que o Espírito pede?", "q_p": "Como aplicar à sua igreja?"},
                        {"verse": "Apocalipse 5:9", "answer": "Cordeiro digno pelo sangue", "wrong": ["Poder sem cruz", "Culto ao Império", "Salvação sem Cristo"], "q_s": "Por que o Cordeiro é digno?", "q_c": "O que o sangue conquista?", "q_p": "Como culto e missão se unem?"},
                        {"verse": "Apocalipse 1:13", "answer": "Jesus no meio dos candeeiros", "wrong": ["Longe da igreja", "Só juízo sem presença", "Ausência total"], "q_s": "Onde está Cristo?", "q_c": "O que isso significa?", "q_p": "Como pastoreio glorioso consola?"},
                        {"verse": "Apocalipse 1–5", "answer": "Do Filho do Homem ao culto do Cordeiro", "wrong": ["Só catástrofe", "Sem esperança", "Sem igreja"], "q_s": "Qual o arco inicial?", "q_c": "O que fica no centro?", "q_p": "Como ler o resto à luz do trono?"},
                    ],
                },
            ],
        },
        {
            "title": "Juízo e esperança",
            "icon": "🌅",
            "section": "esperanca",
            "missions": [
                {
                    "slug": "apo-06-selos",
                    "title": "Selos e testemunho",
                    "subtitle": "Apocalipse 6–7",
                    "intro": "A história dói — mas os selados e a multidão branca mostram: Deus guarda o Seu povo.",
                    "study": {
                        "passageRef": "Apocalipse 7:9–10",
                        "passageText": "Vi… grande multidão… de todas as nações… clamavam: Ao nosso Deus… e ao Cordeiro, pertence a salvação.",
                        "context": "Os selos revelam conflito, fome e martírio — o mundo sob tensão. Mas o interlúdio mostra proteção (144 mil) e multidão incontável lavada no sangue do Cordeiro. Juízo não é o último quadro: culto multiétnico e cuidado divino sustentam a igreja no meio da tribulação.",
                        "keyword": "Selados",
                        "keywordGloss": "Povo de Deus marcado e guardado — pertencimento antes da tempestade.",
                        "focusQuestion": "Em meio ao caos, minha confiança está no Cordeiro ou nas manchetes?",
                        "reflectionPrompts": [
                            "Deus conhece os seus",
                            "Multidão de todas as nações",
                            "Salvação ao Cordeiro",
                        ],
                        "relatedVerses": [
                            {"reference": "Ezequiel 9:4", "reason": "Marca nos que gemem pelo pecado da terra."},
                            {"reference": "João 10:28", "reason": "Ninguém as arrebatará da minha mão."},
                            {"reference": "Romanos 8:35–39", "reason": "Nenhuma tribulação nos separa do amor de Cristo."},
                        ],
                    },
                    "seeds": [
                        {"verse": "Apocalipse 6:9–11", "answer": "Almas dos mártires pedem justiça", "wrong": ["Não há sofrimento", "Deus ignora o sangue", "Vitória imediata sem espera"], "q_s": "O que o quinto selo revela?", "q_c": "O que lhes é dito?", "q_p": "Como esperança e justiça se equilibram?"},
                        {"verse": "Apocalipse 7:3", "answer": "Não danificar até selarmos os servos de Deus", "wrong": ["Sem proteção", "Destruição total dos fiéis", "Selos só para inimigos"], "q_s": "O que o anjo ordena?", "q_c": "Quem é selado?", "q_p": "O que o selo comunica?"},
                        {"verse": "Apocalipse 7:9", "answer": "Multidão de todas as nações", "wrong": ["Só uma etnia", "Ninguém resiste", "Igreja vazia"], "q_s": "O que João vê?", "q_c": "Qual a amplitude?", "q_p": "Como isso cumpre missão?"},
                        {"verse": "Apocalipse 7:14", "answer": "Lavaram as vestes no sangue do Cordeiro", "wrong": ["Salvos por esforço", "Sem Cristo", "Vestes sem significado"], "q_s": "Como a multidão está limpa?", "q_c": "Qual o meio?", "q_p": "Por que o sangue limpa?"},
                        {"verse": "Apocalipse 7:17", "answer": "O Cordeiro os pastoreará e enxugará lágrimas", "wrong": ["Abandono final", "Sem consolo", "Só juízo"], "q_s": "Qual a promessa?", "q_c": "Quem pastoreia?", "q_p": "Como isso aponta para o fim do livro?"},
                    ],
                },
                {
                    "slug": "apo-07-babilonia",
                    "title": "Queda de Babilônia",
                    "subtitle": "Apocalipse 17–18",
                    "intro": "O sistema que seduz e oprime cai. Sai dela, povo meu — fidelidade tem endereço.",
                    "study": {
                        "passageRef": "Apocalipse 18:4",
                        "passageText": "Retirai-vos dela, povo meu, para não serdes cúmplices em seus pecados e para não participardes dos seus flagelos.",
                        "context": "Babilônia simboliza a cidade/império idólatra que embriaga nações com luxo e violência. Sua queda é celebrada no céu e lamentada pelos mercadores. O chamado à igreja é separação fiel — não isolamento covarde, mas recusa de cumplicidade. Apocalipse desmascara sedução: o que parece glamour é juízo anunciado.",
                        "keyword": "Babilônia",
                        "keywordGloss": "Figura do poder idólatra e opressor que rivaliza com o Cordeiro e seduz os povos.",
                        "focusQuestion": "Onde estou cúmplice de um sistema que Cristo já julgou?",
                        "reflectionPrompts": [
                            "Sair da cumplicidade",
                            "Glória do mundo é passageira",
                            "Fidelidade tem custo e clareza",
                        ],
                        "relatedVerses": [
                            {"reference": "Isaías 48:20", "reason": "Saí da Babilônia — eco do chamado."},
                            {"reference": "Jeremias 51:6", "reason": "Fugi… e livrai cada um a sua alma."},
                            {"reference": "1 João 2:15–17", "reason": "Não ameis o mundo; ele passa."},
                        ],
                    },
                    "seeds": [
                        {"verse": "Apocalipse 18:4", "answer": "Retirai-vos dela, povo meu", "wrong": ["Permanecei em cumplicidade", "Amei a Babilônia", "Não há chamado"], "q_s": "Qual o chamado à igreja?", "q_c": "Para evitar o quê?", "q_p": "Como “sair” se vive hoje?"},
                        {"verse": "Apocalipse 18:2", "answer": "Caiu, caiu a grande Babilônia", "wrong": ["Babilônia vence para sempre", "Não há juízo", "O Cordeiro perde"], "q_s": "O que o anjo anuncia?", "q_c": "Qual o tom da queda?", "q_p": "Por que a repetição “caiu, caiu”?"},
                        {"verse": "Apocalipse 18:11–13", "answer": "Mercadores choram a perda do luxo", "wrong": ["Todos celebram a justiça", "Não há economia envolvida", "Só anjos lamentam"], "q_s": "Quem lamenta?", "q_c": "O que isso revela?", "q_p": "Como idolatria econômica aparece?"},
                        {"verse": "Apocalipse 17:14", "answer": "O Cordeiro vencerá — e os chamados com ele", "wrong": ["A besta vence no fim", "Sem vitória", "Igreja abandonada"], "q_s": "Quem vence a guerra?", "q_c": "Quem está com o Cordeiro?", "q_p": "Como isso anima perseve­rança?"},
                        {"verse": "Apocalipse 18:20", "answer": "Céus e santos se alegram com o juízo", "wrong": ["O céu chora a injustiça vitoriosa", "Não há alegria santa", "Juízo é capricho"], "q_s": "Como o céu responde?", "q_c": "Por que há alegria?", "q_p": "Como justiça divina consola oprimidos?"},
                    ],
                },
                {
                    "slug": "apo-03-novo",
                    "title": "Novo céu e nova terra",
                    "subtitle": "Apocalipse 21:1–5",
                    "intro": "A história termina com restauração: Deus com o Seu povo, sem morte nem dor.",
                    "study": {
                        "passageRef": "Apocalipse 21:3–4",
                        "passageText": "Eis o tabernáculo de Deus com os homens… E Deus limpará de seus olhos toda lágrima… e a morte não existirá mais.",
                        "context": "O fim não é fuga da criação, mas renovação. A Nova Jerusalém desce: Deus habita com os humanos. Lágrimas, morte, pranto e dor passam. Quem está no trono diz: “faço novas todas as coisas”. Esperança cristã é escatológica e corporal — sustenta fidelidade agora porque o futuro é comunhão plena.",
                        "keyword": "Nova criação",
                        "keywordGloss": "Renovação de todas as coisas — Deus conosco, criação libertada, dor encerrada.",
                        "focusQuestion": "Como essa esperança muda a forma como você carrega o sofrimento hoje?",
                        "reflectionPrompts": [
                            "Deus conosco",
                            "Toda lágrima enxugada",
                            "Tudo feito novo",
                        ],
                        "relatedVerses": [
                            {"reference": "Isaías 65:17", "reason": "Novos céus e nova terra — promessa antiga."},
                            {"reference": "2 Pedro 3:13", "reason": "Esperamos novos céus e nova terra, nos quais habita justiça."},
                            {"reference": "Romanos 8:18–21", "reason": "A criação será libertada da corrupção."},
                        ],
                    },
                    "seeds": [
                        {"verse": "Apocalipse 21:1", "answer": "Novo céu e nova terra", "wrong": ["Aniquilação sem renovação", "Eterno caos", "Só espírito sem mundo"], "q_s": "O que João vê?", "q_c": "O que passou?", "q_p": "Por que renovação importa?"},
                        {"verse": "Apocalipse 21:3", "answer": "Deus habitará com os homens", "wrong": ["Deus permanece distante", "Sem comunhão", "Só juízo"], "q_s": "Qual a grande voz do trono?", "q_c": "O que é o tabernáculo?", "q_p": "Como isso cumpre Êxodo/Emmanuel?"},
                        {"verse": "Apocalipse 21:4", "answer": "Toda lágrima enxugada; morte não mais", "wrong": ["Dor eterna para os santos", "Morte vence", "Sem consolo"], "q_s": "O que Deus fará?", "q_c": "O que deixa de existir?", "q_p": "Como isso consola agora?"},
                        {"verse": "Apocalipse 21:5", "answer": "Faço novas todas as coisas", "wrong": ["Nada muda", "Só destrói", "Promessa vazia"], "q_s": "O que diz Aquele do trono?", "q_c": "Qual a ordem sobre escrever?", "q_p": "Por que “estas palavras são fiéis”?"},
                        {"verse": "Apocalipse 21:1–5", "answer": "Esperança de comunhão e renovação", "wrong": ["Medo como meta", "Fuga sem Deus", "Vitória do mal"], "q_s": "Qual o tom do fim?", "q_c": "O que está no centro?", "q_p": "Como viver hoje à luz desse fim?"},
                    ],
                },
                {
                    "slug": "apo-boss-02",
                    "title": "Desafio final: Esperança",
                    "subtitle": "Apocalipse 6–22",
                    "intro": "Revise: selados, queda de Babilônia e nova criação no Cordeiro.",
                    "boss": True,
                    "seeds": [
                        {"verse": "Apocalipse 7:9–10", "answer": "Multidão salva pelo Cordeiro", "wrong": ["Nações excluídas", "Salvação sem culto", "Medo no centro"], "q_s": "Qual a visão de esperança no conflito?", "q_c": "A quem pertence a salvação?", "q_p": "Como isso anima missão?"},
                        {"verse": "Apocalipse 18:4", "answer": "Sair da Babilônia", "wrong": ["Ama o sistema idólatra", "Sem separação", "Cumplicidade fiel"], "q_s": "Qual o chamado ético?", "q_c": "O que evitar?", "q_p": "Como fidelidade parece na prática?"},
                        {"verse": "Apocalipse 21:3–4", "answer": "Deus conosco; sem morte nem dor", "wrong": ["Fim sem presença", "Dor eterna dos santos", "Sem renovação"], "q_s": "Como a história fecha?", "q_c": "O que Deus faz às lágrimas?", "q_p": "Por que isso é o fosso cristão?"},
                        {"verse": "Apocalipse 17:14", "answer": "O Cordeiro vence", "wrong": ["Babilônia vence", "Sem vitória", "Igreja derrotada"], "q_s": "Quem ganha a guerra?", "q_c": "Quem está com Ele?", "q_p": "Como isso sustenta sob pressão?"},
                        {"verse": "Apocalipse 1–22", "answer": "De Cristo glorioso à nova criação", "wrong": ["Livro só de medo", "Sem pastor", "Sem fim bom"], "q_s": "Qual o arco do livro?", "q_c": "O que permanece no centro?", "q_p": "Que esperança carregar daqui?"},
                    ],
                },
            ],
        },
    ],
}
