/// Trilhas que usam banco de perguntas com 3 níveis de dificuldade.
const difficultyBankTrails = {
  'genesis-1-11',
  'exodo',
  'genesis-12-50',
  'levitico',
  'numeros',
  'deuteronomio',
  'josue',
  'juizes',
  'rute',
  'samuel',
  'reis',
  'cronicas',
  'esdras',
  'neemias',
  'ester',
  'jo',
  'salmos',
  'proverbios',
  'eclesiastes',
  'cantares',
  'isaias',
  'jeremias',
  'lamentacoes',
  'ezequiel',
  'daniel',
  'oseias',
  'joel',
  'amos',
  'obadias',
  'jonas',
  'miqueias',
  'naum',
  'habacuque',
  'sofonias',
  'ageu',
  'zacarias',
  'malaquias',
  'periodo-intertestamentario',
  // NT vivo (perguntas no banco com 3 modos)
  'evangelhos',
  'atos',
  'apocalipse',
  'sermao-do-monte',
  // Epístolas NT
  'cartas-gerais',
  'cartas-joao',
  'cartas-paulo',
  'colossenses',
  'corintios',
  'efesios',
  'filemom',
  'filipenses',
  'galatas',
  'hebreus',
  'judas',
  'pedro',
  'romanos',
  'tessalonicenses',
  'tiago',
  'timoteo',
  'tito',
  // Buracos preenchidos
  'antropologia',
  'cristologia',
  'doutrina-de-deus',
  'eclesiologia',
  'escatologia',
  'familia',
  'grego',
  'hebraico',
  'hermeneutica',
  'historia-igreja',
  'igreja-primitiva',
  'jejum',
  'joao',
  'linguas-originais',
  'lucas',
  'marcos',
  'mateus',
  'missao',
  'oracao',
  'pneumatologia',
  'reforma',
  'soteriologia',
  'teologia-biblica',
  'teologia-sistematica',
  'vida-crista',
};

bool trailUsesDifficultyBank(String? trailSlug) {
  if (trailSlug == null || trailSlug.isEmpty) return false;
  return difficultyBankTrails.contains(trailSlug);
}
