export const lockedTrails = [
  {
    slug: "evangelhos",
    title: "Evangelhos",
    description: "A vida, morte e ressurreição de Jesus Cristo.",
    icon: "✝️",
    order: 3,
    unlockAfter: "exodo",
    comingSoon: true,
    color: "#E17055",
  },
  {
    slug: "atos",
    title: "Atos dos Apóstolos",
    description: "O nascimento da Igreja e a expansão do Evangelho.",
    icon: "🔥",
    order: 4,
    unlockAfter: "evangelhos",
    comingSoon: true,
    color: "#FDCB6E",
  },
  {
    slug: "apocalipse",
    title: "Apocalipse",
    description: "A revelação final — esperança e vitória de Cristo.",
    icon: "👑",
    order: 5,
    unlockAfter: "atos",
    comingSoon: true,
    color: "#A29BFE",
  },
] as const;
